(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root&&root.document)api.mount(root.document,root);})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const n=v=>{const x=Number(v);return Number.isFinite(x)?x:null;},round=(v,d=1)=>Number.isFinite(v)?Number(v.toFixed(d)):null,ceil=(v,s)=>Number.isFinite(v)?Math.ceil(v/s)*s:null;
const HAZARD=new Set(['hot','wet','damaged','burned','swollen']),FIXED=new Set(['built_in_oven','induction_hob','fixed_heater']),MIXED=new Set(['microwave','coffee_machine','other_motor']),SUPPORTED=new Set(['microwave','coffee_machine','airfryer','kettle','hairdryer','toaster','other_motor']);
const done=(status,title,input,metrics,actions,warnings,evidence,commercial)=>({status,title,input,metrics,actions,warnings,evidence,commercial});
function evaluate(raw={}){
 const input={emergency:Boolean(raw.emergency),scenario:raw.scenario||'planning',applianceType:raw.applianceType||'kettle',condition:raw.condition||'normal',exactModelVerified:raw.exactModelVerified||'no',powerEvidence:raw.powerEvidence||'unknown',ratedInputW:n(raw.ratedInputW),useMinutes:n(raw.useMinutes),sessions:n(raw.sessions),simultaneousLoads:raw.simultaneousLoads||'one',surgeKnown:raw.surgeKnown||'no',surgeW:n(raw.surgeW),directConnection:raw.directConnection||'unknown',outletGrounding:raw.outletGrounding||'unknown',ventilation:raw.ventilation||'unknown',unattendedUse:raw.unattendedUse||'no',sourceStatus:raw.sourceStatus||'none',sourceContinuousW:n(raw.sourceContinuousW),sourceSurgeW:n(raw.sourceSurgeW),sourceWh:n(raw.sourceWh),sourcePureSine:raw.sourcePureSine||'unknown',sourceGroundedOutput:raw.sourceGroundedOutput||'unknown',controlledTest:raw.controlledTest||'untested'};
 const metrics={continuousW:null,surgeW:null,energyPerUseWh:null,requiredNominalWh:null,effectiveSourceWh:null,estimatedSessions:null,utilizationPercent:null},actions=[],warnings=[],evidence=[],commercial={allowed:false,category:null,url:null,reason:null};
 if(input.emergency||HAZARD.has(input.condition)){warnings.push('Duman, erime, şişme, yanık kokusu, su teması, aşırı ısınma veya elektrik çarpması riski alışveriş konusu değildir.');actions.push('Cihazı ve güç kaynağını yeniden çalıştırmayın; güvenli mesafeye geçin. Yangın veya yaralanmada 112’yi arayın.','Hasarlı cihaz, priz, kablo veya batarya için yetkili servis ve elektrik uzmanı incelemesi yaptırın.');return done('emergency','Önce can ve yangın güvenliği',input,metrics,actions,warnings,evidence,commercial);}
 if(FIXED.has(input.applianceType)){warnings.push('Ankastre fırın, indüksiyon ocak ve sabit elektrikli ısıtıcı tüketici tipi power station affiliate sonucuna dönüştürülmez.');actions.push('Devre akımı, bağlantı şekli, kablo kesiti, koruma düzeni ve üretici talimatını yetkili elektrikçiyle değerlendirin.');return done('professional','Sabit ve yüksek güçlü cihaz için profesyonel proje',input,metrics,actions,warnings,evidence,commercial);}
 if(input.simultaneousLoads!=='one'){warnings.push('Bu araç yalnız bir yüksek güçlü cihazın tek başına çalıştırılmasını değerlendirir. Aynı anda birden fazla cihaz ayrı yük hesabı gerektirir.');actions.push('Cihazları aynı anda çalıştırmayın; toplam sürekli güç, priz ve kablo akımı için profesyonel yük hesabı yaptırın.');return done('professional','Eşzamanlı yüksek güç için ayrı yük hesabı',input,metrics,actions,warnings,evidence,commercial);}
 if(input.unattendedUse==='yes'){warnings.push('Isıtıcı, kettle, airfryer, kahve makinesi veya benzeri yüksek güçlü cihazlar gözetimsiz çalıştırılmamalıdır.');actions.push('Kullanımı yalnız uyanık ve cihazın yanında olduğunuz kısa süreli senaryoya çevirin.');return done('unsafe_use','Gözetimsiz kullanım uygun değil',input,metrics,actions,warnings,evidence,commercial);}
 if(!SUPPORTED.has(input.applianceType)||!(input.ratedInputW>0)||!(input.useMinutes>0)||!(input.sessions>0)){actions.push('Cihazın INPUT/giriş watt değerini, bir kullanım süresini ve planlanan kullanım adedini girin.');return done('incomplete','Temel güç ve kullanım verisi eksik',input,metrics,actions,warnings,evidence,commercial);}
 if(input.powerEvidence!=='input_label'){warnings.push(input.applianceType==='microwave'?'Mikrodalgadaki pişirme/çıkış wattı elektrik giriş tüketimi değildir; INPUT veya rated input power değeri gerekir.':'Reklamda yazan performans değeri yerine cihaz etiketindeki gerçek INPUT/giriş wattı kullanılmalıdır.');actions.push('Tam model etiketini veya üretici teknik sayfasını kontrol edin; yalnız çıkış/pişirme gücüyle seçim yapmayın.');return done('needs_evidence','Gerçek giriş wattı doğrulanmalı',input,metrics,actions,warnings,evidence,commercial);}
 metrics.continuousW=ceil(input.ratedInputW*1.15,50);metrics.energyPerUseWh=input.ratedInputW*(input.useMinutes/60);metrics.requiredNominalWh=ceil((metrics.energyPerUseWh*input.sessions)/(0.85*0.90),50);
 evidence.push(`Sürekli AC çıkış alt sınırı: yaklaşık ${metrics.continuousW} W (etiket giriş gücü + %15 çalışma payı).`,`Bir kullanım enerjisi: yaklaşık ${round(metrics.energyPerUseWh)} Wh (${round(input.ratedInputW)} W × ${round(input.useMinutes,1)} dakika).`,`Planlanan ${round(input.sessions,0)} kullanım için nominal kapasite hedefi: yaklaşık ${metrics.requiredNominalWh} Wh (AC kayıpları ve batarya rezervi dahil).`);
 if(MIXED.has(input.applianceType)){if(input.surgeKnown!=='yes'||!(input.surgeW>0)){warnings.push('Pompa, fan, trafo veya motor içeren cihazlarda tepe/kalkış gücü doğrulanmadan yalnız sürekli watt ile seçim yapılamaz.');actions.push('Üretici teknik verisinden veya uygun ölçüm yönteminden tepe gücü doğrulayın.');return done('needs_evidence','Tepe güç kanıtı gerekli',input,metrics,actions,warnings,evidence,commercial);}metrics.surgeW=ceil(Math.max(input.surgeW,metrics.continuousW),50);evidence.push(`Doğrulanan tepe güç alt sınırı: ${metrics.surgeW} W.`);}else{metrics.surgeW=metrics.continuousW;evidence.push('Rezistif ağırlıklı cihaz için tepe güç alt sınırı sürekli güç alt sınırıyla aynı kabul edildi; üretici farklı değer veriyorsa o değer esas alınmalıdır.');}
 if(input.exactModelVerified!=='yes'){warnings.push('Tam model doğrulanmadan güç, fiş, kullanım süresi ve üretici sınırlamaları güvenilir kabul edilemez.');actions.push('Model etiketini ve kullanım kılavuzunu doğrulayın.');return done('needs_evidence','Tam model kanıtı gerekli',input,metrics,actions,warnings,evidence,commercial);}
 if(input.directConnection!=='direct'||input.outletGrounding!=='verified'||input.ventilation!=='clear'){warnings.push('Çoklayıcı, ince uzatma, seyahat adaptörü, belirsiz topraklama veya kapalı dolap yüksek güçlü kullanım için uygunluk kanıtı değildir.');actions.push('Power station ve cihazı üretici izin veriyorsa doğrudan, sağlam ve uygun topraklı AC çıkışta; hava girişleri açık şekilde kullanın.');return done('needs_evidence','Bağlantı ve havalandırma kanıtı eksik',input,metrics,actions,warnings,evidence,commercial);}
 if(input.sourceStatus==='existing'){
  if(!(input.sourceContinuousW>0)||!(input.sourceSurgeW>0)||!(input.sourceWh>0)){actions.push('Mevcut kaynağın sürekli W, tepe W ve nominal Wh değerlerini tam model teknik sayfasından girin.');return done('incomplete','Mevcut kaynak verisi eksik',input,metrics,actions,warnings,evidence,commercial);}
  metrics.effectiveSourceWh=input.sourceWh*0.85*0.90;metrics.estimatedSessions=Math.floor(metrics.effectiveSourceWh/metrics.energyPerUseWh);metrics.utilizationPercent=round((input.ratedInputW/input.sourceContinuousW)*100);
  evidence.push(`Mevcut kaynağın konservatif kullanılabilir enerjisi yaklaşık ${round(metrics.effectiveSourceWh)} Wh; tahmini tam kullanım adedi ${Math.max(0,metrics.estimatedSessions)}.`,`Cihazın kaynak sürekli çıkışını kullanma oranı yaklaşık %${metrics.utilizationPercent}.`);
  const c=input.sourceContinuousW>=metrics.continuousW,s=input.sourceSurgeW>=metrics.surgeW,e=input.sourceWh>=metrics.requiredNominalWh,w=input.sourcePureSine==='yes',g=input.sourceGroundedOutput==='verified';
  if(c&&s&&e&&w&&g&&input.controlledTest==='success'){actions.push('Mevcut kaynak güç, enerji, saf sinüs, çıkış düzeni ve kontrollü kullanım testini karşılıyor. Yeni ürün almayın.','Priz, fiş ve kablo sıcaklığını kullanım sırasında gözleyin; cihazları aynı anda çalıştırmayın.');return done('no_buy','Mevcut power station yeterli',input,metrics,actions,warnings,evidence,commercial);}
  if(c&&s&&e&&w&&g&&input.controlledTest==='untested'){actions.push('Yeni ürün almadan önce kısa, uyanık ve gözetimli bir test yapın; aşırı ısınma, koku, kapanma veya aşırı yük alarmında testi durdurun.');return done('test_first','Kapasite uygun görünüyor; önce kontrollü test',input,metrics,actions,warnings,evidence,commercial);}
  if(!c)warnings.push(`Mevcut sürekli çıkış ${input.sourceContinuousW} W; alt sınır ${metrics.continuousW} W.`);if(!s)warnings.push(`Mevcut tepe çıkış ${input.sourceSurgeW} W; alt sınır ${metrics.surgeW} W.`);if(!e)warnings.push(`Mevcut nominal kapasite ${input.sourceWh} Wh; hedef yaklaşık ${metrics.requiredNominalWh} Wh.`);if(!w)warnings.push('Mevcut AC çıkışın saf sinüs olduğu doğrulanmadı.');if(!g)warnings.push('Mevcut AC çıkışın koruyucu topraklama/çıkış düzeni doğrulanmadı.');if(input.controlledTest==='failed')warnings.push('Mevcut kaynak kontrollü testte cihazı güvenilir biçimde çalıştıramadı.');
 }
 if(input.scenario==='active'){warnings.push('Aktif kesintide ürün teslimatı anlık çözüm değildir; ticari yönlendirme kapalıdır.');actions.push('Yalnız daha önce doğrulanmış ve test edilmiş kaynağı üretici talimatına göre kullanın. Jeneratörü kapalı veya yarı kapalı alanda kullanmayın.');return done('active_outage','Aktif kesintide güvenli kullanım öncelikli',input,metrics,actions,warnings,evidence,commercial);}
 commercial.allowed=true;commercial.category='high_power_power_station';commercial.url='/amazon-elektrik-urunleri/tasinabilir-guc-istasyonu-secimi?from=yuksek-guclu-ev-aleti';commercial.reason=input.sourceStatus==='existing'?'Mevcut kaynak doğrulanan güç veya enerji hedefini karşılamıyor.':'Doğrulanan cihaz yükü için uygun kaynak bulunmuyor.';
 actions.push(`En az ${metrics.continuousW} W sürekli, ${metrics.surgeW} W tepe ve yaklaşık ${metrics.requiredNominalWh} Wh nominal kapasite sağlayan saf sinüs AC kaynak sınıfını karşılaştırın.`,'Tam model teknik föyünde AC çıkış gücü, aşırı yük davranışı, batarya kimyası, garanti ve servis koşullarını yeniden doğrulayın.');return done('capacity_gap','Doğrulanmış kapasite açığı var',input,metrics,actions,warnings,evidence,commercial);
}
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function render(r,doc){const box=doc.getElementById('result'),labels={emergency:'Acil güvenlik',professional:'Profesyonel değerlendirme',unsafe_use:'Uygun olmayan kullanım',incomplete:'Eksik veri',needs_evidence:'Kanıt gerekli',no_buy:'Yeni ürün gerekmiyor',test_first:'Önce test',active_outage:'Aktif kesinti',capacity_gap:'Koşullu ürün karşılaştırması'},list=a=>a.length?`<ul>${a.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'<p>Yok.</p>',metrics=Object.entries(r.metrics).filter(([,v])=>v!==null).map(([k,v])=>`<div><span>${esc(k)}</span><strong>${esc(v)}</strong></div>`).join('');box.hidden=false;box.innerHTML=`<div class="result-head"><span class="status status-${esc(r.status)}">${esc(labels[r.status]||r.status)}</span><h2>${esc(r.title)}</h2></div>${metrics?`<div class="metric-grid">${metrics}</div>`:''}<section><h3>Önerilen adımlar</h3>${list(r.actions)}</section><section><h3>Uyarılar</h3>${list(r.warnings)}</section><section><h3>Hesap ve kanıt izi</h3>${list(r.evidence)}</section><section id="affiliateBox" class="affiliate-box" ${r.commercial.allowed?'':'hidden'}><h3>Şeffaf ürün karşılaştırması</h3><p>${esc(r.commercial.reason||'')}</p><label><input type="checkbox" data-affiliate-check> Mevcut güvenli kaynağın hedefi karşılamadığını doğruladım.</label><label><input type="checkbox" data-affiliate-check> Tam modelde sürekli W, tepe W, Wh, saf sinüs ve çıkış düzenini yeniden kontrol edeceğim.</label><label><input type="checkbox" data-affiliate-check> Sonraki dış bağlantıların Amazon satış ortaklığı bağlantısı olabileceğini ve ALO186'in komisyon kazanabileceğini anlıyorum.</label><a id="affiliateLink" class="button disabled" aria-disabled="true" tabindex="-1" href="${esc(r.commercial.url||'#')}" rel="sponsored nofollow noopener">Uygun power station sınıfını karşılaştır</a><small>ALO186 fiyat, stok, puan, satıcı, teslimat veya garanti iddiası yayımlamaz. Bağlantı kullanımı size ek maliyet getirmez.</small></section>`;box.tabIndex=-1;box.focus();const checks=[...box.querySelectorAll('[data-affiliate-check]')],link=box.querySelector('#affiliateLink'),update=()=>{const ok=checks.length===3&&checks.every(x=>x.checked);link.classList.toggle('disabled',!ok);link.setAttribute('aria-disabled',String(!ok));link.tabIndex=ok?0:-1;};checks.forEach(x=>x.addEventListener('change',update));}
function mount(doc,win){const form=doc.getElementById('compatibilityForm');if(!form)return;form.addEventListener('submit',e=>{e.preventDefault();render(evaluate(Object.fromEntries(new FormData(form).entries())),doc);});doc.getElementById('printResult')?.addEventListener('click',()=>win.print());doc.getElementById('resetForm')?.addEventListener('click',()=>{form.reset();const box=doc.getElementById('result');box.hidden=true;box.innerHTML='';});}
return {evaluate,mount,round,ceilStep:ceil};
});
