(() => {
  'use strict';
  const catalog=window.Alo186ProductCatalog;
  const byId=(id)=>document.getElementById(id);
  const labels={capacityMah:'Kapasite',energyWh:'Enerji',capacityWh:'Kapasite',maxOutputW:'Maks. çıkış',maxSingleDeviceW:'Tek cihaz gücü',totalOutputW:'Toplam güç',continuousW:'Sürekli güç',surgeW:'Tepe güç',outlets:'Priz',joules:'Joule',maxCurrentA:'Nominal akım',maxPowerW:'Etiket gücü',usbPorts:'USB portu',usbCPorts:'USB-C portu',usbAPorts:'USB-A portu',ports:'Toplam port',cableM:'Kablo',lengthM:'Uzunluk',energyMonitoring:'Enerji izleme',wifiGHz:'Wi-Fi',matter:'Matter',motorHp:'Motor sınırı',operatingTempMaxC:'Maks. ortam',pureSine:'Dalga biçimi',chemistry:'Kimya',solarVoltageMinV:'PV min. V',solarVoltageMaxV:'PV maks. V',solarCurrentMaxA:'PV maks. A',solarPowerMaxW:'PV maks. W',usbCMaxW:'USB-C',epsTransferMs:'EPS geçişi',sensor:'Sensör',alarmDb:'Alarm',batteryType:'Pil',batteryLifeYearsClaim:'Pil ömrü beyanı',standard:'Standart',dataTransferGbps:'Veri hızı',dataTransferMbps:'Veri hızı',maxDataGbps:'Bant genişliği',hdmiVersion:'HDMI',displayPortVersion:'DisplayPort',maxResolution:'Azami çözünürlük',maxResolutionClaim:'Çözünürlük beyanı',max4KRefreshHz:'4K yenileme',max2KRefreshHz:'2K yenileme',pdPassThroughW:'PD geçişi',includedCableW:'Dahil kablo',includedCableM:'Dahil kablo uzunluğu',pd31:'USB PD 3.1',pps:'PPS',gan:'GaN',bidirectional:'Çift yön',powerDelivery:'Güç aktarımı'};
  const suffix={capacityMah:' mAh',energyWh:' Wh',capacityWh:' Wh',maxOutputW:' W',maxSingleDeviceW:' W',totalOutputW:' W',continuousW:' W',surgeW:' W',joules:' J',maxCurrentA:' A',maxPowerW:' W',cableM:' m',lengthM:' m',wifiGHz:' GHz',motorHp:' HP',operatingTempMaxC:' °C',solarVoltageMinV:' V',solarVoltageMaxV:' V',solarCurrentMaxA:' A',solarPowerMaxW:' W',usbCMaxW:' W',epsTransferMs:' ms',alarmDb:' dB',batteryLifeYearsClaim:' yıl',dataTransferGbps:' Gbps',dataTransferMbps:' Mbps',maxDataGbps:' Gbps',max4KRefreshHz:' Hz',max2KRefreshHz:' Hz',pdPassThroughW:' W',includedCableW:' W',includedCableM:' m'};
  let graph={needs:[],categories:[],products:[]};
  let filters={category:'all',need:'all',status:'all'};
  function node(tag,className,text){const item=document.createElement(tag);if(className)item.className=className;if(text!==undefined)item.textContent=String(text);return item;}
  function value(key,input){if(input===true)return key==='pureSine'?'Saf sinüs':'Var';if(input===false)return'Yok';if(input===null||input===undefined)return'Bilinmiyor';return`${input}${suffix[key]||''}`;}
  function track(event,data={}){if(typeof window.Alo186Track!=='function')return;const safe={};for(const key of['product_id','category','status','link_mode','gate_state'])if(typeof data[key]==='string'&&data[key].length<90)safe[key]=data[key];window.Alo186Track(event,safe);}
  function isCatalogProduct(product){if(typeof catalog?.isCatalogProduct==='function')return catalog.isCatalogProduct(product);return['verified_listing','manufacturer_verified_search'].includes(product?.status);}
  function graphFromCatalog(){
    if(!catalog||!Array.isArray(catalog.products)||!Array.isArray(catalog.categories))throw new Error('Canlı ürün kataloğu yüklenemedi.');
    const needs=Array.isArray(catalog.needs)?catalog.needs.map((item)=>({id:item.id,name:item.name})):[];
    const categories=catalog.categories.map((item)=>{const relations=catalog.categoryRelations?.[item.id]||{};return{id:item.id,name:item.name,risk:item.risk,affiliatePolicy:item.affiliatePolicy,toolUrls:[...(relations.tools||[]),...(item.nextStepUrl?[item.nextStepUrl.replace('https://www.alo186.com','').replace('https://alo186.com','')]:[])],guideUrls:[...(relations.guides||[])]};});
    const products=catalog.products.filter(isCatalogProduct).map((product)=>({id:product.id,name:product.name,brand:product.brand,model:product.model||product.mpn||product.id,categoryId:product.category,needIds:product.needIds||catalog.categoryNeeds?.[product.category]||[],intentIds:product.intentIds||[],verificationStatus:product.status,verifiedAt:product.verifiedAt,linkMode:product.linkMode||(product.asin?'asin_detail':'exact_model_search'),identifier:{type:product.asin?'ASIN':'Model',value:product.asin||product.model||product.mpn||product.id},technicalProperties:product.attributes||{},requiredEvidence:product.requiredEvidence||catalog.categoryRelations?.[product.category]?.evidence||[],userNeed:product.userNeed||null,bestFor:product.bestFor||[],noBuyWhen:product.noBuyWhen||[],strengths:product.strengths||[],limits:product.limits||[],officialSource:product.technicalSource||null,relatedTools:product.relatedTools||catalog.categoryRelations?.[product.category]?.tools||[],relatedGuides:product.relatedGuides||catalog.categoryRelations?.[product.category]?.guides||[],sourceNote:product.sourceNote||''}));
    return{version:catalog.knowledgeGraphSummary?.().version||'live-catalog',generatedAt:new Date().toISOString().slice(0,10),canonicalUrl:'https://www.alo186.com/urun-bilgi-grafigi/',needs,categories,products};
  }
  function mergeGraph(staticGraph,liveGraph){const needs=new Map((staticGraph.needs||[]).map((item)=>[item.id,item]));for(const item of liveGraph.needs||[])needs.set(item.id,item);const categories=new Map((staticGraph.categories||[]).map((item)=>[item.id,item]));for(const item of liveGraph.categories||[])categories.set(item.id,item);const products=new Map((staticGraph.products||[]).map((item)=>[item.id,item]));for(const item of liveGraph.products||[])products.set(item.id,{...(products.get(item.id)||{}),...item});return{...staticGraph,...liveGraph,needs:[...needs.values()],categories:[...categories.values()],products:[...products.values()]};}
  function categoryFor(product){return graph.categories.find((item)=>item.id===product.categoryId)||null;}
  function needsFor(product){return(product.needIds||[]).map((id)=>graph.needs.find((item)=>item.id===id)?.name||id);}
  function statusClass(product,live){const freshness=live?catalog.verificationStatus(live,new Date()):{fresh:false};if(!freshness.fresh)return'status stale';return product.verificationStatus==='manufacturer_verified_search'?'status search':'status';}
  function statusLabel(product){return product.verificationStatus==='verified_listing'?'Doğrulanmış ASIN':'Üretici verisi · tam model araması';}
  function addList(card,title,items){if(!Array.isArray(items)||!items.length)return;card.append(node('h4','',title));const list=node('ul');for(const item of items)list.append(node('li','',item));card.append(list);}
  function addSources(card,product){const links=node('div','links');if(product.officialSource){const source=node('a','','Üretici teknik kaynağı ↗');source.href=product.officialSource;source.target='_blank';source.rel='noopener';links.append(source);}for(const url of(product.relatedTools||[]).slice(0,1)){const link=node('a','','Ücretsiz uygunluk aracı →');link.href=url;links.append(link);}for(const url of(product.relatedGuides||[]).slice(0,1)){const link=node('a','','Teknik rehber →');link.href=url;links.append(link);}card.append(links);}
  function allChecked(gate){return[...gate.querySelectorAll('input[type=checkbox]')].every((input)=>input.checked);}
  function addGate(card,product,live,category){
    if(!live||!isCatalogProduct(live)){const block=node('div','blocked');block.append(node('strong','','Katalog düğümü doğrulanamadı.'),node('p','','Affiliate bağlantısı gösterilmiyor.'));card.append(block);return;}
    const fresh=catalog.verificationStatus(live,new Date()).fresh;
    if(!fresh){const block=node('div','blocked');block.append(node('strong','','45 günlük doğrulama süresi geçti.'),node('p','','Teknik veri yenilenene kadar affiliate bağlantısı kapalıdır.'));card.append(block);return;}
    if(!category||category.affiliatePolicy==='professional_only'){const block=node('div','blocked');block.append(node('strong','','Affiliate bağlantısı bu kategoride kapalı.'),node('p','','Ölçüm, sabit tesisat veya can güvenliği nedeniyle yalnız güvenli teknik yönlendirme gösterilir.'));const link=node('a','tool','Güvenli sonraki adımı aç');link.href=(category?.toolUrls||[])[0]||'/karar-motoru/';block.append(link);card.append(block);return;}
    const gate=node('div','gate');gate.append(node('strong','','Affiliate bağlantısı için üç doğrulama'));for(const text of['İlgili ücretsiz uygunluk aracını tamamladım.','Mevcut güvenli ürünüm bu ihtiyacı karşılamıyor.','Bağlantının satış ortaklığı bağlantısı olduğunu anladım.']){const label=node('label');const input=document.createElement('input');input.type='checkbox';label.append(input,node('span','',text));gate.append(label);}gate.append(node('p','note',product.linkMode==='exact_model_search'?'Üretici teknik verisi doğrulandı; Amazon bağlantısı tek ürün önerisi değil, tam model aramasıdır. Varyantı yeniden doğrulayın.':'Belirli ASIN kontrol edilmiştir; fiyat, stok, satıcı, teslimat ve garanti Amazon’da yeniden doğrulanır.'));
    const link=node('a','affiliate',product.linkMode==='exact_model_search'?'Amazon’da tam model araması':'Amazon ürün sayfasını aç');link.target='_blank';link.rel='sponsored nofollow noopener';link.setAttribute('aria-disabled','true');link.tabIndex=-1;gate.append(link);const sync=()=>{const ready=allChecked(gate);link.setAttribute('aria-disabled',ready?'false':'true');link.tabIndex=ready?0:-1;if(ready)link.href=live.url;else link.removeAttribute('href');track('affiliate_knowledge_graph_gate_changed',{product_id:product.id,category:product.categoryId,status:product.verificationStatus,link_mode:product.linkMode,gate_state:ready?'open':'closed'});};gate.addEventListener('change',sync);link.addEventListener('click',(event)=>{if(!allChecked(gate)){event.preventDefault();return;}track('affiliate_knowledge_graph_link_opened',{product_id:product.id,category:product.categoryId,status:product.verificationStatus,link_mode:product.linkMode,gate_state:'open'});});card.append(gate);sync();
  }
  function cardFor(product){const live=catalog.getProduct(product.id),category=categoryFor(product),card=node('article','card');card.id=`product-${product.id}`;card.append(node('span',statusClass(product,live),statusLabel(product)),node('h3','',product.name),node('div','model',`${product.brand} · ${product.model} · ${product.identifier.type} ${product.identifier.value}`));const relations=node('div','relations');relations.append(node('span','chip',`İhtiyaç: ${needsFor(product).join(', ')||'genel teknik ihtiyaç'}`),node('span','chip',`Kategori: ${category?.name||product.categoryId}`),node('span','chip',`Politika: ${category?.affiliatePolicy||'bilinmiyor'}`));card.append(relations);if(product.userNeed)card.append(node('p','user-need',product.userNeed));const properties=node('div','properties');for(const[key,input]of Object.entries(product.technicalProperties||{}).slice(0,12)){const box=node('div');box.append(node('small','',labels[key]||key),node('strong','',value(key,input)));properties.append(box);}card.append(properties);addList(card,'En uygun kullanım',product.bestFor?.length?product.bestFor:(product.strengths||[]).slice(0,3));addList(card,'Yeniden doğrulanacak kanıt',product.requiredEvidence);addList(card,'Satın almama / durdurma koşulu',product.noBuyWhen?.length?product.noBuyWhen:(product.limits||[]).slice(0,3));addSources(card,product);addGate(card,product,live,category);return card;}
  function matches(product){return(filters.category==='all'||product.categoryId===filters.category)&&(filters.need==='all'||(product.needIds||[]).includes(filters.need))&&(filters.status==='all'||product.verificationStatus===filters.status);}
  function render(){const products=graph.products.filter(matches);byId('productGrid').replaceChildren(...products.map(cardFor));byId('emptyState').classList.toggle('hidden',products.length>0);byId('resultStatus').textContent=`${products.length} ürün düğümü gösteriliyor.`;}
  function option(select,valueInput,text){const item=document.createElement('option');item.value=valueInput;item.textContent=text;select.append(item);}
  async function loadStaticGraph(){try{const response=await fetch('./product-graph.json',{cache:'no-cache'});if(!response.ok)return{needs:[],categories:[],products:[]};return response.json();}catch(_){return{needs:[],categories:[],products:[]};}}
  async function init(){if(!catalog||typeof catalog.getProduct!=='function')throw new Error('Katalog Knowledge Graph uzantısı yüklenemedi.');graph=mergeGraph(await loadStaticGraph(),graphFromCatalog());byId('needCount').textContent=graph.needs.length;byId('categoryCount').textContent=graph.categories.length;byId('productCount').textContent=graph.products.length;const searchCount=graph.products.filter((item)=>item.verificationStatus==='manufacturer_verified_search').length,exactCount=graph.products.filter((item)=>item.verificationStatus==='verified_listing').length;byId('newModelCount').textContent=searchCount;byId('heroProductCount').textContent=graph.products.length;byId('heroExactCount').textContent=exactCount;byId('heroSearchCount').textContent=searchCount;const jsonLd=byId('affiliateProductGraphJsonLd');if(jsonLd&&typeof catalog.knowledgeGraph==='function')jsonLd.textContent=JSON.stringify(catalog.knowledgeGraph());for(const item of graph.categories)option(byId('categoryFilter'),item.id,item.name);for(const item of graph.needs)option(byId('needFilter'),item.id,item.name);render();byId('categoryFilter').addEventListener('change',(event)=>{filters.category=event.target.value;render();});byId('needFilter').addEventListener('change',(event)=>{filters.need=event.target.value;render();});byId('statusFilter').addEventListener('change',(event)=>{filters.status=event.target.value;render();});byId('clearFilters').addEventListener('click',()=>{filters={category:'all',need:'all',status:'all'};for(const id of['categoryFilter','needFilter','statusFilter'])byId(id).value='all';render();});}
  document.addEventListener('DOMContentLoaded',()=>init().catch(()=>{byId('resultStatus').textContent='Bilgi grafiği yüklenemedi; affiliate bağlantıları gösterilmiyor.';byId('emptyState').classList.remove('hidden');}));
})();
