(() => {
  'use strict';
  const catalog=window.Alo186ProductCatalog;
  const byId=(id)=>document.getElementById(id);
  const labels={capacityMah:'Kapasite',energyWh:'Enerji',maxOutputW:'Maks. çıkış',outlets:'Priz',joules:'Joule',maxCurrentA:'Nominal akım',maxPowerW:'Etiket gücü',usbPorts:'USB portu',cableM:'Kablo',energyMonitoring:'Enerji izleme',wifiGHz:'Wi-Fi',matter:'Matter',motorHp:'Motor sınırı',operatingTempMaxC:'Maks. ortam',capacityWh:'Kapasite',continuousW:'Sürekli güç',surgeW:'Tepe güç',pureSine:'Dalga biçimi',chemistry:'Kimya',solarVoltageMinV:'PV min. V',solarVoltageMaxV:'PV maks. V',solarCurrentMaxA:'PV maks. A',solarPowerMaxW:'PV maks. W',usbCMaxW:'USB-C',epsTransferMs:'EPS geçişi',sensor:'Sensör',alarmDb:'Alarm',batteryType:'Pil',batteryLifeYearsClaim:'Pil ömrü beyanı',standard:'Standart'};
  let graph={needs:[],categories:[],products:[]};
  let filters={category:'all',need:'all',status:'all'};

  function node(tag,className,text){const item=document.createElement(tag);if(className)item.className=className;if(text!==undefined)item.textContent=String(text);return item;}
  function value(key,input){if(input===true)return key==='pureSine'?'Saf sinüs':'Var';if(input===false)return'Yok';if(input===null||input===undefined)return'Bilinmiyor';const suffix={capacityMah:' mAh',energyWh:' Wh',maxOutputW:' W',joules:' J',maxCurrentA:' A',maxPowerW:' W',cableM:' m',wifiGHz:' GHz',motorHp:' HP',operatingTempMaxC:' °C',capacityWh:' Wh',continuousW:' W',surgeW:' W',solarVoltageMinV:' V',solarVoltageMaxV:' V',solarCurrentMaxA:' A',solarPowerMaxW:' W',usbCMaxW:' W',epsTransferMs:' ms',alarmDb:' dB',batteryLifeYearsClaim:' yıl'};return `${input}${suffix[key]||''}`;}
  function track(event,data={}){if(typeof window.Alo186Track!=='function')return;const safe={};for(const key of['product_id','category','status','link_mode','gate_state'])if(typeof data[key]==='string'&&data[key].length<90)safe[key]=data[key];window.Alo186Track(event,safe);}
  function categoryFor(product){return graph.categories.find((item)=>item.id===product.categoryId)||null;}
  function needsFor(product){return(product.needIds||[]).map((id)=>graph.needs.find((item)=>item.id===id)?.name||id);}
  function statusClass(product,live){const freshness=live?catalog.verificationStatus(live,new Date()):{fresh:false};if(!freshness.fresh)return'status stale';return product.verificationStatus==='manufacturer_verified_search'?'status search':'status';}
  function statusLabel(product){return product.verificationStatus==='verified_listing'?'Doğrulanmış ASIN':'Üretici verisi · tam model araması';}
  function addList(card,title,items){if(!Array.isArray(items)||!items.length)return;card.append(node('h4','',title));const list=node('ul');items.forEach((item)=>list.append(node('li','',item)));card.append(list);}
  function addSources(card,product){const links=node('div','links');if(product.officialSource){const source=node('a','','Üretici teknik kaynağı ↗');source.href=product.officialSource;source.target='_blank';source.rel='noopener';links.append(source);}for(const url of(product.relatedTools||[]).slice(0,1)){const link=node('a','','Ücretsiz uygunluk aracı →');link.href=url;links.append(link);}for(const url of(product.relatedGuides||[]).slice(0,1)){const link=node('a','','Teknik rehber →');link.href=url;links.append(link);}card.append(links);}
  function allChecked(gate){return[...gate.querySelectorAll('input[type=checkbox]')].every((input)=>input.checked);}
  function addGate(card,product,live,category){if(!live||!catalog.isCatalogProduct(live)){const block=node('div','blocked');block.append(node('strong','','Katalog düğümü doğrulanamadı.'),node('p','','Affiliate bağlantısı gösterilmiyor.'));card.append(block);return;}const fresh=catalog.verificationStatus(live,new Date()).fresh;if(!fresh){const block=node('div','blocked');block.append(node('strong','','45 günlük doğrulama süresi geçti.'),node('p','','Teknik veri yenilenene kadar affiliate bağlantısı kapalıdır.'));card.append(block);return;}if(!category||category.affiliatePolicy==='professional_only'){const block=node('div','blocked');block.append(node('strong','','Affiliate bağlantısı bu kategoride kapalı.'),node('p','','Ölçüm, sabit tesisat veya can güvenliği nedeniyle yalnız güvenli teknik yönlendirme gösterilir.'));const link=node('a','tool','Güvenli sonraki adımı aç');link.href=(category?.toolUrls||[])[0]||'/karar-motoru/';block.append(link);card.append(block);return;}const gate=node('div','gate');gate.append(node('strong','','Affiliate bağlantısı için üç doğrulama'));for(const text of['İlgili ücretsiz uygunluk aracını tamamladım.','Mevcut ürünüm güvenli biçimde ihtiyacı karşılamıyor.','Bağlantının satış ortaklığı bağlantısı olduğunu anladım.']){const label=node('label');const input=document.createElement('input');input.type='checkbox';label.append(input,node('span','',text));gate.append(label);}gate.append(node('p','note',product.linkMode==='exact_model_search'?'Üretici teknik verisi doğrulandı; Amazon bağlantısı tek ürün önerisi değil, tam model aramasıdır. Varyantı yeniden doğrulayın.':'Belirli ASIN kontrol edilmiştir; fiyat, stok, satıcı, teslimat ve garanti Amazon’da yeniden doğrulanır.'));const link=node('a','affiliate',product.linkMode==='exact_model_search'?'Amazon’da tam model araması':'Amazon ürün sayfasını aç');link.href=live.url;link.target='_blank';link.rel='sponsored nofollow noopener';link.setAttribute('aria-disabled','true');link.tabIndex=-1;gate.append(link);gate.addEventListener('change',()=>{const ready=allChecked(gate);link.setAttribute('aria-disabled',ready?'false':'true');link.tabIndex=ready?0:-1;track('affiliate_knowledge_graph_gate_changed',{product_id:product.id,category:product.categoryId,status:product.verificationStatus,link_mode:product.linkMode,gate_state:ready?'open':'closed'});});link.addEventListener('click',(event)=>{if(!allChecked(gate)){event.preventDefault();return;}track('affiliate_knowledge_graph_link_opened',{product_id:product.id,category:product.categoryId,status:product.verificationStatus,link_mode:product.linkMode,gate_state:'open'});});card.append(gate);}
  function cardFor(product){const live=catalog.getProduct(product.id);const category=categoryFor(product);const card=node('article','card');card.id=`product-${product.id}`;card.append(node('span',statusClass(product,live),statusLabel(product)),node('h3','',product.name),node('div','model',`${product.brand} · ${product.model} · ${product.identifier.type} ${product.identifier.value}`));const relations=node('div','relations');relations.append(node('span','chip',`İhtiyaç: ${needsFor(product).join(', ')}`),node('span','chip',`Kategori: ${category?.name||product.categoryId}`),node('span','chip',`Politika: ${category?.affiliatePolicy||'bilinmiyor'}`));card.append(relations);const properties=node('div','properties');for(const[key,input]of Object.entries(product.technicalProperties||{}).slice(0,10)){const box=node('div');box.append(node('small','',labels[key]||key),node('strong','',value(key,input)));properties.append(box);}card.append(properties);addList(card,'Yeniden doğrulanacak kanıt',product.requiredEvidence);addSources(card,product);addGate(card,product,live,category);return card;}
  function matches(product){return(filters.category==='all'||product.categoryId===filters.category)&&(filters.need==='all'||(product.needIds||[]).includes(filters.need))&&(filters.status==='all'||product.verificationStatus===filters.status);}
  function render(){const products=graph.products.filter(matches);byId('productGrid').replaceChildren(...products.map(cardFor));byId('emptyState').classList.toggle('hidden',products.length>0);byId('resultStatus').textContent=`${products.length} ürün düğümü gösteriliyor.`;}
  function option(select,value,text){const item=document.createElement('option');item.value=value;item.textContent=text;select.append(item);}
  async function init(){if(!catalog||typeof catalog.getProduct!=='function')throw new Error('Katalog Knowledge Graph uzantısı yüklenemedi.');const response=await fetch('./product-graph.json',{cache:'no-cache'});if(!response.ok)throw new Error(`HTTP ${response.status}`);graph=await response.json();byId('needCount').textContent=graph.needs.length;byId('categoryCount').textContent=graph.categories.length;byId('productCount').textContent=graph.products.length;byId('newModelCount').textContent=graph.products.filter((item)=>item.verificationStatus==='manufacturer_verified_search').length;graph.categories.forEach((item)=>option(byId('categoryFilter'),item.id,item.name));graph.needs.forEach((item)=>option(byId('needFilter'),item.id,item.name));render();byId('categoryFilter').addEventListener('change',(event)=>{filters.category=event.target.value;render();});byId('needFilter').addEventListener('change',(event)=>{filters.need=event.target.value;render();});byId('statusFilter').addEventListener('change',(event)=>{filters.status=event.target.value;render();});byId('clearFilters').addEventListener('click',()=>{filters={category:'all',need:'all',status:'all'};for(const id of['categoryFilter','needFilter','statusFilter'])byId(id).value='all';render();});}
  document.addEventListener('DOMContentLoaded',()=>init().catch(()=>{byId('resultStatus').textContent='Bilgi grafiği yüklenemedi; affiliate bağlantıları gösterilmiyor.';byId('emptyState').classList.remove('hidden');}));
})();
