(()=>{
'use strict';
const $=id=>document.getElementById(id);
const form=$('evChargeForm');
const resultEl=$('result');
const affiliateGate=$('affiliateGate');
const affiliateAction=$('affiliateAction');
let lastResult=null;
const boolIds=['connectorVerified','vehicleDocsVerified','evseDocsVerified','installationPowerVerified','dedicatedCircuit','protectionCoordinationVerified','residualProtectionVerified','earthVerified','commissioningPassed','damageFree','noRecurringTrips','directEvseConnection','loadManagementRequired','loadManagementVerified','advancedEnergySystem','existingSafeSolutionAdequate'];
const valueIds=['usage','ownership','phase','batteryKwh','currentSoc','targetSoc','planningEfficiencyPct','targetHours','vehicleAcMaxKw','evseMaxKw','installationMaxKw'];
function values(){const data={};valueIds.forEach(id=>data[id]=$(id).value);boolIds.forEach(id=>data[id]=$(id).checked);return data;}
function fmt(value,d=1){return Number(value).toLocaleString('tr-TR',{maximumFractionDigits:d});}
function esc(text){return String(text).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function hours(value){const total=Math.max(0,Number(value));const h=Math.floor(total);const min=Math.round((total-h)*60);if(h===0)return `${min} dk`;if(min===60)return `${h+1} sa`;return min?`${h} sa ${min} dk`:`${h} sa`;}
function list(title,items,kind='neutral'){if(!items||!items.length)return '';return `<div class="result-list ${kind}"><h3>${esc(title)}</h3><ul>${items.map(item=>`<li>${esc(item)}</li>`).join('')}</ul></div>`;}
function statusText(r){if(r.noPurchaseNeeded)return ['Mevcut çözüm yeterli','Yeni wallbox almayın'];if(r.blockers.length)return ['Önce elektrik güvenliğini çözün','Ürün yönlendirmesi kapalı'];if(!r.targetFeasibleByVehicleAndSite)return ['Hedef süre yalnız wallbox ile mümkün görünmüyor','Araç veya tesisat darboğazını çözün'];if(!r.candidateMeetsTime)return ['EVSE hedef sürenin altında kalıyor','Daha yüksek etkili güç ancak araç ve tesisat izin veriyorsa işe yarar'];if(r.commercialAllowed)return ['Teknik ön koşullar uyumlu','Aday wallbox sınıfı karşılaştırılabilir'];return ['Koşullu sonuç','Eksik kanıtları doğrulayın'];}
function render(r){
  const [title,subtitle]=statusText(r);
  const useful=r.usefulClassKw?`${fmt(r.usefulClassKw,1)} kW yaygın sınıf veya tam model eşdeğeri`:`${fmt(r.usefulCeilingKw,1)} kW üstüne çıkmadan tam model karşılaştırması`;
  const targetClass=r.requiredEffectiveKw<=r.usefulCeilingKw+0.001?useful:'Daha büyük wallbox değil; araç/tesisat sınırı belirleyici';
  resultEl.innerHTML=`<div class="result-head"><div><span class="eyebrow">Sonuç</span><h2>${esc(title)}</h2><p>${esc(subtitle)}</p></div><span class="status-pill ${r.blockers.length?'bad':r.noPurchaseNeeded?'good':r.commercialAllowed?'good':'warn'}">${r.blockers.length?'Güvenlik kapısı':r.noPurchaseNeeded?'Satın alma yok':r.commercialAllowed?'Uygun aday':'Doğrulama gerekli'}</span></div><div class="metrics"><article><span>Bataryaya eklenecek</span><strong>${fmt(r.batteryEnergyKwh,2)} kWh</strong></article><article><span>Yaklaşık şebeke enerjisi</span><strong>${fmt(r.gridEnergyKwh,2)} kWh</strong></article><article><span>Etkili AC güç</span><strong>${fmt(r.effectivePowerKw,2)} kW</strong></article><article><span>Yaklaşık şarj süresi</span><strong>${hours(r.chargeTimeHours)}</strong></article><article><span>Hedef süre için etkili güç</span><strong>${fmt(r.requiredEffectiveKw,2)} kW</strong></article><article><span>Yaklaşık hat akımı*</span><strong>${fmt(r.approximateCurrentA,1)} A</strong></article></div><div class="decision-card"><h3>Darboğaz</h3><p>${r.bottlenecks.length?esc(r.bottlenecks.join(' + ')):'Birden fazla yakın sınır olabilir; tam model verisini doğrulayın.'}</p><h3>Faydalı wallbox yönü</h3><p>${esc(targetClass)}</p><small>* Akım yalnız yaklaşık güç dönüşümüdür; kablo/sigorta boyutlandırması değildir.</small></div>${list('Ürün seçimini durduran nedenler',r.blockers,'bad')}${list('Dikkat / belirsizlikler',r.warnings,'warn')}${list('Sonraki doğrulamalar',r.checks,'neutral')}${r.noPurchaseNeeded?'<div class="no-buy"><strong>Satın almama sonucu:</strong> Güvenli mevcut çözüm hedef süreyi karşılıyorsa yeni wallbox almak yerine mevcut kurulumun periyodik kontrolünü sürdürün.</div>':''}`;
  resultEl.hidden=false;resultEl.focus({preventScroll:true});resultEl.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});affiliateGate.hidden=!r.commercialAllowed;if(!r.commercialAllowed){affiliateAction.innerHTML='';}updateAffiliate();
}
function updateAffiliate(){if(!lastResult||!lastResult.commercialAllowed||affiliateGate.hidden)return;const ready=$('affNeed').checked&&$('affSpecs').checked&&$('affDisclosure').checked;if(!ready){affiliateAction.innerHTML='<p class="gate-note">Üç doğrulamayı tamamlayınca Amazon Türkiye kategori araması etkinleşir.</p>';return;}const query=encodeURIComponent(lastResult.affiliateQuery);const href=`https://www.amazon.com.tr/s?k=${query}&tag=alo186rehber-21`;affiliateAction.innerHTML=`<a class="affiliate-link" href="${href}" target="_blank" rel="sponsored nofollow noopener">Amazon Türkiye’de uygun wallbox/EVSE sınıfını karşılaştır →</a><small>Satış ortaklığı bağlantısıdır. Tam modelin araç, tesisat, konnektör ve koruma uyumu satın almadan önce yeniden doğrulanmalıdır.</small>`;}
function reset(){form.reset();applyPreset('home7');resultEl.hidden=true;affiliateGate.hidden=true;affiliateAction.innerHTML='';['affNeed','affSpecs','affDisclosure'].forEach(id=>$(id).checked=false);lastResult=null;}
function safeChecks(on=false){['connectorVerified','vehicleDocsVerified','evseDocsVerified','installationPowerVerified','dedicatedCircuit','protectionCoordinationVerified','residualProtectionVerified','earthVerified','commissioningPassed','damageFree','noRecurringTrips','directEvseConnection'].forEach(id=>$(id).checked=on);$('loadManagementRequired').checked=false;$('loadManagementVerified').checked=false;$('advancedEnergySystem').checked=false;$('existingSafeSolutionAdequate').checked=false;}
function applyPreset(name){$('usage').value='private';$('ownership').value='candidate';$('planningEfficiencyPct').value='90';$('targetHours').value='8';safeChecks(false);if(name==='home11'){$('batteryKwh').value='75';$('currentSoc').value='20';$('targetSoc').value='80';$('vehicleAcMaxKw').value='11';$('evseMaxKw').value='11';$('installationMaxKw').value='11';$('phase').value='three';}else if(name==='oversize'){$('batteryKwh').value='75';$('currentSoc').value='20';$('targetSoc').value='80';$('vehicleAcMaxKw').value='11';$('evseMaxKw').value='22';$('installationMaxKw').value='22';$('phase').value='three';}else{$('batteryKwh').value='60';$('currentSoc').value='20';$('targetSoc').value='80';$('vehicleAcMaxKw').value='7.4';$('evseMaxKw').value='7.4';$('installationMaxKw').value='7.4';$('phase').value='single';}}
form.addEventListener('submit',event=>{event.preventDefault();try{lastResult=window.Alo186EvHomeCharge.analyze(values());render(lastResult);}catch(error){resultEl.hidden=false;resultEl.innerHTML=`<div class="result-head"><div><span class="eyebrow">Girdi kontrolü</span><h2>Hesap tamamlanamadı</h2><p>${esc(error.message||'Girdileri kontrol edin.')}</p></div></div>`;resultEl.focus();affiliateGate.hidden=true;lastResult=null;}});
document.querySelectorAll('[data-preset]').forEach(button=>button.addEventListener('click',()=>applyPreset(button.dataset.preset)));$('resetBtn').addEventListener('click',reset);['affNeed','affSpecs','affDisclosure'].forEach(id=>$(id).addEventListener('change',updateAffiliate));applyPreset('home7');
})();
