(()=>{'use strict';
const $=id=>document.getElementById(id),KEY='alo186_plug_voltage_monitor_v2',TTL=365*86400000,MAX=30;const today=()=>new Date().toISOString().slice(0,10);$('date').value=today();
function load(){let x=[];try{x=JSON.parse(localStorage.getItem(KEY)||'[]')}catch(_){x=[]}const now=Date.now();x=x.filter(r=>r&&Number.isFinite(r.createdAt)&&now-r.createdAt<TTL).slice(-MAX);localStorage.setItem(KEY,JSON.stringify(x));return x}
function save(x){localStorage.setItem(KEY,JSON.stringify(x.slice(-MAX)))}function labels(id){const el=$(id);return el.options[el.selectedIndex].textContent}
function render(){const x=load(),box=$('records');if(!x.length){box.innerHTML='<p class="small">Henüz kayıt yok.</p>';return}box.replaceChildren(...x.slice().reverse().map(r=>{const d=document.createElement('div');d.className='record';const s=document.createElement('strong');s.textContent=`${r.date} · ${r.symptomLabel}`;const p=document.createElement('p');p.className='small';p.textContent=`${r.scopeLabel} · ${r.goalLabel} · ${r.decision}`;d.append(s,p);return d}))}
function evaluate(r){let level='good',label='Satın almama',title='Mevcut ölçüm yolu için yeni cihaz gerekmiyor.',summary='Mevcut monitör ihtiyacı karşılıyorsa veya resmî/profesyonel ölçüm başladıysa yeni ürün almayın.',steps=['Olay saatini ve etkilenen kapsamı kaydedin.','Gerilim olay günlüğüyle sonuçları karşılaştırın.'],service=false;const officialGoal=r.goal==='official',pqGoal=r.goal==='harmonics'||r.scope==='threephase',sharedGrid=r.scope==='neighbors',buildingScope=r.scope==='building',highLoad=r.load==='heater'||r.load==='motor'||r.load==='ev',observationReady=r.outletSafe&&r.manual&&r.rating&&r.timestamp&&r.memory&&!highLoad;
if(r.hazard){level='bad';label='Ölçüm yapma';title='Priz veya devrede güvenlik tehlikesi var.';summary='Priz tipi monitör takmak mevcut bağlantı arızasını çözmez ve riski artırabilir.';steps=['Devreyi zorlamayın ve yüksek güçlü yük bağlamayın.','Elektrikçi tarafından priz, bağlantı ve devre kontrolü yaptırın.','Tehlike sürerken affiliate veya ücretli hizmet yönlendirmesi gösterilmez.']}
else if(officialGoal||sharedGrid){level='warn';label='Görevli dağıtım şirketi süreci';title='Basit priz monitörü resmî teknik kalite değerlendirmesi değildir.';summary='Komşu kullanıcıları etkileyen veya resmî kanıt amaçlı olayda önce görevli dağıtım şirketi kayıt ve ölçüm süreci izlenmelidir.';steps=['Tarih, saat, kaynak ve etkilenen kapsamı kişisel verisiz günlükte kaydedin.','Görevli dağıtım şirketine teknik kalite ölçüm talebi iletin.','ALO186 veya bağımsız hizmet sağlayıcı resmî dağıtım şirketi kararının yerine geçmez.']}
else if(pqGoal){level='warn';label='Güç kalitesi ölçümü';title='Üç faz, harmonik, flicker veya transient için priz tipi monitör yeterli değildir.';summary='Uygun güç kalitesi analizörü, zaman senkronu, ölçüm noktası ve kayıt planı gerekir.';steps=['Tek hat ve ölçüm noktalarını belirleyin.','Üç faz gerilim-akım, harmonik ve olay kayıt kapsamını tanımlayın.','Sonucu cihaz resetleri, UPS/jeneratör logları ve yük değişimleriyle eşleştirin.'];service=true}
else if(buildingScope){level='warn';label='Bina içi kaynak ayrımı';title='Tek priz gözlemi bina genelindeki kök nedeni kanıtlamaz.';summary='Şebeke, kolon hattı, nötr, pano, yük ve priz gerilim düşümü ayrı ölçülmelidir.';steps=['Ana giriş ve etkilenen tali noktalar için zaman eşleşmeli kayıt planlayın.','Nötr, faz dengesizliği ve yüksek güçlü yük etkisini ayırın.','Dağıtım şirketi kaydı gerekiyorsa bağımsız incelemeden ayrı yürütün.'];service=true}
else if(r.professional){level='good';label='Satın almama';title='Ölçüm süreci zaten başlatılmış.';summary='Aynı amaç için ek tüketici cihazı zorunlu değildir.';steps=['Kurulan cihazın ölçüm sınıfını ve zaman senkronunu kaydedin.','Sonuç raporunu olay günlüğüyle eşleştirin.']}
else if(!r.repeat){level='warn';label='Önce olay günlüğü';title='Tek olay yeni cihaz ihtiyacını kanıtlamaz.';summary='Olayı tekrar, saat ve kapsam bilgisiyle kaydedin.';steps=['Gerilim olayı günlüğünü kullanın.','Aynı prizde yüksek güçlü yük etkisini ayırın.']}
else if(!observationReady){level='warn';label='Ön gözlem kapısı eksik';title='Güvenli ve anlamlı priz gözlemi için cihaz/kurulum kanıtları eksik.';summary='Kapsamı belirsiz cihazla resmî ya da uzun süreli kanıt oluşturmayın.';steps=[];if(!r.outletSafe)steps.push('Prizin kuru, sıkı ve hasarsız olduğunu doğrulayın.');if(!r.manual||!r.rating)steps.push('Tam model ölçüm kapsamı, gerilim/akım ve güvenlik sınıfını doğrulayın.');if(!r.timestamp||!r.memory)steps.push('Tarih-saat damgası ile en az 7 günlük kayıt/dışa aktarımı doğrulayın.');if(highLoad)steps.push('Isıtıcı, motor veya EV şarj yükünde tüketici tipi monitör yerine devre ve profesyonel kayıt yolunu değerlendirin.')}
else if((r.scope==='single'||r.scope==='room')&&(r.goal==='spot'||r.goal==='week')){level='good';label='Düşük riskli ön gözlem';title='Mevcut veya kullanıcı tarafından seçilecek cihaz yalnız ön gözlem için kullanılabilir.';summary='Bu sonuç ürün önerisi, resmî ölçüm veya şebeke kusuru kanıtı değildir.';steps=['Mevcut cihazınız işlevleri karşılıyorsa yenisini almayın.','Zaman damgası, min/max ve dışa aktarım sınırını kılavuzdan doğrulayın.','Kapsam bina veya komşulara genişlerse dağıtım şirketi/profesyonel ölçüm yoluna dönün.']}
return{level,label,title,summary,steps,service}}
$('form').addEventListener('submit',e=>{e.preventDefault();const r={createdAt:Date.now(),date:$('date').value||today(),scope:$('scope').value,scopeLabel:labels('scope'),symptom:$('symptom').value,symptomLabel:labels('symptom'),goal:$('goal').value,goalLabel:labels('goal'),load:$('load').value,purpose:$('purpose').value,repeat:$('repeat').checked,outletSafe:$('outletSafe').checked,manual:$('manual').checked,rating:$('rating').checked,timestamp:$('timestamp').checked,memory:$('memory').checked,professional:$('professional').checked,hazard:$('hazard').checked,officialMeasurement:false,retentionMode:'per-record'};const out=evaluate(r);r.decision=out.label;const all=load();all.push(r);save(all);render();$('result').classList.remove('hidden');$('state').textContent=out.label;$('state').className=`pill ${out.level}`;$('title').textContent=out.title;$('summary').textContent=out.summary;$('steps').replaceChildren(...out.steps.map(t=>{const li=document.createElement('li');li.textContent=t;return li}));$('service').classList.toggle('hidden',!out.service);$('result').scrollIntoView({behavior:'smooth',block:'start'})});
$('export').addEventListener('click',()=>{const data={tool:'ALO186 priz tipi gerilim monitörü uygunluk günlüğü',exportedAt:new Date().toISOString(),rawPersonalDataCollected:false,officialMeasurement:false,directAffiliateLinks:false,records:load()};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='alo186-gerilim-monitoru-gunlugu.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)});
$('calendar').addEventListener('click',()=>{const d=new Date();d.setDate(d.getDate()+7);const fmt=x=>x.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z/,'Z');const ics=`BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//ALO186//Voltage Evidence Review//TR\r\nBEGIN:VEVENT\r\nUID:${Date.now()}@alo186.com\r\nDTSTAMP:${fmt(new Date())}\r\nDTSTART:${fmt(d)}\r\nSUMMARY:Gerilim olay kayıtlarını karşılaştır\r\nDESCRIPTION:7 günlük zaman damgalı olay, kapsam ve varsa dağıtım şirketi veya bağımsız ölçüm durumunu kontrol edin.\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([ics],{type:'text/calendar'}));a.download='gerilim-7-gun-takip.ics';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)});render()})();