(()=>{'use strict';
const $=id=>document.getElementById(id),KEY='alo186_plug_voltage_monitor_v1',TTL=365*86400000,MAX=30;const today=()=>new Date().toISOString().slice(0,10);$('date').value=today();
function load(){let x=[];try{x=JSON.parse(localStorage.getItem(KEY)||'[]')}catch(_){x=[]}const now=Date.now();x=x.filter(r=>r&&now-r.createdAt<TTL).slice(-MAX);localStorage.setItem(KEY,JSON.stringify(x));return x}function save(x){localStorage.setItem(KEY,JSON.stringify(x.slice(-MAX)))}function labels(id){const el=$(id);return el.options[el.selectedIndex].textContent}
function render(){const x=load(),box=$('records');if(!x.length){box.innerHTML='<p class="small">Henüz kayıt yok.</p>';return}box.replaceChildren(...x.slice().reverse().map(r=>{const d=document.createElement('div');d.className='record';const s=document.createElement('strong');s.textContent=`${r.date} · ${r.symptomLabel}`;const p=document.createElement('p');p.className='small';p.textContent=`${r.scopeLabel} · ${r.goalLabel} · ${r.decision}`;d.append(s,p);return d}))}
function evaluate(r){let level='good',label='Satın almama',title='Mevcut ölçüm yolu için yeni cihaz gerekmiyor.',summary='Mevcut monitör ihtiyacı karşılıyorsa veya profesyonel ölçüm başladıysa yeni ürün almayın.',steps=['Olay saatini ve etkilenen kapsamı kaydedin.','Gerilim olay günlüğüyle sonuçları karşılaştırın.'],commercial=false;const officialScope=r.scope==='building'||r.scope==='neighbors'||r.scope==='threephase'||r.goal==='official'||r.goal==='harmonics';const highLoad=r.load==='heater'||r.load==='motor'||r.load==='ev';const productGate=r.outletSafe&&r.manual&&r.rating&&r.timestamp&&r.memory&&!highLoad;
if(r.hazard){level='bad';label='Ölçüm yapma';title='Priz veya devrede güvenlik tehlikesi var.';summary='Priz tipi monitör takmak mevcut bağlantı arızasını çözmez ve riski artırabilir.';steps=['Devreyi zorlamayın ve yüksek güçlü yük bağlamayın.','Elektrikçi tarafından priz, bağlantı ve devre kontrolü yaptırın.','Tehlike sürerken ürün veya affiliate yolu kapalıdır.']}
else if(officialScope){level='warn';label='Profesyonel / EDAŞ ölçümü';title='Basit priz monitörü bu kanıt amacı için yeterli değildir.';summary='Bina geneli, komşu kullanıcılar, üç faz, harmonik veya resmî teknik kalite için uygun cihaz ve kayıt süreci gerekir.';steps=['Gerilim olayı günlüğünde tarih, saat, kaynak ve kapsamı kaydedin.','Önce görevli dağıtım şirketine teknik kalite ölçüm talebi iletin.','Harmonik, flicker, transient veya üç faz için uygun güç kalitesi loggerı kullanın.','ALO186 kaydı resmî ölçüm değildir.']}
else if(r.professional){level='good';label='Satın almama';title='Profesyonel ölçüm süreci zaten başlatılmış.';summary='Aynı amaç için ek tüketici cihazı zorunlu değildir.';steps=['Kurulan cihazın ölçüm sınıfını ve zaman senkronunu kaydedin.','Sonuç raporunu olay günlüğüyle eşleştirin.']}
else if(!r.repeat){level='warn';label='Önce olay günlüğü';title='Tek olay yeni cihaz ihtiyacını kanıtlamaz.';summary='Olayı tekrar, saat ve kapsam bilgisiyle kaydedin.';steps=['Gerilim olayı günlüğünü kullanın.','Aynı prizde yüksek güçlü yük etkisini ayırın.']}
else if(!productGate){level='warn';label='Ürün kapısı eksik';title='Priz tipi monitör seçimi için güvenlik veya kayıt işlevi eksik.';summary='Kapsamı belirsiz cihazla resmî ya da uzun süreli kanıt oluşturmayın.';steps=[];if(!r.outletSafe)steps.push('Prizin kuru, sıkı ve hasarsız olduğunu doğrulayın.');if(!r.manual||!r.rating)steps.push('Tam model ölçüm kapsamı, gerilim/akım ve güvenlik sınıfını doğrulayın.');if(!r.timestamp||!r.memory)steps.push('Tarih-saat damgası ile en az 7 günlük kayıt/dışa aktarımı doğrulayın.');if(highLoad)steps.push('Isıtıcı, motor veya EV şarj yükünde tüketici tipi monitör yerine devre ve profesyonel kayıt yolunu değerlendirin.')}
else if(r.purpose==='purchase'&&(r.scope==='single'||r.scope==='room')&&(r.goal==='spot'||r.goal==='week')){level='good';label='Nitelikli kategori';title='Düşük riskli ön gözlem için teknik kategoriye geçebilirsiniz.';summary='Bu sonuç resmî ölçüm veya şebeke kusuru kanıtı değildir.';steps=['Mevcut cihazı seçenek olarak koruyun.','Zaman damgası, min/max, kayıt süresi ve güvenlik kapsamını karşılaştırın.','Bina veya komşu kapsamına geçerse EDAŞ/profesyonel ölçüm yoluna dönün.'];commercial=true}return{level,label,title,summary,steps,commercial}}
$('form').addEventListener('submit',e=>{e.preventDefault();const r={createdAt:Date.now(),date:$('date').value||today(),scope:$('scope').value,scopeLabel:labels('scope'),symptom:$('symptom').value,symptomLabel:labels('symptom'),goal:$('goal').value,goalLabel:labels('goal'),load:$('load').value,purpose:$('purpose').value,repeat:$('repeat').checked,outletSafe:$('outletSafe').checked,manual:$('manual').checked,rating:$('rating').checked,timestamp:$('timestamp').checked,memory:$('memory').checked,professional:$('professional').checked,hazard:$('hazard').checked,officialMeasurement:false,retentionMode:'per-record'};const out=evaluate(r);r.decision=out.label;const all=load();all.push(r);save(all);render();$('result').classList.remove('hidden');$('state').textContent=out.label;$('state').className=`pill ${out.level}`;$('title').textContent=out.title;$('summary').textContent=out.summary;$('steps').replaceChildren(...out.steps.map(t=>{const li=document.createElement('li');li.textContent=t;return li}));$('commercial').classList.toggle('hidden',!out.commercial);$('result').scrollIntoView({behavior:'smooth',block:'start'})});
$('export').addEventListener('click',()=>{const data={tool:'ALO186 priz tipi gerilim monitörü uygunluk günlüğü',exportedAt:new Date().toISOString(),rawPersonalDataCollected:false,officialMeasurement:false,records:load()};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='alo186-gerilim-monitoru-gunlugu.json';a.click();URL.revokeObjectURL(a.href)});
$('calendar').addEventListener('click',()=>{const d=new Date();d.setDate(d.getDate()+7);const fmt=x=>x.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z/,'Z');const ics=`BEGIN:VCALENDAR\nVERSION:2.0\nPRODID:-//ALO186//Voltage Evidence Review//TR\nBEGIN:VEVENT\nUID:${Date.now()}@alo186.com\nDTSTAMP:${fmt(new Date())}\nDTSTART:${fmt(d)}\nSUMMARY:Gerilim olay kayıtlarını karşılaştır\nDESCRIPTION:7 günlük zaman damgalı olay, kapsam ve varsa EDAŞ/profesyonel ölçüm durumunu kontrol edin.\nEND:VEVENT\nEND:VCALENDAR`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([ics],{type:'text/calendar'}));a.download='gerilim-7-gun-takip.ics';a.click();URL.revokeObjectURL(a.href)});render()})();