(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.Alo186ProposalScope=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const VERSION=1,MAX_RECORDS=6,TTL_DAYS=90,REVIEW_DAYS=14,DAY_MS=86400000;
const CONTEXTS={home:'Ev / bireysel kullanım',small_business:'Küçük işletme',hotel:'Otel / konaklama tesisi',site:'Site / ortak yaşam alanı'};
const STAGES={request:'Teklif isteme',comparison:'Teklif karşılaştırma',clarification:'Eksik kapsam tamamlama',award:'Sipariş öncesi son kontrol',acceptance:'Kabul ve devreye alma'};
const VALUES={included:'Açıkça dahil',unclear:'Belirsiz / belge yok',excluded:'Hariç / karşılamıyor'};
const SYSTEMS={
 plug_products:{label:'Tak-çalıştır düşük riskli ürün',highRisk:false,tool:'/hesaplama/teknik-urun-karsilastirma/',professional:'/kurumsal-elektrik-surekliligi-on-degerlendirme?problem=urun_uygunlugu&scope=uzaktan_dokuman',criteria:[['model','Tam model ve teknik veri sayfası',true],['capacity','Gerçek kapasite / güç / süre',true],['connection','Bağlantı ve uyumluluk',true],['safety','Koruma ve güvenli kullanım sınırı',true],['support','Kılavuz ve destek kanalı',false],['recheck','Yeniden kontrol / bakım tarihi',false]]},
 ups:{label:'UPS ve akü sistemi',highRisk:true,tool:'/hesaplama/ups-suresi/',professional:'/kurumsal-elektrik-surekliligi-on-degerlendirme?problem=yedek_guc&scope=karsilastirma',criteria:[['load','Sürekli/tepe yük ve güç faktörü',true],['runtime','Gerçek runtime ve batarya hesabı',true],['topology','UPS topolojisi, bypass ve transfer',true],['battery','Kartuş/string ve sıcaklık sınırları',true],['commissioning','Devreye alma ve yük testi',true],['maintenance','Bakım, alarm ve yeniden test planı',false]]},
 generator:{label:'Jeneratör, ATS ve AMF',highRisk:true,tool:'/hesaplama/jenerator-gucu-secimi/',professional:'/kurumsal-elektrik-surekliligi-on-degerlendirme?problem=yedek_guc&scope=karsilastirma',criteria:[['load','Sürekli/kalkış yükü ve kVA hesabı',true],['ats','ATS/AMF, transfer ve geri dönüş',true],['neutral','Nötr-toprak ve RCD topolojisi',true],['fuel','Yakıt, egzoz, havalandırma ve akü',true],['loadtest','Kademeli yük ve kabul testi',true],['service','Bakım, yedek parça ve servis kapsamı',false]]},
 inverter_storage:{label:'İnverter ve enerji depolama',highRisk:true,tool:'/hesaplama/inverter-uygunluk/',professional:'/kurumsal-elektrik-surekliligi-on-degerlendirme?problem=ges_batarya&scope=karsilastirma',criteria:[['power','Sürekli/tepe güç ve DC akımı',true],['battery','Batarya kimyası, BMS ve string uyumu',true],['reserve','DoD, SoC rezervi ve sıcaklık sınırı',true],['transfer','Transfer/ada çalışma ve korumalar',true],['runtime','Gerçek yükte runtime ve verim',true],['lifecycle','Çevrim, bakım ve yeniden test',false]]},
 ev_charging:{label:'EV şarj ve wallbox',highRisk:true,tool:'/hesaplama/ev-sarj-uygunluk/',professional:'/kurumsal-elektrik-surekliligi-on-degerlendirme?problem=ev_sarj&scope=karsilastirma',criteria:[['power','Faz, akım, güç ve araç sınırı',true],['cable','Kablo, soket ve iletken sınıfı',true],['protection','RCD/RDC-DD ve PE sürekliliği',true],['loadmgmt','Dinamik yük yönetimi',true],['thermal','Terminal/konnektör sıcaklık testi',true],['commissioning','Araçla gerçek şarj ve kabul kaydı',false]]},
 ges:{label:'GES ve PV inverter',highRisk:true,tool:'/hesaplama/gunes-paneli-power-station-uygunluk/',professional:'/kurumsal-elektrik-surekliligi-on-degerlendirme?problem=ges_batarya&scope=karsilastirma',criteria:[['string','Voc, Vmp, Isc, Imp ve string planı',true],['mppt','MPPT akım/gerilim ve konnektör uyumu',true],['protection','DC/AC koruma ve topraklama',true],['grid','Şebeke, ihracat ve haberleşme ayarları',true],['acceptance','İzolasyon, AFCI, event log ve üretim testi',true],['monitoring','İzleme, bakım ve sıcaklık trendi',false]]},
 protection:{label:'RCD, SPD, topraklama ve pano',highRisk:true,tool:'/hesaplama/gerilim-koruma-cozum-secici/',professional:'/kurumsal-elektrik-surekliligi-on-degerlendirme?problem=genel_risk&scope=karsilastirma',criteria:[['singleline','Tek hat ve şebeke sistemi',true],['rcd','RCD tipi, eşik ve açma süresi',true],['spd','SPD, SCPD ve bağlantı yolu',true],['earthing','PE sürekliliği, RA/Zs ölçümü',true],['thermal','Pano etiketleme ve termal kontrol',true],['maintenance','Periyodik test ve bakım planı',false]]},
 power_quality:{label:'Harmonik ve güç kalitesi',highRisk:true,tool:'/isletme-surekliligi',professional:'/kurumsal-elektrik-surekliligi-on-degerlendirme?problem=genel_risk&scope=olcum_kampanyasi',criteria:[['pcc','PCC ve fider THDv/THDi ölçümü',true],['spectrum','Harmonik spektrum ve gerçek amper',true],['neutral','Nötr akımı ve sıcaklık trendi',true],['profile','Günlük/mevsimsel yük profili',true],['design','Rezonans ve çözüm boyutlandırması',true],['verification','Önce/sonra kabul ölçümü',true]]}
};
const CANDIDATES=['A','B','C'];
function hasOwn(o,k){return Object.prototype.hasOwnProperty.call(o,k)}
function enumValue(v,map,fallback){v=String(v||'').trim();return hasOwn(map,v)?v:fallback}
function bool(v){return v===true||v==='true'||v===1||v==='1'||v==='yes'||v==='on'}
function sanitize(raw={}){const system=enumValue(raw.system,SYSTEMS,'ups'),criteria=SYSTEMS[system].criteria;return{context:enumValue(raw.context,CONTEXTS,'small_business'),stage:enumValue(raw.stage,STAGES,'comparison'),system,existingSufficient:enumValue(raw.existingSufficient,{yes:1,no:1,unknown:1},'unknown'),safetyRisk:bool(raw.safetyRisk),technicalToolCompleted:bool(raw.technicalToolCompleted),affiliateAcknowledged:bool(raw.affiliateAcknowledged),candidates:Object.fromEntries(CANDIDATES.map(c=>[c,Object.fromEntries(criteria.map(([k])=>[k,enumValue(raw.candidates&&raw.candidates[c]&&raw.candidates[c][k],VALUES,'unclear')]))]))}}
function candidateResult(input,candidate){const profile=SYSTEMS[input.system],values=input.candidates[candidate];let earned=0,total=0;const gaps=[],criticalMissing=[];profile.criteria.forEach(([key,label,critical])=>{const weight=critical?3:1,totalValue=VALUES[values[key]];total+=weight;if(values[key]==='included')earned+=weight;else{gaps.push({key,label,status:values[key],critical});if(critical)criticalMissing.push(label)}});const score=Math.round(earned/total*100);return{candidate,score,ready:criticalMissing.length===0&&score>=85,gaps,criticalMissing}}
function questions(result){return result.gaps.map(g=>`${result.candidate} adayı: “${g.label}” ${g.status==='excluded'?'neden kapsam dışında ve hangi ayrı teslimle tamamlanacak?':'hangi model, belge, ölçüm veya kabul çıktısıyla doğrulanacak?'}`)}
function evaluate(raw={}){const input=sanitize(raw),profile=SYSTEMS[input.system],results=CANDIDATES.map(c=>candidateResult(input,c)),ready=results.filter(x=>x.ready).sort((a,b)=>b.score-a.score);let status='conditional',commercialAllowed=false,title='Teklifler henüz teknik olarak karşılaştırılabilir değil',summary='Kritik kapsam eksikleri tamamlanmadan marka, fiyat veya teslim süresi üzerinden seçim yapmayın.',primary={label:'Eksik kapsam sorularını kopyala',href:'#questions'},secondary={label:'İlgili ücretsiz aracı aç',href:profile.tool};
 if(input.safetyRisk){status='safety';title='Teklif karşılaştırmasını durdurun';summary='Duman, alev, elektrik çarpması, erime veya hızla artan sıcaklıkta önce güvenlik ve resmî kanal gerekir.';primary={label:'Karar Motorunu aç',href:'/karar-motoru'};secondary={label:'Doğru EDAŞ kanalını bul',href:'/edas-bul'};}
 else if(input.existingSufficient==='yes'){status='no_buy';title='Mevcut çözüm yeterli; yeni teklif veya ürün gerekmiyor';summary='Bakım ve kabul kaydı tamamlanmalı, fakat yeni sipariş ya da affiliate rotası açılmamalıdır.';primary={label:'Bakım planı oluştur',href:'/hesaplama/ekipman-bakim-plani/'};secondary={label:'Elektrik Planım’ı aç',href:'/hesaplama/elektrik-planim/'};}
 else if(!ready.length){status=profile.highRisk?'professional':'conditional';title=profile.highRisk?'Kritik kapsam eksik; bağımsız teknik teklif incelemesi gerekli':'Kritik teknik alanlar tamamlanmalı';summary='A, B ve C adaylarından hiçbiri zorunlu teknik kapsamı eksiksiz sunmuyor.';primary={label:profile.highRisk?'Profesyonel teklif kapsamı incelemesini aç':'Teknik kısa listeyi aç',href:profile.highRisk?profile.professional:'/hesaplama/teknik-urun-karsilastirma/'};}
 else if(profile.highRisk){status='ready_review';title=`${ready.length} teklif teknik kapsam açısından karşılaştırılabilir`;summary='Bu sonuç yüklenici seçimi değildir. Fiyat, marka, garanti ve ticari koşullar kullanılmadan yalnız teknik kapsam yeterliliği gösterilir.';primary={label:'Teknik devir ve kabul paketini oluştur',href:'/hesaplama/teknik-devir-kabul-paketi/'};secondary={label:'Bağımsız kapsam incelemesini aç',href:profile.professional};}
 else if(!input.technicalToolCompleted||input.existingSufficient!=='no'||!input.affiliateAcknowledged){status='conditional';title='Düşük riskli ürün rotası için üç güven kapısı gerekli';summary='Ücretsiz teknik araç, mevcut çözümün yetersizliği ve satış ortaklığı açıklaması ayrı ayrı doğrulanmadan affiliate rota açılmaz.';primary={label:'Teknik kısa listeyi aç',href:'/hesaplama/teknik-urun-karsilastirma/'};secondary={label:'Şimdilik satın alma',href:'/hesaplama/elektrik-planim/'};}
 else{status='ready_affiliate';commercialAllowed=true;title='Teknik kapsamı doğrulanmış düşük riskli karşılaştırmaya hazır';summary='Kritik alanlar açıkça dahil. Affiliate niteliği görünür Akıllı Ürün Merkezi kullanıcı onayıyla açılabilir.';primary={label:'Şeffaf Ürün Merkezini aç',href:'/akilli-urun-secimi'};secondary={label:'Şimdilik satın alma',href:'/hesaplama/elektrik-planim/'};}
 const allQuestions=results.flatMap(questions);return{version:VERSION,input,status,title,summary,commercialAllowed,systemLabel:profile.label,contextLabel:CONTEXTS[input.context],stageLabel:STAGES[input.stage],results,readyCandidates:ready.map(x=>x.candidate),questions:allQuestions,primary,secondary,followupDays:status==='safety'?0:REVIEW_DAYS}}
function hashText(text){let h=2166136261;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(16).padStart(8,'0')}
function record(raw,nowValue=new Date()){const now=nowValue instanceof Date?nowValue:new Date(nowValue),r=evaluate(raw);const payload={schema:'alo186-proposal-scope-v1',version:VERSION,createdAt:now.toISOString(),expiresAt:new Date(now.getTime()+TTL_DAYS*DAY_MS).toISOString(),reviewAt:r.followupDays?new Date(now.getTime()+r.followupDays*DAY_MS).toISOString():null,context:r.input.context,stage:r.input.stage,system:r.input.system,status:r.status,readyCandidates:r.readyCandidates,scores:Object.fromEntries(r.results.map(x=>[x.candidate,x.score])),criticalGapCounts:Object.fromEntries(r.results.map(x=>[x.candidate,x.criticalMissing.length])),questionCount:r.questions.length,commercialAllowed:r.commercialAllowed};return{...payload,checksum:hashText(JSON.stringify(payload))}}
function validateRecord(pkg){if(!pkg||pkg.schema!=='alo186-proposal-scope-v1'||pkg.version!==VERSION)return false;const copy={...pkg};delete copy.checksum;if(hashText(JSON.stringify(copy))!==pkg.checksum)return false;return hasOwn(CONTEXTS,pkg.context)&&hasOwn(STAGES,pkg.stage)&&hasOwn(SYSTEMS,pkg.system)&&Array.isArray(pkg.readyCandidates)}
function prune(records,nowValue=new Date()){const now=nowValue instanceof Date?nowValue:new Date(nowValue);return(Array.isArray(records)?records:[]).filter(validateRecord).filter(x=>Date.parse(x.expiresAt)>now.getTime()).sort((a,b)=>Date.parse(b.createdAt)-Date.parse(a.createdAt)).slice(0,MAX_RECORDS)}
function buildIcs(pkg,origin='https://alo186.com'){if(!validateRecord(pkg)||!pkg.reviewAt)return'';const d=new Date(pkg.reviewAt),date=`${d.getUTCFullYear()}${String(d.getUTCMonth()+1).padStart(2,'0')}${String(d.getUTCDate()).padStart(2,'0')}`;return['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//ALO186//Proposal Scope Review//TR','BEGIN:VEVENT',`UID:${pkg.checksum}@alo186.com`,`DTSTART;VALUE=DATE:${date}`,'SUMMARY:ALO186 teknik teklif kapsamını yeniden kontrol et',`DESCRIPTION:${SYSTEMS[pkg.system].label} için eksik teknik kapsamların tamamlanıp tamamlanmadığını kontrol edin. Fiyat\, satıcı ve kişisel veri içermez.`,`URL:${origin.replace(/\/$/,'')}/hesaplama/teknik-teklif-kapsam-karsilastirma/`,'END:VEVENT','END:VCALENDAR',''].join('\r\n')}
return{VERSION,MAX_RECORDS,TTL_DAYS,REVIEW_DAYS,CONTEXTS,STAGES,VALUES,SYSTEMS,CANDIDATES,sanitize,candidateResult,evaluate,record,validateRecord,prune,buildIcs,hashText};});
