(() => {
  'use strict';
  const unique = (items) => [...new Set(items.filter(Boolean))];
  const escapeIcs = (value) => String(value).replace(/\\/g, '\\\\').replace(/,/g, '\\,').replace(/;/g, '\\;').replace(/\n/g, '\\n');
  const stamp = (date) => date.toISOString().replace(/[-:]/g, '').replace(/\.\d{3}Z$/, 'Z');
  function buildPlan(raw) {
    const data = { ...raw }, immediate = [], next = [], repeat = [];
    let priority = 'P2', cadence = 90;
    if (data.scenario === 'water-electric') { priority='P0'; cadence=7; immediate.push('Su birikintisi, ıslak priz/fiş, elektrikli cihazla su teması veya elektrik çarpması riski varsa alana yaklaşmayın; güvenli alandan acil yardım ve yetkili uzman rotasına geçin.'); next.push('Elektrik ve su kaynağı güvenli biçimde ayrılmadan nem ölçümü veya cihaz deneyi yapmayın.'); }
    else if (data.scenario === 'active-leak') { priority='P1'; cadence=7; immediate.push('Aktif sızıntı veya kaçak kaynağını önce onarın; nem alma cihazını onarımın yerine kullanmayın.'); next.push('Islanan malzemenin tamamen kuruduğunu ve tekrar ıslanmadığını 24–48 saatlik kontrollerle doğrulayın.'); }
    else if (data.scenario === 'mold') { priority='P1'; cadence=7; immediate.push('Görünür küfü yalnız cihazla gizlemeyin; nem kaynağını, etkilenen malzemeyi ve sağlık etkisini ayrı değerlendirin.'); next.push('Geniş, tekrarlayan veya kirli su kaynaklı hasarda uygun uzman desteği alın.'); }
    else if (data.scenario === 'condensation') { priority='P1'; cadence=30; immediate.push('Pencere, duvar, boru ve klima çevresindeki yoğuşmayı aynı saatlerde metrik kayıtla izleyin: RH, sıcaklık, süre ve oda kullanımı.'); next.push('Havalandırma, yalıtım, soğuk yüzey ve nem üretim kaynağını ayırın.'); }
    else if (data.scenario === 'high-rh') { priority='P1'; cadence=30; immediate.push('En az 7 gün sabah-akşam bağıl nem kaydı oluşturun; tek yüksek ölçümü ürün kararı saymayın.'); next.push('Kaynak giderildikten sonra mevcut havalandırma/klima veya nem alma cihazının gerçek RH sonucunu yeniden test edin.'); }
    else if (data.scenario === 'new-device') { priority='P1'; cadence=30; immediate.push('Yeni nem ölçer veya nem alma cihazında etiketi, üretici kapasite test koşullarını, priz bağlantısını, tank/şamandıra ve drenajı kontrol edin.'); next.push('İlk 7 günlük gerçek görev sonucunu kaydedin; hedef karşılanıyorsa daha büyük cihaz almayın.'); }
    else { immediate.push('Higrometre doğruluğunu karşılaştırın; filtre, hava girişi/çıkışı, tank şamandırası, hortum ve priz sıcaklığını kontrol edin.'); next.push('Aynı odada 7 günlük RH ve çalışma süresi kaydını yenileyin.'); }
    if (data.vulnerable === 'yes') { priority = priority === 'P0' ? 'P0' : 'P1'; cadence=Math.min(cadence,7); immediate.push('Astım, alerji, bağışıklık sorunu veya başka sağlık hassasiyeti varsa kişisel değerlendirme için sağlık uzmanına başvurun; ALO186 teşhis vermez.'); }
    if (data.scope === 'commercial') { priority = priority === 'P0' ? 'P0' : 'P1'; immediate.push('Otel, işyeri, arşiv, ilaç/gıda veya kritik depolama alanında tüketici tipi oda cihazı planını resmî kabul veya profesyonel HVAC değerlendirmesi yerine kullanmayın.'); }
    repeat.push(`${cadence} gün sonra aynı oda ve benzer kullanım koşullarında RH, yoğuşma, koku, kaynak ve cihaz sonucunu yeniden kontrol edin.`);
    repeat.push('Mevsim geçişi, oda kullanım değişikliği, yeni su kaçağı, filtre bakımı veya cihaz taşınmasında planı yeniden oluşturun.');
    repeat.push('Mevcut sistem hedefi güvenli biçimde karşılıyorsa yeni higrometre veya nem alma cihazı almayın.');
    return { ok:true, priority, cadence, immediate:unique(immediate), next:unique(next), repeat:unique(repeat), privacy:'Plan cihazınızda oluşturulur; ad, adres, konum, fotoğraf veya seri numarası istenmez.' };
  }
  function download(name,content,type){const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([content],{type}));link.download=name;link.click();URL.revokeObjectURL(link.href);}
  function render(plan){const result=document.querySelector('#result');result.hidden=false;result.dataset.status=plan.priority==='P0'?'stop':plan.priority==='P1'?'evidence':'no-buy';const list=(title,items)=>`<section><h3>${title}</h3><ul>${items.map((item)=>`<li>${item}</li>`).join('')}</ul></section>`;result.innerHTML=`<h2>${plan.priority} rutubet ve yoğuşma planı</h2><div class="summary-grid"><div class="metric"><span>Öncelik</span><strong>${plan.priority}</strong></div><div class="metric"><span>Tekrar kontrol</span><strong>${plan.cadence} gün</strong></div><div class="metric"><span>Doğrudan affiliate</span><strong>Yok</strong></div></div>${list('Şimdi',plan.immediate)}${list('Sonraki doğrulama',plan.next)}${list('Tekrar ziyaret nedeni',plan.repeat)}<p class="hint">${plan.privacy}</p><div class="actions"><button type="button" id="downloadJson">JSON planını indir</button><button type="button" class="ghost" id="downloadIcs">Takvime ekle (.ics)</button></div>`;result.querySelector('#downloadJson').addEventListener('click',()=>download('alo186-rutubet-yogusma-plani.json',JSON.stringify(plan,null,2),'application/json'));result.querySelector('#downloadIcs').addEventListener('click',()=>{const start=new Date(Date.now()+plan.cadence*86400000);start.setUTCHours(9,0,0,0);const end=new Date(start.getTime()+30*60000);const description=[...plan.immediate,...plan.next,...plan.repeat].join('\n');const ics=`BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//ALO186//Rutubet Tekrar Testi//TR\r\nBEGIN:VEVENT\r\nUID:alo186-humidity-${Date.now()}@alo186.com\r\nDTSTAMP:${stamp(new Date())}\r\nDTSTART:${stamp(start)}\r\nDTEND:${stamp(end)}\r\nSUMMARY:${escapeIcs('Ev rutubet ve yoğuşma tekrar testi')}\r\nDESCRIPTION:${escapeIcs(description)}\r\nURL:https://alo186.com/sektor-rehberi/ev-rutubet-yogusma-tekrar-test-merkezi/\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n`;download('alo186-rutubet-yogusma-tekrar-testi.ics',ics,'text/calendar');});result.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});}
  if(typeof module!=='undefined'&&module.exports)module.exports={buildPlan};if(typeof document!=='undefined'){const form=document.querySelector('#planForm');if(form)form.addEventListener('submit',(event)=>{event.preventDefault();render(buildPlan(Object.fromEntries(new FormData(form).entries())));});}
})();
