(function(){
'use strict';
const core=window.PowerStationSolarCore;
const form=document.getElementById('solarForm');
const result=document.getElementById('result');
const affiliatePanel=document.getElementById('affiliatePanel');
const affiliateBtn=document.getElementById('affiliateBtn');
const confirmIds=['confirmNeed','confirmSpecs','confirmAffiliate'];
const AFFILIATE_URL='https://www.amazon.com.tr/s?k=ta%C5%9F%C4%B1nabilir+g%C3%BCne%C5%9F+paneli+power+station&tag=alo186rehber-21';
let latest=null;
const value=id=>document.getElementById(id).value;
const checked=id=>document.getElementById(id).checked;
const fmt=(n,d=1)=>Number.isFinite(Number(n))?Number(n).toLocaleString('tr-TR',{maximumFractionDigits:d}):'—';
function collect(){return{stationMinV:value('stationMinV'),stationMaxV:value('stationMaxV'),stationMaxCurrentA:value('stationMaxCurrentA'),stationMaxIscA:value('stationMaxIscA'),stationMaxPowerW:value('stationMaxPowerW'),batteryWh:value('batteryWh'),currentSoc:value('currentSoc'),targetSoc:value('targetSoc'),solarPlanningPct:value('solarPlanningPct'),panelPmaxW:value('panelPmaxW'),panelVocV:value('panelVocV'),panelVmpV:value('panelVmpV'),panelIscA:value('panelIscA'),panelImpA:value('panelImpA'),tempCoeffVocPct:value('tempCoeffVocPct'),minTempC:value('minTempC'),seriesCount:value('seriesCount'),parallelCount:value('parallelCount'),ownership:value('ownership'),installationType:value('installationType'),stationDocsVerified:checked('stationDocsVerified'),panelDocsVerified:checked('panelDocsVerified'),tempDataVerified:checked('tempDataVerified'),connectorPolarityVerified:checked('connectorPolarityVerified'),cableVerified:checked('cableVerified'),noDamageDry:checked('noDamageDry'),noLiveWork:checked('noLiveWork'),activeStorm:checked('activeStorm'),currentClippingVerified:checked('currentClippingVerified'),overpanelVerified:checked('overpanelVerified'),realSolarTestPassed:checked('realSolarTestPassed')};}
const messages={invalid:['Girişleri tamamlayın','Voc, Vmp, Isc, Imp, sıcaklık katsayısı ve SOC alanlarında tutarsız veya eksik değer var. Panel Voc değeri Vmp’den yüksek, Isc değeri Imp’ye eşit veya yüksek olmalıdır.'],stop:['Bağlantıyı durdurun','Aktif fırtına, ıslak/hasarlı kablo-konnektör veya enerjili bağlantıda müdahale riski varken panel bağlamayın. Önce güvenli koşulları sağlayın.'],professional:['Bu senaryo profesyonel PV tasarımı gerektiriyor','Sabit çatı/cephe veya şebekeye bağlı PV dizileri; DC ayırma, kablo, koruma, yapı ve yerel kurallarla birlikte tasarlanmalıdır. Tüketici tipi affiliate yolu kapalıdır.'],evidence:['Önce teknik kanıtları tamamlayın','Power station ve panel tam model belgeleri, Voc sıcaklık verisi, polarite ve üretici kablo/adaptör şartı doğrulanmadan uyumluluk sonucu veya ürün yönlendirmesi açılmaz.'],incompatible:['Bu dizi bağlanmamalı','Hesaplanan dizi power station giriş sınırlarından en az birini aşıyor veya MPPT çalışma alt gerilimine ulaşmıyor. Seri/paralel düzeni ve tam model kılavuzunu yeniden değerlendirin.'],conditional:['Üretici onayı olmadan ilerlemeyin','Watt veya akım tarafında power station sınırının üzerinde çalışma ancak üretici tam model için akım kırpması/overpaneling koşullarını açıkça izinliyorsa değerlendirilebilir. Güvenli varsayım yapılmadı.'],no_buy:['Mevcut paneliniz ön kontrolde yeterli — yeni panel almayın','Elektriksel sınırlar, bağlantı kanıtları ve gerçek güneş testi uygunsa mevcut çözümü kullanmaya devam edin. Gereksiz ürün yönlendirmesi açılmadı.'],compatible_candidate:['Aday panel/dizi ön kontrolde uyumlu görünüyor','Soğuk Voc, çalışma gerilimi, akım ve güç ekranlaması geçti. Bu yine de üretici onayı değildir; tam model bağlantı ve garanti şartlarını siparişten önce yeniden kontrol edin.']};
const reasonText={cold_voc_at_or_above_max:'Soğukta düzeltilmiş toplam Voc, power station azami PV gerilimine eşit veya daha yüksek.',vmp_below_mppt_min:'Toplam Vmp, PV/MPPT çalışma alt geriliminin altında.',vmp_at_or_above_input_max:'Toplam Vmp, azami PV giriş gerilimine eşit veya daha yüksek.',isc_above_documented_max:'Toplam Isc, üreticinin belgelenmiş kısa devre akımı sınırını aşıyor.',no_documented_isc_limit_for_overcurrent:'Panel Imp giriş akımını aşıyor ancak güvenli Isc sınırı belgelenmemiş.',input_current_clipping_not_verified:'Akım kırpmasının bu tam modelde güvenli olduğu doğrulanmamış.',overpanel_power_not_verified:'Panel dizi wattı PV giriş watt sınırını aşıyor ve overpaneling izni doğrulanmamış.',real_solar_test_missing:'Mevcut panel için gerçek güneş testi henüz doğrulanmamış.',station_docs:'Power station PV kılavuzu eksik.',panel_docs:'Panel datasheet/etiket kanıtı eksik.',connector_polarity:'Konnektör/polarite kanıtı eksik.',manufacturer_cable:'Üretici kablo/adaptör şartı doğrulanmamış.',voc_temperature_data:'Voc sıcaklık katsayısı doğrulanmamış.'};
function render(r){latest=r;affiliatePanel.hidden=true;affiliateBtn.disabled=true;affiliateBtn.onclick=null;confirmIds.forEach(id=>{document.getElementById(id).checked=false;});const m=messages[r.status]||['Sonuç','Değerlendirme tamamlandı.'];const cls=(r.status==='stop'||r.status==='incompatible')?'status-stop':(r.status==='compatible_candidate'||r.status==='no_buy')?'status-ok':'status-warn';const c=r.calc||{};const metrics=`<div class="result-grid"><div class="metric"><span>Soğuk toplam Voc</span><strong>${fmt(c.arrayColdVocV,2)} V</strong></div><div class="metric"><span>Toplam Vmp</span><strong>${fmt(c.arrayVmpV,2)} V</strong></div><div class="metric"><span>Toplam Isc</span><strong>${fmt(c.arrayIscA,2)} A</strong></div><div class="metric"><span>Dizi gücü</span><strong>${fmt(c.arrayPmaxW,0)} Wp</strong></div><div class="metric"><span>Ekranlanmış giriş tavanı</span><strong>${fmt(c.screenedInputCeilingW,0)} W</strong></div><div class="metric"><span>Yaklaşık güneşli çalışma süresi</span><strong>${fmt(c.estimatedSolarHours,2)} saat</strong></div></div>`;const reasons=(r.reasons||[]).filter(x=>reasonText[x]).map(x=>`<li>${reasonText[x]}</li>`).join('');result.className=`result ${cls}`;result.innerHTML=`<h2>${m[0]}</h2><p>${m[1]}</p>${metrics}${reasons?`<div class="decision"><strong>Neden?</strong><ul>${reasons}</ul></div>`:''}<p class="help">Planlama süresi; güneş, gölge, panel sıcaklığı, açı, MPPT davranışı ve batarya şarj eğrisi nedeniyle değişebilir. Bu sonuç kablo/koruma veya garanti onayı değildir.</p>`;result.hidden=false;if(r.affiliateEligible){affiliatePanel.hidden=false;updateAffiliate();}result.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});}
function updateAffiliate(){const enabled=latest&&latest.affiliateEligible&&confirmIds.every(checked);affiliateBtn.disabled=!enabled;if(enabled){affiliateBtn.onclick=()=>{const a=document.createElement('a');a.href=AFFILIATE_URL;a.target='_blank';a.rel='sponsored nofollow noopener';a.setAttribute('aria-label','Amazon Türkiye üzerinde taşınabilir güneş paneli sınıfını yeni sekmede incele');document.body.appendChild(a);a.click();a.remove();};}}
form.addEventListener('submit',e=>{e.preventDefault();render(core.evaluate(collect()));});
confirmIds.forEach(id=>document.getElementById(id).addEventListener('change',updateAffiliate));
document.getElementById('resetBtn').addEventListener('click',()=>{form.reset();result.hidden=true;affiliatePanel.hidden=true;affiliateBtn.disabled=true;latest=null;});
})();
