'use strict';const assert=require('node:assert/strict');const Core=require('./core.js');
function scenario(oneTime,annualMaintenance,annualEnergy,annualDowntime,residual=0,quality='documented'){return{oneTime,annualMaintenance,annualEnergy,annualDowntime,residual,quality}}
function base(overrides={}){return{context:'small_business',system:'ups',horizon:'5',existingSafe:'yes',safetyRisk:false,technicalToolCompleted:false,existingInsufficient:false,affiliateAcknowledged:false,scenarios:{maintain:scenario(1000,300,500,100,0),repair:scenario(5000,200,450,50,500),replace:scenario(12000,100,350,20,2500)},...overrides}}
let r=Core.evaluate(base());assert.equal(r.status,'no_buy');assert.equal(r.best.key,'maintain');assert.equal(r.commercialAllowed,false);
r=Core.evaluate(base({safetyRisk:true}));assert.equal(r.status,'safety');assert.equal(r.followupDays,0);
r=Core.evaluate(base({existingSafe:'no'}));assert.equal(r.status,'professional');
r=Core.evaluate(base({scenarios:{maintain:scenario(12000,1000,1000,1000),repair:scenario(4000,300,400,50),replace:scenario(15000,100,300,20)}}));assert.equal(r.status,'professional');assert.equal(r.best.key,'repair');
const plug={system:'plug_products',existingSafe:'yes',scenarios:{maintain:scenario(8000,500,500,500),repair:scenario(6000,400,400,300),replace:scenario(1000,100,100,50)}};
r=Core.evaluate(base(plug));assert.equal(r.status,'conditional');assert.equal(r.commercialAllowed,false);
r=Core.evaluate(base({...plug,technicalToolCompleted:true,existingInsufficient:true,affiliateAcknowledged:true}));assert.equal(r.status,'ready_affiliate');assert.equal(r.commercialAllowed,true);
r=Core.evaluate(base({scenarios:{maintain:scenario(1000,100,100,0),repair:scenario(1100,100,100,0),replace:scenario(9000,100,100,0)}}));assert.equal(r.status,'review');assert.equal(r.nearTie,true);
r=Core.evaluate(base({scenarios:{maintain:{oneTime:'',annualMaintenance:0,annualEnergy:0,annualDowntime:0,residual:0,quality:'documented'},repair:scenario(5000,200,450,50),replace:scenario(12000,100,350,20)}}));assert.equal(r.status,'conditional');assert.equal(r.results[0].ready,false);assert.ok(r.results[0].missing.includes('oneTime'));
const raw=base(),pkg=Core.record(raw,new Date('2026-07-29T00:00:00Z'));assert.equal(Core.validateRecord(pkg),true);assert.equal(pkg.schema,'alo186-lifecycle-cost-v1');assert.equal('scenarios' in pkg,false);assert.equal('total' in pkg,false);const tampered={...pkg,status:'ready_affiliate'};assert.equal(Core.validateRecord(tampered),false);const many=Array.from({length:9},(_,i)=>Core.record(raw,new Date(Date.UTC(2026,6,29,0,0,i))));assert.equal(Core.prune(many,new Date('2026-07-30T00:00:00Z')).length,6);const ics=Core.buildIcs(pkg);assert.match(ics,/BEGIN:VCALENDAR/);assert.doesNotMatch(ics,/1000|12000|email|telefon|adres/i);console.log('ALO186 yaşam döngüsü maliyet karar senaryoları başarılı.');
