(()=>{'use strict';const $=id=>document.getElementById(id),K='alo186.deviceDamageTracker.v1',TTL=365*86400000;let receipt=null;
function addCalendarDays(date,count){const d=new Date(date);d.setDate(d.getDate()+count);return d}
function calendarDaysUntil(from,to){const a=new Date(from);a.setHours(0,0,0,0);const b=new Date(to);b.setHours(0,0,0,0);return Math.round((b-a)/86400000)}
function fmt(date){return new Intl.DateTimeFormat('tr-TR',{day:'2-digit',month:'long',year:'numeric'}).format(date)}
function dl(name,type,text){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function ymd(d){return `${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}`}
function save(data){try{localStorage.setItem(K,JSON.stringify({schema:K,personalData:false,createdAt:new Date().toISOString(),expiresAt:new Date(Date.now()+TTL).toISOString(),data}))}catch(_){}}
function load(){try{const p=JSON.parse(localStorage.getItem(K)||'null');if(!p||p.schema!==K||Date.parse(p.expiresAt)<=Date.now()){localStorage.removeItem(K);return null}return p.data}catch(_){return null}}
function setChecks(data){for(const id of ['record','photo','service','invoice','kept','written'])$(id).checked=Boolean(data[id])}
function evaluate(data,scroll=true){const event=new Date(`${data.eventDate}T12:00:00`);if(Number.isNaN(event.getTime()))return;const deadline=addCalendarDays(event,30),remaining=calendarDaysUntil(new Date(),deadline),checks=['record','photo','service','invoice','kept','written'],done=checks.filter(id=>data[id]).length,steps=[];let cls='good',state='Takip sürüyor',title='Dosyanızı resmî kanalda izlemeyi sürdürün.',summary='Kanıtları koruyun; yeni koruma ürünü almadan önce olayın ve tesisin teknik nedenini doğrulayın.';
if(data.status==='none'){steps.push('İlgili dağıtım şirketinin resmî, izlenebilir kanalında başvuruyu gecikmeden açın.');}if(!data.record)steps.push('186 veya dağıtım şirketi olay/arıza kayıt numarasını alın.');if(!data.photo)steps.push('Güvenliyse hasarı ve cihaz etiketini fotoğrafla belgeleyin.');if(!data.service)steps.push('Servisten arıza bulgusu ve teknik neden değerlendirmesi içeren yazılı rapor isteyin.');if(!data.kept)steps.push('Hasarlı cihazı ve değişen parçaları inceleme tamamlanana kadar koruyun.');if(!data.written)steps.push('Telefon görüşmesini yazılı veya izlenebilir resmî kanalla destekleyin.');if(!data.invoice)steps.push('Mevcut satın alma, servis veya tamir belgelerini dosyalayın.');
if(data.status==='answered'){cls='good';state='Gerekçeli cevap alındı';title='Cevap ve kanıtları birlikte değerlendirin.';summary='Kabul, ret veya ek inceleme sonucunu belgelerle saklayın; uyuşmazlıkta tüketici hukuku uzmanı veya resmî şikâyet kanalını değerlendirin.'}else if(remaining<0){cls='bad';state='Yaklaşık süre geçmiş görünüyor';title='Yine de resmî kayıt oluşturun ve gerekçeli cevap isteyin.';summary='Bu yardımcı 30 takvim gününü yaklaşık hesaplar; somut hukuki süre için güncel mevzuatı, resmî kanalı veya uzman görüşünü doğrulayın.'}else if(remaining<=2){cls='bad';state='Süre kritik';title='Resmî başvuruyu bugün tamamlamayı önceliklendirin.';summary='Yaklaşık hesapta son güne çok az süre kaldı. Eksik belge varsa başvuru açıp ek belge yöntemini resmî kanaldan sorun.'}else if(data.status==='none'){cls='warn';state='Başvuru bekliyor';title='30 günlük süreyi kaçırmadan resmî kayıt açın.';summary='Takip makbuzu başvuru değildir; işlem ALO186 yerine görevli dağıtım şirketinde tamamlanmalıdır.'}
if(!steps.length)steps.push('Başvuru numarası, gönderilen belgeler, tarih ve gerekçeli cevabı aynı dosyada saklayın.');receipt={schema:K,personalData:false,legalAdvice:false,officialApplication:false,createdAt:new Date().toISOString(),eventDate:data.eventDate,deadlineApproximate:deadline.toISOString().slice(0,10),calendarDayWindow:30,status:data.status,evidenceCount:done,evidenceTotal:checks.length,inputs:data,steps};save(data);$('result').classList.remove('hidden');$('state').className=`pill ${cls}`;$('state').textContent=state;$('title').textContent=title;$('summary').textContent=summary;$('deadline').textContent=fmt(deadline);$('remaining').textContent=remaining>=0?`${remaining} gün`:`${Math.abs(remaining)} gün geçti`;$('evidence').textContent=`${done}/${checks.length}`;$('steps').replaceChildren(...steps.map(t=>{const li=document.createElement('li');li.textContent=t;return li}));if(scroll)$('result').scrollIntoView({behavior:'smooth',block:'start'})}
$('eventDate').value=new Date().toISOString().slice(0,10);$('form').addEventListener('submit',e=>{e.preventDefault();const data={eventDate:$('eventDate').value,eventType:$('eventType').value,device:$('device').value,status:$('status').value};for(const id of ['record','photo','service','invoice','kept','written'])data[id]=$(id).checked;evaluate(data)});$('json').addEventListener('click',()=>receipt&&dl('alo186-cihaz-hasari-takip-makbuzu.json','application/json',JSON.stringify(receipt,null,2)));$('print').addEventListener('click',()=>window.print());$('ics').addEventListener('click',()=>{if(!receipt)return;const d=new Date(`${receipt.deadlineApproximate}T09:00:00`),e=new Date(d.getTime()+1800000);dl('alo186-cihaz-hasari-son-kontrol.ics','text/calendar',`BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//ALO186//Cihaz Hasari//TR\r\nBEGIN:VEVENT\r\nUID:${Date.now()}@alo186.com\r\nDTSTART:${ymd(d)}T090000\r\nDTEND:${ymd(e)}T093000\r\nSUMMARY:Cihaz hasari basvuru durumunu kontrol et\r\nDESCRIPTION:Tahmini tarihtir. Resmi tatil ve sureyi dagitim sirketinin resmi kanalindan dogrulayin.\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n`)});const old=load();if(old){$('eventDate').value=old.eventDate;$('eventType').value=old.eventType;$('device').value=old.device;$('status').value=old.status;setChecks(old);evaluate(old,false)}})();
