'use strict';
const assert = require('node:assert/strict');
const { calculate, evaluate } = require('./app.js');
let metrics = calculate({ watts: 450, hours: 8, days: 30, liters: 4, tank: 2 });
assert.equal(metrics.kwhDay, 3.6);
assert.equal(metrics.kwhPeriod, 108);
assert.equal(metrics.tankCycles, 2);
const base = { electricalWaterRisk: false, scope: 'room', sourceFixed: 'yes', rhLog: 'yes', watts: 450, hours: 8, days: 30, liters: 4, tank: 2, drain: 'tank', drainSafe: 'yes', outletSafe: 'yes', existingDevice: 'no', targetMet: 'no', needConfirmed: 'yes', confirmNeed: true, confirmSpecs: true, confirmAffiliate: true };
let result = evaluate(base);
assert.equal(result.status, 'recommend');
assert.equal(result.affiliateAllowed, true);
result = evaluate({ ...base, existingDevice: 'yes', targetMet: 'yes' });
assert.equal(result.status, 'no-buy');
assert.equal(result.affiliateAllowed, false);
result = evaluate({ ...base, outletSafe: 'no' });
assert.equal(result.status, 'stop');
assert.equal(result.affiliateAllowed, false);
result = evaluate({ ...base, sourceFixed: 'no' });
assert.equal(result.status, 'evidence');
assert.equal(result.affiliateAllowed, false);
console.log(JSON.stringify({ ok: true, scenarios: 5 }));
