(()=>{'use strict';
const $=id=>document.getElementById(id),KEY='alo186_ev_cable_health_v1',TTL=540*86400000,MAX=18;
const today=()=>new Date().toISOString().slice(0,10);
$('date').value=today();
function load(){let x=[];try{x=JSON.parse(localStorage.getItem(KEY)||'[]')}catch(_){x=[]}const now=Date.now();x=x.filter(r=>r&&now-r.createdAt<TTL).slice(-MAX);localStorage.setItem(KEY,JSON.stringify(x));return x}
function save(x){localStorage.setItem(KEY,JSON.stringify(x.slice(-MAX)))}
function render(){const x=load(),box=$('records');if(!x.length){box.innerHTML='<p class="small">Henüz kayıt yok.</p>';return}box.replaceChildren(...x.slice().reverse().map(r=>{const d=document.createElement('div');d.className='record';const strong=document.createElement('strong');strong.textContent=`${r.date} · ${r.eventLabel}`;const p=document.createElement('p');p.className='small';p.textContent=`${r.cableLabel} · ${r.locationLabel} · ${r.decision}`;d.append(strong,p);return d}))}
function labels(id){const el=$(id);return el.options[el.selectedIndex].textContent}
function evaluate(r){let level='good',label='Kayıt alındı',title='Kablo için acil değişim kanıtı oluşmadı.',summary='Olay tekrarlamıyorsa ve fiziksel belirti yoksa mevcut kabloyla devam edin.',steps=['Konnektörü zorlamadan tam oturtun.','Araç ve wallbox olay kayıtlarını aynı saatle karşılaştırın.'],commercial=false;const safetyEvent=r.burn||r.damage||r.wet;
if(r.burn||r.damage){level='bad';label='Kullanımı durdur';title='Fiziksel veya termal hasar işareti var.';summary='Kabloyu veya mobil konnektörü tekrar enerjilendirmeyin. Sabit kabloda üretici/yetkili servis; taşınabilir kabloda araç ve EVSE soketiyle birlikte profesyonel doğrulama gerekir.';steps=['Enerjiyi güvenli şekilde ayırın.','Hasarlı temas yüzeyini temizleyerek kullanmaya çalışmayın.','Araç ve EVSE soketini de hasar açısından yetkili personele kontrol ettirin.','Güvenlik olayı sürerken ürün veya satış ortaklığı bağlantısı açılmaz.']}
else if(r.wet){level='bad';label='Kir/su sınırı';title='Soket veya temas yüzeyinde kirlenme şüphesi var.';summary='Enerjisiz bırakın ve yalnız üreticinin temizlik/kurutma prosedürünü uygulayın. Metal cisim veya basınçlı su kullanmayın.';steps=['Tam kuruma ve görsel kontrol olmadan şarj etmeyin.','Pitting veya korozyon görülürse kullanımı durdurun.','Kirlenme veya su olayı çözülmeden ürün bağlantısı açılmaz.']}
else if(r.event==='warm'||r.event==='interrupt'||r.event==='error'||r.event==='lock'){level='warn';label='Kök neden ayrımı gerekli';title='Tek olay, kablonun arızalı olduğunu kanıtlamaz.';summary=r.repeat?'Olay tekrarlandı; araç, wallbox ve kablo çapraz kontrolüyle neden ayrılmalıdır.':'Olayı aynı koşullarda tekrar izleyin; yeni ürün almadan önce tekrarı ve olay kaydını doğrulayın.';steps=['Şarj gücü ve seans süresini kaydedin.','Aynı kabloyu bilinen sağlam istasyonda veya aynı istasyonu bilinen sağlam kabloyla karşılaştırın.'];if(r.repeat&&!r.crosscheck)steps.unshift('Çapraz kontrol tamamlanmadan kablo değişim kararı vermeyin.');if(r.repeat&&r.crosscheck&&r.cableType==='portable'&&r.purpose==='replacement'&&r.manual){commercial=true;summary='Çapraz kontrol kabloyu işaret ediyorsa, araç ve wallbox sınırlarıyla uyumlu Type 2 kablo rehberine geçebilirsiniz.'}}
if(safetyEvent)commercial=false;
if(r.cableType!=='portable')commercial=false;
if(!r.manual&&commercial){commercial=false;steps.unshift('Tam model üretici talimatını doğrulayın.')}
return{level,label,title,summary,steps,commercial}}
$('form').addEventListener('submit',e=>{e.preventDefault();const r={createdAt:Date.now(),date:$('date').value||today(),cableType:$('cableType').value,cableLabel:labels('cableType'),powerClass:$('powerClass').value,event:$('event').value,eventLabel:labels('event'),location:$('location').value,locationLabel:labels('location'),purpose:$('purpose').value,damage:$('damage').checked,burn:$('burn').checked,wet:$('wet').checked,repeat:$('repeat').checked,crosscheck:$('crosscheck').checked,manual:$('manual').checked,retentionMode:'per-record',officialRecord:false};const out=evaluate(r);r.decision=out.label;const all=load();all.push(r);save(all);render();$('result').classList.remove('hidden');$('state').textContent=out.label;$('state').className=`pill ${out.level}`;$('title').textContent=out.title;$('summary').textContent=out.summary;$('steps').replaceChildren(...out.steps.map(t=>{const li=document.createElement('li');li.textContent=t;return li}));$('commercial').classList.toggle('hidden',!out.commercial);$('result').scrollIntoView({behavior:'smooth',block:'start'})});
$('export').addEventListener('click',()=>{const data={tool:'ALO186 EV şarj kablosu sağlık günlüğü',exportedAt:new Date().toISOString(),rawPersonalDataCollected:false,records:load()};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='alo186-ev-sarj-kablosu-gunlugu.json';a.click();URL.revokeObjectURL(a.href)});
$('calendar').addEventListener('click',()=>{const d=new Date();d.setDate(d.getDate()+90);const stamp=d.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z/,'Z');const ics=`BEGIN:VCALENDAR\nVERSION:2.0\nPRODID:-//ALO186//EV Cable Review//TR\nBEGIN:VEVENT\nUID:${Date.now()}@alo186.com\nDTSTAMP:${new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z/,'Z')}\nDTSTART:${stamp}\nSUMMARY:EV şarj kablosu sağlık kontrolü\nDESCRIPTION:Konnektör, kablo gövdesi, kilit ve olay kayıtlarını yeniden kontrol edin.\nEND:VEVENT\nEND:VCALENDAR`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([ics],{type:'text/calendar'}));a.download='ev-sarj-kablosu-kontrol.ics';a.click();URL.revokeObjectURL(a.href)});
render()})();
