'use strict';
(function(root,factory){
  const api=factory();
  if(typeof module==='object'&&module.exports)module.exports=api;
  if(root){root.ALO186SummerCoolingPlan=api;if(root.document)api.mount(root.document);}
})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const ROUTE='/sektor-rehberi/yaz-serinleme-elektrik-ve-tekrar-test-merkezi/';
  const LINKS={choice:'/hesaplama/vantilator-hava-sogutucu-klima-karar/',portable:'/hesaplama/portatif-klima-egzoz-pencere-priz-uygunluk/',sizing:'/hesaplama/klima-btu-elektrik-altyapi-uygunluk/',backup:'/hesaplama/klima-yedek-guc-uygunluk/',energy:'/hesaplama/elektrik-faturasi-kwh-gun-karsilastirma/',outage:'/elektrik-kesintisi/',emergency:'/acil-numaralar/'};
  function buildPlan(data){
    const tasks=[];
    let level='P2',repeatDays=90;
    if(data.heatSymptoms){level='P0';repeatDays=7;tasks.push({priority:'P0',title:'Sıcak çarpması belirtisinde ürün seçimini bırakın',route:LINKS.emergency,detail:'Bilinç değişikliği, nöbet veya bayılmada 112 desteği isteyin ve güvenli serin alana geçin.'});}
    if(data.activeOutage){level=level==='P0'?level:'P1';repeatDays=Math.min(repeatDays,30);tasks.push({priority:'P1',title:'Kesintiyi resmî kanaldan doğrulayın',route:LINKS.outage,detail:'Yeni ürün teslimatını anlık çözüm saymayın; mevcut test edilmiş düşük güçlü serinleme planını kullanın.'});}
    if(data.vulnerablePerson){level=level==='P0'?level:'P1';repeatDays=Math.min(repeatDays,7);tasks.push({priority:'P1',title:'Riskli kişiyi aynı gün kontrol planına alın',route:LINKS.choice,detail:'Bebek, ileri yaş, gebelik veya kronik hastalıkta yalnız cihaz seçimi değil serin alan, sıvı ve düzenli temas planı gerekir.'});}
    if(data.unsureDevice)tasks.push({priority:'P1',title:'Vantilatör, hava soğutucu ve klima görevini ayırın',route:LINKS.choice,detail:'Sıcaklık, nem, hava kalitesi ve gerçek etiket W ile ücretsiz karar testini tamamlayın.'});
    if(data.portableAC){repeatDays=Math.min(repeatDays,30);tasks.push({priority:'P1',title:'Portatif klima kurulumunu doğrulayın',route:LINKS.portable,detail:'Egzoz, pencere kiti, hortum, yoğuşma, doğrudan priz ve RCD kanıtını birlikte test edin.'});}
    if(data.newAC||data.roomChanged){repeatDays=Math.min(repeatDays,30);tasks.push({priority:'P1',title:'Oda yükünü ve elektrik altyapısını yeniden hesaplayın',route:LINKS.sizing,detail:'Metrekareyi tek başına kullanmayın; tavan, güneş, kişi, giriş W/A ve devre şartını birlikte doğrulayın.'});}
    if(data.activeOutage||data.backupNeed)tasks.push({priority:'P1',title:'Klima yedek güç ihtiyacını ayrı değerlendirin',route:LINKS.backup,detail:'Aktif kesintide satın alma değil; sürekli/tepe W, Wh, bağlantı ve gerçek yük testi üzerinden plan yapın.'});
    if(data.highBill){repeatDays=Math.min(repeatDays,30);tasks.push({priority:'P2',title:'Tüketimi TL yerine kWh/gün ile karşılaştırın',route:LINKS.energy,detail:'Tarife değişikliği ile gerçek tüketim artışını ayırın; yeni ölçüm cihazını yalnız açıklanamayan artışta değerlendirin.'});}
    if(data.existingFailure){repeatDays=Math.min(repeatDays,30);tasks.push({priority:'P1',title:'Mevcut cihazı değiştirmeden önce bakım kanıtı oluşturun',route:LINKS.sizing,detail:'Filtre, hava akışı, dış ünite, egzoz, hortum ve elektrik bağlantısı kontrol edilmeden daha büyük cihaz seçmeyin.'});}
    if(!tasks.length)tasks.push({priority:'P2',title:'90 günlük mevsimsel kontrolü planlayın',route:LINKS.choice,detail:'Priz sıcaklığı, filtre, hortum, yoğuşma, etiket W ve gerçek konfor testini yeniden doğrulayın.'});
    return {level,repeatDays,tasks,commerce:false,personalData:false,officialRecord:false};
  }
  function read(doc){const id=(x)=>doc.getElementById(x);return {heatSymptoms:id('heatSymptoms').checked,activeOutage:id('activeOutage').checked,vulnerablePerson:id('vulnerablePerson').checked,unsureDevice:id('unsureDevice').checked,portableAC:id('portableAC').checked,newAC:id('newAC').checked,roomChanged:id('roomChanged').checked,backupNeed:id('backupNeed').checked,highBill:id('highBill').checked,existingFailure:id('existingFailure').checked};}
  function esc(s){return String(s).replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function mount(doc){const form=doc.getElementById('summerPlanForm');if(!form)return;const result=doc.getElementById('result');let last=null;const render=()=>{last=buildPlan(read(doc));result.className='result '+(last.level==='P0'?'danger':last.level==='P1'?'warn':'ok');result.innerHTML='<h2>'+esc(last.level)+' görev planı</h2><p>Tekrar kontrol: <b>'+esc(last.repeatDays)+' gün</b>. Bu merkez doğrudan ürün bağlantısı göstermez.</p><ol>'+last.tasks.map((task)=>'<li><b>'+esc(task.priority)+' · '+esc(task.title)+'</b><p>'+esc(task.detail)+'</p><a href="'+esc(task.route)+'">İlgili ücretsiz rotayı aç →</a></li>').join('')+'</ol>';};form.addEventListener('submit',(e)=>{e.preventDefault();render();result.scrollIntoView({behavior:'smooth',block:'start'});});doc.getElementById('exportJson').addEventListener('click',()=>{if(!last)render();const a=doc.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({route:ROUTE,createdAt:new Date().toISOString(),input:read(doc),plan:last},null,2)],{type:'application/json'}));a.download='alo186-yaz-serinleme-plani.json';a.click();URL.revokeObjectURL(a.href);});doc.getElementById('calendar').addEventListener('click',()=>{if(!last)render();const d=new Date();d.setDate(d.getDate()+last.repeatDays);const stamp=(x)=>x.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z');const ics=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//ALO186//Summer Cooling Review//TR','BEGIN:VEVENT','UID:'+Date.now()+'@alo186.com','DTSTAMP:'+stamp(new Date()),'DTSTART:'+stamp(d),'SUMMARY:Yaz serinleme ve elektrik planını yeniden doğrula','DESCRIPTION:İç sıcaklık nem filtre egzoz hortumu pencere kiti priz sıcaklığı RCD etiket W ve gerçek konfor testini yeniden kontrol edin.','END:VEVENT','END:VCALENDAR'].join('\r\n');const a=doc.createElement('a');a.href=URL.createObjectURL(new Blob([ics],{type:'text/calendar'}));a.download='alo186-yaz-serinleme-'+last.repeatDays+'-gun.ics';a.click();URL.revokeObjectURL(a.href);});}
  return {buildPlan,mount,ROUTE,LINKS};
});