(()=>{'use strict';
const $=id=>document.getElementById(id),KEY='alo186_grounding_trend_v1',TTL=1095*86400000,MAX=30;
const today=()=>new Date().toISOString().slice(0,10);$('date').value=today();
const soilOption=document.createElement('option');soilOption.value='soil4';soilOption.textContent='4 kutuplu toprak özdirenci (Wenner)';$('method').append(soilOption);
function load(){let x=[];try{x=JSON.parse(localStorage.getItem(KEY)||'[]')}catch(_){x=[]}const now=Date.now();x=x.filter(r=>r&&now-r.createdAt<TTL).slice(-MAX);localStorage.setItem(KEY,JSON.stringify(x));return x}
function save(x){localStorage.setItem(KEY,JSON.stringify(x.slice(-MAX)))}
function label(id){const el=$(id);return el.options[el.selectedIndex].textContent}
function unit(metric){return metric==='soil'?'Ω·m':'Ω'}
function methodMetricValid(metric,method){if(metric==='soil')return method==='soil4';if(metric==='loop')return method==='stakeless';if(metric==='earth')return ['fall','selective','two'].includes(method);return false}
function trendEligible(r){return !!(r&&r.qualified&&r.instrument&&methodMetricValid(r.metric,r.method)&&!(r.method==='stakeless'&&!r.bonded))}
function comparable(a,b){return trendEligible(a)&&trendEligible(b)&&a.point===b.point&&a.metric===b.metric&&a.method===b.method&&a.condition===b.condition}
function syncMethod(){const metric=$('metric').value,method=$('method').value;if(metric==='soil'&&method!=='soil4')$('method').value='soil4';else if(metric==='loop'&&method!=='stakeless')$('method').value='stakeless';else if(metric==='earth'&&!['fall','selective','two'].includes(method))$('method').value='fall'}
$('metric').addEventListener('change',syncMethod);syncMethod();
function render(){const x=load(),box=$('records');if(!x.length){box.innerHTML='<p class="small">Henüz kayıt yok.</p>';return}box.replaceChildren(...x.slice().reverse().map(r=>{const d=document.createElement('div');d.className='record';const s=document.createElement('strong');s.textContent=`${r.date} · ${r.pointLabel}`;const p=document.createElement('p');p.className='small';p.textContent=`${r.value.toLocaleString('tr-TR')} ${unit(r.metric)} · ${r.methodLabel} · ${r.decision}`;d.append(s,p);return d}))}
function evaluate(r,previous){let level='good',labelText='Trend kaydı oluşturuldu',title='Ölçüm karşılaştırma günlüğüne eklendi.',summary='Bu kayıt tek başına tesis uygunluğu veya uygunsuzluğu oluşturmaz.',steps=['Proje kabul sınırı, koruma düzeni, RCD ve çevrim empedansı ile birlikte değerlendirin.'],prev=null,delta=null;
if(!methodMetricValid(r.metric,r.method)){level='bad';labelText='Yöntem-büyüklük uyuşmuyor';title='Seçilen yöntem bu ölçülen büyüklük için kullanılamaz.';summary='Toprak özdirenci için dört kutuplu özdirenç yöntemi, kazıksız pens sonucu için çevrim direnci ve elektrot direnci için uygun elektrot yöntemi seçilmelidir.';steps=['Ölçüm cihazının fonksiyonunu ve bağlantı şemasını doğrulayın.','Yanlış yöntemle alınan değeri trend veya uygunluk kanıtı olarak kullanmayın.']}
else if(!r.qualified||!r.instrument){level='warn';labelText='Kanıt eksik';title='Ölçümün personel veya cihaz kanıtı eksik.';summary='Değeri resmî/periyodik ölçüm sonucu gibi kullanmayın.';steps=['Ölçüm yöntemi, cihaz, kalibrasyon ve uygulayan personel kaydını tamamlayın.']}
else if(r.method==='stakeless'&&!r.bonded){level='bad';labelText='Yöntem uygunluğu doğrulanmadı';title='Kazıksız yöntem için kapalı çoklu topraklama çevrimi doğrulanmadı.';summary='Tek izole elektrot veya açık çevrimde pens sonucu geçerli elektrot direnci kabul edilmemelidir.';steps=['Sistem topolojisini doğrulayın.','Gerekirse kazıklı düşüm veya seçici yöntemi yetkili personelle uygulayın.']}
else if(r.acceptance==='outside'){level='bad';labelText='Uzman sınırı dışında';title='Kayıt proje veya uzman kabul sınırı dışında işaretlendi.';summary='Değeri düşürmek için rastgele N-PE bağı veya ek elektrot uygulamayın; kök neden ve koruma koordinasyonu incelenmelidir.';steps=['Ölçümü aynı yöntemle teyit edin.','Bağlantı, korozyon, süreklilik, paralel yol ve elektrot durumunu inceleyin.']}
else if(r.acceptance==='unknown'){level='warn';labelText='Kabul kararı yok';title='Trend kaydı var; uygunluk kararı henüz verilmedi.';summary='Evrensel tek ohm sınırı kullanılmadı. Proje, sistem tipi ve ulusal kurallar uzman tarafından değerlendirilmelidir.'}
const matches=previous.filter(x=>comparable(r,x));if(matches.length){prev=matches[matches.length-1];delta=(r.value-prev.value)/prev.value*100;steps.push(delta>0?'Değer önceki karşılaştırılabilir kayda göre arttı; saha koşulu ve bağlantıları doğrulayın.':delta<0?'Değer önceki karşılaştırılabilir kayda göre azaldı; yöntemin ve koşulların aynı kaldığını teyit edin.':'Değer önceki karşılaştırılabilir kayıtla aynı.')}
else steps.push(trendEligible(r)?'Aynı nokta, büyüklük, yöntem ve saha koşulunda önceki geçerli kayıt bulunmadı; bu değer başlangıç referansıdır.':'Bu kayıt yöntem veya kanıt kapısını geçmediği için trend başlangıç referansı olarak kullanılmaz.');
if(r.method==='stakeless')steps.push('Kazıksız sonuç çevrim direncidir; izole tek elektrot değeri olarak etiketlemeyin.');
return{level,labelText,title,summary,steps,prev,delta}}
$('form').addEventListener('submit',e=>{e.preventDefault();const previous=load();const r={createdAt:Date.now(),date:$('date').value||today(),point:$('point').value,pointLabel:label('point'),metric:$('metric').value,metricLabel:label('metric'),method:$('method').value,methodLabel:label('method'),value:Number($('value').value),condition:$('condition').value,conditionLabel:label('condition'),acceptance:$('acceptance').value,acceptanceLabel:label('acceptance'),interval:Number($('interval').value),qualified:$('qualified').checked,instrument:$('instrument').checked,bonded:$('bonded').checked,parallel:$('parallel').checked,retentionMode:'per-record',officialReport:false,affiliateLinks:0};r.trendEligible=trendEligible(r);const out=evaluate(r,previous);r.decision=out.labelText;previous.push(r);save(previous);render();$('result').classList.remove('hidden');$('state').textContent=out.labelText;$('state').className=`pill ${out.level}`;$('title').textContent=out.title;$('summary').textContent=out.summary;$('newValue').textContent=`${r.value.toLocaleString('tr-TR',{maximumFractionDigits:3})} ${unit(r.metric)}`;$('previous').textContent=out.prev?`${out.prev.value.toLocaleString('tr-TR',{maximumFractionDigits:3})} ${unit(r.metric)}`:'Yok';$('delta').textContent=out.delta===null?'Karşılaştırma yok':`%${out.delta.toLocaleString('tr-TR',{maximumFractionDigits:1})}`;$('steps').replaceChildren(...out.steps.map(t=>{const li=document.createElement('li');li.textContent=t;return li}));$('result').scrollIntoView({behavior:'smooth',block:'start'})});
$('export').addEventListener('click',()=>{const data={tool:'ALO186 topraklama ölçüm trend günlüğü',exportedAt:new Date().toISOString(),rawPersonalDataCollected:false,officialReport:false,records:load()};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='alo186-topraklama-olcum-trendi.json';a.click();URL.revokeObjectURL(a.href)});
$('calendar').addEventListener('click',()=>{const days=Number($('interval').value)||365,d=new Date();d.setDate(d.getDate()+days);const fmt=x=>x.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z/,'Z');const ics=`BEGIN:VCALENDAR\nVERSION:2.0\nPRODID:-//ALO186//Grounding Retest//TR\nBEGIN:VEVENT\nUID:${Date.now()}@alo186.com\nDTSTAMP:${fmt(new Date())}\nDTSTART:${fmt(d)}\nSUMMARY:Topraklama ölçümünü yeniden doğrula\nDESCRIPTION:Aynı nokta, yöntem ve benzer saha koşulunda profesyonel ölçüm planlayın.\nEND:VEVENT\nEND:VCALENDAR`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([ics],{type:'text/calendar'}));a.download='topraklama-yeniden-test.ics';a.click();URL.revokeObjectURL(a.href)});
render()})();
