'use strict';
(function(root,factory){
  const api=factory();
  if(typeof module==='object'&&module.exports)module.exports=api;
  if(root){root.ALO186VehicleInverter=api;if(root.document)api.mount(root.document);}
})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const ROUTE='/hesaplama/arac-12v-priz-inverter-yuk-uygunluk/';
  const n=(v)=>Number(v); const round=(v,d=2)=>Number(n(v).toFixed(d));
  function calculate(data){
    const voltage=n(data.voltage), loadW=n(data.loadW), efficiency=n(data.efficiencyPct)/100;
    const dcA=voltage>0&&loadW>=0&&efficiency>0?loadW/(voltage*efficiency):NaN;
    const plannedA=Number.isFinite(dcA)?dcA*1.2:NaN;
    const socketW=n(data.socketMaxA)*voltage;
    return {dcA:round(dcA,2),plannedA:round(plannedA,2),socketW:round(socketW,0)};
  }
  function decide(data){
    const calc=calculate(data); const confirms=Boolean(data.confirmNeed&&data.confirmLabel&&data.confirmAffiliate);
    if(data.danger||data.socketDamage)return {...calc,code:'danger',commerce:false,tone:'danger',title:'Aracın 12 V prizini kullanmayın',summary:'Duman, erime, yanık kokusu, gevşeklik, aşırı ısınma veya kablo hasarında devreyi kapatın ve araç elektriği servisine başvurun.'};
    if(data.loadClass==='medical'||data.loadClass==='heater'||data.loadClass==='motor'||data.loadClass==='fixed')return {...calc,code:'unsupported',commerce:false,tone:'warn',title:'Bu yük tüketici tipi 12 V priz/inverter akışına uygun değil',summary:'Tıbbi, ısıtıcı, kettle, saç kurutma, motorlu veya sabit bağlantılı yükleri araç aksesuar prizinden beslemeyin.'};
    if(data.connection!=='accessory')return {...calc,code:'installation',commerce:false,tone:'warn',title:'Doğrudan akü veya sabit montaj profesyonel tasarım gerektirir',summary:'Sigorta, kablo kesiti, güzergâh, havalandırma ve akü koruması araç elektriği uzmanı tarafından belirlenmelidir.'};
    if(!data.manualVerified||!data.socketLabelVerified||!data.inverterLabelVerified)return {...calc,code:'evidence',commerce:false,tone:'warn',title:'Kılavuz ve etiket kanıtı eksik',summary:'Araç prizinin azami A/W sınırı ile inverterin DC giriş ve AC çıkış sınırı doğrulanmadan uygunluk sonucu üretilemez.'};
    if(!Number.isFinite(calc.plannedA)||n(data.socketMaxA)<=0||n(data.inverterInputMaxA)<=0)return {...calc,code:'invalid',commerce:false,tone:'warn',title:'Geçerli güç ve akım değerleri girin',summary:'Gerilim, yük W, verim, priz A ve inverter giriş A değerlerini tam model etiketinden girin.'};
    if(calc.plannedA>n(data.socketMaxA)||calc.plannedA>n(data.inverterInputMaxA)||n(data.loadW)>n(data.inverterOutputW))return {...calc,code:'overload',commerce:false,tone:'danger',title:'Planlanan yük etiket sınırını aşıyor',summary:'Daha büyük priz sigortası takmayın. Yükü azaltın veya araç üreticisi ve uzman tarafından tasarlanmış ayrı besleme kullanın.'};
    if(data.engineOff&&n(data.runtimeMinutes)>30&&!data.batteryEnergyVerified)return {...calc,code:'battery_runtime',commerce:false,tone:'warn',title:'Marş aküsü çalışma süresi kanıtı eksik',summary:'Motor kapalıyken aksesuar yükü marş aküsünü boşaltabilir. Akü kapasitesi, kullanım rezervi ve düşük gerilim kesmesi doğrulanmadan uzun süre planlamayın.'};
    if(data.existingSuitable&&data.realLoadTest&&data.noHeat)return {...calc,code:'no_buy',commerce:false,tone:'ok',title:'Mevcut araç inverteri yeterli — yeni ürün almayın',summary:'Priz ve inverter etiketleri, yüzde 20 planlama payı, sıcaklık ve gerçek yük testi karşılanıyor.'};
    if(!confirms)return {...calc,code:'confirm',commerce:false,tone:'info',title:'Önce üç güven onayını tamamlayın',summary:'Gerçek eksik, etiket doğrulaması ve satış ortaklığı bilgisini ayrı ayrı onaylayın.'};
    return {...calc,code:'eligible',commerce:true,tone:'ok',title:'Koşullu düşük güçlü ürün sınıfı açıldı',summary:'Yalnız laptop, kamera, telefon adaptörü ve benzeri düşük güçlü elektronikler için; araç prizi ve inverter etiket sınırlarının altında kalan çözümü karşılaştırın.'};
  }
  function read(doc){const id=(x)=>doc.getElementById(x);return {danger:id('danger').checked,socketDamage:id('socketDamage').checked,voltage:id('voltage').value,loadW:id('loadW').value,efficiencyPct:id('efficiencyPct').value,socketMaxA:id('socketMaxA').value,inverterInputMaxA:id('inverterInputMaxA').value,inverterOutputW:id('inverterOutputW').value,loadClass:id('loadClass').value,connection:id('connection').value,manualVerified:id('manualVerified').checked,socketLabelVerified:id('socketLabelVerified').checked,inverterLabelVerified:id('inverterLabelVerified').checked,engineOff:id('engineOff').checked,runtimeMinutes:id('runtimeMinutes').value,batteryEnergyVerified:id('batteryEnergyVerified').checked,existingSuitable:id('existingSuitable').checked,realLoadTest:id('realLoadTest').checked,noHeat:id('noHeat').checked,confirmNeed:id('confirmNeed').checked,confirmLabel:id('confirmLabel').checked,confirmAffiliate:id('confirmAffiliate').checked};}
  function esc(s){return String(s).replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function mount(doc){const form=doc.getElementById('inverterForm');if(!form)return;const result=doc.getElementById('result');const affiliate=doc.getElementById('affiliate');let last=null;const render=()=>{last=decide(read(doc));result.className='result '+last.tone;result.innerHTML='<h2>'+esc(last.title)+'</h2><p>'+esc(last.summary)+'</p><div class="metrics"><span><b>'+esc(last.dcA)+'</b> A tahmini DC akım</span><span><b>'+esc(last.plannedA)+'</b> A %20 planlama</span><span><b>'+esc(last.socketW)+'</b> W etiket teorik üst sınırı</span></div>';affiliate.classList.toggle('hidden',!last.commerce);};form.addEventListener('submit',(e)=>{e.preventDefault();render();result.scrollIntoView({behavior:'smooth',block:'start'});});doc.getElementById('exportJson').addEventListener('click',()=>{if(!last)render();const a=doc.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({route:ROUTE,createdAt:new Date().toISOString(),input:read(doc),decision:last},null,2)],{type:'application/json'}));a.download='alo186-arac-12v-inverter.json';a.click();URL.revokeObjectURL(a.href);});doc.getElementById('calendar').addEventListener('click',()=>{const d=new Date();d.setDate(d.getDate()+90);const stamp=(x)=>x.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z');const ics=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//ALO186//Vehicle Outlet Check//TR','BEGIN:VEVENT','UID:'+Date.now()+'@alo186.com','DTSTAMP:'+stamp(new Date()),'DTSTART:'+stamp(d),'SUMMARY:Araç 12 V priz ve inverter kontrolü','DESCRIPTION:Priz sıcaklığı sigorta etiketi kablo inverter havalandırması ve gerçek yük testini yeniden doğrulayın.','END:VEVENT','END:VCALENDAR'].join('\r\n');const a=doc.createElement('a');a.href=URL.createObjectURL(new Blob([ics],{type:'text/calendar'}));a.download='alo186-arac-inverter-90-gun.ics';a.click();URL.revokeObjectURL(a.href);});}
  return {calculate,decide,mount,ROUTE};
});