(() => {
  'use strict';
  const $=id=>document.getElementById(id);
  const core=window.Alo186UPSBatterySuitability;
  const valueIds=['upsType','upsVa','upsAgeYears','batteryChemistry','batteryAgeYears','ambientC','runtimeNowMinutes','runtimeRequiredMinutes','selfTest','batterySystem'];
  const checkIds=['replaceAlarm','physicalSafe','fullyChargedBeforeTest','normalLoadTested','exactUpsModelKnown','cartridgeCodeKnown','exactSpecsMatch','manufacturerUserReplaceable','manualChecked','supportChecked','allModulesSameAge','criticalLoad','medicalLoad'];
  const presets={healthy:{upsType:'desktop',upsVa:1000,upsAgeYears:2,batteryChemistry:'vrla',batteryAgeYears:2,ambientC:23,runtimeNowMinutes:25,runtimeRequiredMinutes:15,selfTest:'pass',batterySystem:'internal-single',replaceAlarm:false,physicalSafe:true,fullyChargedBeforeTest:true,normalLoadTested:true,exactUpsModelKnown:true,cartridgeCodeKnown:true,exactSpecsMatch:true,manufacturerUserReplaceable:true,manualChecked:true,supportChecked:true,allModulesSameAge:true,criticalLoad:false,medicalLoad:false},replace:{upsType:'desktop',upsVa:1500,upsAgeYears:4,batteryChemistry:'vrla',batteryAgeYears:4,ambientC:24,runtimeNowMinutes:4,runtimeRequiredMinutes:15,selfTest:'fail',batterySystem:'internal-single',replaceAlarm:true,physicalSafe:true,fullyChargedBeforeTest:true,normalLoadTested:true,exactUpsModelKnown:true,cartridgeCodeKnown:true,exactSpecsMatch:true,manufacturerUserReplaceable:true,manualChecked:true,supportChecked:true,allModulesSameAge:true,criticalLoad:false,medicalLoad:false},old:{upsType:'desktop',upsVa:1500,upsAgeYears:9,batteryChemistry:'vrla',batteryAgeYears:5,ambientC:27,runtimeNowMinutes:3,runtimeRequiredMinutes:15,selfTest:'fail',batterySystem:'internal-single',replaceAlarm:true,physicalSafe:true,fullyChargedBeforeTest:true,normalLoadTested:true,exactUpsModelKnown:true,cartridgeCodeKnown:true,exactSpecsMatch:true,manufacturerUserReplaceable:true,manualChecked:true,supportChecked:true,allModulesSameAge:true,criticalLoad:false,medicalLoad:false}};
  const labels={monitor:'Mevcut akü ihtiyacı karşılıyor; satın alma gerekmeyebilir',retest:'Önce tam şarj ve kontrollü self-test yapın','replace-battery':'Doğrulanmış kullanıcı-değiştirilebilir kartuş değerlendirilebilir','information-needed':'Akü değişiminden önce teknik bilgiler tamamlanmalı','compare-ups':'Akü değişimini yeni UPS ile karşılaştırın',professional:'Yetkili servis / profesyonel değerlendirme gerekir',stop:'Kullanımı durdurun ve güvenli servis sürecini başlatın',conditional:'Koşullu değerlendirme'};
  const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const list=items=>items.map(x=>`<li>${esc(x)}</li>`).join('');
  function values(){const data={};valueIds.forEach(id=>data[id]=$(id).value);checkIds.forEach(id=>data[id]=$(id).checked);return data;}
  function setValues(data){valueIds.forEach(id=>{if(data[id]!=null)$(id).value=String(data[id]);});checkIds.forEach(id=>{$(id).checked=Boolean(data[id]);});}
  function emit(name,params={}){if(typeof window.Alo186Track==='function')window.Alo186Track(name,params);}
  function updateAffiliate(){const enabled=['needAck','specAck','affiliateAck'].every(id=>$(id).checked),link=$('productCenterLink');link.classList.toggle('disabled-link',!enabled);link.setAttribute('aria-disabled',enabled?'false':'true');link.tabIndex=enabled?0:-1;}
  function render(r){
    $('results').classList.remove('hidden');$('resultStatus').textContent=labels[r.status]||'Sonuç';$('resultStatus').className=`status ${['monitor','replace-battery'].includes(r.status)?'ok':['stop','professional'].includes(r.status)?'bad':'warn'}`;
    $('runtimeMetric').textContent=`${Math.abs(r.runtimeMargin).toLocaleString('tr-TR')} dk ${r.runtimeMargin>=0?'fazla':'eksik'}`;$('ageMetric').textContent=`${Number(r.input.batteryAgeYears).toLocaleString('tr-TR')} yıl`;$('confidenceMetric').textContent=`${r.confidence}/100`;$('routeMetric').textContent=r.commercialAllowed?'Kartuş ön seçimi':r.noPurchaseNeeded?'Satın almama':r.professionalRequired?'Uzman/servis':'Önce bilgi/test';
    $('blockerCard').classList.toggle('hidden',!r.blockers.length);$('blockerList').innerHTML=list(r.blockers);$('warningList').innerHTML=list(r.warnings.length?r.warnings:['Belirgin bir ek uyarı yok; tam model kılavuzu yine esas alınmalıdır.']);$('checkList').innerHTML=list(r.checks);
    $('noPurchasePanel').classList.toggle('hidden',!r.noPurchaseNeeded);$('retestPanel').classList.toggle('hidden',!r.retestFirst);$('comparePanel').classList.toggle('hidden',!r.compareUps);$('professionalPanel').classList.toggle('hidden',!r.professionalRequired);$('affiliatePanel').classList.toggle('hidden',!r.commercialAllowed);
    ['needAck','specAck','affiliateAck'].forEach(id=>$(id).checked=false);updateAffiliate();
    $('results').focus({preventScroll:true});$('results').scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});
    emit('ups_battery_suitability_completed',{status:r.status,commercial_allowed:r.commercialAllowed,no_purchase_needed:r.noPurchaseNeeded,confidence_band:r.confidence>=90?'high':r.confidence>=70?'medium':'low',ups_band:r.input.upsVa<=1500?'small':r.input.upsVa<=3000?'medium':'professional'});
  }
  document.querySelectorAll('[data-preset]').forEach(btn=>btn.addEventListener('click',()=>{setValues(presets[btn.dataset.preset]);emit('ups_battery_preset_selected',{preset:btn.dataset.preset});}));
  $('upsBatteryForm').addEventListener('submit',event=>{event.preventDefault();try{$('validation').textContent='';render(core.analyze(values()));}catch(error){$('validation').textContent=error.message;$('validation').focus();}});
  $('resetBtn').addEventListener('click',()=>{$('upsBatteryForm').reset();setValues(presets.healthy);$('results').classList.add('hidden');$('validation').textContent='';emit('ups_battery_reset');});
  ['needAck','specAck','affiliateAck'].forEach(id=>$(id).addEventListener('change',updateAffiliate));
  $('productCenterLink').addEventListener('click',event=>{if(event.currentTarget.getAttribute('aria-disabled')==='true'){event.preventDefault();return;}emit('ups_battery_product_center_opened',{category:'ups_replacement_battery'});});
  setValues(presets.healthy);
})();