'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const core=require('./core.js');
const base={upsType:'desktop',upsVa:1500,upsAgeYears:4,batteryChemistry:'vrla',batteryAgeYears:4,ambientC:24,runtimeNowMinutes:4,runtimeRequiredMinutes:15,selfTest:'fail',replaceAlarm:true,physicalSafe:true,fullyChargedBeforeTest:true,normalLoadTested:true,exactUpsModelKnown:true,cartridgeCodeKnown:true,exactSpecsMatch:true,manufacturerUserReplaceable:true,manualChecked:true,supportChecked:true,allModulesSameAge:true,batterySystem:'internal-single',criticalLoad:false,medicalLoad:false};
const run=o=>core.analyze({...base,...o});
const replace=run({});assert.equal(replace.status,'replace-battery');assert.equal(replace.commercialAllowed,true);assert.equal(replace.confidence,100);
const healthy=run({batteryAgeYears:2,runtimeNowMinutes:25,runtimeRequiredMinutes:15,selfTest:'pass',replaceAlarm:false});assert.equal(healthy.noPurchaseNeeded,true);assert.equal(healthy.commercialAllowed,false);assert.equal(healthy.status,'monitor');
const hazard=run({physicalSafe:false});assert.equal(hazard.status,'stop');assert.equal(hazard.commercialAllowed,false);assert(hazard.blockerCodes.includes('physical_hazard'));
const medical=run({medicalLoad:true});assert.equal(medical.status,'stop');assert.equal(medical.commercialAllowed,false);
const retest=run({selfTest:'not-run',replaceAlarm:false,runtimeNowMinutes:5,fullyChargedBeforeTest:false,normalLoadTested:false});assert.equal(retest.status,'retest');assert.equal(retest.commercialAllowed,false);
const old=run({upsAgeYears:9});assert.equal(old.status,'compare-ups');assert.equal(old.compareUps,true);assert.equal(old.commercialAllowed,false);
const unknown=run({cartridgeCodeKnown:false});assert.equal(unknown.status,'information-needed');assert.equal(unknown.commercialAllowed,false);
const rack=run({upsType:'rack'});assert.equal(rack.status,'professional');assert.equal(rack.commercialAllowed,false);
const external=run({batterySystem:'external-cabinet'});assert.equal(external.status,'professional');assert.equal(external.commercialAllowed,false);
const lithium=run({batteryChemistry:'lithium'});assert.equal(lithium.status,'professional');assert.equal(lithium.commercialAllowed,false);
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
assert(html.includes('https://www.alo186.com/hesaplama/ups-akusu-degisim-uygunluk/'));
assert(html.includes('Şeffaf satış ortaklığı'));
assert(html.includes('Schneider Electric'));
assert(html.includes('28 Temmuz 2026'));
assert(html.includes('Satın almama sonucu'));
assert(html.includes('aria-live="polite"'));
assert(html.includes('type="application/ld+json"'));
assert(!/amazon\.(com|com\.tr)/i.test(html));
const fields=[...html.matchAll(/<(?:input|select|textarea)\b[^>]*(?:id|name)="([^"]+)"/gi)].map(m=>m[1]);
assert(!fields.some(field=>/(^|[-_])(name|email|phone|telefon|address|adres|abonelik|tc|identity|plaka|serial|seri)([-_]|$)/i.test(field)));
console.log('UPS aküsü değişim uygunluk testleri başarılı.');