(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.Alo186OutageKitCore=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';

const DAY_MS=86400000;
const STORAGE_KEY='alo186:outage-kit:v1';
const VERSION=1;
const REVIEW_DAYS=90;
const PROFILES={home:'Ev',small_business:'Küçük işletme',hotel_site:'Otel / site / tesis'};
const INVENTORY_STATES={tested:'Var ve gerçek kullanımda yeterli',unknown:'Var; kapasitesi veya güvenliği doğrulanmadı',missing:'Yok'};
const NEEDS={mobile:'Telefon ve mobil iletişim',internet:'Modem / fiber ONT / POS',lighting:'Güvenli acil aydınlatma',cold_chain:'Buzdolabı veya soğuk zincir',electronics:'Hassas elektronik ve kayıt cihazı',medical:'Elektrikle çalışan tıbbi cihaz'};
const CATEGORIES={
 powerbank:{label:'Powerbank',need:'mobile',tool:'/hesaplama/powerbank-usb-c-uygunluk/',product:'/akilli-urun-secimi?kategori=powerbank',priority:2,risk:'consumer',criteria:['USB-C / port çıkış gücü','Kullanılabilir Wh ve hedef şarj sayısı','Kablo ve protokol uyumu','Şişme, ısı ve port hasarı']},
 mini_ups:{label:'Modem / ONT mini UPS',need:'internet',tool:'/hesaplama/modem-internet-yedekleme/',product:'/akilli-urun-secimi?kategori=mini_ups',priority:1,risk:'compatibility',criteria:['Cihaz voltajı, polaritesi ve jak ölçüsü','Toplam watt ve hedef çalışma süresi','Geçişte yeniden başlama testi','Gerçek runtime ve batarya sıcaklığı']},
 emergency_light:{label:'Şarjlı acil aydınlatma',need:'lighting',tool:'/hesaplama/acil-aydinlatma-sure-uygunluk/',product:'/akilli-urun-secimi?kategori=emergency_light',priority:0,risk:'consumer',criteria:['Alan ve aynı moddaki lümen','Hedef çalışma süresi','Fiziksel düğme / otomatik yanma','Pil, gövde ve kablo güvenliği']},
 smoke_alarm:{label:'Duman alarmı',need:'lighting',tool:'/hesaplama/duman-alarmi-yerlesim-bakim-uygunluk/',product:'/akilli-urun-secimi?kategori=smoke_alarm',priority:0,risk:'safety',criteria:['Kat ve uyuma alanı adedi','Tam model ve ilgili standart belgesi','Aylık test ve ürün yaşı','Düşük pil / ömür sonu uyarısı']},
 surge_strip:{label:'Akım korumalı grup priz',need:'electronics',tool:'/hesaplama/akim-korumali-grup-priz-uygunluk/',product:'/akilli-urun-secimi?kategori=surge_strip',priority:3,risk:'consumer',criteria:['Toplam sürekli ve tepe yük','Etiket amper / watt sınırı','Joule, gösterge ve aşırı akım koruması','İşlevsel topraklama ve doğrudan duvar bağlantısı']},
 power_station:{label:'Taşınabilir güç istasyonu',need:'cold_chain',tool:'/hesaplama/power-station-kapasite-eps-uygunluk/',product:'/akilli-urun-secimi?kategori=power_station',priority:1,risk:'compatibility',criteria:['Sürekli ve kalkış gücü','Hedef kullanılabilir Wh','Saf sinüs, EPS ve bypass sınırı','Batarya sıcaklığı ve üretici yük onayı']}
};

function hasOwn(obj,key){return Object.prototype.hasOwnProperty.call(obj,key);}
function safeEnum(value,map,fallback){const raw=String(value||'');return hasOwn(map,raw)?raw:fallback;}
function safeArray(value,allowed){return[...new Set((Array.isArray(value)?value:[]).map(String).filter(item=>hasOwn(allowed,item)))];}
function asDate(value){const date=value instanceof Date?value:new Date(value);return Number.isFinite(date.getTime())?date:null;}
function normalizeInventory(value={}){const result={};Object.keys(CATEGORIES).forEach(id=>{result[id]=safeEnum(value[id],INVENTORY_STATES,'missing');});return result;}
function normalizeInput(input={}){return{profile:safeEnum(input.profile,PROFILES,'home'),outageHours:[2,6,12,24].includes(Number(input.outageHours))?Number(input.outageHours):6,needs:safeArray(input.needs,NEEDS),inventory:normalizeInventory(input.inventory)};}
function requiredCategories(input){const required=new Set(['emergency_light','smoke_alarm']);input.needs.forEach(need=>Object.entries(CATEGORIES).forEach(([id,item])=>{if(item.need===need)required.add(id);}));if(input.outageHours>=8&&input.needs.some(need=>['internet','lighting','cold_chain'].includes(need)))required.add('power_station');return[...required];}
function professionalReason(input,category){if(input.needs.includes('medical'))return'Elektrikle çalışan tıbbi cihaz için üretici acil planı ve profesyonel kesintisiz güç tasarımı gerekir.';if(input.profile==='hotel_site')return'Otel, site veya tesis için tek ürün yerine kritik yük, transfer, yangın, bakım ve işletme planı birlikte doğrulanmalıdır.';if(input.profile==='small_business'&&category==='power_station'&&(input.needs.includes('cold_chain')||input.outageHours>=12))return'İşletme soğuk zinciri veya uzun kesinti için kapasite, transfer ve operasyon maliyeti profesyonel değerlendirilmelidir.';return'';}
function readinessValue(state){return state==='tested'?1:state==='unknown'?.45:0;}
function evaluate(raw={}){const input=normalizeInput(raw),required=requiredCategories(input),items=[];required.forEach(id=>{const meta=CATEGORIES[id],state=input.inventory[id],professional=professionalReason(input,id);let status='missing',affiliateAllowed=false;if(professional)status='professional';else if(state==='tested')status='covered';else if(state==='unknown')status='verify';else{status='missing';affiliateAllowed=true;}items.push({id,label:meta.label,status,state,priority:meta.priority,risk:meta.risk,need:meta.need,criteria:[...meta.criteria],toolRoute:meta.tool,productRoute:meta.product,affiliateAllowed,professionalReason:professional});});items.sort((a,b)=>a.priority-b.priority||a.label.localeCompare(b.label,'tr'));
 const denominator=Math.max(1,items.length),score=Math.round(items.reduce((sum,item)=>sum+(item.status==='professional'?0:readinessValue(item.state)),0)/denominator*100);
 const covered=items.filter(item=>item.status==='covered').length,verify=items.filter(item=>item.status==='verify').length,missing=items.filter(item=>item.status==='missing').length,professional=items.filter(item=>item.status==='professional').length;
 const status=professional?'professional':missing?'gaps':verify?'verify':'ready';
 return{input,status,score,items,metrics:{required:items.length,covered,verify,missing,professional,noBuy:covered},affiliateAllowed:items.some(item=>item.affiliateAllowed),professionalRequired:professional>0};}
function record(raw={},nowValue=new Date()){const now=asDate(nowValue)||new Date(),result=evaluate(raw);return{version:VERSION,createdAt:now.toISOString(),reviewAt:new Date(now.getTime()+REVIEW_DAYS*DAY_MS).toISOString(),profile:result.input.profile,outageHours:result.input.outageHours,needs:[...result.input.needs],inventory:{...result.input.inventory},status:result.status,score:result.score,metrics:{...result.metrics},missingCategories:result.items.filter(item=>item.status==='missing').map(item=>item.id),verifyCategories:result.items.filter(item=>item.status==='verify').map(item=>item.id),professionalCategories:result.items.filter(item=>item.status==='professional').map(item=>item.id)};}
function isValidRecord(value){return value&&value.version===VERSION&&hasOwn(PROFILES,value.profile)&&[2,6,12,24].includes(Number(value.outageHours))&&Number.isFinite(Date.parse(value.createdAt))&&Number.isFinite(Date.parse(value.reviewAt))&&Array.isArray(value.needs)&&Array.isArray(value.missingCategories)&&Array.isArray(value.verifyCategories)&&Array.isArray(value.professionalCategories);}
function brief(result){const lines=['ALO186 Marka Bağımsız Elektrik Kesintisi Kiti','',`Hazırlık skoru: ${result.score}/100`,`Gerekli kategori: ${result.metrics.required}`,`Mevcut ve yeterli: ${result.metrics.covered}`,`Önce doğrulanacak: ${result.metrics.verify}`,`Eksik: ${result.metrics.missing}`,`Profesyonel plan: ${result.metrics.professional}`,''];result.items.forEach((item,index)=>{const label={covered:'MEVCUT — yeni ürün önerilmez',verify:'ÖNCE TEST ET',missing:'EKSİK — teknik araç sonrası karşılaştır',professional:'PROFESYONEL PLAN'}[item.status];lines.push(`${index+1}. ${item.label}: ${label}`);item.criteria.forEach(criterion=>lines.push(`   - ${criterion}`));});lines.push('','ALO186 EDAŞ, kamu kurumu veya ürün satıcısı değildir. Haricî ürün bağlantıları satış ortaklığı bağlantısı olabilir; fiyat, stok, puan, satıcı ve garanti mağazada doğrulanır.');return lines.join('\n');}
function sharePayload(result){const missing=result.items.filter(item=>item.status==='missing').slice(0,3).map(item=>item.label),verify=result.items.filter(item=>item.status==='verify').slice(0,2).map(item=>item.label);return{title:'ALO186 Elektrik Kesintisi Kiti',text:['ALO186 kişisel verisiz kesinti kiti özeti',`Hazırlık skoru: ${result.score}/100`,missing.length?`Eksik: ${missing.join(', ')}`:'Eksik düşük riskli kategori görünmüyor.',verify.length?`Önce doğrula: ${verify.join(', ')}`:'',result.professionalRequired?'Profesyonel plan gereken alan var.':'','ALO186 resmî kurum veya ürün satıcısı değildir.'].filter(Boolean).join('\n'),url:'https://alo186.com/hesaplama/elektrik-kesintisi-kiti/'};}
return{STORAGE_KEY,VERSION,REVIEW_DAYS,PROFILES,INVENTORY_STATES,NEEDS,CATEGORIES,normalizeInput,requiredCategories,evaluate,record,isValidRecord,brief,sharePayload};
});
