(function(root,factory){
  const api=factory();
  if(typeof module==='object'&&module.exports){module.exports=api;}
  root.Alo186ProductCatalog=api;
})(typeof globalThis!=='undefined'?globalThis:this,function(){
  'use strict';

  const affiliateTag='alo186hazirlik-21';
  const verifiedAt='2026-07-27';
  const verificationMaxAgeDays=45;
  const catalogStatuses=new Set(['verified_listing','manufacturer_verified_search']);

  function amazonProductUrl(asin){
    const base=`https://www.amazon.com.tr/dp/${encodeURIComponent(asin)}`;
    return affiliateTag?`${base}?tag=${encodeURIComponent(affiliateTag)}`:base;
  }

  function amazonSearchUrl(query){
    const base=`https://www.amazon.com.tr/s?k=${encodeURIComponent(query)}`;
    return affiliateTag?`${base}&tag=${encodeURIComponent(affiliateTag)}`:base;
  }

  const needs=[
    {id:'mobile-continuity',name:'Mobil cihaz enerji sürekliliği'},
    {id:'plug-in-surge-protection',name:'Fişli cihaz darbe koruması'},
    {id:'internet-continuity',name:'Modem ve internet sürekliliği'},
    {id:'outage-lighting',name:'Kesintide taşınabilir aydınlatma'},
    {id:'fire-early-warning',name:'Yangın erken uyarısı'},
    {id:'carbon-monoxide-warning',name:'Karbonmonoksit erken uyarısı'},
    {id:'portable-backup-energy',name:'Taşınabilir yedek enerji'},
    {id:'portable-generation',name:'Taşınabilir elektrik üretimi'},
    {id:'dc-ac-conversion',name:'DC–AC dönüşümü ve batarya kullanımı'},
    {id:'basic-outlet-screening',name:'Priz ve RCD ön kontrolü'},
    {id:'device-energy-measurement',name:'Cihaz bazlı enerji ölçümü'},
    {id:'ev-ac-cable',name:'EV AC şarj kablosu uyumu'},
    {id:'ups-runtime-restoration',name:'UPS çalışma süresini geri kazanma'},
    {id:'temporary-power-extension',name:'Geçici kablo ve makara kullanımı'}
  ];

  const categories=[
    {id:'powerbank',name:'Telefon ve mobil cihaz için powerbank',mode:'direct',risk:'consumer',affiliatePolicy:'verified_direct',description:'Kapasite, USB-C çıkış gücü ve kablosuz şarj ihtiyacına göre ürün sayfası teknik verilerini karşılaştırır.',searchQuery:'USB C PD powerbank 20000 mAh dijital ekran',graph:{needIds:['mobile-continuity'],relatedTools:['/hesaplama/powerbank-usb-c-uygunluk/'],relatedGuides:['/amazon-elektrik-urunleri/powerbank-usb-c-secimi'],requiredEvidence:['mAh yanında Wh','USB-C PD profili','port başına ve toplam W','kablo gücü'],blockedWhen:['şişme','aşırı ısınma','fiziksel hasar']}},
    {id:'surge_strip',name:'Akım korumalı grup priz',mode:'guide',risk:'consumer',affiliatePolicy:'after_tool',nextStepUrl:'https://www.alo186.com/hesaplama/akim-korumali-grup-priz-uygunluk/',nextStepLabel:'Önce yük, priz, joule ve topraklama uygunluğunu test et',description:'Toplam sürekli/tepe yük, etiket amperi ve wattı, joule, priz sayısı, koruma göstergesi, bağlantı ve işlevsel topraklama doğrulanmadan ürün kartı açılmaz. Pano tipi SPD ve tesisat korumasının yerine geçmez.',searchQuery:'akım korumalı grup priz joule',graph:{needIds:['plug-in-surge-protection'],relatedTools:['/hesaplama/akim-korumali-grup-priz-uygunluk/'],relatedGuides:['/amazon-elektrik-urunleri/akim-korumali-grup-priz-secimi','/haberler/parafudr-gerilim-koruma-rolesi-farki'],requiredEvidence:['joule','nominal akım','toplam sürekli yük','koruma göstergesi'],blockedWhen:['işlevsel topraklama belirsiz','pano tipi SPD yerine kullanılmak istenmesi','yanık veya erime']}},
    {id:'mini_ups',name:'Modem ve fiber ONT için mini UPS',mode:'guide',risk:'compatibility',affiliatePolicy:'after_tool',nextStepUrl:'https://www.alo186.com/hesaplama/modem-internet-yedekleme/',nextStepLabel:'Önce modem ve ONT hesabını yap',description:'Voltaj, polarite, jak ölçüsü, toplam watt ve geçiş davranışı doğrulanmadan ürün seçilmemelidir.',searchQuery:'modem mini UPS 12V 9V 5V',graph:{needIds:['internet-continuity'],relatedTools:['/hesaplama/modem-internet-yedekleme/','/hesaplama/yedek-guc-runtime-saglik-gunlugu/'],relatedGuides:['/amazon-elektrik-urunleri/modem-mini-ups-secimi'],requiredEvidence:['çıkış gerilimi','polarite','jak ölçüsü','gerçek watt ve süre'],blockedWhen:['gerilim belirsiz','polarite belirsiz','şişme veya aşırı ısı']}},
    {id:'emergency_light',name:'Şarjlı acil aydınlatma',mode:'guide',risk:'consumer',affiliatePolicy:'after_tool',nextStepUrl:'https://www.alo186.com/hesaplama/acil-aydinlatma-sure-uygunluk/',nextStepLabel:'Önce lümen, adet ve çalışma süresini test et',description:'Alan, aynı moddaki lümen ve çalışma süresi, otomatik yanma, fiziksel düğme, pil göstergesi ve kullanım ortamı doğrulanmadan ürün seçilmemelidir.',searchQuery:'şarjlı acil durum lambası kamp lambası',graph:{needIds:['outage-lighting'],relatedTools:['/hesaplama/acil-aydinlatma-sure-uygunluk/','/hesaplama/acil-aydinlatma-test-bakim-gunlugu/'],relatedGuides:['/amazon-elektrik-urunleri/acil-aydinlatma-duman-alarmi'],requiredEvidence:['lümen','aynı modda çalışma süresi','fiziksel düğme','pil göstergesi'],blockedWhen:['sabit kaçış sistemini ikame etme','ilk kötü test','batarya hasarı']}},
    {id:'smoke_alarm',name:'Fotoelektrik duman alarmı',mode:'guide',risk:'safety',affiliatePolicy:'after_tool',nextStepUrl:'https://www.alo186.com/hesaplama/duman-alarmi-yerlesim-bakim-uygunluk/',nextStepLabel:'Önce adet, yerleşim, ürün yaşı ve aylık test uygunluğunu değerlendir',description:'Kat, uyuma odası, ayrı uyuma alanı, pişirme uzaklığı, test düğmesi, ürün yaşı, bağlantı ve erişilebilirlik doğrulanmadan ürün rotası açılmaz.',searchQuery:'EN 14604 fotoelektrik duman dedektörü',graph:{needIds:['fire-early-warning'],relatedTools:['/hesaplama/duman-alarmi-yerlesim-bakim-uygunluk/','/hesaplama/duman-co-alarmi-bakim-gunlugu/'],relatedGuides:['/amazon-elektrik-urunleri/acil-aydinlatma-duman-alarmi'],requiredEvidence:['EN 14604 kapsamı','fotoelektrik sensör','test düğmesi','düşük pil uyarısı','üretim ve değiştirme tarihi'],blockedWhen:['aktif duman veya yangın','ilk başarısız test doğrulanmadan değişim','yerleşim belirsiz']}},
    {id:'co_alarm',name:'Karbonmonoksit alarmı',mode:'guide',risk:'safety',affiliatePolicy:'after_tool',nextStepUrl:'https://www.alo186.com/hesaplama/karbonmonoksit-alarmi-jenerator-guvenligi/',nextStepLabel:'Önce kaynak, jeneratör konumu, alarm yerleşimi ve test uygunluğunu değerlendir',description:'CO alarmı taşınabilir jeneratörü kapalı veya binaya yakın alanda güvenli yapmaz. Kaynak, kat ve uyuma alanı kapsamı, pil yedeği, test, üretici ömrü ve EN 50291 belgesi doğrulanmadan ürün rotası açılmaz.',searchQuery:'EN 50291 karbonmonoksit alarmı pil yedekli',graph:{needIds:['carbon-monoxide-warning'],relatedTools:['/hesaplama/karbonmonoksit-alarmi-jenerator-guvenligi/','/hesaplama/duman-co-alarmi-bakim-gunlugu/'],relatedGuides:['/amazon-elektrik-urunleri/acil-aydinlatma-duman-alarmi'],requiredEvidence:['EN 50291 kapsamı','sensör ömrü','test düğmesi','yerleşim'],blockedWhen:['CO belirtisi','jeneratör kapalı alanda','ürün ömrü belirsiz']}},
    {id:'power_station',name:'Taşınabilir güç istasyonu',mode:'guide',risk:'compatibility',affiliatePolicy:'after_tool',nextStepUrl:'https://www.alo186.com/hesaplama/power-station-kapasite-eps-uygunluk/',nextStepLabel:'Önce kapasite, güç ve EPS uyumunu test et',description:'Wh kapasitesi, sürekli/tepe güç, saf sinüs, EPS geçişi, bypass, batarya ve şarj girişleri yük hesabıyla birlikte seçilmelidir.',searchQuery:'LiFePO4 taşınabilir güç istasyonu power station',graph:{needIds:['portable-backup-energy'],relatedTools:['/hesaplama/power-station-kapasite-eps-uygunluk/','/hesaplama/power-station-gunes-paneli-uygunluk/','/hesaplama/yedek-guc-runtime-saglik-gunlugu/'],relatedGuides:['/amazon-elektrik-urunleri/tasinabilir-guc-istasyonu-secimi','/haberler/power-station-gunes-paneli-nasil-secilir'],requiredEvidence:['kullanılabilir Wh','sürekli W','tepe W','saf sinüs','PV giriş sınırı'],blockedWhen:['yük hesabı yok','kalkış gücü belirsiz','batarya hasarı']}},
    {id:'generator',name:'Taşınabilir jeneratör',mode:'guide',risk:'safety',affiliatePolicy:'after_tool',nextStepUrl:'https://www.alo186.com/hesaplama/jenerator-gucu-secimi/',nextStepLabel:'Önce sürekli ve kalkış gücünü hesapla',description:'Sürekli ve kalkış W, faz, bağlantı biçimi, CO güvenliği, gürültü, yakıt ve servis koşulları güç hesabıyla birlikte doğrulanmalıdır.',searchQuery:'inverter jeneratör CO sensörü sürekli kalkış watt',graph:{needIds:['portable-generation'],relatedTools:['/hesaplama/jenerator-gucu-secimi/','/hesaplama/jenerator-ats-test-gunlugu/'],relatedGuides:['/haberler/jenerator-ups-birlikte-calisir-mi','/haberler/jenerator-wet-stacking-dusuk-yuk-load-bank-testi'],requiredEvidence:['sürekli güç','kalkış gücü','faz','CO güvenliği','bağlantı biçimi'],blockedWhen:['bina tesisatına uygunsuz bağlantı','kapalı alan kullanımı','ATS ve nötr topolojisi belirsiz']}},
    {id:'inverter',name:'Saf sinüs inverter ve batarya sistemi',mode:'guide',risk:'compatibility',affiliatePolicy:'after_tool',nextStepUrl:'https://www.alo186.com/hesaplama/inverter-uygunluk/',nextStepLabel:'Önce inverter ve batarya hesabını yap',description:'Sürekli/tepe W, saf sinüs, 12/24/48 V DC gerilim, batarya akımı, BMS ve koruma doğrulanmadan ürün seçilmemelidir.',searchQuery:'saf sinüs inverter 12V 24V sürekli tepe watt',graph:{needIds:['dc-ac-conversion'],relatedTools:['/hesaplama/inverter-uygunluk/'],relatedGuides:['/haberler/saf-sinus-modifiye-sinus-inverter-farki','/haberler/batarya-c-rate-dod-kullanilabilir-kapasite'],requiredEvidence:['sürekli ve tepe W','DC gerilim','batarya akımı','BMS','koruma'],blockedWhen:['sabit tesisat projesi yok','batarya kısa devre koruması belirsiz','yük türü bilinmiyor']}},
    {id:'outlet_tester',name:'Priz ve RCD test cihazı',mode:'guide',risk:'measurement',affiliatePolicy:'professional_only',nextStepUrl:'https://www.alo186.com/karar-motoru/',nextStepLabel:'Önce güvenli yönlendirmeyi aç',description:'Gösterge yalnız temel bağlantı hatalarını ön kontrol eder; izolasyon, topraklama direnci ve koruma açma testi yerine geçmez.',searchQuery:'priz test cihazı RCD tester',graph:{needIds:['basic-outlet-screening'],relatedTools:['/karar-motoru/'],relatedGuides:['/haberler/prizde-topraklama-var-mi-priz-test-cihazi','/haberler/topraklama-direnci-ariza-cevrim-empedansi-farki'],requiredEvidence:['gerilim bölgesi','gösterge kapsamı','RCD test akımı','ölçüm sınırı'],blockedWhen:['topraklama uygunluğu kanıtı olarak kullanma','enerjili pano müdahalesi','izolasyon testi yerine kullanma']}},
    {id:'smart_plug',name:'Akıllı priz ve enerji ölçer',mode:'guide',risk:'compatibility',affiliatePolicy:'after_tool',nextStepUrl:'https://www.alo186.com/hesaplama/akilli-priz-enerji-olcer-uygunluk/',nextStepLabel:'Önce akım, güç ve ölçüm ihtiyacını test et',description:'Cihazın gerçek akımı, motor kalkışı, ölçüm çözünürlüğü, kayıt süresi ve gözetimsiz anahtarlama riski doğrulanmadan ürün seçilmemelidir.',searchQuery:'enerji ölçerli akıllı priz 16A watt kWh geçmiş kayıt',graph:{needIds:['device-energy-measurement'],relatedTools:['/hesaplama/akilli-priz-enerji-olcer-uygunluk/','/hesaplama/7-gunluk-cihaz-tuketim-deneyi/'],relatedGuides:['/amazon-elektrik-urunleri/akilli-priz-enerji-olcer-secimi'],requiredEvidence:['nominal akım','yük türü','kWh geçmişi','yerel/bulut davranışı'],blockedWhen:['sabit bağlı yük','yüksek kalkış akımı doğrulanmamış','aşırı ısınma veya erime']}},
    {id:'ev_cable',name:'Type 2 elektrikli araç şarj kablosu',mode:'guide',risk:'compatibility',affiliatePolicy:'after_tool',nextStepUrl:'https://www.alo186.com/hesaplama/ev-sarj-kablosu-uygunluk/',nextStepLabel:'Önce araç, istasyon, faz ve akım uyumunu test et',description:'Araç soketi, istasyon tipi, monofaze/trifaze yapı, 16/32 A sınıfı, kablo uzunluğu ve fiziksel güvenlik birlikte doğrulanmalıdır.',searchQuery:'Type 2 EV şarj kablosu 32A trifaze 22 kW',graph:{needIds:['ev-ac-cable'],relatedTools:['/hesaplama/ev-sarj-kablosu-uygunluk/','/hesaplama/ev-sarj-kablosu-saglik-gunlugu/'],relatedGuides:['/haberler/tip-2-ev-sarj-kablosu-nasil-secilir','/haberler/ev-sarj-kablosu-soketi-isiniyor-termal-derating'],requiredEvidence:['Type 2 uçlar','faz ve akım','kablo uzunluğu','üretici uygunluğu'],blockedWhen:['yanık veya pitting','sabit wallbox kablosu','su/kir olayı','araç veya EVSE kök nedeni belirsiz']}},
    {id:'ups_battery',name:'UPS yedek aküsü ve kartuşu',mode:'guide',risk:'compatibility',affiliatePolicy:'after_tool',nextStepUrl:'https://www.alo186.com/hesaplama/ups-aku-degisim-uygunluk/',nextStepLabel:'Önce değişim gereğini ve tam kartuş uyumunu kontrol et',description:'UPS tam modeli, üreticinin kartuş kodu, seri/paralel adet, gerilim, kapasite, terminal ve batarya kimyası doğrulanmadan akü alınmamalıdır.',searchQuery:'UPS yedek akü kartuş 12V 7Ah 9Ah RBC uyumlu',graph:{needIds:['ups-runtime-restoration'],relatedTools:['/hesaplama/ups-aku-degisim-uygunluk/','/hesaplama/yedek-guc-runtime-saglik-gunlugu/'],relatedGuides:['/haberler/ups-akusu-ne-zaman-degisir','/haberler/ups-aku-ic-direnc-impedans-kapasite-testi-farki'],requiredEvidence:['UPS tam modeli','kartuş kodu','gerilim ve Ah','adet ve seri/paralel düzen'],blockedWhen:['şişme/sızıntı/koku','eski-yeni akü karıştırma','kritik yükte yalnız self-test']}},
    {id:'extension_cord',name:'Uzatma kablosu ve kablo makarası',mode:'guide',risk:'safety',affiliatePolicy:'after_tool',nextStepUrl:'https://www.alo186.com/hesaplama/uzatma-kablosu-kablo-makarasi-uygunluk/',nextStepLabel:'Önce yük, uzunluk, kesit, etiket ve makara güvenliğini test et',description:'Yük, uzunluk, kesit, etiket akımı, topraklama, sarılı/açılmış makara sınırı ve ortam uygunluğu doğrulanmadan ürün rotası açılmaz.',searchQuery:'topraklı uzatma kablosu kablo makarası 16A termik koruma',graph:{needIds:['temporary-power-extension'],relatedTools:['/hesaplama/uzatma-kablosu-kablo-makarasi-uygunluk/'],relatedGuides:['/haberler/ev-sarj-kablosu-kesiti-gerilim-dusumu-isinma'],requiredEvidence:['kesit','uzunluk','etiket akımı','topraklama','sarılı/açılmış sınır'],blockedWhen:['sarılı makara yüksek yük','dış ortam uyumu yok','motor/ısıtıcı yükü belirsiz','yanık veya hasar']}}
  ];

  const products=[
    {id:'anker-prime-a1336',category:'powerbank',asin:'B0BYNZXFM2',name:'Anker Prime A1336 20.000 mAh 200 W',brand:'Anker',model:'A1336',status:'verified_listing',verifiedAt,linkMode:'asin_detail',attributes:{capacityMah:20000,energyWh:72,maxOutputW:200,wireless:false,usbCPorts:2,usbAPorts:1,display:true},strengths:['Yüksek USB-C çıkışı','Dijital ekran','20.000 mAh / 72 Wh'],limits:['Yüksek fiyat ve 544 g ağırlık','Samsung SFC 2.0 desteği ürün sayfasında sınırlı belirtilmiş'],sourceNote:'ASIN ve teknik ürün sayfası alanları kontrol edildi; fiyat ve stok ALO186 tarafından gösterilmez.',technicalSource:null,graph:{useCaseIds:['mobile-continuity'],relatedTools:['/hesaplama/powerbank-usb-c-uygunluk/'],relatedGuides:['/amazon-elektrik-urunleri/powerbank-usb-c-secimi'],incompatibleWith:['kablosuz şarj zorunluluğu'],requiredEvidence:['USB-C PD profili','kablo e-marker','cihazın kabul ettiği W']},url:amazonProductUrl('B0BYNZXFM2')},
    {id:'xiaomi-wireless-10000',category:'powerbank',asin:'B09TWRHGWV',name:'Xiaomi 10 W Wireless Power Bank 10.000',brand:'Xiaomi',model:'Wireless Power Bank 10000',status:'verified_listing',verifiedAt,linkMode:'asin_detail',attributes:{capacityMah:10000,energyWh:null,maxOutputW:10,wireless:true,usbCPorts:1,usbAPorts:null,display:false},strengths:['Kablosuz şarj','10.000 mAh','Düşük akım modu'],limits:['Yüksek güçlü dizüstü ihtiyacı için uygun kabul edilmemeli','Kablolu maksimum çıkış üründe yeniden doğrulanmalı'],sourceNote:'ASIN, 10.000 mAh ve 10 W kablosuz özellikleri ürün sayfasından kontrol edildi.',technicalSource:null,graph:{useCaseIds:['mobile-continuity'],relatedTools:['/hesaplama/powerbank-usb-c-uygunluk/'],relatedGuides:['/amazon-elektrik-urunleri/powerbank-usb-c-secimi'],incompatibleWith:['yüksek güçlü USB-C dizüstü'],requiredEvidence:['kablolu maksimum W','kablosuz cihaz uyumu','kablo protokolü']},url:amazonProductUrl('B09TWRHGWV')},
    {id:'samsung-eb-u2510x',category:'powerbank',asin:'B0CVGVG7NW',name:'Samsung EB-U2510X 10.000 mAh Kablosuz Powerbank',brand:'Samsung',model:'EB-U2510X',status:'verified_listing',verifiedAt,linkMode:'asin_detail',attributes:{capacityMah:10000,energyWh:null,maxOutputW:null,wireless:true,usbCPorts:null,usbAPorts:null,display:false},strengths:['Kablosuz kullanım','10.000 mAh','Kompakt sınıf'],limits:['Çıkış gücü ve port sayısı Amazon ürün sayfasında satın alma öncesi yeniden doğrulanmalı'],sourceNote:'ASIN, model ve kapasite ürün sayfasından kontrol edildi; eksik teknik alanlar bilinmiyor olarak tutuldu.',technicalSource:null,graph:{useCaseIds:['mobile-continuity'],relatedTools:['/hesaplama/powerbank-usb-c-uygunluk/'],relatedGuides:['/amazon-elektrik-urunleri/powerbank-usb-c-secimi'],incompatibleWith:['çıkış gücü doğrulanmadan yüksek güçlü cihaz'],requiredEvidence:['maksimum çıkış W','port sayısı','kablosuz protokol uyumu']},url:amazonProductUrl('B0CVGVG7NW')},
    {id:'tuncmatik-tsk6136',category:'surge_strip',asin:'B07CST4766',name:'Tunçmatik TSK6136 PowerSurge 5 Priz 1050 J',brand:'Tunçmatik',model:'TSK6136',status:'verified_listing',verifiedAt,linkMode:'asin_detail',attributes:{outlets:5,joules:1050,maxCurrentA:10,maxPowerW:null,usbPorts:0,cableM:1.5},strengths:['1050 joule','5 çocuk emniyetli priz','1,5 m kablo'],limits:['10 A nominal akım','Pano tipi SPD ve uygun topraklamanın yerine geçmez'],sourceNote:'ASIN, 1050 J, 8000 A tepe, 10 A nominal ve 5 priz bilgileri ürün sayfasından kontrol edildi.',technicalSource:null,graph:{useCaseIds:['plug-in-surge-protection'],relatedTools:['/hesaplama/akim-korumali-grup-priz-uygunluk/'],relatedGuides:['/amazon-elektrik-urunleri/akim-korumali-grup-priz-secimi'],incompatibleWith:['10 A üzeri sürekli toplam yük','pano tipi SPD ikamesi'],requiredEvidence:['işlevsel topraklama','toplam sürekli akım','koruma göstergesi']},url:amazonProductUrl('B07CST4766')},
    {id:'viko-multilet-6',category:'surge_strip',asin:'B08L9KVRP1',name:'Viko Multilet Şok Korumalı 6’lı Grup Priz',brand:'Viko',model:'Multilet 6',status:'verified_listing',verifiedAt,linkMode:'asin_detail',attributes:{outlets:6,joules:282,maxCurrentA:16,maxPowerW:3500,usbPorts:0,cableM:1.5},strengths:['6 priz','16 A / 3500 W etiket bilgisi','Çocuk koruma'],limits:['282 joule seviyesi','Pano tipi koruma yerine kullanılamaz'],sourceNote:'ASIN, 6 priz, 16 A, 3500 W, 282 J ve 1,7 kV koruma seviyesi ürün açıklamasından kontrol edildi.',technicalSource:null,graph:{useCaseIds:['plug-in-surge-protection'],relatedTools:['/hesaplama/akim-korumali-grup-priz-uygunluk/'],relatedGuides:['/amazon-elektrik-urunleri/akim-korumali-grup-priz-secimi'],incompatibleWith:['yüksek joule minimumu','pano tipi SPD ikamesi'],requiredEvidence:['toplam yük','topraklama','koruma göstergesi']},url:amazonProductUrl('B08L9KVRP1')},
    {id:'tuncmatik-tsk5015',category:'surge_strip',asin:'B08KW6X13Y',name:'Tunçmatik PowerSurge 5 Priz + USB TSK5015',brand:'Tunçmatik',model:'TSK5015',status:'verified_listing',verifiedAt,linkMode:'asin_detail',attributes:{outlets:5,joules:null,maxCurrentA:null,maxPowerW:null,usbPorts:2,cableM:null},strengths:['5 priz','USB çıkışları','Elektronik cihaz kullanım senaryosu'],limits:['Joule ve nominal akım satın alma öncesi ürün etiketinden doğrulanmalı'],sourceNote:'ASIN, model, 5 priz ve USB özellikleri ürün sayfasından kontrol edildi; bilinmeyen alanlar puanda cezalandırılır.',technicalSource:null,graph:{useCaseIds:['plug-in-surge-protection'],relatedTools:['/hesaplama/akim-korumali-grup-priz-uygunluk/'],relatedGuides:['/amazon-elektrik-urunleri/akim-korumali-grup-priz-secimi'],incompatibleWith:['joule minimumu doğrulanmadan seçim'],requiredEvidence:['joule','nominal akım','USB çıkış protokolü']},url:amazonProductUrl('B08KW6X13Y')},
    {id:'cata-ct9186',category:'surge_strip',asin:'B09YTYTZ4J',name:'Cata CT-9186 Tekli Akım Korumalı Priz 918 J',brand:'Cata',model:'CT-9186',status:'verified_listing',verifiedAt,linkMode:'asin_detail',attributes:{outlets:1,joules:918,maxCurrentA:null,maxPowerW:4000,usbPorts:0,cableM:0},strengths:['918 joule','Tek cihaz için kompakt kullanım','LED gösterge'],limits:['Tek priz','4000 W ifadesi ürün sayfasında tekrar doğrulanmalı','Pano tipi koruma yerine geçmez'],sourceNote:'ASIN, 918 J ve 4000 W ürün başlığı/açıklamasından kontrol edildi.',technicalSource:null,graph:{useCaseIds:['plug-in-surge-protection'],relatedTools:['/hesaplama/akim-korumali-grup-priz-uygunluk/'],relatedGuides:['/amazon-elektrik-urunleri/akim-korumali-grup-priz-secimi'],incompatibleWith:['çoklu priz ihtiyacı','pano tipi SPD ikamesi'],requiredEvidence:['nominal akım','gerçek etiket W','topraklama']},url:amazonProductUrl('B09YTYTZ4J')},
    {id:'tp-link-tapo-p110',category:'smart_plug',asin:null,name:'TP-Link Tapo P110 Enerji İzlemeli Akıllı Priz',brand:'TP-Link',model:'Tapo P110',status:'manufacturer_verified_search',verifiedAt:'2026-07-29',linkMode:'exact_model_search',attributes:{maxCurrentA:16,maxPowerW:3680,energyMonitoring:true,wifiGHz:2.4,matter:false,localSchedules:true,powerMemory:true,operatingTempMaxC:35},strengths:['Gerçek zamanlı enerji izleme','Yerel planların internet olmadan devam etmesi','16 A / 3680 W üretici etiketi'],limits:['Motor ve yüksek kalkış akımlı yükler tam üretici sınırı olmadan uygun kabul edilmemeli','Gözetimsiz yüksek güçlü ısıtıcı kullanımında ürün talimatı ve risk ayrı doğrulanmalı','Amazon bağlantısı tam model aramasıdır; liste modeli yeniden eşleştirilmelidir'],sourceNote:'TP-Link Türkiye teknik sayfasında enerji izleme, 2,4 GHz, 220–240 V, 16 A / 3680 W ve 0–35 °C bilgileri doğrulandı. Amazon’da tam model araması açılır; fiyat ve stok kopyalanmaz.',technicalSource:'https://www.tp-link.com/tr/home-networking/smart-plug/tapo-p110/',graph:{useCaseIds:['device-energy-measurement'],relatedTools:['/hesaplama/akilli-priz-enerji-olcer-uygunluk/','/hesaplama/7-gunluk-cihaz-tuketim-deneyi/'],relatedGuides:['/amazon-elektrik-urunleri/akilli-priz-enerji-olcer-secimi'],incompatibleWith:['sabit bağlı yük','doğrulanmamış motor/kompresör','priz ve fiş sınırını aşan yük'],requiredEvidence:['gerçek yük akımı','yük türü','uygulama/bulut tercihi','Amazon listesindeki tam model']},url:amazonSearchUrl('TP-Link Tapo P110 enerji izlemeli akıllı priz')},
    {id:'tp-link-tapo-p110m',category:'smart_plug',asin:null,name:'TP-Link Tapo P110M Matter Enerji İzlemeli Akıllı Priz',brand:'TP-Link',model:'Tapo P110M',status:'manufacturer_verified_search',verifiedAt:'2026-07-29',linkMode:'exact_model_search',attributes:{maxCurrentA:16,maxPowerW:3680,energyMonitoring:true,wifiGHz:2.4,matter:true,motorHp:1,localSchedules:true,operatingTempMaxC:40},strengths:['Matter sertifikalı ekosistem desteği','Enerji izleme ve güç eşiği işlevleri','16 A / 3680 W genel/rezistif ve 1 HP motor üretici etiketi'],limits:['Matter işlevi üçüncü taraf platform/hub gerektirebilir','Yük sınıfı ve kalkış akımı gerçek cihazla doğrulanmalı','Amazon bağlantısı tam model aramasıdır; P110 ve P110M karıştırılmamalıdır'],sourceNote:'TP-Link Türkiye teknik sayfasında Matter, 2,4 GHz, 16 A / 3680 W genel/rezistif yük, 1 HP motor ve 0–40 °C bilgileri doğrulandı. Amazon’da tam model araması açılır.',technicalSource:'https://www.tp-link.com/tr/home-networking/smart-plug/tapo-p110m/',graph:{useCaseIds:['device-energy-measurement'],relatedTools:['/hesaplama/akilli-priz-enerji-olcer-uygunluk/','/hesaplama/7-gunluk-cihaz-tuketim-deneyi/'],relatedGuides:['/amazon-elektrik-urunleri/akilli-priz-enerji-olcer-secimi'],incompatibleWith:['sabit bağlı yük','1 HP üzeri veya bilinmeyen motor','yüksek güçlü gözetimsiz kullanım'],requiredEvidence:['gerçek yük akımı','Matter platform/hub uyumu','yük türü','Amazon listesindeki tam P110M modeli']},url:amazonSearchUrl('TP-Link Tapo P110M Matter enerji izlemeli akıllı priz')},
    {id:'ecoflow-river-2',category:'power_station',asin:null,name:'EcoFlow RIVER 2 Taşınabilir Güç İstasyonu',brand:'EcoFlow',model:'RIVER 2',status:'manufacturer_verified_search',verifiedAt:'2026-07-29',linkMode:'exact_model_search',attributes:{capacityWh:256,continuousW:300,surgeW:600,pureSine:true,chemistry:'LFP',solarVoltageMinV:11,solarVoltageMaxV:30,solarCurrentMaxA:8,solarPowerMaxW:110,usbCMaxW:60,epsTransferMs:30,weightKg:3.5},strengths:['256 Wh ve 300 W saf sinüs üretici verisi','11–30 V / 8 A / 110 W solar giriş','LFP kimyası ve 3000 döngü sonrası %80+ kapasite üretici beyanı'],limits:['600 W X-Boost/tepe ifadesi 300 W sürekli çıkışın yerine kullanılmamalı','30 ms altı EPS her kritik cihaz için kesintisiz çalışma garantisi değildir','Amazon bağlantısı tam model aramasıdır; RIVER 2, Max ve Pro varyantları karıştırılmamalıdır'],sourceNote:'EcoFlow Türkiye teknik sayfasında 256 Wh, 300 W saf sinüs, 600 W dalgalanma, 11–30 V/8 A/110 W solar giriş, 60 W USB-C, LFP ve yaklaşık 3,5 kg bilgileri doğrulandı.',technicalSource:'https://ecoflow.com.tr/urun/ecoflow-river-2-tasinabilir-guc-kaynagi/',graph:{useCaseIds:['portable-backup-energy'],relatedTools:['/hesaplama/power-station-kapasite-eps-uygunluk/','/hesaplama/power-station-gunes-paneli-uygunluk/','/hesaplama/yedek-guc-runtime-saglik-gunlugu/'],relatedGuides:['/amazon-elektrik-urunleri/tasinabilir-guc-istasyonu-secimi','/haberler/power-station-gunes-paneli-nasil-secilir'],incompatibleWith:['300 W üzeri sürekli yük','30 ms geçişe dayanamayan kritik yük','PV Voc/akımı sınır dışı panel'],requiredEvidence:['yükün sürekli ve tepe W değeri','hedef runtime','EPS toleransı','solar Voc/Isc ve konektör']},url:amazonSearchUrl('EcoFlow RIVER 2 256Wh 300W taşınabilir güç istasyonu')},
    {id:'x-sense-xs01',category:'smoke_alarm',asin:null,name:'X-Sense XS01 Fotoelektrik Duman Alarmı',brand:'X-Sense',model:'XS01',status:'manufacturer_verified_search',verifiedAt:'2026-07-29',linkMode:'exact_model_search',attributes:{sensor:'photoelectric',alarmDb:85,batteryType:'CR123A',batteryLifeYearsClaim:10,standard:'EN 14604',interconnected:null},strengths:['Fotoelektrik algılama','≥85 dB yerel alarm','EN 14604 ve CE belge kapsamı üretici/distribütör sayfasında belirtilmiş'],limits:['10 yıl pil ifadesi üretici beyanıdır; üretim ve değiştirme tarihi ürün üzerinde doğrulanmalı','Yerleşim ve adet ücretsiz araçla belirlenmeli','Amazon bağlantısı tam model aramasıdır; XS01, XS01-M, XS01-WR ve XS01-WX karıştırılmamalıdır'],sourceNote:'X-Sense Türkiye ürün sayfasında fotoelektrik algılama, ≥85 dB alarm, CR123A pil için 10 yıl beyanı ve EN 14604/CE belge kapsamı doğrulandı. Stok ve garanti bilgisi ALO186’e taşınmadı.',technicalSource:'https://x-sense.com.tr/urunler/duman-dedektorleri/xs01-duman-alarmi',graph:{useCaseIds:['fire-early-warning'],relatedTools:['/hesaplama/duman-alarmi-yerlesim-bakim-uygunluk/','/hesaplama/duman-co-alarmi-bakim-gunlugu/'],relatedGuides:['/amazon-elektrik-urunleri/acil-aydinlatma-duman-alarmi'],incompatibleWith:['CO alarmı ikamesi','yerleşim hesabı yapılmadan tek cihaz','aktif yangın/duman olayı'],requiredEvidence:['tam XS01 model kodu','EN 14604 belge kapsamı','üretim/değiştirme tarihi','yerleşim ve aylık test planı']},url:amazonSearchUrl('X-Sense XS01 fotoelektrik duman alarmı EN 14604')}
  ];

  function dateOnly(value){const date=value instanceof Date?value:new Date(value);return Number.isNaN(date.getTime())?null:new Date(Date.UTC(date.getUTCFullYear(),date.getUTCMonth(),date.getUTCDate()));}
  function verificationStatus(item,now=new Date()){const checked=dateOnly(item&&item.verifiedAt);const today=dateOnly(now);if(!checked||!today)return {fresh:false,ageDays:null,verifiedAt:item&&item.verifiedAt||null,maxAgeDays:verificationMaxAgeDays};const ageDays=Math.max(0,Math.floor((today.getTime()-checked.getTime())/86400000));return {fresh:ageDays<=verificationMaxAgeDays,ageDays,verifiedAt:item.verifiedAt,maxAgeDays:verificationMaxAgeDays};}
  function getCategory(id){return categories.find(category=>category.id===id)||null;}
  function getProduct(id){return products.find(product=>product.id===id)||null;}
  function isCatalogProduct(product){return Boolean(product&&catalogStatuses.has(product.status));}
  function productsFor(category,options={}){const now=options.now||new Date();const freshOnly=Boolean(options.freshOnly);return products.filter(product=>product.category===category&&isCatalogProduct(product)&&(!freshOnly||verificationStatus(product,now).fresh));}
  function searchUrl(category){const current=getCategory(category);return current?amazonSearchUrl(current.searchQuery):'https://www.amazon.com.tr';}
  function productLinkLabel(product){return product&&product.linkMode==='asin_detail'?'Amazon ürün sayfasını aç':'Amazon’da tam model araması';}
  function graphForCategory(categoryId){const category=getCategory(categoryId);if(!category)return null;return {category,needs:needs.filter(need=>(category.graph.needIds||[]).includes(need.id)),products:productsFor(categoryId,{freshOnly:false})};}
  function knowledgeGraphSummary(){return {version:'2026-07-29-run34',generatedAt:'2026-07-29',needCount:needs.length,categoryCount:categories.length,productCount:products.filter(isCatalogProduct).length,exactListingCount:products.filter(product=>product.status==='verified_listing').length,manufacturerSearchCount:products.filter(product=>product.status==='manufacturer_verified_search').length,affiliatePolicies:[...new Set(categories.map(category=>category.affiliatePolicy))]};}

  return {affiliateTag,verifiedAt,verificationMaxAgeDays,catalogStatuses:[...catalogStatuses],needs,categories,products,getCategory,getProduct,isCatalogProduct,productsFor,verificationStatus,amazonProductUrl,amazonSearchUrl,searchUrl,productLinkLabel,graphForCategory,knowledgeGraphSummary};
});
