(function(root,factory){
  const api=factory();
  if(typeof module==='object'&&module.exports){module.exports=api;}
  root.Alo186ProductCatalog=api;
  if(root&&root.document&&root.document.head&&typeof root.document.createElement==='function'&&typeof api.knowledgeGraph==='function'){
    const id='alo186-affiliate-knowledge-graph';
    const current=typeof root.document.getElementById==='function'?root.document.getElementById(id):null;
    if(current&&typeof current.remove==='function')current.remove();
    const script=root.document.createElement('script');
    script.id=id;
    script.type='application/ld+json';
    if(script.dataset)script.dataset.generated='alo186-affiliate-knowledge-graph';
    script.textContent=JSON.stringify(api.knowledgeGraph());
    root.document.head.appendChild(script);
  }
})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const affiliateTag='alo186rehber-21';
  const verifiedAt='2026-07-29';
  const verificationMaxAgeDays=45;
  const siteOrigin='https://www.alo186.com';

  function amazonProductUrl(asin){const base=`https://www.amazon.com.tr/dp/${encodeURIComponent(asin)}`;return affiliateTag?`${base}?tag=${encodeURIComponent(affiliateTag)}`:base;}
  function amazonSearchUrl(query){const base=`https://www.amazon.com.tr/s?k=${encodeURIComponent(query)}`;return affiliateTag?`${base}&tag=${encodeURIComponent(affiliateTag)}`:base;}

  const categories=[
    {id:'powerbank',name:'Telefon ve mobil cihaz için powerbank',mode:'direct',risk:'consumer',affiliatePolicy:'verified_direct',description:'Kapasite, USB-C çıkış gücü ve kablosuz şarj ihtiyacına göre ürün sayfası teknik verilerini karşılaştırır.',searchQuery:'USB C PD powerbank 20000 mAh dijital ekran'},
    {id:'usb_c_cable',name:'USB-C hızlı şarj kablosu',mode:'direct',risk:'consumer',affiliatePolicy:'verified_direct',description:'Kablo uzunluğu, beyan edilen güç, konnektör tipi ve cihaz uyumu birlikte değerlendirilir; kablo tek başına hızlı şarjı garanti etmez.',searchQuery:'USB C to USB C 100W şarj kablosu'},
    {id:'surge_strip',name:'Akım korumalı grup priz',mode:'guide',risk:'consumer',affiliatePolicy:'after_tool',nextStepUrl:'https://www.alo186.com/hesaplama/akim-korumali-grup-priz-uygunluk/',nextStepLabel:'Önce yük, priz, joule ve topraklama uygunluğunu test et',description:'Toplam sürekli/tepe yük, etiket amperi ve wattı, joule, priz sayısı, koruma göstergesi, bağlantı ve işlevsel topraklama doğrulanmadan ürün kartı açılmaz. Pano tipi SPD ve tesisat korumasının yerine geçmez.',searchQuery:'akım korumalı grup priz joule'},
    {id:'mini_ups',name:'Modem ve fiber ONT için mini UPS',mode:'guide',risk:'compatibility',affiliatePolicy:'after_tool',nextStepUrl:'https://www.alo186.com/hesaplama/modem-internet-yedekleme/',nextStepLabel:'Önce modem ve ONT hesabını yap',description:'Voltaj, polarite, jak ölçüsü, toplam watt ve geçiş davranışı doğrulanmadan ürün seçilmemelidir.',searchQuery:'modem mini UPS 12V 9V 5V'},
    {id:'emergency_light',name:'Şarjlı acil aydınlatma',mode:'guide',risk:'consumer',affiliatePolicy:'after_tool',nextStepUrl:'https://www.alo186.com/hesaplama/acil-aydinlatma-sure-uygunluk/',nextStepLabel:'Önce lümen, adet ve çalışma süresini test et',description:'Alan, aynı moddaki lümen ve çalışma süresi, otomatik yanma, fiziksel düğme, pil göstergesi ve kullanım ortamı doğrulanmadan ürün seçilmemelidir.',searchQuery:'şarjlı acil durum lambası kamp lambası'},
    {id:'smoke_alarm',name:'Fotoelektrik duman alarmı',mode:'guide',risk:'safety',affiliatePolicy:'after_tool',nextStepUrl:'https://www.alo186.com/hesaplama/duman-alarmi-yerlesim-bakim-uygunluk/',nextStepLabel:'Önce adet, yerleşim, ürün yaşı ve aylık test uygunluğunu değerlendir',description:'Kat, uyuma odası, ayrı uyuma alanı, pişirme uzaklığı, test düğmesi, ürün yaşı, bağlantı ve erişilebilirlik doğrulanmadan ürün rotası açılmaz.',searchQuery:'EN 14604 fotoelektrik duman dedektörü'},
    {id:'co_alarm',name:'Karbonmonoksit alarmı',mode:'guide',risk:'safety',affiliatePolicy:'after_tool',nextStepUrl:'https://www.alo186.com/hesaplama/karbonmonoksit-alarmi-jenerator-guvenligi/',nextStepLabel:'Önce kaynak, jeneratör konumu, alarm yerleşimi ve test uygunluğunu değerlendir',description:'CO alarmı taşınabilir jeneratörü kapalı veya binaya yakın alanda güvenli yapmaz. Kaynak, kat ve uyuma alanı kapsamı, pil yedeği, test, üretici ömrü ve EN 50291 belgesi doğrulanmadan ürün rotası açılmaz.',searchQuery:'EN 50291 karbonmonoksit alarmı pil yedekli'},
    {id:'power_station',name:'Taşınabilir güç istasyonu',mode:'guide',risk:'compatibility',affiliatePolicy:'after_tool',nextStepUrl:'https://www.alo186.com/hesaplama/power-station-kapasite-eps-uygunluk/',nextStepLabel:'Önce kapasite, güç ve EPS uyumunu test et',description:'Wh kapasitesi, sürekli/tepe güç, saf sinüs, EPS geçişi, bypass, batarya ve şarj girişleri yük hesabıyla birlikte seçilmelidir.',searchQuery:'LiFePO4 taşınabilir güç istasyonu power station'},
    {id:'generator',name:'Taşınabilir jeneratör',mode:'guide',risk:'safety',affiliatePolicy:'after_tool',nextStepUrl:'https://www.alo186.com/hesaplama/jenerator-gucu-secimi/',nextStepLabel:'Önce sürekli ve kalkış gücünü hesapla',description:'Sürekli ve kalkış W, faz, bağlantı biçimi, CO güvenliği, gürültü, yakıt ve servis koşulları güç hesabıyla birlikte doğrulanmalıdır.',searchQuery:'inverter jeneratör CO sensörü sürekli kalkış watt'},
    {id:'inverter',name:'Saf sinüs inverter ve batarya sistemi',mode:'guide',risk:'compatibility',affiliatePolicy:'after_tool',nextStepUrl:'https://www.alo186.com/hesaplama/inverter-uygunluk/',nextStepLabel:'Önce inverter ve batarya hesabını yap',description:'Sürekli/tepe W, saf sinüs, 12/24/48 V DC gerilim, batarya akımı, BMS ve koruma doğrulanmadan ürün seçilmemelidir.',searchQuery:'saf sinüs inverter 12V 24V sürekli tepe watt'},
    {id:'outlet_tester',name:'Priz ve RCD test cihazı',mode:'guide',risk:'measurement',affiliatePolicy:'professional_only',nextStepUrl:'https://www.alo186.com/karar-motoru/',nextStepLabel:'Önce güvenli yönlendirmeyi aç',description:'Gösterge yalnız temel bağlantı hatalarını ön kontrol eder; izolasyon, topraklama direnci ve koruma açma testi yerine geçmez.',searchQuery:'priz test cihazı RCD tester'},
    {id:'smart_plug',name:'Akıllı priz ve enerji ölçer',mode:'guide',risk:'compatibility',affiliatePolicy:'after_tool',nextStepUrl:'https://www.alo186.com/hesaplama/akilli-priz-enerji-olcer-uygunluk/',nextStepLabel:'Önce akım, güç ve ölçüm ihtiyacını test et',description:'Cihazın gerçek akımı, motor kalkışı, ölçüm çözünürlüğü, kayıt süresi ve gözetimsiz anahtarlama riski doğrulanmadan ürün seçilmemelidir.',searchQuery:'enerji ölçerli akıllı priz 16A watt kWh geçmiş kayıt'},
    {id:'ev_cable',name:'Type 2 elektrikli araç şarj kablosu',mode:'guide',risk:'compatibility',affiliatePolicy:'after_tool',nextStepUrl:'https://www.alo186.com/hesaplama/ev-sarj-kablosu-uygunluk/',nextStepLabel:'Önce araç, istasyon, faz ve akım uyumunu test et',description:'Araç soketi, istasyon tipi, monofaze/trifaze yapı, 16/32 A sınıfı, kablo uzunluğu ve fiziksel güvenlik birlikte doğrulanmalıdır.',searchQuery:'Type 2 EV şarj kablosu 32A trifaze 22 kW'},
    {id:'ups_battery',name:'UPS yedek aküsü ve kartuşu',mode:'guide',risk:'compatibility',affiliatePolicy:'after_tool',nextStepUrl:'https://www.alo186.com/haberler/ups-akusu-ne-zaman-degisir',nextStepLabel:'Önce değişim gereğini ve tam kartuş uyumunu kontrol et',description:'UPS tam modeli, üreticinin kartuş kodu, seri/paralel adet, gerilim, kapasite, terminal ve batarya kimyası doğrulanmadan akü alınmamalıdır.',searchQuery:'UPS yedek akü kartuş 12V 7Ah 9Ah RBC uyumlu'},
    {id:'extension_cord',name:'Uzatma kablosu ve kablo makarası',mode:'guide',risk:'safety',affiliatePolicy:'after_tool',nextStepUrl:'https://www.alo186.com/hesaplama/uzatma-kablosu-kablo-makarasi-uygunluk/',nextStepLabel:'Önce yük, uzunluk, kesit, etiket ve makara güvenliğini test et',description:'Yük, uzunluk, kesit, etiket akımı, topraklama, sarılı/açılmış makara sınırı ve ortam uygunluğu doğrulanmadan ürün rotası açılmaz.',searchQuery:'topraklı uzatma kablosu kablo makarası 16A termik koruma'}
  ];

  const products=[
    {id:'anker-prime-a1336',category:'powerbank',asin:'B0BYNZXFM2',name:'Anker Prime A1336 20.000 mAh 200 W',brand:'Anker',status:'verified_listing',verifiedAt,attributes:{capacityMah:20000,energyWh:72,maxOutputW:200,wireless:false,usbCPorts:2,usbAPorts:1,display:true},strengths:['Yüksek USB-C çıkışı','Dijital ekran','20.000 mAh / 72 Wh'],limits:['544 g ağırlık','Samsung SFC 2.0 desteği ürün sayfasında sınırlı belirtilmiş'],sourceNote:'ASIN ve teknik ürün sayfası alanları kontrol edildi; fiyat ve stok ALO186 tarafından gösterilmez.',url:amazonProductUrl('B0BYNZXFM2')},
    {id:'xiaomi-wireless-10000',category:'powerbank',asin:'B09TWRHGWV',name:'Xiaomi 10 W Wireless Power Bank 10.000',brand:'Xiaomi',status:'verified_listing',verifiedAt,attributes:{capacityMah:10000,energyWh:null,maxOutputW:10,wireless:true,usbCPorts:1,usbAPorts:null,display:false},strengths:['Kablosuz şarj','10.000 mAh','Düşük akım modu'],limits:['Yüksek güçlü dizüstü ihtiyacı için uygun kabul edilmemeli','Kablolu maksimum çıkış üründe yeniden doğrulanmalı'],sourceNote:'ASIN, 10.000 mAh ve 10 W kablosuz özellikleri ürün sayfasından kontrol edildi.',url:amazonProductUrl('B09TWRHGWV')},
    {id:'samsung-eb-u2510x',category:'powerbank',asin:'B0CVGVG7NW',mpn:'EB-U2510X',name:'Samsung EB-U2510X 10.000 mAh Kablosuz Powerbank',brand:'Samsung',status:'verified_listing',verifiedAt,attributes:{capacityMah:10000,energyWh:null,maxOutputW:null,wireless:true,usbCPorts:2,usbAPorts:0,display:false},strengths:['Kablosuz kullanım','10.000 mAh','İki bağlantı noktası'],limits:['Maksimum çıkış gücü satın alma öncesi ürün sayfasında yeniden doğrulanmalı'],sourceNote:'ASIN, model, 10.000 mAh kapasite ve iki bağlantı noktası ürün sayfasından kontrol edildi; eksik güç alanı null tutuldu.',url:amazonProductUrl('B0CVGVG7NW')},
    {id:'baseus-crystal-shine-100w-2m',category:'usb_c_cable',asin:'B0B46PHW14',mpn:'CAJY000701',name:'Baseus Crystal Shine USB-C 100 W 2 m Şarj Kablosu',brand:'Baseus',status:'verified_listing',verifiedAt,attributes:{maxPowerW:100,cableM:2,connectorA:'USB-C',connectorB:'USB-C',dataMbps:480},strengths:['100 W beyanı','2 m uzunluk','USB-C–USB-C bağlantı'],limits:['Gerçek şarj gücü adaptör, cihaz ve protokolün ortak sınırıyla belirlenir','E-marker ve tam PD profili satın alma öncesi ürün sayfasında yeniden doğrulanmalı'],sourceNote:'ASIN, model, 100 W, 2 m ve USB-C bağlantı bilgileri ürün sayfasından doğrulandı; fiyat, stok ve puan yayımlanmaz.',url:amazonProductUrl('B0B46PHW14')},
    {id:'tuncmatik-tsk6136',category:'surge_strip',asin:'B07CST4766',name:'Tunçmatik TSK6136 PowerSurge 5 Priz 1050 J',brand:'Tunçmatik',status:'verified_listing',verifiedAt,attributes:{outlets:5,joules:1050,maxCurrentA:10,maxPowerW:null,usbPorts:0,cableM:1.5},strengths:['1050 joule','5 çocuk emniyetli priz','1,5 m kablo'],limits:['10 A nominal akım','Pano tipi SPD ve uygun topraklamanın yerine geçmez'],sourceNote:'ASIN, 1050 J, 8000 A tepe, 10 A nominal ve 5 priz bilgileri ürün sayfasından kontrol edildi.',url:amazonProductUrl('B07CST4766')},
    {id:'viko-multilet-6',category:'surge_strip',asin:'B08L9KVRP1',name:'Viko Multilet Şok Korumalı 6’lı Grup Priz',brand:'Viko',status:'verified_listing',verifiedAt,attributes:{outlets:6,joules:282,maxCurrentA:16,maxPowerW:3500,usbPorts:0,cableM:1.5},strengths:['6 priz','16 A / 3500 W etiket bilgisi','Çocuk koruma'],limits:['282 joule seviyesi','Pano tipi koruma yerine kullanılamaz'],sourceNote:'ASIN, 6 priz, 16 A, 3500 W, 282 J ve 1,7 kV koruma seviyesi ürün açıklamasından kontrol edildi.',url:amazonProductUrl('B08L9KVRP1')},
    {id:'tuncmatik-tsk5015',category:'surge_strip',asin:'B08KW6X13Y',name:'Tunçmatik PowerSurge 5 Priz + USB TSK5015',brand:'Tunçmatik',status:'verified_listing',verifiedAt,attributes:{outlets:5,joules:null,maxCurrentA:null,maxPowerW:null,usbPorts:2,cableM:null},strengths:['5 priz','USB çıkışları','Elektronik cihaz kullanım senaryosu'],limits:['Joule ve nominal akım satın alma öncesi ürün etiketinden doğrulanmalı'],sourceNote:'ASIN, model, 5 priz ve USB özellikleri ürün sayfasından kontrol edildi; bilinmeyen alanlar puanda cezalandırılır.',url:amazonProductUrl('B08KW6X13Y')},
    {id:'cata-ct9186',category:'surge_strip',asin:'B09YTYTZ4J',name:'Cata CT-9186 Tekli Akım Korumalı Priz 918 J',brand:'Cata',status:'verified_listing',verifiedAt,attributes:{outlets:1,joules:918,maxCurrentA:null,maxPowerW:4000,usbPorts:0,cableM:0},strengths:['918 joule','Tek cihaz için kompakt kullanım','LED gösterge'],limits:['Tek priz','4000 W ifadesi ürün sayfasında tekrar doğrulanmalı','Pano tipi koruma yerine geçmez'],sourceNote:'ASIN, 918 J ve 4000 W ürün başlığı/açıklamasından kontrol edildi.',url:amazonProductUrl('B09YTYTZ4J')},
    {id:'philips-spn7040wa-62',category:'surge_strip',asin:'B09Y5VH14K',mpn:'SPN7040WA/62',name:'Philips SPN7040WA/62 4’lü Akım Korumalı Grup Priz 600 J',brand:'Philips',status:'verified_listing',verifiedAt,attributes:{outlets:4,joules:600,maxCurrentA:16,maxPowerW:3680,usbPorts:0,cableM:2,doublePoleSwitch:true},strengths:['4 topraklı priz','600 joule','2 m kablo','16 A / 3680 W'],limits:['Pano tipi SPD ve uygun topraklamanın yerine geçmez','600 J sınıfı daha yüksek darbe enerjisi ihtiyacında ayrıca değerlendirilmelidir'],sourceNote:'ASIN, model, 4 priz, 600 J, 2 m, 16 A ve 3680 W alanları ürün sayfasından doğrulandı; fiyat ve stok gösterilmez.',url:amazonProductUrl('B09Y5VH14K')},
    {id:'tuncmatik-tsk6134',category:'surge_strip',asin:'B08L9LF2WC',mpn:'TSK6134',name:'Tunçmatik TSK6134 PowerSurge 5 Priz 1050 J',brand:'Tunçmatik',status:'verified_listing',verifiedAt,attributes:{outlets:5,joules:1050,maxCurrentA:null,maxPowerW:null,usbPorts:0,cableM:1.5},strengths:['5 priz','1050 joule','1,5 m kablo'],limits:['Nominal akım ve maksimum güç ürün etiketinden satın alma öncesi yeniden doğrulanmalı','Pano tipi SPD yerine geçmez'],sourceNote:'ASIN, model, 5 priz, 1050 J ve 1,5 m alanları ürün listelemesinden doğrulandı; bilinmeyen alanlar null tutuldu.',url:amazonProductUrl('B08L9LF2WC')},
    {id:'brennenstuhl-eco-line-6',category:'surge_strip',asin:'B07RWYSQKV',name:'Brennenstuhl Eco-Line 6’lı Akım Korumalı Grup Priz',brand:'Brennenstuhl',status:'verified_listing',verifiedAt,attributes:{outlets:6,joules:null,maxCurrentA:16,maxPowerW:3500,usbPorts:0,cableM:1.5,surgeCurrentA:13500},strengths:['6 priz','13.500 A azami darbe akımı','1,5 m kablo','16 A / 3500 W'],limits:['Joule değeri Amazon sayfasında yeniden doğrulanmalı','Darbe akımı değeri joule değeriyle aynı değildir'],sourceNote:'ASIN; üretici kaynağından 6 priz, 13.500 A, 1,5 m, 16 A ve 3500 W alanları doğrulandı; fiyat ve stok yayımlanmaz.',url:amazonProductUrl('B07RWYSQKV')}
  ];

  function dateOnly(value){const date=value instanceof Date?value:new Date(value);return Number.isNaN(date.getTime())?null:new Date(Date.UTC(date.getUTCFullYear(),date.getUTCMonth(),date.getUTCDate()));}
  function verificationStatus(item,now=new Date()){const checked=dateOnly(item&&item.verifiedAt);const today=dateOnly(now);if(!checked||!today)return {fresh:false,ageDays:null,verifiedAt:item&&item.verifiedAt||null,maxAgeDays:verificationMaxAgeDays};const ageDays=Math.max(0,Math.floor((today.getTime()-checked.getTime())/86400000));return {fresh:ageDays<=verificationMaxAgeDays,ageDays,verifiedAt:item.verifiedAt,maxAgeDays:verificationMaxAgeDays};}
  function getCategory(id){return categories.find(c=>c.id===id)||null;}
  function productsFor(category,options={}){const now=options.now||new Date();const freshOnly=Boolean(options.freshOnly);return products.filter(product=>product.category===category&&product.status==='verified_listing'&&(!freshOnly||verificationStatus(product,now).fresh));}
  function searchUrl(category){const c=getCategory(category);return c?amazonSearchUrl(c.searchQuery):'https://www.amazon.com.tr';}
  function publicAffiliateEligible(product,options={}){const category=getCategory(product&&product.category);const now=options.now||new Date();const freshOnly=options.freshOnly!==false;return Boolean(category&&category.mode==='direct'&&category.affiliatePolicy==='verified_direct'&&product&&product.status==='verified_listing'&&(!freshOnly||verificationStatus(product,now).fresh));}
  function slug(value){return String(value||'').toLocaleLowerCase('tr-TR').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');}
  function productId(product){return `${siteOrigin}/akilli-urun-secimi/urun/${encodeURIComponent(product.id)}#product`;}
  function productPageUrl(product){return `${siteOrigin}/akilli-urun-secimi?kategori=${encodeURIComponent(product.category)}&urun=${encodeURIComponent(product.id)}`;}
  function brandId(brand){return `${siteOrigin}/knowledge-graph/brand/${slug(brand)}#brand`;}
  function categoryId(category){return `${siteOrigin}/knowledge-graph/category/${encodeURIComponent(category)}#category`;}
  function additionalProperties(product,publicDirect){return [...Object.entries(product.attributes||{}).filter(([,value])=>value!==null&&value!==undefined).map(([name,value])=>({'@type':'PropertyValue',name,value})),{'@type':'PropertyValue',name:'Teknik doğrulama tarihi',value:product.verifiedAt},{'@type':'PropertyValue',name:'Ticari ilişki',value:publicDirect?'Doğrulanmış Amazon satış ortaklığı bağlantısı':'Teknik uygunluk kapısından sonra açılan Amazon satış ortaklığı yolu'}];}
  function productNode(product,options={}){
    const publicDirect=options.publicDirect===undefined?publicAffiliateEligible(product,{now:options.now||new Date()}):Boolean(options.publicDirect);
    const category=getCategory(product.category);
    const identifiers=[{'@type':'PropertyValue',propertyID:'ASIN',value:product.asin}];
    if(product.mpn)identifiers.push({'@type':'PropertyValue',propertyID:'MPN',value:product.mpn});
    return {'@type':'Product','@id':productId(product),name:product.name,url:productPageUrl(product),sku:product.id,identifier:identifiers,
      ...(product.mpn?{mpn:product.mpn}:{}),...(publicDirect?{sameAs:product.url}:{}),brand:{'@id':brandId(product.brand)},category:{'@id':categoryId(product.category)},
      description:product.sourceNote,dateModified:product.verifiedAt,additionalProperty:additionalProperties(product,publicDirect),
      ...(publicDirect?{}:{potentialAction:{'@type':'ViewAction',target:category&&category.nextStepUrl?category.nextStepUrl:productPageUrl(product),name:category&&category.nextStepLabel?category.nextStepLabel:'Önce teknik uygunluğu doğrula'}}),
      subjectOf:{'@id':`${productPageUrl(product)}#webpage`},mainEntityOfPage:{'@id':`${productPageUrl(product)}#webpage`}};
  }
  function catalogHealth(options={}){const now=options.now||new Date();const fresh=products.filter(product=>product.status==='verified_listing'&&verificationStatus(product,now).fresh);const publicProducts=fresh.filter(product=>publicAffiliateEligible(product,{now}));const checked=dateOnly(verifiedAt);const reviewBy=checked?new Date(checked.getTime()+30*86400000).toISOString().slice(0,10):null;const staleAfter=checked?new Date(checked.getTime()+(verificationMaxAgeDays+1)*86400000).toISOString().slice(0,10):null;return {verifiedAt,verificationMaxAgeDays,totalVerified:fresh.length,publicDirect:publicProducts.length,gatedVerified:fresh.length-publicProducts.length,reviewBy,staleAfter};}
  function knowledgeGraph(options={}){
    const now=options.now||new Date();
    const verifiedProducts=products.filter(product=>product.status==='verified_listing'&&verificationStatus(product,now).fresh);
    const publicProducts=verifiedProducts.filter(product=>publicAffiliateEligible(product,{now}));
    const gatedProducts=verifiedProducts.filter(product=>!publicAffiliateEligible(product,{now,freshOnly:false}));
    const uniqueBrands=[...new Set(verifiedProducts.map(product=>product.brand))].sort((a,b)=>a.localeCompare(b,'tr'));
    const brands=uniqueBrands.map(name=>({'@type':'Brand','@id':brandId(name),name}));
    const categoryNodes=categories.map(category=>({'@type':'DefinedTerm','@id':categoryId(category.id),termCode:category.id,name:category.name,description:category.description,inDefinedTermSet:{'@id':`${siteOrigin}/knowledge-graph/electrical-product-categories#termset`}}));
    const allList={'@type':'ItemList','@id':`${siteOrigin}/akilli-urun-secimi#verified-products`,name:'ALO186 doğrulanmış affiliate ürün bilgi grafiği',numberOfItems:verifiedProducts.length,itemListElement:verifiedProducts.map((product,index)=>({'@type':'ListItem',position:index+1,item:{'@id':productId(product)}}))};
    const directList={'@type':'ItemList','@id':`${siteOrigin}/akilli-urun-secimi#direct-affiliate-products`,name:'ALO186 doğrudan affiliate uygun ürünleri',numberOfItems:publicProducts.length,itemListElement:publicProducts.map((product,index)=>({'@type':'ListItem',position:index+1,item:{'@id':productId(product)}}))};
    const gatedList={'@type':'ItemList','@id':`${siteOrigin}/akilli-urun-secimi#tool-gated-products`,name:'ALO186 teknik uygunluk kapılı affiliate ürünleri',numberOfItems:gatedProducts.length,itemListElement:gatedProducts.map((product,index)=>({'@type':'ListItem',position:index+1,item:{'@id':productId(product)}}))};
    const graph=[
      {'@type':'Organization','@id':`${siteOrigin}/#organization`,name:'ALO186',url:`${siteOrigin}/`,description:'Bağımsız elektrik bilgi ve ürün uygunluk platformu.'},
      {'@type':'WebSite','@id':`${siteOrigin}/#website`,url:`${siteOrigin}/`,name:'ALO186',publisher:{'@id':`${siteOrigin}/#organization`}},
      {'@type':'DefinedTermSet','@id':`${siteOrigin}/knowledge-graph/electrical-product-categories#termset`,name:'ALO186 elektrik ürün kategorileri',hasDefinedTerm:categoryNodes.map(node=>({'@id':node['@id']}))},
      allList,directList,gatedList,...categoryNodes,...brands,...verifiedProducts.map(product=>productNode(product,{now,publicDirect:publicAffiliateEligible(product,{now})}))
    ];
    return {'@context':'https://schema.org','@graph':graph};
  }

  return {affiliateTag,verifiedAt,verificationMaxAgeDays,categories,products,getCategory,productsFor,verificationStatus,amazonProductUrl,amazonSearchUrl,searchUrl,publicAffiliateEligible,productId,productNode,catalogHealth,knowledgeGraph};
});
