(() => {
  'use strict';
  const core=window.Alo186ConversionGrowthCore;
  const catalog=window.Alo186ProductCatalog;
  if(!core||!catalog)return;
  const $=id=>document.getElementById(id);
  let activeCategory=null;

  function escapeHtml(value){return String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));}
  function escapeAttr(value){return escapeHtml(value).replace(/`/g,'&#96;');}
  function selectedCategory(){const active=document.querySelector('[data-category][aria-pressed="true"]');return active?active.dataset.category:null;}
  function emit(name,params={}){if(core.hasForbiddenEventData(params))return;const clean=core.sanitizeEvent(params);if(typeof window.Alo186Track==='function')window.Alo186Track(name,clean);else{window.dataLayer=window.dataLayer||[];window.dataLayer.push({event:name,...clean});}}
  function ensureEvidenceRuntime(){if(window.Alo186EvidenceWallet||document.querySelector('script[data-product-evidence-wallet]'))return;const script=document.createElement('script');script.src='../hesaplama/evidence-wallet.js';script.dataset.productEvidenceWallet='true';script.addEventListener('load',()=>{if(activeCategory)applyEvidence(activeCategory);},{once:true});document.head.appendChild(script);}
  function ensurePanels(){
    if(!$('qualifiedSearch')){
      const results=$('results');
      if(!results)return false;
      results.insertAdjacentHTML('afterend',`<section id="qualifiedSearch" class="content-section qualified-search hidden" aria-live="polite"><div class="panel"><span class="eyebrow">Şeffaf satış ortaklığı araması</span><h2 id="qualifiedSearchTitle">Teknik arama oluşturucu</h2><p id="qualifiedSearchIntro">Önce teknik uygunluğu doğrulayın.</p><div id="qualifiedEvidenceStatus" class="qualified-search-status"></div><div id="qualifiedSearchFields" class="qualified-search-fields"></div><div class="qualified-checks"><label class="check-item"><input type="checkbox" id="qualifiedToolConfirmed"><span><b id="qualifiedToolLabel">Teknik kontrolü tamamladım.</b><br><small id="qualifiedToolHelp">Bu onay bir ürün sertifikası değildir.</small></span></label><label class="check-item"><input type="checkbox" id="qualifiedExistingInsufficient"><span><b>Mevcut ekipmanım ihtiyacı karşılamıyor.</b><br><small>Mevcut ürün yeterliyse yeni ürün araması açılmaz.</small></span></label><label class="check-item"><input type="checkbox" id="qualifiedAffiliateAccepted"><span><b>Bağlantının satış ortaklığı bağlantısı olduğunu anladım.</b><br><small>Nitelikli satın alımdan komisyon kazanılabilir; kullanıcıya ek maliyet yansımaz.</small></span></label></div><p id="qualifiedSearchQuery" class="qualified-search-query"></p><div class="qualified-disclosure"><strong>Reklam / satış ortaklığı:</strong> Bu araç ürün önermeden, yalnız seçtiğiniz teknik ifadelerle Amazon araması oluşturur. Fiyat, stok, satıcı, teslimat, puan, garanti ve nihai teknik özellik Amazon’un güncel sayfasında yeniden doğrulanır.</div><div class="actions"><a id="qualifiedAffiliateLink" class="btn btn-primary disabled-link" aria-disabled="true" tabindex="-1" target="_blank" rel="sponsored nofollow noopener">Amazon’da teknik aramayı aç</a><button id="qualifiedNoPurchaseBtn" class="btn btn-secondary" type="button">Şimdilik satın alma</button></div><p id="qualifiedSearchStatus" class="qualified-search-status" role="status">Güvenli arama için bütün adımları tamamlayın.</p></div></section><section id="professionalConversion" class="content-section professional-conversion hidden" aria-live="polite"><div class="panel"><span class="paid-label">Ücretli profesyonel hizmet</span><h2 id="professionalConversionTitle">Profesyonel teknik kapsam</h2><p id="professionalConversionText"></p><p><strong>Bağımsızlık:</strong> ALO186 resmî kurum, EDAŞ veya ürün satıcısı değildir. Hazırlık skoru ücretsizdir; teknik inceleme ancak kapsam ve ücret yazılı teyit edildikten sonra başlar.</p><div class="actions"><a id="professionalConversionLink" class="btn btn-primary" href="/kurumsal-elektrik-surekliligi-on-degerlendirme">Kişisel verisiz hazırlık skorunu aç</a><a class="btn btn-secondary" href="/hesaplama/">Ücretsiz araçlara dön</a></div></div></section>`);
    }
    return Boolean($('qualifiedSearch')&&$('professionalConversion'));
  }
  function selections(){const values={};$('qualifiedSearchFields').querySelectorAll('[data-qualified-field]').forEach(field=>values[field.dataset.qualifiedField]=field.value);return values;}
  function confirmations(){return{toolConfirmed:$('qualifiedToolConfirmed').checked,checklistConfirmed:$('qualifiedToolConfirmed').checked,existingInsufficient:$('qualifiedExistingInsufficient').checked,affiliateAccepted:$('qualifiedAffiliateAccepted').checked};}
  function categoryIntro(category){const c=catalog.getCategory(category);if(!c)return'';if(c.affiliatePolicy==='after_tool')return'Ücretsiz teknik aracı tamamladıktan sonra yalnız doğruladığınız minimumlarla arama oluşturun.';if(c.affiliatePolicy==='after_checklist')return'Güvenlik ve ürün etiketi kontrolünü tamamladıktan sonra yalnız kapalı teknik seçeneklerle arama oluşturun.';return'Teknik minimumları belirledikten sonra doğrulanmış kart bulunamazsa daha dar bir arama oluşturun.';}
  function confirmationLabel(category){const c=catalog.getCategory(category);if(!c)return'Teknik kontrolü tamamladım.';if(c.affiliatePolicy==='after_tool')return'Ücretsiz hesaplayıcı veya uygunluk testini tamamladım.';if(c.affiliatePolicy==='after_checklist')return'Güvenlik ve ürün etiketi kontrol listesini tamamladım.';return'Bu sayfadaki teknik minimumları belirledim.';}
  function renderFields(category){const profile=core.getProfile(category);if(!profile)return;$('qualifiedSearchTitle').textContent=profile.label;$('qualifiedSearchIntro').textContent=categoryIntro(category);$('qualifiedToolLabel').textContent=confirmationLabel(category);$('qualifiedSearchFields').innerHTML=profile.fields.map(field=>`<label class="qualified-field"><span>${escapeHtml(field.label)}</span><select data-qualified-field="${escapeAttr(field.id)}">${field.options.map(option=>`<option value="${escapeAttr(option[0])}">${escapeHtml(option[1])}</option>`).join('')}</select></label>`).join('');$('qualifiedSearchFields').querySelectorAll('select').forEach(field=>field.addEventListener('change',updateGate));}
  function resetChecks(){$('qualifiedToolConfirmed').disabled=false;$('qualifiedToolConfirmed').checked=false;$('qualifiedExistingInsufficient').checked=false;$('qualifiedAffiliateAccepted').checked=false;$('qualifiedToolHelp').textContent='Bu onay bir ürün sertifikası değildir.';$('qualifiedEvidenceStatus').textContent='';}
  function formatDate(value){const date=new Date(value);return Number.isFinite(date.getTime())?new Intl.DateTimeFormat('tr-TR',{dateStyle:'medium'}).format(date):'tarih bilinmiyor';}
  function applyEvidence(category){const wallet=window.Alo186EvidenceWallet;if(!wallet||!wallet.CATEGORIES.has(category))return;const evidence=wallet.status(category),box=$('qualifiedToolConfirmed'),status=$('qualifiedEvidenceStatus');if(evidence.state==='current'||evidence.state==='expiring'){box.checked=true;box.disabled=true;$('qualifiedToolLabel').textContent='Ücretsiz teknik araç tamamlandı.';$('qualifiedToolHelp').textContent=`Yerel doğrulama: ${formatDate(evidence.record.completedAt)} · ${Math.max(0,evidence.daysLeft)} gün geçerli.`;status.textContent=evidence.state==='expiring'?'Teknik doğrulamanın süresi yakında doluyor. Bu karşılaştırmadan sonra yeniden kontrol tarihi oluşturun.':'Teknik doğrulama kaydı güncel; ham hesap veya kişisel veri saklanmadı.';emit('qualified_affiliate_search_rendered',{category,status:`evidence_${evidence.state}`,affiliate_policy:catalog.getCategory(category).affiliatePolicy,search_profile:category});}else if(evidence.state==='expired'){box.checked=false;box.disabled=false;status.innerHTML=`Teknik doğrulama süresi doldu. <a href="${escapeAttr(evidence.toolRoute)}">Ücretsiz aracı yeniden açın</a> veya manuel olarak güncel kontrolü doğrulayın.`;}else{status.innerHTML=`Bu kategori için güncel teknik kanıt bulunmuyor. <a href="${escapeAttr(evidence.toolRoute)}">Ücretsiz aracı açın</a>. Yalnız kategori, araç yolu ve tarih tarayıcıda saklanır.`;}updateGate();}
  function updateGate(){if(!activeCategory)return;const gate=core.gateStatus(activeCategory,confirmations());const link=$('qualifiedAffiliateLink');const query=core.buildQuery(activeCategory,selections());$('qualifiedSearchQuery').textContent=query?`Oluşturulan teknik arama: ${query}`:'';if(gate.allowed){link.href=core.buildAffiliateUrl(activeCategory,selections());link.classList.remove('disabled-link');link.setAttribute('aria-disabled','false');link.tabIndex=0;$('qualifiedSearchStatus').textContent='Teknik arama hazır. Amazon sayfasında ürün etiketini, satıcıyı, stok durumunu ve nihai özellikleri yeniden doğrulayın.';}else{link.removeAttribute('href');link.classList.add('disabled-link');link.setAttribute('aria-disabled','true');link.tabIndex=-1;const messages={tool_not_confirmed:'Önce ücretsiz teknik aracı veya kontrol listesini tamamlayın.',checklist_not_confirmed:'Önce güvenlik ve etiket kontrolünü tamamlayın.',existing_may_be_sufficient:'Mevcut ürünün ihtiyacı karşılamadığını doğrulamadan yeni ürün araması açılmaz.',affiliate_not_accepted:'Satış ortaklığı açıklamasını kabul etmeden haricî bağlantı açılmaz.',no_safe_profile:'Bu kategoride güvenli genel ürün araması oluşturulamıyor.',professional_only:'Bu kategoride ürün araması yerine profesyonel değerlendirme gerekir.'};$('qualifiedSearchStatus').textContent=messages[gate.reason]||'Güvenli arama için bütün adımları tamamlayın.';}}
  function showQualifiedSearch(category){const profile=core.getProfile(category);const section=$('qualifiedSearch');if(!profile){section.classList.add('hidden');return;}const c=catalog.getCategory(category);const hasVerifiedCards=Boolean(document.querySelector('#directResult .product-card'));if(c&&c.mode==='direct'&&hasVerifiedCards){section.classList.add('hidden');return;}activeCategory=category;renderFields(category);resetChecks();section.classList.remove('hidden');applyEvidence(category);updateGate();emit('qualified_affiliate_search_rendered',{category,status:'shown',affiliate_policy:c.affiliatePolicy,search_profile:category});}
  function hideQualifiedSearch(){activeCategory=null;$('qualifiedSearch').classList.add('hidden');}
  function showProfessionalRoute(category){const route=core.professionalRoute(category);if(!route)return;const link=$('professionalConversionLink');link.href=route;$('professionalConversionTitle').textContent=`${catalog.getCategory(category).name} için profesyonel kapsam`;$('professionalConversionText').textContent='Sabit bağlantı, ölçüm, yüksek güç veya batarya seti riski nedeniyle ürün araması yerine kişisel veri istemeyen ücretli teknik ön değerlendirme rotası açılır.';$('professionalConversion').classList.remove('hidden');emit('professional_conversion_rendered',{category,status:'shown',professional_route:'corporate_readiness'});}
  function hideProfessionalRoute(){$('professionalConversion').classList.add('hidden');}
  function renderForCurrentResult(){const category=selectedCategory();if(!category)return;hideQualifiedSearch();hideProfessionalRoute();if(core.isProfessional(category)||catalog.getCategory(category).affiliatePolicy==='professional_only')showProfessionalRoute(category);else showQualifiedSearch(category);}
  function noPurchase(){if(!activeCategory)return;$('qualifiedSearchStatus').textContent='Satın almama seçildi. Mevcut ekipmanı kullanmaya devam edin veya yeniden kontrol tarihi oluşturun.';emit('qualified_affiliate_no_purchase',{category:activeCategory,status:'selected',placement:'qualified_search'});}
  function init(){
    if(window.Alo186ConversionGrowthInitialized)return;
    if(!ensurePanels()||!$('matchBtn'))return;
    window.Alo186ConversionGrowthInitialized=true;
    ensureEvidenceRuntime();
    $('matchBtn').addEventListener('click',()=>setTimeout(renderForCurrentResult,0));
    document.addEventListener('click',event=>{const categoryButton=event.target.closest('[data-category],[data-intent-category]');if(categoryButton){hideQualifiedSearch();hideProfessionalRoute();}});
    ['qualifiedToolConfirmed','qualifiedExistingInsufficient','qualifiedAffiliateAccepted'].forEach(id=>$(id).addEventListener('change',updateGate));
    $('qualifiedAffiliateLink').addEventListener('click',event=>{if($('qualifiedAffiliateLink').getAttribute('aria-disabled')==='true'){event.preventDefault();return;}emit('qualified_affiliate_search_opened',{category:activeCategory,status:'opened',placement:'qualified_search',affiliate_policy:catalog.getCategory(activeCategory).affiliatePolicy,search_profile:activeCategory});});
    $('qualifiedNoPurchaseBtn').addEventListener('click',noPurchase);
    $('professionalConversionLink').addEventListener('click',()=>{const category=selectedCategory();emit('professional_conversion_opened',{category,status:'opened',professional_route:'corporate_readiness'});});
    window.addEventListener('alo186:evidence-updated',()=>{if(activeCategory)applyEvidence(activeCategory);});
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
