'use strict';
const assert=require('node:assert/strict');
const core=require('./outcome-trust-circuit-core.js');
const now=new Date('2026-07-28T18:00:00Z');
const record=(patch={})=>({createdAt:'2026-07-27T12:00:00Z',category:'backup_power',outcome:'resolved',recurrence:'none',purchase:'not_applicable',action:'free_tool',...patch});
let result=core.evaluate('power_station',[record({outcome:'safety'})],now);
assert.equal(result.status,'safety_block');assert.equal(result.blocked,true);assert.equal(result.route,'/karar-motoru');
result=core.evaluate('generator',[record({outcome:'unresolved',recurrence:'multiple'})],now);
assert.equal(result.status,'repeated_block');assert.match(result.route,/kurumsal-elektrik-surekliligi-on-degerlendirme/);
result=core.evaluate('power_station',[record({outcome:'partial'})],now);
assert.equal(result.status,'recheck_block');assert.equal(result.route,'/hesaplama/power-station-kapasite-eps-uygunluk/');
result=core.evaluate('powerbank',[record({category:'product_selection',outcome:'resolved',purchase:'existing',action:'existing_equipment'})],now);
assert.equal(result.status,'no_buy_hold');assert.equal(result.blocked,true);
result=core.evaluate('powerbank',[record({category:'product_selection',outcome:'resolved',purchase:'new_product',action:'product'})],now);
assert.equal(result.status,'duplicate_hold');assert.equal(result.route,'/hesaplama/ekipman-bakim-plani/');
result=core.evaluate('ev_cable',[record({createdAt:'2026-01-01T00:00:00Z',category:'ev_charging',outcome:'unresolved'})],now);
assert.equal(result.status,'allow');assert.equal(result.blocked,false);
result=core.evaluate('smart_plug',[record({category:'backup_power',outcome:'unresolved'})],now);
assert.equal(result.status,'allow','Başka problem kategorisinin sonucu ilgisiz ürünü engellememeli.');
assert.doesNotMatch(JSON.stringify(result),/email|phone|address|asin|price|stock|seller|warranty/i);
assert.match(core.professionalRoute('ups_battery'),/source=outcome_circuit/);
console.log('Outcome trust circuit: safety, repeat, unresolved, no-buy, duplicate and allow decisions successful.');
