(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.ALO186StandbyExperiment=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const ROUTE='/hesaplama/priz-tipi-enerji-olcer-standby-deneyi/';
const n=v=>Number.isFinite(Number(v))?Number(v):0;
function calculate(input){const activeW=n(input.activeW),standbyW=n(input.standbyW),activeHours=Math.min(24,Math.max(0,n(input.activeHours))),offHours=Math.min(24,Math.max(0,n(input.offHours))),standbyHours=Math.max(0,24-activeHours);const activeDay=activeW*activeHours/1000;const standbyDay=standbyW*standbyHours/1000;const totalDay=activeDay+standbyDay;const avoidableDay=standbyW*Math.min(offHours,standbyHours)/1000;return{activeW,standbyW,activeHours,standbyHours,offHours,activeKwhDay:activeDay,standbyKwhDay:standbyDay,totalKwhDay:totalDay,standbyKwhMonth:standbyDay*30,standbyKwhYear:standbyDay*365,avoidableKwhMonth:avoidableDay*30};}
function decide(input){const m=calculate(input);if(input.emergency)return{code:'emergency',title:'Deneyi durdurun',text:'Duman, erime, su teması, elektrik çarpması veya aşırı ısınmada cihazı ve ölçeri kullanmayın. Güvenli alandan 112 veya yetkili elektrikçi rotasına geçin.',commerce:false};if(input.excludedLoad)return{code:'excluded',title:'Bu yük tüketici tipi priz ölçümü kapsamı dışında',text:'Isıtıcı, beyaz eşya, motor, pompa, EV, tıbbi cihaz ve sabit tesisat için üretici talimatı ve yetkili ölçüm gerekir. Ürün bağlantısı gösterilmez.',commerce:false};if(!input.safePlug)return{code:'unsafe',title:'Priz, fiş ve ölçer sınırını doğrulayın',text:'Fiziksel durum ve üretici akım/güç sınırı doğrulanmadan ölçüm yapmayın. Daha yüksek etiketli bir ölçer sabit tesisat kapasitesini artırmaz.',commerce:false};if(input.existingMeter)return{code:'no_buy',title:'Mevcut ölçeri kullanın — yenisini almayın',text:'Güvenli ve çalışır mevcut ölçerle 7 günlük aktif/standby deneyi yapın. Yalnız yeni model veya uygulama özelliği için değiştirmeyin.',commerce:false,noBuy:true};if(!m.activeW&&!m.standbyW){const confirmed=input.confirmNeed&&input.confirmSafe&&input.confirmAffiliate;return confirmed?{code:'qualified_meter',title:'Ölçüm aracı ihtiyacı doğrulandı',text:input.networkNeeded?'Uzaktan kontrol gerçekten gerekiyorsa enerji izlemeli akıllı priz; yalnız W/kWh ölçümü gerekiyorsa daha sade priz tipi enerji ölçer sınıfını değerlendirin.':'Yalnız W/kWh ölçümü için ağ bağlantısız sade priz tipi enerji ölçer yeterli olabilir.',commerce:true}:{code:'measure_first',title:'Önce ölçüm ihtiyacını ve güvenli yükü doğrulayın',text:'Üç onay tamamlanmadan ürün merkezi açılmaz. Mevcut araç, düşük güçlü fişli yük ve üretici sınırı yeniden kontrol edilmelidir.',commerce:false};}
if(m.standbyW>100||m.activeW>1000)return{code:'range',title:'Girilen değer tüketici deneyi sınırını aşıyor',text:'Yük sınıfını ve ölçüm kaynağını yeniden kontrol edin. Yüksek güçlü veya motorlu cihazı bu akışta değerlendirmeyin.',commerce:false};if(m.offHours>m.standbyHours)return{code:'hours',title:'Kapatılabilir süre aktif saatlerle çakışıyor',text:'Günde güvenle kapatılabilecek süre, standby süresinden uzun olamaz.',commerce:false};if(m.standbyW===0)return{code:'zero',title:'Standby değeri sıfır girildi',text:'Bu değer gerçek ölçümse standby tüketimi görünmüyor. Yalnız daha yeni ölçer veya cihaz için satın alma gerekmez; farklı çalışma modlarını ayrı ölçün.',commerce:false,noBuy:true};return{code:'measured',title:'Standby tüketimi ölçüldü; cihazı hemen değiştirmeyin',text:'Aylık ve yıllık kWh değerini kullanım gereksinimiyle karşılaştırın. Güvenle kapatılabilen süre varsa önce davranış ve ayar değişikliğini test edin; ürün değişimini yalnız standby değerine dayandırmayın.',commerce:false};}
function report(input){return{generatedAt:new Date().toISOString(),route:ROUTE,input:{device:input.device||'other',days:n(input.days)||7,safePlug:!!input.safePlug,excludedLoad:!!input.excludedLoad,existingMeter:!!input.existingMeter,networkNeeded:!!input.networkNeeded},metrics:calculate(input),decision:decide(input)};}
function calendar(days){const start=new Date(Date.now()+86400000);const end=new Date(start.getTime()+30*60000);const stamp=d=>d.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z');return['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//ALO186//Standby Deneyi//TR','BEGIN:VEVENT',`DTSTAMP:${stamp(new Date())}`,`DTSTART:${stamp(start)}`,`DTEND:${stamp(end)}`,'SUMMARY:ALO186 7 günlük standby tüketim deneyini başlat','DESCRIPTION:Priz, fiş ve ölçer sınırını doğrulayın; düşük güçlü fişli elektroniğin aktif ve standby W/kWh değerlerini 7 gün ölçün. Fiyat veya kampanya takibi değildir.','END:VEVENT','END:VCALENDAR'].join('\r\n');}
function download(name,type,content){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove();},0);}
function init(){if(typeof document==='undefined')return;const $=id=>document.getElementById(id);const form=$('meterForm'),result=$('result'),affiliate=$('affiliate');let last=null;const read=()=>({device:$('device').value,days:$('days').value,safePlug:$('safePlug').checked,excludedLoad:$('excludedLoad').checked,existingMeter:$('existingMeter').checked,networkNeeded:$('networkNeeded').checked,activeW:$('activeW').value,standbyW:$('standbyW').value,activeHours:$('activeHours').value,offHours:$('offHours').value,confirmNeed:$('confirmNeed').checked,confirmSafe:$('confirmSafe').checked,confirmAffiliate:$('confirmAffiliate').checked,emergency:$('emergency').checked});
form.addEventListener('submit',e=>{e.preventDefault();const input=read(),m=calculate(input),d=decide(input);last=report(input);result.className=`result status ${['emergency','excluded','unsafe','range'].includes(d.code)?'danger':d.noBuy||d.code==='measured'?'ok':'warn'}`;result.innerHTML=`<h2>${d.title}</h2><p>${d.text}</p><div class="metrics"><div class="metric"><span>Aktif</span><strong>${m.activeKwhDay.toFixed(3)} kWh/gün</strong></div><div class="metric"><span>Standby</span><strong>${m.standbyKwhMonth.toFixed(2)} kWh/ay</strong></div><div class="metric"><span>Standby yıllık</span><strong>${m.standbyKwhYear.toFixed(1)} kWh</strong></div><div class="metric"><span>Güvenli kapatma senaryosu</span><strong>${m.avoidableKwhMonth.toFixed(2)} kWh/ay</strong></div></div>`;affiliate.classList.toggle('hidden',!d.commerce);result.scrollIntoView({behavior:'smooth',block:'start'});});
$('exportJson').addEventListener('click',()=>download('alo186-standby-tuketim-deneyi.json','application/json',JSON.stringify(last||report(read()),null,2)));$('calendar').addEventListener('click',()=>download('alo186-7-gun-standby-deneyi.ics','text/calendar;charset=utf-8',calendar(Number($('days').value)||7)));}
if(typeof window!=='undefined')window.addEventListener('DOMContentLoaded',init);
return{ROUTE,calculate,decide,report,calendar};});