(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.ALO186OutageLog=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const ROUTE='/hesaplama/elektrik-kesintisi-sure-siklik-gunlugu/';
const STORAGE_KEY='alo186_outage_evidence_v128';
const MAX_RECORDS=24;
const TTL_DAYS=540;
const now=()=>Date.now();
const n=v=>Number.isFinite(Number(v))?Number(v):0;
const iso=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?'':d.toISOString();};
function durationMinutes(start,end){const a=new Date(start).getTime(),b=new Date(end).getTime();return Number.isFinite(a)&&Number.isFinite(b)&&b>a?Math.round((b-a)/60000):0;}
function cleanRecord(raw){const duration=durationMinutes(raw.start,raw.end);return{createdAt:n(raw.createdAt)||now(),start:iso(raw.start),end:iso(raw.end),duration,scope:['home','building','street','unknown'].includes(raw.scope)?raw.scope:'unknown',officialRecord:raw.officialRecord==='yes',active:raw.active===true,restoration:raw.restoration||'normal',impacts:Array.isArray(raw.impacts)?raw.impacts.filter(v=>['internet','cold','water','security','work','medical'].includes(v)):[],criticalGap:raw.criticalGap===true};}
function validStored(record){return record&&n(record.createdAt)>now()-TTL_DAYS*86400000&&n(record.duration)>0;}
function summarize(records){const clean=records.map(cleanRecord).filter(validStored).sort((a,b)=>new Date(a.start)-new Date(b.start));const cutoff30=now()-30*86400000,cutoff90=now()-90*86400000;const recent30=clean.filter(r=>new Date(r.start).getTime()>=cutoff30);const recent90=clean.filter(r=>new Date(r.start).getTime()>=cutoff90);const total=recent90.reduce((s,r)=>s+r.duration,0);const longest=recent90.reduce((m,r)=>Math.max(m,r.duration),0);const avg=recent90.length?Math.round(total/recent90.length):0;const repeatedCritical=recent90.filter(r=>r.criticalGap&&r.impacts.some(x=>x!=='work')).length;const medical=recent90.some(r=>r.impacts.includes('medical'));return{records:clean,recent30:recent30.length,recent90:recent90.length,total90:total,longest90:longest,average90:avg,repeatedCritical,medical};}
function decide(input,records){const record=cleanRecord(input);const summary=summarize([...records,record]);if(input.emergency)return{code:'emergency',commerce:false,title:'Önce güvenli alana geçin',text:'Yangın, elektrik çarpması, kopmuş hat, duman veya kıvılcım varsa kayıt tutmak için yaklaşmayın. Güvenli alandan 112’yi arayın.'};if(record.active)return{code:'active_outage',commerce:false,title:'Aktif kesintide ürün teslimatı çözüm değildir',text:'Yetkili EDAŞ kanalını açın veya 186’yı arayın. Kritik yükler için yalnız önceden test edilmiş mevcut planı kullanın.'};if(!record.duration)return{code:'invalid',commerce:false,title:'Başlangıç ve bitişi kontrol edin',text:'Bitiş zamanı başlangıçtan sonra olmalıdır.'};if(record.impacts.includes('medical')||summary.medical)return{code:'medical',commerce:false,title:'Yaşam desteği için tüketici ürünü rotası kapalı',text:'Sağlık hizmeti sağlayıcısı, cihaz üreticisi ve profesyonel kesinti planı önceliklidir. Yeni ürün bağlantısı gösterilmez.'};if(summary.recent90<2)return{code:'single_event',commerce:false,title:'Tek olay satın alma gerekçesi değildir',text:'Kaydı dışa aktarın; aynı koşul tekrarlanırsa süre, kapsam ve kritik etkiyi karşılaştırın.'};if(summary.repeatedCritical<2)return{code:'evidence_more',commerce:false,title:'Kesinti tekrarlanıyor; önce kritik açığı doğrulayın',text:'Toplam süre tek başına ürün seçmez. Hangi kritik yükün gerçekten çalışmadığını en az iki olayda kaydedin.'};return{code:'qualified_gap',commerce:true,title:'Tekrarlanan kritik süreklilik açığı doğrulandı',text:'Doğrudan mağaza yerine ilgili teknik hesaplayıcıya ilerleyin. Mevcut güvenli çözüm yeterliyse yeni ürün almayın.',productClass:record.impacts.includes('internet')&&!record.impacts.includes('cold')?'internet_backup':record.impacts.includes('cold')?'cold_chain_backup':'critical_load_backup'};}
function load(){try{const raw=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');return Array.isArray(raw)?raw.map(cleanRecord).filter(validStored).slice(-MAX_RECORDS):[];}catch(_){return[];}}
function save(records){const clean=records.map(cleanRecord).filter(validStored).slice(-MAX_RECORDS);localStorage.setItem(STORAGE_KEY,JSON.stringify(clean));return clean;}
function csv(records){const head='start,end,duration_minutes,scope,official_record,restoration,impacts,critical_gap';const rows=records.map(r=>[r.start,r.end,r.duration,r.scope,r.officialRecord?'yes':'no',r.restoration,r.impacts.join('|'),r.criticalGap?'yes':'no'].map(v=>`"${String(v).replaceAll('"','""')}"`).join(','));return[head,...rows].join('\n');}
function calendar(days){const start=new Date(now()+days*86400000);const end=new Date(start.getTime()+30*60000);const stamp=d=>d.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z');return['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//ALO186//Kesinti Kanıt Kontrolü//TR','BEGIN:VEVENT',`DTSTAMP:${stamp(new Date())}`,`DTSTART:${stamp(start)}`,`DTEND:${stamp(end)}`,'SUMMARY:ALO186 kesinti sürekliliği kaydını gözden geçir','DESCRIPTION:Son 30/90 gündeki kesinti sürelerini, kritik yük açıklarını ve mevcut hazırlık testini yeniden kontrol edin. Kampanya değil teknik kontrol hatırlatmasıdır.','END:VEVENT','END:VCALENDAR'].join('\r\n');}
function download(name,type,content){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove();},0);}
function init(){if(typeof document==='undefined')return;const $=id=>document.getElementById(id);const form=$('outageForm'),result=$('result'),recordsBox=$('records'),affiliate=$('affiliate');let records=load();
const checked=name=>[...document.querySelectorAll(`input[name="${name}"]:checked`)].map(el=>el.value);
const read=()=>({start:$('start').value,end:$('end').value,scope:$('scope').value,officialRecord:$('officialRecord').value,active:$('active').checked,restoration:$('restoration').value,impacts:checked('impact'),criticalGap:$('criticalGap').checked,emergency:$('emergency').checked,createdAt:now()});
function routeFor(kind){if(kind==='internet_backup')return'/hesaplama/home-office-internet-sureklilik-plani/';if(kind==='cold_chain_backup')return'/amazon-elektrik-urunleri/buzdolabi-dondurucu-power-station-secimi';return'/hesaplama/yedek-guc/';}
function renderRecords(){const s=summarize(records);$('m30').textContent=s.recent30;$('m90').textContent=s.recent90;$('mtotal').textContent=`${s.total90} dk`;$('mlong').textContent=`${s.longest90} dk`;recordsBox.innerHTML=records.length?records.slice().reverse().map((r,i)=>`<div class="record"><div><strong>${new Date(r.start).toLocaleString('tr-TR')} · ${r.duration} dk</strong><small>${r.scope} · ${r.impacts.join(', ')||'etki seçilmedi'} · ${r.officialRecord?'resmî kayıt var':'resmî kayıt yok'}</small></div><button type="button" data-remove="${records.length-1-i}">Kaydı sil</button></div>`).join(''):'<p class="note">Bu cihazda saklanan kayıt yok. Saklama yalnız açık seçiminizle çalışır.</p>';recordsBox.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>{records.splice(Number(b.dataset.remove),1);save(records);renderRecords();}));}
form.addEventListener('submit',e=>{e.preventDefault();const input=read();const record=cleanRecord(input);const decision=decide(input,records);result.className=`result status ${decision.code==='emergency'||decision.code==='medical'?'danger':decision.commerce?'ok':'warn'}`;result.innerHTML=`<h2>${decision.title}</h2><p>${decision.text}</p><div class="metrics"><div class="metric"><span>Bu olay</span><strong>${record.duration} dk</strong></div><div class="metric"><span>90 gün olay</span><strong>${summarize([...records,record]).recent90}</strong></div><div class="metric"><span>90 gün toplam</span><strong>${summarize([...records,record]).total90} dk</strong></div><div class="metric"><span>Kanıt durumu</span><strong>${decision.commerce?'tekrarlandı':'izleniyor'}</strong></div></div>`;affiliate.classList.toggle('hidden',!decision.commerce);if(decision.commerce){const link=$('affiliateLink');link.href=routeFor(decision.productClass);link.textContent='Teknik uygunluk aracına geç — sonraki sayfa satış ortaklığı bağlantıları içerebilir';}if($('storeLocal').checked&&record.duration&&!input.emergency){records=save([...records,record]);renderRecords();}result.scrollIntoView({behavior:'smooth',block:'start'});});
$('exportJson').addEventListener('click',()=>download('alo186-kesinti-kayitlari.json','application/json',JSON.stringify({exportedAt:new Date().toISOString(),records},null,2)));$('exportCsv').addEventListener('click',()=>download('alo186-kesinti-kayitlari.csv','text/csv;charset=utf-8',csv(records)));$('calendar').addEventListener('click',()=>download('alo186-30-gun-kesinti-kontrolu.ics','text/calendar;charset=utf-8',calendar(30)));$('clearAll').addEventListener('click',()=>{records=[];localStorage.removeItem(STORAGE_KEY);renderRecords();});renderRecords();}
if(typeof window!=='undefined')window.addEventListener('DOMContentLoaded',init);
return{ROUTE,STORAGE_KEY,MAX_RECORDS,TTL_DAYS,durationMinutes,cleanRecord,summarize,decide,csv,calendar};});