(() => {'use strict';
const core=window.Alo186TechnicalHandoff,STORE='alo186:technical-handoff:v1',$=id=>document.getElementById(id),IMPORT_KEYS=new Set(['schema','version','createdAt','expiresAt','context','role','stage','system','productCategory','status','readiness','commercialAllowed','missingEvidence','missingAcceptance','tasks','followupDays','checksum']);let lastPackage=null;
function safeJson(){try{return JSON.parse(localStorage.getItem(STORE)||'[]')}catch{return[]}}
function write(records){try{localStorage.setItem(STORE,JSON.stringify(core.prune(records)));return true}catch{return false}}
function val(id){return $(id).value}
function checks(name){return Object.fromEntries([...document.querySelectorAll(`[name="${name}"]`)].map(x=>[x.value,x.checked]))}
function input(){return{context:val('context'),role:val('role'),stage:val('stage'),system:val('system'),productCategory:val('productCategory'),existingSufficient:val('existingSufficient'),safetyRisk:$('safetyRisk').checked,technicalToolCompleted:$('technicalToolCompleted').checked,affiliateAcknowledged:$('affiliateAcknowledged').checked,evidence:checks('evidence'),acceptance:checks('acceptance')}}
function escape(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderAcceptance(){const s=core.SYSTEMS[val('system')];$('productRow').hidden=val('system')!=='plug_products';$('acceptanceList').innerHTML=s.acceptance.map((x,i)=>`<label><input type="checkbox" name="acceptance" value="a${i}"><span>${escape(x)}</span></label>`).join('')}
function renderHistory(){const list=core.prune(safeJson());$('history').hidden=!list.length;$('historyList').innerHTML=list.map(x=>`<article><strong>${escape(core.SYSTEMS[x.system].label)}</strong><span>${escape(x.status)} · ${x.readiness}/100</span><small>${new Intl.DateTimeFormat('tr-TR',{dateStyle:'medium'}).format(new Date(x.createdAt))}</small><button type="button" data-open="${x.checksum}">Paketi görüntüle</button></article>`).join('');$('historyList').querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{const p=list.find(x=>x.checksum===b.dataset.open);if(p)renderImported(p)})}
function actions(result){return`<a class="button primary" href="${escape(result.primary.href)}">${escape(result.primary.label)}</a><a class="button secondary" href="${escape(result.secondary.href)}">${escape(result.secondary.label)}</a>`}
function renderResult(result,pkg){lastPackage=pkg;$('result').hidden=false;$('score').textContent=`${result.readiness}/100`;$('status').textContent=result.status;$('resultTitle').textContent=result.title;$('resultText').textContent=result.summary;$('roleTasks').innerHTML=result.tasks.map(x=>`<li>${escape(x)}</li>`).join('');$('missingEvidence').innerHTML=(result.missingEvidence.length?result.missingEvidence.map(k=>`<li>${escape(core.EVIDENCE[k])}</li>`):['Eksik belge yok']).map(x=>x.startsWith('<li>')?x:`<li>${escape(x)}</li>`).join('');$('missingAcceptance').innerHTML=(result.missingAcceptance.length?result.missingAcceptance:['Eksik kabul adımı yok']).map(x=>`<li>${escape(x)}</li>`).join('');$('resultActions').innerHTML=actions(result);$('affiliateNote').textContent=result.commercialAllowed?'Satış ortaklığı rotası yalnız teknik araç, mevcut ürün yetersizliği ve görünür affiliate onayıyla açıldı. Fiyat, stok, puan ve garanti ALO186 tarafından doğrulanmaz.':'Bu sonuç affiliate veya doğrudan mağaza yönlendirmesi açmaz.';$('result').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth'});renderHistory()}
function renderImported(pkg){if(!core.validatePackage(pkg))return;lastPackage=pkg;$('result').hidden=false;$('score').textContent=`${pkg.readiness}/100`;$('status').textContent=pkg.status;$('resultTitle').textContent='İçe aktarılan teknik devir paketi';$('resultText').textContent=`${core.CONTEXTS[pkg.context]} · ${core.ROLES[pkg.role]} · ${core.SYSTEMS[pkg.system].label}`;$('roleTasks').innerHTML=pkg.tasks.map(x=>`<li>${escape(x)}</li>`).join('');$('missingEvidence').innerHTML=(pkg.missingEvidence.length?pkg.missingEvidence.map(k=>core.EVIDENCE[k]):['Eksik belge yok']).map(x=>`<li>${escape(x)}</li>`).join('');$('missingAcceptance').innerHTML=(pkg.missingAcceptance.length?pkg.missingAcceptance:['Eksik kabul adımı yok']).map(x=>`<li>${escape(x)}</li>`).join('');$('resultActions').innerHTML='<a class="button secondary" href="/hesaplama/elektrik-planim/">Elektrik Planım’ı aç</a>';$('affiliateNote').textContent='İçe aktarılan paket marka, fiyat, stok, satıcı, garanti veya kişisel veri içermez.';$('result').scrollIntoView({behavior:'smooth'})}
function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),500)}
function submit(e){e.preventDefault();const raw=input(),result=core.evaluate(raw),pkg=core.packageRecord(raw);write([pkg,...safeJson()]);renderResult(result,pkg);window.Alo186Track?.('technical_handoff_created',{system:raw.system,role:raw.role,stage:raw.stage,status:result.status})}
async function importFile(file){if(!file||file.size>100000)return;$('importStatus').textContent='';try{const raw=JSON.parse(await file.text());if(!raw||Object.keys(raw).some(key=>!IMPORT_KEYS.has(key))||Object.keys(raw).length!==IMPORT_KEYS.size)throw new Error('Fazladan veya eksik alan');if(!core.validatePackage(raw))throw new Error('Geçersiz paket');write([raw,...safeJson()]);renderImported(raw);$('importStatus').textContent='Paket doğrulandı ve yalnız bu tarayıcıya aktarıldı.'}catch{$('importStatus').textContent='Yalnız ALO186 tarafından oluşturulmuş, alan ve checksum doğrulaması geçen JSON paketleri kabul edilir.'}}
document.addEventListener('DOMContentLoaded',()=>{if(!core)return;$('system').onchange=renderAcceptance;renderAcceptance();$('form').onsubmit=submit;$('downloadJson').onclick=()=>lastPackage&&download(`alo186-teknik-devir-${lastPackage.checksum}.json`,JSON.stringify(lastPackage,null,2),'application/json');$('downloadIcs').onclick=()=>lastPackage&&download(`alo186-kabul-kontrol-${lastPackage.checksum}.ics`,core.buildIcs(lastPackage,location.origin),'text/calendar');$('copySummary').onclick=async()=>{if(!lastPackage)return;await navigator.clipboard.writeText(core.summaryText(lastPackage));$('copySummary').textContent='Kopyalandı';setTimeout(()=>$('copySummary').textContent='Özeti kopyala',1200)};$('print').onclick=()=>print();$('importFile').onchange=e=>importFile(e.target.files[0]);$('clear').onclick=()=>{localStorage.removeItem(STORE);lastPackage=null;$('result').hidden=true;renderHistory()};renderHistory()});
})();
