'use strict';const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),core=require('./core.js');const fullEvidence=Object.fromEntries(Object.keys(core.EVIDENCE).map(k=>[k,true]));
function acceptance(system,value=true){return Object.fromEntries(core.SYSTEMS[system].acceptance.map((_,i)=>[`a${i}`,value]))}
const base={context:'home',role:'procurement',stage:'purchase',system:'plug_products',productCategory:'power_station',existingSufficient:'no',safetyRisk:false,technicalToolCompleted:true,affiliateAcknowledged:true,evidence:fullEvidence,acceptance:acceptance('plug_products')};
const ready=core.evaluate(base);assert.equal(ready.status,'ready');assert.equal(ready.commercialAllowed,true);assert.match(ready.primary.href,/akilli-urun-secimi\?kategori=power_station/);assert.equal(ready.readiness,100);
const noBuy=core.evaluate({...base,existingSufficient:'yes'});assert.equal(noBuy.status,'no_buy');assert.equal(noBuy.commercialAllowed,false);assert.match(noBuy.title,/yeni ürün gerekmiyor/i);
const missing=core.evaluate({...base,evidence:{...fullEvidence,model_manual:false}});assert.equal(missing.status,'conditional');assert.equal(missing.commercialAllowed,false);assert.ok(missing.missingCritical.includes('model_manual'));
const noAffiliate=core.evaluate({...base,affiliateAcknowledged:false});assert.equal(noAffiliate.status,'conditional');assert.equal(noAffiliate.commercialAllowed,false);
const generator=core.evaluate({...base,system:'generator',acceptance:acceptance('generator')});assert.ok(['professional','blocked'].includes(generator.status));assert.equal(generator.commercialAllowed,false);assert.match(generator.primary.href,/kurumsal-elektrik-surekliligi/);
const repeat=core.evaluate({...base,stage:'recurring_fault'});assert.ok(['blocked','professional'].includes(repeat.status));assert.equal(repeat.followupDays,3);
const safety=core.evaluate({...base,safetyRisk:true});assert.equal(safety.status,'safety');assert.equal(safety.followupDays,0);assert.equal(safety.primary.href,'/karar-motoru');
const now=new Date('2026-07-29T00:00:00.000Z'),pkg=core.packageRecord(base,now);assert.equal(pkg.schema,'alo186-technical-handoff-v1');assert.equal(pkg.expiresAt,'2027-01-25T00:00:00.000Z');assert(core.validatePackage(pkg));const corrupted={...pkg,readiness:1};assert.equal(core.validatePackage(corrupted),false);assert.doesNotMatch(JSON.stringify(pkg),/name|email|phone|address|price|stock|seller|warranty|asin/i);assert.match(core.summaryText(pkg),/kişisel veri/i);const ics=core.buildIcs(pkg);assert.match(ics,/BEGIN:VCALENDAR/);assert.doesNotMatch(ics,/ATTENDEE|ORGANIZER|LOCATION|EMAIL|TEL/i);const old={...pkg,checksum:''};old.createdAt='2025-01-01T00:00:00.000Z';old.expiresAt='2025-06-01T00:00:00.000Z';const copy={...old};delete copy.checksum;old.checksum=core.hashText(JSON.stringify(copy));assert.equal(core.prune([old,pkg],now).length,1);
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');assert.match(html,/https:\/\/www\.alo186\.com\/hesaplama\/teknik-devir-kabul-paketi\//);assert.match(html,/WebApplication/);assert.match(html,/FAQPage/);assert.match(html,/Satın almama geçerli sonuç/);assert.doesNotMatch(html,/type="(?:text|email|tel)"|<textarea/i);assert.doesNotMatch(html,/amazon\.(?:com|com\.tr)/i);assert.doesNotMatch(html,/fiyat\s*[:=]|stok\s*[:=]|puan\s*[:=]|garanti\s*[:=]/i);console.log('ALO186 teknik devir ve kabul paketi: rol, kabul, no-buy, profesyonel sınır, affiliate kapısı, JSON/ICS ve gizlilik testleri başarılı.');
