'use strict';
const assert=require('node:assert/strict');
const {calculate}=require('./app.js');
const base={scenario:'planning',topology:'poe_nvr',cameraCount:8,cameraW:8,recorderW:25,switchOwnW:12,routerW:12,monitorW:0,otherW:0,targetHours:4,poeBudgetW:120,poePorts:8,sourceStatus:'none',sourceType:'auto',installation:'small',redundancy:'not_required'};
let r=calculate({...base,emergency:true});assert.equal(r.status,'emergency');assert.equal(r.commercialAllowed,false);
r=calculate({...base,securityCritical:true});assert.equal(r.status,'professional');
r=calculate({...base,topology:'unknown'});assert.equal(r.status,'evidence_required');
r=calculate({...base,poeBudgetW:'',poePorts:''});assert.equal(r.status,'evidence_required');
r=calculate({...base,poeBudgetW:40});assert.equal(r.status,'poe_gap');assert.equal(r.commercialAllowed,false);
r=calculate(base);assert.equal(r.status,'conditional_purchase');assert.equal(r.metrics.requiredPoePorts,8);assert.equal(r.metrics.requiredPoeBudgetW,95);assert.equal(r.metrics.requiredContinuousW,160);assert.equal(r.metrics.requiredWh,690);assert.equal(r.metrics.recommendedCategory,'power_station');
r=calculate({...base,scenario:'active'});assert.equal(r.status,'active_event');assert.equal(r.commercialAllowed,false);
r=calculate({...base,sourceStatus:'existing',sourceContinuousW:200,sourceWh:900,outputVerified:'yes',blackoutTest:'success'});assert.equal(r.status,'no_buy');
r=calculate({...base,sourceStatus:'existing',sourceContinuousW:100,sourceWh:900,outputVerified:'yes',blackoutTest:'success'});assert.equal(r.status,'conditional_purchase');assert.equal(r.commercialAllowed,true);
r=calculate({...base,sourceStatus:'existing',sourceContinuousW:200,sourceWh:900,outputVerified:'unknown',blackoutTest:'success'});assert.equal(r.status,'evidence_required');
r=calculate({...base,cameraCount:40});assert.equal(r.status,'professional');
r=calculate({scenario:'planning',topology:'wifi',cameraCount:1,cameraW:6,recorderW:0,routerW:12,targetHours:4,sourceStatus:'none',sourceType:'auto',installation:'small',redundancy:'not_required'});assert.equal(r.metrics.recommendedCategory,'mini_ups');assert.equal(r.status,'conditional_purchase');
r=calculate({...base,installation:'fixed_rack'});assert.equal(r.status,'professional');
r=calculate({...base,redundancy:'required'});assert.equal(r.status,'professional');
console.log(JSON.stringify({ok:true,scenarios:14},null,2));
