'use strict';
(function(root,factory){
  const api=factory();
  if(typeof module==='object'&&module.exports)module.exports=api;
  if(root){root.ALO186SurgeHealth=api;if(root.document)api.mount(root.document);}
})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const ROUTE='/hesaplama/akim-korumali-priz-koruma-gostergesi-omur-testi/';
  const n=(value)=>Number(value);
  const finite=(value)=>Number.isFinite(n(value));
  const round=(value,digits=1)=>Number(n(value).toFixed(digits));
  function metrics(data){
    const loadW=finite(data.loadW)?n(data.loadW):NaN;
    const ratedW=finite(data.ratedW)?n(data.ratedW):NaN;
    const ratio=Number.isFinite(loadW)&&Number.isFinite(ratedW)&&ratedW>0?(loadW/ratedW)*100:NaN;
    return {loadW,ratedW,loadRatio:Number.isFinite(ratio)?round(ratio,1):NaN};
  }
  function decision(data){
    const m=metrics(data);
    if(data.emergency||!data.physicalSafe)return {code:'unsafe',commerce:false,tone:'danger',title:'Kullanmayı bırakın; ürün seçimine geçmeyin',summary:'Duman, erime, yanık kokusu, kıvılcım, gevşeklik, kararma, su teması veya elektrik çarpması belirtisinde enerjiyi güvenle kesin ve yetkili elektrikçi/servis rotasına geçin.'};
    if(data.excludedLoad)return {code:'excluded',commerce:false,tone:'danger',title:'Bu yük tüketici tipi akım korumalı prize uygun değil',summary:'Elektrikli araç, tıbbi veya yaşam destek cihazı, ısıtıcı, yüksek güçlü beyaz eşya, motor/pompa ve sabit tesisat için grup priz ürününe yönlendirme yapılmaz.'};
    if(data.wholeHomeNeed||data.repeatedVoltage)return {code:'professional',commerce:false,tone:'warn',title:'Kök neden ve pano koruması uzman tarafından değerlendirilmeli',summary:'Bina genelinde yıldırım/darbe riski veya tekrarlayan düşük-yüksek gerilim, fişli akım korumalı prizle tek başına çözülemez. SPD koordinasyonu, topraklama, nötr ve gerilim kaynağı profesyonel ölçüm gerektirir.'};
    if(!finite(m.loadW)||!finite(m.ratedW)||m.loadW<0||m.ratedW<=0)return {code:'invalid',commerce:false,tone:'warn',title:'Yük ve ürün etiketi eksik',summary:'Toplam eşzamanlı watt ile ürün etiketindeki azami watt/akım doğrulanmadan kullanım veya satın alma sonucu üretilemez.'};
    const planningLimit=data.longUse?80:90;
    if(m.loadRatio>100)return {code:'overload',commerce:false,tone:'danger',title:'Etiket sınırı aşılıyor',summary:`Toplam yük ürün etiketinin yaklaşık %${m.loadRatio} düzeyinde. Daha yüksek etiketli grup priz satın almak sabit devre kapasitesini büyütmez; yükleri ayırın ve devreyi kontrol ettirin.`};
    if(m.loadRatio>planningLimit)return {code:'high_load',commerce:false,tone:'warn',title:'Yük payı yüksek; önce kullanım düzenini düzeltin',summary:`ALO186 planlama bandına göre yük oranı %${m.loadRatio}. Bu oran standart hükmü değildir; uzun süreli kullanımda yüksek güçlü cihazları grup prizden ayırın ve etiket/tesisat uygunluğunu doğrulayın.`};
    if(data.groundIndicator==='fault')return {code:'ground_fault',commerce:false,tone:'danger',title:'Topraklama göstergesi hata veriyor',summary:'Yeni akım korumalı priz satın almak topraklama sorununu düzeltmez. Priz ve koruma iletkeni yetkili elektrikçi tarafından ölçülmelidir.'};
    if(data.productType==='powerstrip'){
      if(data.existingAlternative)return {code:'use_existing',commerce:false,tone:'ok',title:'Mevcut güvenli koruma çözümünü kullanın',summary:'Elinizde etiketi okunur, göstergesi normal ve yüke uygun bir koruma cihazı varsa yalnız mevcut çoklayıcının korumasız olması nedeniyle ikinci ürün almayın; güvenli mevcut çözümü kullanın.'};
      const approved=Boolean(data.confirmNeed&&data.confirmLowRisk&&data.confirmAffiliate);
      return approved?{code:'qualified_missing',commerce:true,tone:'warn',title:'Korumasız çoklayıcı yerine doğrulanabilir koruma sınıfı açıldı',summary:'Yalnız düşük güçlü elektronikler, topraklı tek bağlantı ve doğrulanabilir koruma göstergesi için ürün sınıfını karşılaştırın. Zincirleme bağlantı yapmayın.'}:{code:'not_protected',commerce:false,tone:'warn',title:'Bu ürün koruma cihazı değil; ticari geçiş henüz kapalı',summary:'Sıradan grup priz veya etiketi belirsiz çoklayıcı darbe koruması kanıtı değildir. Önce gerçek ihtiyacı, düşük riskli yükü ve satış ortaklığı bilgisini doğrulayın.'};
    }
    if(data.protectionIndicator==='off'){
      if(data.existingAlternative)return {code:'use_existing',commerce:false,tone:'ok',title:'Mevcut güvenli alternatifinizi kullanın',summary:'Koruma göstergesi kapanmış ürün yerine elinizdeki doğrulanmış güvenli koruma cihazını kullanın; gereksiz yeni ürün almayın.'};
      const approved=Boolean(data.confirmNeed&&data.confirmLowRisk&&data.confirmAffiliate);
      return approved?{code:'qualified_failed',commerce:true,tone:'warn',title:'Koruma kaybı doğrulandı; ürün sınıfı açıldı',summary:'Üretici kılavuzu göstergenin koruma kaybı anlamına geldiğini doğruluyorsa ve düşük güçlü elektronik yük sınırı uygunsa yeni koruma sınıfı karşılaştırılabilir.'}:{code:'indicator_off',commerce:false,tone:'danger',title:'Koruma göstergesi kapalı; ürünü koruma cihazı saymayın',summary:'Önce üretici kılavuzundaki gösterge anlamını doğrulayın. Koruma kaybı teyit edilirse cihazı yalnız çoklayıcı olarak kullanmaya devam etmeyin.'};
    }
    if(data.protectionIndicator==='unknown'||!data.manualChecked)return {code:'verify_manual',commerce:false,tone:'warn',title:'Gösterge ve kılavuz doğrulanmalı',summary:'LED rengi, sesli uyarı, otomatik kapanma ve toprak göstergesi her modelde aynı anlama gelmez. Tam model üretici kılavuzunu kontrol etmeden değişim veya kullanım kararı vermeyin.'};
    if(data.majorEvent)return {code:'post_event',commerce:false,tone:'warn',title:'Büyük olay sonrası kontrollü yeniden doğrulama yapın',summary:'Yıldırım veya belirgin darbe sonrasında yalnız olay yaşandı diye otomatik değişim yapmayın. Gösterge, fiziksel durum, üretici talimatı ve bağlı cihaz davranışını yeniden kontrol edin.'};
    if(data.higherJouleOnly)return {code:'no_buy_joule',commerce:false,tone:'ok',title:'Yalnız daha yüksek joule etiketi için değiştirmeyin',summary:'Joule sayısı tek başına güvenilir ürün karşılaştırması değildir. Mevcut cihazın koruma durumu, standart/üretici verisi, topraklama, bağlantı ve yük sınırı uygunsa yeni ürün almayın.'};
    if(data.existingHealthy)return {code:'no_buy',commerce:false,tone:'ok',title:'Mevcut koruma cihazı yeterli — yeni ürün almayın',summary:'Fiziksel durum, koruma göstergesi, topraklama, etiket sınırı ve bağlantı düzeni uygunsa yalnız yaş veya daha yeni model gerekçesiyle değiştirmeyin.'};
    const approved=Boolean(data.confirmNeed&&data.confirmLowRisk&&data.confirmAffiliate);
    return approved?{code:'qualified',commerce:true,tone:'warn',title:'Doğrulanmış düşük riskli eksik için ürün sınıfı açıldı',summary:'Düşük güçlü elektronikler, topraklı tek bağlantı, görünür koruma göstergesi ve üretici verileri doğrulanabilen sınıfları karşılaştırın.'}:{code:'need_unconfirmed',commerce:false,tone:'warn',title:'Ürün ihtiyacı henüz doğrulanmadı',summary:'Mevcut cihazın göstergesini, tam model kılavuzunu, topraklamayı ve gerçek yükü doğrulayın; üç açık onay olmadan ticari bağlantı açılmaz.'};
  }
  function report(data){return {route:ROUTE,generatedAt:new Date().toISOString(),metrics:metrics(data),decision:decision(data),personalData:false,officialApproval:false};}
  function calendar(days=90){const start=new Date(Date.now()+Math.max(1,n(days)||90)*86400000);const end=new Date(start.getTime()+30*60000);const stamp=(date)=>date.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z');return ['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//ALO186//Surge Protector Check//TR','BEGIN:VEVENT',`UID:surge-check-${Date.now()}@alo186.com`,`DTSTAMP:${stamp(new Date())}`,`DTSTART:${stamp(start)}`,`DTEND:${stamp(end)}`,'SUMMARY:Akım korumalı priz ve gösterge kontrolü','DESCRIPTION:Fiziksel durumu, koruma/toprak göstergesini, üretici kılavuzunu, toplam yükü ve son elektrik olaylarını yeniden kontrol edin.','END:VEVENT','END:VCALENDAR'].join('\r\n');}
  function download(name,text,type){const blob=new Blob([text],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),0);}
  function read(doc){const value=(id)=>doc.getElementById(id)?.value;const checked=(id)=>Boolean(doc.getElementById(id)?.checked);return {productType:value('productType'),protectionIndicator:value('protectionIndicator'),groundIndicator:value('groundIndicator'),loadW:value('loadW'),ratedW:value('ratedW'),longUse:checked('longUse'),manualChecked:checked('manualChecked'),physicalSafe:checked('physicalSafe'),majorEvent:checked('majorEvent'),wholeHomeNeed:checked('wholeHomeNeed'),repeatedVoltage:checked('repeatedVoltage'),existingHealthy:checked('existingHealthy'),existingAlternative:checked('existingAlternative'),higherJouleOnly:checked('higherJouleOnly'),excludedLoad:checked('excludedLoad'),emergency:checked('emergency'),confirmNeed:checked('confirmNeed'),confirmLowRisk:checked('confirmLowRisk'),confirmAffiliate:checked('confirmAffiliate')};}
  function mount(doc){const form=doc.getElementById('surgeForm');if(!form)return;let last=null;form.addEventListener('submit',(event)=>{event.preventDefault();const data=read(doc);const result=decision(data);last=report(data);const metricsData=metrics(data);const node=doc.getElementById('result');node.className=`result ${result.tone}`;node.innerHTML=`<h2>${result.title}</h2><p>${result.summary}</p><div class="metrics"><div class="metric"><span>Toplam yük</span><strong>${Number.isFinite(metricsData.loadW)?metricsData.loadW+' W':'—'}</strong></div><div class="metric"><span>Etiket sınırı</span><strong>${Number.isFinite(metricsData.ratedW)?metricsData.ratedW+' W':'—'}</strong></div><div class="metric"><span>Yük oranı</span><strong>${Number.isFinite(metricsData.loadRatio)?'%'+metricsData.loadRatio:'—'}</strong></div><div class="metric"><span>Ticari yol</span><strong>${result.commerce?'Açık':'Kapalı'}</strong></div></div>`;node.scrollIntoView({behavior:'smooth',block:'start'});doc.getElementById('affiliate').classList.toggle('hidden',!result.commerce);});doc.getElementById('exportJson')?.addEventListener('click',()=>download('alo186-akim-korumali-priz-kontrolu.json',JSON.stringify(last||report(read(doc)),null,2),'application/json'));doc.getElementById('calendar')?.addEventListener('click',()=>download('alo186-akim-korumali-priz-kontrolu.ics',calendar(90),'text/calendar'));}
  return {ROUTE,metrics,decision,report,calendar,mount};
});
