(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.Alo186TechnicalHandoff=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const VERSION=1,MAX_RECORDS=6,TTL_DAYS=180,DAY_MS=86400000;
const CONTEXTS={home:'Ev / bireysel kullanım',small_business:'Küçük işletme',hotel:'Otel / konaklama tesisi',site:'Site / ortak yaşam alanı'};
const ROLES={owner:'İşletme sahibi / yönetici',technical:'Teknik ekip / servis',procurement:'Satın alma / tedarik'};
const STAGES={planning:'Planlama',purchase:'Satın alma öncesi',installation:'Kurulum',acceptance:'Kabul ve devreye alma',operation:'İşletme / bakım',recurring_fault:'Tekrarlayan arıza'};
const SYSTEMS={
plug_products:{label:'Tak-çalıştır düşük riskli ürünler',highRisk:false,tool:'/hesaplama/teknik-urun-karsilastirma/',professional:'/kurumsal-elektrik-surekliligi-on-degerlendirme?problem=urun_uygunlugu&scope=uzaktan_dokuman',acceptance:['Etiket ve teknik doküman adayla aynı','Gerçek yükte ısınma ve çalışma süresi kontrolü','Kablo, fiş, gövde ve ortam güvenliği','Mevcut ürünün yetersizliği doğrulandı']},
ups:{label:'UPS ve akü sistemi',highRisk:true,tool:'/hesaplama/ups-suresi/',professional:'/kurumsal-elektrik-surekliligi-on-degerlendirme?problem=yedek_guc&scope=karsilastirma',acceptance:['Sürekli ve tepe yük kaydı','Tam yükte gerçek runtime testi','Bypass / transfer ve alarm testi','Akü kartuşu / string uyumu','Bakım ve yeniden test tarihi']},
generator:{label:'Jeneratör, ATS ve AMF',highRisk:true,tool:'/hesaplama/jenerator-gucu-secimi/',professional:'/kurumsal-elektrik-surekliligi-on-degerlendirme?problem=yedek_guc&scope=saha_inceleme',acceptance:['Yüksüz ve kademeli yük testi','Gerilim, frekans ve faz akımı kaydı','ATS transfer / geri dönüş testi','RCD ve nötr-toprak topolojisi doğrulaması','Yakıt, akü, havalandırma ve bakım planı']},
inverter_storage:{label:'İnverter ve enerji depolama',highRisk:true,tool:'/hesaplama/inverter-uygunluk/',professional:'/kurumsal-elektrik-surekliligi-on-degerlendirme?problem=ges_batarya&scope=karsilastirma',acceptance:['Sürekli / tepe güç ve DC akım doğrulaması','Batarya gerilim, kimya ve BMS uyumu','DoD, sıcaklık ve rezerv sınırları','Ada çalışma / transfer / koruma testi','Gerçek yükte runtime ve bakım kaydı']},
ev_charging:{label:'EV şarj ve wallbox',highRisk:true,tool:'/hesaplama/ev-sarj-uygunluk/',professional:'/kurumsal-elektrik-surekliligi-on-degerlendirme?problem=ev_sarj&scope=saha_inceleme',acceptance:['Faz, akım, güç ve kablo sınıfı','RCD / RDC-DD ve PE sürekliliği','Dinamik yük yönetimi testi','Konnektör ve terminal sıcaklık kontrolü','Araçla gerçek şarj ve hata kaydı']},
ges:{label:'GES ve PV inverter',highRisk:true,tool:'/hesaplama/gunes-paneli-power-station-uygunluk/',professional:'/kurumsal-elektrik-surekliligi-on-degerlendirme?problem=ges_batarya&scope=saha_inceleme',acceptance:['String Voc, Vmp, Isc ve Imp doğrulaması','MPPT, konnektör ve DC koruma uyumu','AC koruma, topraklama ve haberleşme testi','İzolasyon / AFCI / event log kontrolü','Üretim ve sıcaklık trendi kabul kaydı']},
protection:{label:'RCD, SPD, topraklama ve pano koruması',highRisk:true,tool:'/hesaplama/gerilim-koruma-cozum-secici/',professional:'/kurumsal-elektrik-surekliligi-on-degerlendirme?problem=genel_risk&scope=saha_inceleme',acceptance:['Şebeke sistemi ve tek hat şeması','RCD tipi, eşik ve açma süresi','SPD tipi, SCPD ve bağlantı yolu','PE sürekliliği, RA / Zs ölçümleri','Etiket, pano sıcaklığı ve bakım tarihi']},
power_quality:{label:'Harmonik ve güç kalitesi',highRisk:true,tool:'/isletme-surekliligi',professional:'/kurumsal-elektrik-surekliligi-on-degerlendirme?problem=genel_risk&scope=olcum_kampanyasi',acceptance:['PCC ve fider bazında THDv / THDi','Harmonik spektrum ve gerçek amperler','Nötr akımı ve sıcaklık trendi','Yük profili ve kompanzasyon kademeleri','Önce / sonra ölçüm kabul raporu']}
};
const PRODUCT_CATEGORIES={powerbank:'Powerbank',surge_strip:'Akım korumalı grup priz',mini_ups:'Modem / ONT mini UPS',emergency_light:'Acil aydınlatma',smoke_alarm:'Duman alarmı',power_station:'Power station',smart_plug:'Akıllı priz ve enerji ölçer',ev_cable:'Type 2 EV kablosu',ups_battery:'UPS aküsü / kartuşu'};
const EVIDENCE={model_manual:'Tam model ve üretici kılavuzu',single_line:'Tek hat / bağlantı şeması',load_data:'Gerçek yük, akım veya enerji verisi',protection_plan:'Koruma ve topraklama planı',test_report:'Ölçüm / test raporu',commissioning:'Devreye alma ve kabul kaydı',maintenance:'Bakım ve yeniden test planı',outcome:'Çözüm sonucu / tekrar kaydı'};
const ROLE_TASKS={owner:['Kritik işlev ve kabul sahibini belirleyin','Eksik kanıtları tarihlendirin','Kabul tamamlanmadan işletme riski kapandı saymayın'],technical:['Üretici limitleriyle gerçek ölçümü karşılaştırın','Koruma ve işlev testlerini kanıtlayın','Kalan riski ve yeniden test tarihini yazın'],procurement:['Teknik minimumları marka ve fiyat iddiasından ayırın','Kritik belge eksik adayı elemek için soru paketi kullanın','Teslim koşuluna kabul testini ve belge setini ekleyin']};
function hasOwn(o,k){return Object.prototype.hasOwnProperty.call(o,k)}
function enumValue(v,map,fallback){v=String(v||'').trim();return hasOwn(map,v)?v:fallback}
function bool(v){return v===true||v==='true'||v===1||v==='1'||v==='yes'||v==='on'}
function sanitize(raw={}){const system=enumValue(raw.system,SYSTEMS,'plug_products');return{context:enumValue(raw.context,CONTEXTS,'home'),role:enumValue(raw.role,ROLES,'owner'),stage:enumValue(raw.stage,STAGES,'planning'),system,productCategory:enumValue(raw.productCategory,PRODUCT_CATEGORIES,'powerbank'),existingSufficient:enumValue(raw.existingSufficient,{yes:1,no:1,unknown:1},'unknown'),safetyRisk:bool(raw.safetyRisk),technicalToolCompleted:bool(raw.technicalToolCompleted),affiliateAcknowledged:bool(raw.affiliateAcknowledged),evidence:Object.fromEntries(Object.keys(EVIDENCE).map(k=>[k,bool(raw.evidence&&raw.evidence[k])])),acceptance:Object.fromEntries(SYSTEMS[system].acceptance.map((_,i)=>[`a${i}`,bool(raw.acceptance&&raw.acceptance[`a${i}`])]))}}
function criticalEvidence(input){const base=['model_manual','load_data','test_report'];if(input.system==='plug_products')return['model_manual','load_data'];if(input.system==='power_quality')return['load_data','test_report','outcome'];if(['protection','ev_charging','generator','ges','inverter_storage'].includes(input.system))return['model_manual','single_line','load_data','protection_plan','test_report'];return base}
function score(input){const critical=new Set(criticalEvidence(input));let earned=0,total=0;Object.keys(EVIDENCE).forEach(k=>{const w=critical.has(k)?2:1;total+=w;if(input.evidence[k])earned+=w});const acceptanceKeys=Object.keys(input.acceptance);total+=acceptanceKeys.length*2;acceptanceKeys.forEach(k=>{if(input.acceptance[k])earned+=2});return Math.round(earned/total*100)}
function followupDays(input,status){if(status==='safety')return 0;if(input.stage==='recurring_fault')return 3;if(status==='blocked'||status==='conditional')return 7;if(input.stage==='acceptance'||input.stage==='installation')return 14;if(input.stage==='purchase')return 14;return 90}
function evaluate(raw={}){const input=sanitize(raw),system=SYSTEMS[input.system],critical=criticalEvidence(input);const missingCritical=critical.filter(k=>!input.evidence[k]);const missingEvidence=Object.keys(EVIDENCE).filter(k=>!input.evidence[k]);const missingAcceptance=system.acceptance.filter((_,i)=>!input.acceptance[`a${i}`]);const readiness=score(input);let status='ready',commercialAllowed=false,title='Devir ve kabul paketi hazır',summary='Rol bazlı görevler, belge listesi ve kabul adımları birlikte paylaşılabilir.';let primary={label:'Paketi dışa aktar',href:'#export'};let secondary={label:'Elektrik Planım’ı aç',href:'/hesaplama/elektrik-planim/'};
if(input.safetyRisk){status='safety';title='Normal devir ve satın alma akışını durdurun';summary='Duman, alev, elektrik çarpması, erime veya hızla artan sıcaklık varsa enerjili bölüme müdahale etmeyin; 112 ve güvenli resmî kanal önceliklidir.';primary={label:'Karar Motorunu aç',href:'/karar-motoru'};secondary={label:'Doğru EDAŞ kanalını bul',href:'/edas-bul'};}
else if(input.existingSufficient==='yes'){status='no_buy';title='Mevcut çözüm yeterli; yeni ürün gerekmiyor';summary='Kabul adımları ve bakım tarihi tamamlanmalı, fakat yeni ürün veya affiliate rotası açılmamalıdır.';primary={label:'Bakım planı oluştur',href:'/hesaplama/ekipman-bakim-plani/'};}
else if(system.highRisk||input.stage==='recurring_fault'){status=missingCritical.length||missingAcceptance.length?'blocked':'professional';title=input.stage==='recurring_fault'?'Tekrarlayan sorun için ürün denemesini durdurun':'Profesyonel devir ve kabul gerekli';summary='Sabit tesisat, yüksek güç veya tekrar eden arızada genel ürün araması yerine ölçüm, devreye alma ve kabul kapsamı hazırlanmalıdır.';primary={label:'Profesyonel ön değerlendirmeyi aç',href:system.professional};secondary={label:'İlgili ücretsiz aracı aç',href:system.tool};}
else if(missingCritical.length||missingAcceptance.length||readiness<80){status='conditional';title='Kritik kanıt veya kabul adımı eksik';summary='Ürün karşılaştırmasına geçmeden önce eksik teknik belgeyi ve gerçek kullanım testini tamamlayın.';primary={label:'Ücretsiz teknik aracı aç',href:system.tool};secondary={label:'Teknik kısa listeyi aç',href:'/hesaplama/teknik-urun-karsilastirma/'};}
else if(!input.technicalToolCompleted||input.existingSufficient!=='no'||!input.affiliateAcknowledged){status='conditional';title='Affiliate kapısı için üç ayrı doğrulama gerekli';summary='Ücretsiz teknik araç, mevcut ürünün yetersizliği ve satış ortaklığı açıklaması ayrı ayrı doğrulanmadan ticari rota açılmaz.';primary={label:'Teknik kısa listeyi aç',href:'/hesaplama/teknik-urun-karsilastirma/'};secondary={label:'Şimdilik satın alma',href:'/hesaplama/elektrik-planim/'};}
else{commercialAllowed=true;title='Düşük riskli ürün karşılaştırmasına hazır';summary='Teknik kanıt ve kabul adımları yeterli. Affiliate niteliği görünür ürün merkezine yalnız kullanıcı onayıyla ilerlenebilir.';primary={label:'Şeffaf Ürün Merkezini aç',href:`/akilli-urun-secimi?kategori=${input.productCategory}`};secondary={label:'Şimdilik satın alma',href:'/hesaplama/elektrik-planim/'};}
const tasks=[...ROLE_TASKS[input.role]];missingCritical.forEach(k=>tasks.push(`${EVIDENCE[k]} eksikliğini tamamlayın`));missingAcceptance.slice(0,3).forEach(x=>tasks.push(`Kabul: ${x}`));return{version:VERSION,input,status,readiness,title,summary,commercialAllowed,missingCritical,missingEvidence,missingAcceptance,tasks:[...new Set(tasks)].slice(0,8),acceptance:system.acceptance,primary,secondary,followupDays:followupDays(input,status),roleLabel:ROLES[input.role],systemLabel:system.label,contextLabel:CONTEXTS[input.context],stageLabel:STAGES[input.stage]}}
function hashText(text){let h=2166136261;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(16).padStart(8,'0')}
function packageRecord(raw,nowValue=new Date()){const now=nowValue instanceof Date?nowValue:new Date(nowValue),result=evaluate(raw);const payload={schema:'alo186-technical-handoff-v1',version:VERSION,createdAt:now.toISOString(),expiresAt:new Date(now.getTime()+TTL_DAYS*DAY_MS).toISOString(),context:result.input.context,role:result.input.role,stage:result.input.stage,system:result.input.system,productCategory:result.input.system==='plug_products'?result.input.productCategory:null,status:result.status,readiness:result.readiness,commercialAllowed:result.commercialAllowed,missingEvidence:result.missingEvidence,missingAcceptance:result.missingAcceptance,tasks:result.tasks,followupDays:result.followupDays};return{...payload,checksum:hashText(JSON.stringify(payload))}}
function validatePackage(pkg){if(!pkg||pkg.schema!=='alo186-technical-handoff-v1'||pkg.version!==VERSION)return false;const copy={...pkg};delete copy.checksum;if(hashText(JSON.stringify(copy))!==pkg.checksum)return false;if(!hasOwn(CONTEXTS,pkg.context)||!hasOwn(ROLES,pkg.role)||!hasOwn(STAGES,pkg.stage)||!hasOwn(SYSTEMS,pkg.system))return false;if(!Array.isArray(pkg.tasks)||!Array.isArray(pkg.missingEvidence)||!Array.isArray(pkg.missingAcceptance))return false;return true}
function summaryText(pkg){if(!validatePackage(pkg))return'';return[`ALO186 Teknik Devir ve Kabul Paketi`,`Bağlam: ${CONTEXTS[pkg.context]}`,`Rol: ${ROLES[pkg.role]}`,`Sistem: ${SYSTEMS[pkg.system].label}`,`Aşama: ${STAGES[pkg.stage]}`,`Hazırlık: ${pkg.readiness}/100`,`Durum: ${pkg.status}`,`Eksik belge: ${pkg.missingEvidence.length}`,`Eksik kabul adımı: ${pkg.missingAcceptance.length}`,'','Bu paket kişisel veri, marka, fiyat, stok, satıcı, garanti veya ASIN içermez.'].join('\n')}
function buildIcs(pkg,origin='https://alo186.com'){if(!validatePackage(pkg)||!pkg.followupDays)return'';const start=new Date(new Date(pkg.createdAt).getTime()+pkg.followupDays*DAY_MS),end=new Date(start.getTime()+DAY_MS),d=d=>`${d.getUTCFullYear()}${String(d.getUTCMonth()+1).padStart(2,'0')}${String(d.getUTCDate()).padStart(2,'0')}`;return['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//ALO186//Technical Handoff//TR','BEGIN:VEVENT',`UID:${pkg.checksum}@alo186.com`,`DTSTART;VALUE=DATE:${d(start)}`,`DTEND;VALUE=DATE:${d(end)}`,'SUMMARY:ALO186 teknik devir ve kabul kontrolü',`DESCRIPTION:${SYSTEMS[pkg.system].label} için eksik belge ve kabul adımlarını yeniden kontrol edin.`, `URL:${String(origin).replace(/\/$/,'')}/hesaplama/teknik-devir-kabul-paketi/`,'END:VEVENT','END:VCALENDAR',''].join('\r\n')}
function prune(records,nowValue=new Date()){const now=nowValue instanceof Date?nowValue:new Date(nowValue);return(Array.isArray(records)?records:[]).filter(validatePackage).filter(x=>Date.parse(x.expiresAt)>now.getTime()).sort((a,b)=>Date.parse(b.createdAt)-Date.parse(a.createdAt)).slice(0,MAX_RECORDS)}
return{VERSION,MAX_RECORDS,TTL_DAYS,CONTEXTS,ROLES,STAGES,SYSTEMS,PRODUCT_CATEGORIES,EVIDENCE,sanitize,evaluate,packageRecord,validatePackage,summaryText,buildIcs,prune,hashText};
});
