(() => {
'use strict';
const core=window.Alo186ElectricalPlanCore,$=id=>document.getElementById(id);let currentPlan=null;
const KEYS={outcomes:'alo186:solution-outcomes:v1',pending:'alo186:pending-solutions:v1',reviews:'alo186_product_review_calendar_v1',maintenance:'alo186_product_maintenance_v1',outageJournal:'alo186.outageJournal.v1',savedDecision:'alo186_product_decision_v1',outageKit:'alo186:outage-kit:v1'};
function read(key,fallback){try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw):fallback;}catch(_){return fallback;}}
function snapshot(){return{outcomes:read(KEYS.outcomes,[]),pending:read(KEYS.pending,[]),reviews:read(KEYS.reviews,[]),maintenance:read(KEYS.maintenance,{}),outageJournal:read(KEYS.outageJournal,{entries:[]}),savedDecision:read(KEYS.savedDecision,null),outageKit:read(KEYS.outageKit,null)};}
function emit(name,params={}){if(typeof window.Alo186Track==='function')window.Alo186Track(name,params);}
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));}
function formatDate(value){if(!value)return'Tarih yok';const d=new Date(value);return Number.isFinite(d.getTime())?new Intl.DateTimeFormat('tr-TR',{dateStyle:'medium'}).format(d):'Tarih yok';}
function priorityLabel(value){return{critical:'P0 · Acil',high:'P1 · Öncelikli',medium:'P2 · Planla',low:'P3 · İzle'}[value]||'P2 · Planla';}
function renderMetrics(plan){$('metricHealth').textContent=`${plan.metrics.health}/100`;$('metricTasks').textContent=String(plan.metrics.taskCount);$('metricCritical').textContent=String(plan.metrics.critical);$('metricUnresolved').textContent=String(plan.metrics.unresolved);$('metricNoPurchase').textContent=String(plan.metrics.noPurchase);$('metricOutages').textContent=String(plan.metrics.outages90d);$('healthText').textContent=plan.metrics.health>=85?'Planınız dengeli görünüyor.':plan.metrics.health>=60?'Bazı takipler ve çözülmemiş kayıtlar var.':'Acil veya tekrar eden kayıtları önce ele alın.';}
function taskCard(item){return`<article class="task-card priority-${item.priority}"><div class="task-head"><span class="priority">${priorityLabel(item.priority)}</span>${item.dueAt?`<time datetime="${escapeHtml(item.dueAt)}">${escapeHtml(formatDate(item.dueAt))}</time>`:''}</div><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.detail)}</p><div class="task-meta"><span>${escapeHtml(core.categoryLabels[item.category]||item.category)}</span><span>${escapeHtml(item.source)}</span></div><a class="button secondary" href="${escapeHtml(item.route)}" data-plan-route="${escapeHtml(item.kind)}">Sonraki adımı aç →</a></article>`;}
function renderTasks(plan){$('taskList').innerHTML=plan.tasks.length?plan.tasks.map(taskCard).join(''):'<div class="empty"><strong>Bugün için açık takip görünmüyor.</strong><p>Yeni hesap, kesinti kaydı, kesinti kiti, ürün kararı veya çözüm sonucu eklediğinizde plan burada oluşur.</p></div>';$('taskList').querySelectorAll('[data-plan-route]').forEach(link=>link.addEventListener('click',()=>emit('electrical_plan_task_opened',{route:link.dataset.planRoute})));}
function renderSources(plan){const labels={outcomes:'Çözüm sonuçları',pending:'Bekleyen çözüm kontrolleri',reviews:'Ürün yeniden kontrol takvimi',maintenance:'Bakım kategorileri',outages:'Son 90 gün kesintileri',outageKit:'Kesinti kiti envanteri'};$('sourceList').innerHTML=Object.entries(plan.sourceCounts).map(([key,value])=>`<div><span>${escapeHtml(labels[key]||key)}</span><strong>${value}</strong></div>`).join('');}
function professionalText(pack){return['ALO186 Kişisel Verisiz Profesyonel Ön Değerlendirme Paketi',`Alan: ${pack.label}`,`Neden: ${pack.summary}`,'','Hazırlanacak girdiler:',...pack.checklist.map((item,index)=>`${index+1}. ${item}`),'','ALO186 resmî kurum değildir. Teknik inceleme ancak kapsam ve ücret yazılı teyit edilirse başlar.'].join('\n');}
function renderProfessional(plan){const section=$('professionalPack'),pack=plan.professionalPack;section.classList.toggle('hidden',!pack.needed);if(!pack.needed)return;$('professionalTitle').textContent=`${pack.label} için profesyonel paket`;$('professionalText').textContent=pack.summary;$('professionalChecklist').innerHTML=pack.checklist.map(item=>`<li>${escapeHtml(item)}</li>`).join('');$('professionalLink').href=pack.route;}
function download(name,content,type){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function copyProfessional(){if(!currentPlan||!currentPlan.professionalPack.needed)return;const text=professionalText(currentPlan.professionalPack);try{await navigator.clipboard.writeText(text);$('professionalStatus').textContent='Kişisel verisiz kapsam özeti kopyalandı.';}catch(_){window.prompt('Kapsam özetini kopyalayın:',text);}emit('electrical_plan_professional_pack_copied',{category:currentPlan.professionalPack.category});}
function exportPlan(){if(!currentPlan)return;download(`alo186-elektrik-planim-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(core.buildExport(currentPlan),null,2),'application/json;charset=utf-8');emit('electrical_plan_exported',{format:'json'});}
function exportCalendar(){if(!currentPlan)return;const ics=core.buildCalendar(currentPlan,location.origin);download(`alo186-elektrik-planim-${new Date().toISOString().slice(0,10)}.ics`,ics,'text/calendar;charset=utf-8');emit('electrical_plan_exported',{format:'ics'});}
function render(){if(!core){$('status').textContent='Plan motoru yüklenemedi.';return;}currentPlan=core.buildPlan(snapshot(),new Date());renderMetrics(currentPlan);renderTasks(currentPlan);renderSources(currentPlan);renderProfessional(currentPlan);$('generatedAt').textContent=`Son yerel hesap: ${new Intl.DateTimeFormat('tr-TR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(currentPlan.generatedAt))}`;emit('electrical_plan_rendered',{status:currentPlan.tasks.length?'active':'empty',critical:String(currentPlan.metrics.critical),professional_required:String(currentPlan.professionalPack.needed),outage_kit:String(currentPlan.sourceCounts.outageKit||0)});}
document.addEventListener('DOMContentLoaded',()=>{render();$('refreshBtn').addEventListener('click',render);$('exportBtn').addEventListener('click',exportPlan);$('calendarBtn').addEventListener('click',exportCalendar);$('printBtn').addEventListener('click',()=>window.print());$('copyProfessionalBtn').addEventListener('click',copyProfessional);$('professionalLink').addEventListener('click',()=>{if(currentPlan&&currentPlan.professionalPack.needed)emit('electrical_plan_professional_route_opened',{category:currentPlan.professionalPack.category});});window.addEventListener('storage',render);});
})();
