(() => {
'use strict';
const core=window.Alo186PlanGrowthCore,planCore=window.Alo186ElectricalPlanCore,$=id=>document.getElementById(id);
const KEYS={outcomes:'alo186:solution-outcomes:v1',pending:'alo186:pending-solutions:v1',reviews:'alo186_product_review_calendar_v1',maintenance:'alo186_product_maintenance_v1',outageJournal:'alo186.outageJournal.v1',savedDecision:'alo186_product_decision_v1',seasonal:'alo186:seasonal-readiness:v1',outageKit:'alo186:outage-kit:v1'};
let currentPlan=null,currentSeasonal=null,currentBrief=null;
function read(key,fallback){try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw):fallback;}catch(_){return fallback;}}
function write(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true;}catch(_){return false;}}
function snapshot(){return{outcomes:read(KEYS.outcomes,[]),pending:read(KEYS.pending,[]),reviews:read(KEYS.reviews,[]),maintenance:read(KEYS.maintenance,{}),outageJournal:read(KEYS.outageJournal,{entries:[]}),savedDecision:read(KEYS.savedDecision,null),outageKit:read(KEYS.outageKit,null)};}
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));}
function emit(name,params={}){if(typeof window.Alo186Track==='function')window.Alo186Track(name,params);}
function formatDate(value){const d=new Date(value);return Number.isFinite(d.getTime())?new Intl.DateTimeFormat('tr-TR',{dateStyle:'medium'}).format(d):'Tarih yok';}
function renderSeasonal(){currentSeasonal=core.seasonalActions(new Date());const labels={summer:'Yaz sıcakları ve kesinti yükü',winter:'Kış, batarya ve jeneratör hazırlığı',storm:'Fırtına, darbe ve uzun kesinti hazırlığı',spring:'Bahar bakım ve kapasite kontrolü'};$('seasonalTitle').textContent=labels[currentSeasonal.key];$('seasonalList').innerHTML=currentSeasonal.actions.map(action=>`<article class="season-card"><span class="mode mode-${escapeHtml(action.mode)}">${action.mode==='qualified'?'Teknik doğrulama sonrası ürün':'professional'===action.mode?'Profesyonel sınır':'Ücretsiz kontrol'}</span><h3>${escapeHtml(action.title)}</h3><p>${escapeHtml(action.detail)}</p><div class="actions"><a class="button secondary" href="${escapeHtml(action.route)}" data-season-route="${escapeHtml(action.id)}">Kontrolü aç</a><button class="button ghost" type="button" data-season-save="${escapeHtml(action.id)}">30 gün sonra hatırlat</button></div></article>`).join('');$('seasonalList').querySelectorAll('[data-season-route]').forEach(link=>link.addEventListener('click',()=>emit('seasonal_readiness_opened',{action:link.dataset.seasonRoute,season:currentSeasonal.key})));$('seasonalList').querySelectorAll('[data-season-save]').forEach(button=>button.addEventListener('click',()=>saveSeasonal(button.dataset.seasonSave)));
const reviews=core.sanitizeReviews(read(KEYS.seasonal,[]),new Date());$('seasonalReviewStatus').textContent=reviews.length?`${reviews.length} mevsimsel kontrol yalnız bu tarayıcıda saklanıyor. En yakın tarih: ${formatDate(reviews.sort((a,b)=>Date.parse(a.reviewAt)-Date.parse(b.reviewAt))[0].reviewAt)}.`:'Henüz mevsimsel takip tarihi oluşturulmadı.';
}
function saveSeasonal(id){const action=currentSeasonal.actions.find(item=>item.id===id);if(!action)return;const records=core.sanitizeReviews([core.reviewRecord(action,30,new Date()),...read(KEYS.seasonal,[])],new Date());if(write(KEYS.seasonal,records)){$('seasonalReviewStatus').textContent=`${action.title} için 30 günlük kontrol kaydı cihazınıza eklendi.`;emit('seasonal_readiness_saved',{action:id,season:currentSeasonal.key,review_days:'30'});}else $('seasonalReviewStatus').textContent='Tarayıcı kaydı kullanılamadı; tarih saklanmadı.';}
function renderBrief(){currentBrief=core.procurementBrief(snapshot(),new Date());const section=$('procurementBrief');section.dataset.status=currentBrief.status;$('briefTitle').textContent=currentBrief.available?`${currentBrief.label} için marka bağımsız teknik alım kartı`:'Marka bağımsız teknik alım kartı';if(!currentBrief.available){$('briefText').textContent='Akıllı Ürün Merkezi’nde bir kategori seçip teknik minimumları belirlediğinizde alım kartı burada oluşur.';$('briefRequirements').innerHTML='';$('briefPrimary').href='/akilli-urun-secimi';$('briefPrimary').textContent='İhtiyacı belirle';$('briefDisclosure').textContent='Fiyat, stok, puan, garanti veya marka önerisi oluşturulmaz.';return;}
const messages={ready:'Teknik minimumları üretici etiketi ve ücretsiz araçla doğruladıktan sonra karşılaştırmaya geçin.',no_buy:'Yakın sonuç geçmişi mevcut ekipman, bakım veya resmî kanalın yeterli olduğunu gösteriyor. Yeni ürün önermiyoruz.',professional:'Tekrar eden, çözülmemiş veya yüksek riskli sonuç nedeniyle genel ürün araması yerine profesyonel doğrulama gerekir.'};$('briefText').textContent=messages[currentBrief.status]||messages.ready;$('briefRequirements').innerHTML=currentBrief.requirements.map(item=>`<li>${escapeHtml(item)}</li>`).join('');$('briefPrimary').href=currentBrief.route;$('briefPrimary').textContent=currentBrief.status==='ready'?'Teknik doğrulama sonrası ürün merkezine dön':currentBrief.status==='no_buy'?'Ücretsiz aracı yeniden aç':'Kişisel verisiz profesyonel hazırlığı aç';$('briefDisclosure').textContent=currentBrief.disclosure;$('briefReview').textContent=`Yeniden kontrol: ${formatDate(currentBrief.reviewAt)}`;emit('vendor_neutral_brief_rendered',{category:currentBrief.category||'none',status:currentBrief.status,affiliate_allowed:String(currentBrief.affiliateAllowed)});
}
function buildCurrentPlan(){return planCore?planCore.buildPlan(snapshot(),new Date()):{tasks:[]};}
async function sharePlan(){currentPlan=buildCurrentPlan();const payload=core.sharePayload(currentPlan,currentSeasonal||core.seasonalActions(),currentBrief||core.procurementBrief(snapshot()));try{if(navigator.share){await navigator.share(payload);$('shareStatus').textContent='Plan cihazınızın paylaşım menüsüne gönderildi.';emit('electrical_plan_shared',{method:'native'});}else{await navigator.clipboard.writeText(`${payload.text}\n${payload.url}`);$('shareStatus').textContent='Paylaşım özeti panoya kopyalandı.';emit('electrical_plan_shared',{method:'clipboard'});}}catch(error){if(error&&error.name==='AbortError'){$('shareStatus').textContent='Paylaşım iptal edildi.';return;}try{await navigator.clipboard.writeText(`${payload.text}\n${payload.url}`);$('shareStatus').textContent='Paylaşım özeti panoya kopyalandı.';}catch(_){window.prompt('Kişisel verisiz plan özetini kopyalayın:',`${payload.text}\n${payload.url}`);}}
}
async function copyBrief(){if(!currentBrief||!currentBrief.available)return;const text=['ALO186 Marka Bağımsız Teknik Alım Kartı',`Kategori: ${currentBrief.label}`,`Durum: ${currentBrief.status}`,'','Doğrulanacak teknik minimumlar:',...currentBrief.requirements.map((item,index)=>`${index+1}. ${item}`),'',currentBrief.disclosure,'','ALO186 resmî kurum veya ürün satıcısı değildir.'].join('\n');try{await navigator.clipboard.writeText(text);$('briefStatus').textContent='Marka bağımsız teknik kart kopyalandı.';emit('vendor_neutral_brief_copied',{category:currentBrief.category,status:currentBrief.status});}catch(_){window.prompt('Teknik kartı kopyalayın:',text);}}
function init(){if(!core||!planCore){$('growthStatus').textContent='Büyüme ve tekrar ziyaret katmanı yüklenemedi.';return;}renderSeasonal();renderBrief();$('sharePlanBtn').addEventListener('click',sharePlan);$('copyBriefBtn').addEventListener('click',copyBrief);if(window.Alo186PwaInstall)window.Alo186PwaInstall.bind({button:'installBtnPlan',status:'installStatusPlan',help:'installHelpPlan',label:'ALO186’i ana ekrana ekle'});window.addEventListener('storage',()=>{renderSeasonal();renderBrief();});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
