(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.Alo186ElectricalPlanCore=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const DAY_MS=86400000,MAX_TASKS=24;
const categoryLabels={outage_official:'Kesinti ve resmî işlem',indoor_fault:'İç tesisat, pano veya priz',backup_power:'UPS, jeneratör ve yedek güç',protection:'RCD, parafudr ve gerilim koruması',solar_storage:'GES, inverter ve enerji depolama',ev_charging:'EV şarj ve wallbox',product_selection:'Tak-çalıştır ürün seçimi',business_continuity:'Otel, site ve işletme sürekliliği'};
const categoryRoutes={outage_official:'/hesaplama/kesinti-gunlugu/',indoor_fault:'/karar-motoru',backup_power:'/hesaplama/yedek-guc-cozum-secici/',protection:'/hesaplama/gerilim-koruma-cozum-secici/',solar_storage:'/hesaplama/inverter-uygunluk/',ev_charging:'/hesaplama/ev-sarj-uygunluk/',product_selection:'/akilli-urun-secimi',business_continuity:'/hesaplama/elektrik-surekliligi-olgunluk-skoru/'};
const productLabels={powerbank:'Powerbank',surge_strip:'Akım korumalı grup priz',mini_ups:'Modem/ONT mini UPS',emergency_light:'Acil aydınlatma',smoke_alarm:'Duman alarmı',power_station:'Power station',generator:'Jeneratör',inverter:'İnverter ve batarya',outlet_tester:'Priz/RCD test cihazı',smart_plug:'Akıllı priz ve enerji ölçer',ev_cable:'Type 2 EV kablosu',ups_battery:'UPS aküsü ve kartuşu'};
const productToOutcome={powerbank:'product_selection',surge_strip:'protection',mini_ups:'backup_power',emergency_light:'product_selection',smoke_alarm:'product_selection',power_station:'backup_power',generator:'backup_power',inverter:'solar_storage',outlet_tester:'protection',smart_plug:'product_selection',ev_cable:'ev_charging',ups_battery:'backup_power'};
function asDate(value){const date=value instanceof Date?value:new Date(value);return Number.isFinite(date.getTime())?date:null;}
function safeArray(value){return Array.isArray(value)?value:[];}
function daysFrom(now,value){const date=asDate(value);return date?Math.ceil((date-now)/DAY_MS):null;}
function safePath(value,fallback='/hesaplama/'){try{const url=new URL(String(value||''),'https://alo186.com');if(/^https?:\/\//i.test(String(value||''))&&!['www.alo186.com','alo186.com'].includes(url.hostname.toLowerCase()))return fallback;return /^\/[a-zA-Z0-9_\-/.?=&%]*$/.test(url.pathname+url.search)?url.pathname+url.search:fallback;}catch(_){return fallback;}}
function task(input){return{id:String(input.id||'').slice(0,80),kind:input.kind||'followup',priority:['critical','high','medium','low'].includes(input.priority)?input.priority:'medium',title:String(input.title||'Kontrol').slice(0,160),detail:String(input.detail||'').slice(0,320),route:safePath(input.route),dueAt:input.dueAt&&asDate(input.dueAt)?asDate(input.dueAt).toISOString():null,category:categoryLabels[input.category]?input.category:'product_selection',source:String(input.source||'local').slice(0,40)};}
function sanitizeOutcome(record){if(!record||typeof record!=='object')return null;const created=asDate(record.createdAt);if(!created||!categoryLabels[record.category])return null;return{...record,createdAt:created.toISOString(),dueAt:record.dueAt&&asDate(record.dueAt)?asDate(record.dueAt).toISOString():null,followupRoute:safePath(record.followupRoute,categoryRoutes[record.category])};}
function sanitizePending(record){if(!record||typeof record!=='object')return null;const ask=asDate(record.askAfter),expires=asDate(record.expiresAt);if(!ask||!expires||!categoryLabels[record.category])return null;return{...record,askAfter:ask.toISOString(),expiresAt:expires.toISOString(),recommendedPath:safePath(record.recommendedPath,categoryRoutes[record.category])};}
function sanitizeReview(record){if(!record||typeof record!=='object'||!productLabels[record.category])return null;const review=asDate(`${record.reviewDate||''}T12:00:00Z`);if(!review)return null;return{...record,reviewDate:review.toISOString()};}
function sanitizeOutageKit(record){if(!record||typeof record!=='object'||Number(record.version)!==1)return null;const created=asDate(record.createdAt),review=asDate(record.reviewAt);if(!created||!review||!['home','small_business','hotel_site'].includes(record.profile))return null;return{version:1,createdAt:created.toISOString(),reviewAt:review.toISOString(),profile:record.profile,status:['ready','verify','gaps','professional'].includes(record.status)?record.status:'verify',score:Math.max(0,Math.min(100,Number(record.score)||0)),metrics:{required:Math.max(0,Number(record.metrics&&record.metrics.required)||0),covered:Math.max(0,Number(record.metrics&&record.metrics.covered)||0),verify:Math.max(0,Number(record.metrics&&record.metrics.verify)||0),missing:Math.max(0,Number(record.metrics&&record.metrics.missing)||0),professional:Math.max(0,Number(record.metrics&&record.metrics.professional)||0),noBuy:Math.max(0,Number(record.metrics&&record.metrics.noBuy)||0)},missingCategories:safeArray(record.missingCategories).filter(item=>productLabels[item]),verifyCategories:safeArray(record.verifyCategories).filter(item=>productLabels[item]),professionalCategories:safeArray(record.professionalCategories).filter(item=>productLabels[item])};}
function recentOutageEntries(journal,now){const entries=safeArray(journal&&journal.entries);return entries.filter(entry=>{const date=asDate(`${entry.date||''}T12:00:00Z`);return date&&now-date<=90*DAY_MS&&now-date>=-DAY_MS;});}
function taskPriorityFromDays(days,high=false){if(days===null)return high?'high':'medium';if(days<0)return high?'critical':'high';if(days===0)return high?'critical':'high';if(days<=7)return high?'high':'medium';return 'low';}
function buildPlan(snapshot={},nowValue=new Date()){
 const now=asDate(nowValue)||new Date(),tasks=[];
 const outcomes=safeArray(snapshot.outcomes).map(sanitizeOutcome).filter(Boolean);
 const pending=safeArray(snapshot.pending).map(sanitizePending).filter(Boolean).filter(item=>asDate(item.expiresAt)>now);
 const reviews=safeArray(snapshot.reviews).map(sanitizeReview).filter(Boolean);
 const maintenance=snapshot.maintenance&&typeof snapshot.maintenance==='object'?snapshot.maintenance:{};
 const journal=snapshot.outageJournal&&typeof snapshot.outageJournal==='object'?snapshot.outageJournal:{entries:[]};
 const saved=snapshot.savedDecision&&typeof snapshot.savedDecision==='object'?snapshot.savedDecision:null;
 const outageKit=sanitizeOutageKit(snapshot.outageKit);
 pending.filter(item=>asDate(item.askAfter)<=now&&(!item.dismissedUntil||asDate(item.dismissedUntil)<=now)).forEach(item=>tasks.push(task({id:`pending-${item.id}`,kind:'outcome',priority:'high',title:'Bu çözüm işe yaradı mı?',detail:`${categoryLabels[item.category]} için izlediğiniz yolu sonuçlandırın.`,route:`/hesaplama/cozum-sonucu/?pending=${encodeURIComponent(item.id)}`,dueAt:item.askAfter,category:item.category,source:'pending'})));
 outcomes.forEach(item=>{const days=daysFrom(now,item.dueAt);if(item.outcome==='safety')tasks.push(task({id:`safety-${item.id}`,kind:'safety',priority:'critical',title:'Güvenlik sonucu yeniden değerlendirilmemeli',detail:`${categoryLabels[item.category]} için ürün veya normal kontrol yerine güvenli/resmî kanalı kullanın.`,route:'/karar-motoru',category:item.category,source:'outcome'}));else if(item.outcome==='unresolved'||item.outcome==='partial'||(item.dueAt&&days<=7))tasks.push(task({id:`outcome-${item.id}`,kind:'followup',priority:taskPriorityFromDays(days,item.recurrence==='multiple'||item.outcome==='unresolved'),title:item.recurrence==='multiple'?'Tekrar eden sorunu yükseltin':'Çözümü yeniden kontrol edin',detail:`${categoryLabels[item.category]} · ${item.outcome==='partial'?'Kısmi çözüm':'Çözülmedi veya takip zamanı geldi'}.`,route:item.followupRoute||categoryRoutes[item.category],dueAt:item.dueAt,category:item.category,source:'outcome'}));});
 reviews.forEach(item=>{const days=daysFrom(now,item.reviewDate);if(days<=14)tasks.push(task({id:`review-${item.id}`,kind:'review',priority:taskPriorityFromDays(days),title:`${productLabels[item.category]} yeniden kontrolü`,detail:'Teknik özellik, bakım veya katalog doğrulama tarihi geldi.',route:`/akilli-urun-secimi?kategori=${encodeURIComponent(item.category)}`,dueAt:item.reviewDate,category:productToOutcome[item.category],source:'review'}));});
 Object.entries(maintenance).forEach(([category,record])=>{if(!productLabels[category]||!record||!Array.isArray(record.checks))return;const done=record.checks.filter(Boolean).length;if(done<record.checks.length)tasks.push(task({id:`maintenance-${category}`,kind:'maintenance',priority:'medium',title:`${productLabels[category]} bakım kontrolü eksik`,detail:`${done}/${record.checks.length} madde tamamlandı. Satın alma öncesi bakım ve güvenlik kontrolünü bitirin.`,route:`/akilli-urun-secimi?kategori=${encodeURIComponent(category)}`,category:productToOutcome[category],source:'maintenance'}));});
 if(outageKit){const days=daysFrom(now,outageKit.reviewAt);if(outageKit.professionalCategories.length)tasks.push(task({id:'outage-kit-professional',kind:'professional',priority:'high',title:'Kesinti kiti için profesyonel süreklilik planı gerekli',detail:`${outageKit.professionalCategories.length} kategori genel ürün karşılaştırmasına uygun değil. Kritik yük, transfer ve bakım planını birlikte doğrulayın.`,route:'/kurumsal-elektrik-surekliligi-on-degerlendirme?source=outage_kit',dueAt:outageKit.reviewAt,category:'business_continuity',source:'outage_kit'}));else if(outageKit.missingCategories.length)tasks.push(task({id:'outage-kit-missing',kind:'outage_kit',priority:'medium',title:'Kesinti kitindeki eksik işlevleri doğrulayın',detail:`${outageKit.missingCategories.length} kategori eksik görünüyor. Ürün aramadan önce her kategori için ücretsiz teknik aracı tamamlayın.`,route:'/hesaplama/elektrik-kesintisi-kiti/',dueAt:outageKit.reviewAt,category:'backup_power',source:'outage_kit'}));else if(outageKit.verifyCategories.length)tasks.push(task({id:'outage-kit-verify',kind:'outage_kit',priority:taskPriorityFromDays(days),title:'Mevcut kesinti ekipmanını gerçek yükte test edin',detail:`${outageKit.verifyCategories.length} kategoride ürün var ancak kapasite veya güvenlik doğrulanmadı.`,route:'/hesaplama/elektrik-kesintisi-kiti/',dueAt:outageKit.reviewAt,category:'backup_power',source:'outage_kit'}));else if(days<=14)tasks.push(task({id:'outage-kit-review',kind:'outage_kit',priority:taskPriorityFromDays(days),title:'Kesinti kitini yeniden kontrol edin',detail:'Mevcut ekipman daha önce yeterliydi; pil, runtime, test ve fiziksel durumunu yeniden doğrulayın.',route:'/hesaplama/elektrik-kesintisi-kiti/',dueAt:outageKit.reviewAt,category:'backup_power',source:'outage_kit'}));}
 const recentEntries=recentOutageEntries(journal,now),damage=recentEntries.filter(entry=>entry.deviceDamage),long=recentEntries.filter(entry=>Number(entry.durationMinutes)>=720);
 if(damage.length)tasks.push(task({id:'outage-damage',kind:'official',priority:'critical',title:'Cihaz hasarı belgesini gecikmeden hazırlayın',detail:`Son 90 günde ${damage.length} cihaz hasarı şüphesi kaydı var. 30 günlük resmî başvuru süresini kontrol edin.`,route:'/haberler/elektrik-kesintisi-cihaz-hasari-edas-basvurusu',category:'outage_official',source:'outage'}));
 if(long.length)tasks.push(task({id:'outage-long',kind:'official',priority:'high',title:'Uzun kesinti kayıtlarını resmî kanalla doğrulayın',detail:`${long.length} kayıt 12 saati aşıyor; otomatik hak sonucu değildir.`,route:'/hesaplama/kesinti-gunlugu/',category:'outage_official',source:'outage'}));
 if(saved&&saved.category&&productLabels[saved.category]&&saved.reviewAt){const days=daysFrom(now,saved.reviewAt);if(days<=7)tasks.push(task({id:'saved-decision',kind:'review',priority:taskPriorityFromDays(days),title:'Son ürün kararını yeniden doğrulayın',detail:`${productLabels[saved.category]} için teknik minimumlar değişmiş olabilir.`,route:`/akilli-urun-secimi?kategori=${encodeURIComponent(saved.category)}`,dueAt:saved.reviewAt,category:productToOutcome[saved.category],source:'saved_decision'}));}
 const order={critical:0,high:1,medium:2,low:3};tasks.sort((a,b)=>order[a.priority]-order[b.priority]||(Date.parse(a.dueAt||'2999-01-01')-Date.parse(b.dueAt||'2999-01-01')));
 const cleanTasks=tasks.slice(0,MAX_TASKS);
 const unresolved=outcomes.filter(item=>item.outcome==='unresolved'||item.outcome==='partial');
 const repeated=outcomes.filter(item=>item.recurrence==='multiple');
 const noPurchase=outcomes.filter(item=>['no_purchase','existing'].includes(item.purchase)||['official_channel','maintenance','existing_equipment'].includes(item.action));
 const professionalCategories={};unresolved.forEach(item=>{if(item.recurrence==='multiple'||['indoor_fault','backup_power','protection','solar_storage','ev_charging','business_continuity'].includes(item.category))professionalCategories[item.category]=(professionalCategories[item.category]||0)+1;});
 if(outageKit&&outageKit.professionalCategories.length)professionalCategories.business_continuity=(professionalCategories.business_continuity||0)+outageKit.professionalCategories.length;
 const topProfessional=Object.keys(professionalCategories).sort((a,b)=>professionalCategories[b]-professionalCategories[a])[0]||null;
 const professionalPack=topProfessional?{needed:true,category:topProfessional,label:categoryLabels[topProfessional],reasonCount:professionalCategories[topProfessional],route:professionalRoute(topProfessional),summary:`${categoryLabels[topProfessional]} alanında ${professionalCategories[topProfessional]} çözülmemiş, tekrar eden veya kit düzeyinde profesyonel sonuç ön değerlendirme için hazırlandı.`,checklist:professionalChecklist(topProfessional)}:{needed:false,category:null,label:'Profesyonel paket gerekmiyor',reasonCount:0,route:'/kurumsal-elektrik-surekliligi-on-degerlendirme',summary:'Tekrar eden yüksek riskli sonuç bulunmadı.',checklist:[]};
 const critical=cleanTasks.filter(item=>item.priority==='critical').length,high=cleanTasks.filter(item=>item.priority==='high').length;
 const health=Math.max(0,Math.min(100,100-critical*20-high*8-unresolved.length*5-repeated.length*7-(outageKit?outageKit.metrics.missing*2+outageKit.metrics.professional*5:0)));
 return{tasks:cleanTasks,metrics:{taskCount:cleanTasks.length,critical,high,unresolved:unresolved.length,repeated:repeated.length,noPurchase:noPurchase.length+(outageKit?outageKit.metrics.noBuy:0),outages90d:recentEntries.length,health},professionalPack,sourceCounts:{outcomes:outcomes.length,pending:pending.length,reviews:reviews.length,maintenance:Object.keys(maintenance).length,outages:recentEntries.length,outageKit:outageKit?1:0},generatedAt:now.toISOString()};
}
function professionalRoute(category){const map={indoor_fault:['genel_risk','saha_inceleme'],backup_power:['yedek_guc','karsilastirma'],protection:['genel_risk','saha_inceleme'],solar_storage:['ges_batarya','karsilastirma'],ev_charging:['ev_sarj','saha_inceleme'],business_continuity:['yedek_guc','uzaktan_dokuman']};const pair=map[category]||['genel_risk','uzaktan_dokuman'];return`/kurumsal-elektrik-surekliligi-on-degerlendirme?source=elektrik_planim&problem=${pair[0]}&scope=${pair[1]}`;}
function professionalChecklist(category){const base=['Sonuç ve tekrar geçmişinin kişisel verisiz özeti','İlgili üretici kılavuzu veya teknik veri sayfası','Varsa tarih-saat ve güvenli gözlem kaydı'];const extra={indoor_fault:'Yetkili ölçüm ve pano/tesisat kontrol sonuçları',backup_power:'Kritik yük, sürekli/tepe güç ve runtime kaydı',protection:'Gerilim, RCD/SPD ve topraklama ölçüm sonuçları',solar_storage:'İnverter event kodu, string/AC değerleri ve sıcaklık kaydı',ev_charging:'Araç AC sınırı, wallbox logu ve faz/akım bilgisi',business_continuity:'Tek hat, kritik yük listesi ve jeneratör/UPS test kaydı'};return[...base,extra[category]||'İlgili teknik ölçüm sonuçları'];}
function buildExport(plan){return{schema:'alo186-electrical-plan-v1',privacy:'Kişisel veri, açık adres, abonelik, cihaz modeli, fiyat, satıcı veya serbest metin içermez.',generatedAt:plan.generatedAt,metrics:plan.metrics,tasks:plan.tasks,professionalPack:plan.professionalPack,sourceCounts:plan.sourceCounts};}
function escapeIcs(value){return String(value||'').replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');}
function dateOnly(value){const d=asDate(value)||new Date();return`${d.getUTCFullYear()}${String(d.getUTCMonth()+1).padStart(2,'0')}${String(d.getUTCDate()).padStart(2,'0')}`;}
function buildCalendar(plan,origin='https://alo186.com'){const events=plan.tasks.filter(item=>item.dueAt).slice(0,12).map(item=>{const start=dateOnly(item.dueAt),end=dateOnly(new Date(Date.parse(item.dueAt)+DAY_MS)),url=`${String(origin).replace(/\/$/,'')}${safePath(item.route)}`;return['BEGIN:VEVENT',`UID:${escapeIcs(item.id)}@alo186.com`,`DTSTART;VALUE=DATE:${start}`,`DTEND;VALUE=DATE:${end}`,`SUMMARY:${escapeIcs(item.title)}`,`DESCRIPTION:${escapeIcs(item.detail+' ALO186 kişisel veri tutmaz.')}`,`URL:${escapeIcs(url)}`,'TRANSP:TRANSPARENT','END:VEVENT'].join('\r\n');});return['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//ALO186//Electrical Plan//TR','CALSCALE:GREGORIAN',...events,'END:VCALENDAR',''].join('\r\n');}
return{DAY_MS,MAX_TASKS,categoryLabels,categoryRoutes,productLabels,productToOutcome,safePath,sanitizeOutageKit,buildPlan,buildExport,buildCalendar,professionalRoute,professionalChecklist};
});
