(() => {
'use strict';
const core=window.Alo186OutageKitCore,$=id=>document.getElementById(id);let current=null;const gateKey='alo186:outage-kit-tool-gates:v1';
function emit(name,params={}){if(typeof window.Alo186Track==='function')window.Alo186Track(name,params);}
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));}
function readJson(key,fallback){try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback));}catch(_){return fallback;}}
function writeJson(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true;}catch(_){return false;}}
function readForm(){const inventory={};document.querySelectorAll('[data-inventory]').forEach(select=>inventory[select.dataset.inventory]=select.value);return{profile:$('profile').value,outageHours:Number($('outageHours').value),needs:[...document.querySelectorAll('input[name="need"]:checked')].map(input=>input.value),inventory};}
function statusText(status){return{covered:'Mevcut ve yeterli',verify:'Önce ücretsiz test',missing:'Eksik işlev',professional:'Profesyonel plan'}[status]||status;}
function statusDescription(item){if(item.status==='covered')return'Gerçek kullanımda yeterli olduğunu belirttiniz. Yeni ürün önermiyoruz; bakım ve periyodik test yeterlidir.';if(item.status==='verify')return'Ürün var, ancak kapasite veya güvenlik doğrulanmadı. Yeni ürün aramadan önce ücretsiz teknik aracı tamamlayın.';if(item.status==='professional')return item.professionalReason;return'Bu işlev eksik görünüyor. Önce ücretsiz teknik aracı tamamlayın; yalnız teknik eksik doğrulanırsa ürün merkezine ilerleyin.';}
function itemCard(item){const criteria=item.criteria.map(value=>`<li>${escapeHtml(value)}</li>`).join('');let actions='';if(item.status==='covered'){actions=`<a class="button secondary" href="/hesaplama/ekipman-bakim-plani/" data-kit-route="maintenance">Bakım planını aç</a>`;}else if(item.status==='professional'){actions=`<a class="button primary" href="/kurumsal-elektrik-surekliligi-on-degerlendirme?source=outage_kit&category=${encodeURIComponent(item.id)}" data-kit-route="professional">Kişisel verisiz profesyonel hazırlığı aç</a>`;}else if(item.status==='verify'){actions=`<a class="button primary" href="${escapeHtml(item.toolRoute)}" data-kit-route="verify" data-tool-id="${escapeHtml(item.id)}">Ücretsiz teknik testi aç</a>`;}else{actions=`<a class="button primary" href="${escapeHtml(item.toolRoute)}" data-kit-route="tool" data-tool-id="${escapeHtml(item.id)}">1. Ücretsiz teknik testi aç</a><div class="gate"><label><input type="checkbox" data-tool-confirm="${escapeHtml(item.id)}"><span>Teknik aracı tamamladım; mevcut ekipmanın yetersiz olduğunu doğruladım.</span></label><a class="button secondary affiliate-link" href="${escapeHtml(item.productRoute)}" data-kit-route="affiliate" data-affiliate-category="${escapeHtml(item.id)}" hidden>2. Şeffaf ürün merkezinde karşılaştır</a></div>`;}return`<article class="kit-item" data-status="${escapeHtml(item.status)}"><div class="item-head"><h3>${escapeHtml(item.label)}</h3><span class="status ${escapeHtml(item.status)}">${escapeHtml(statusText(item.status))}</span></div><p>${escapeHtml(statusDescription(item))}</p><ul>${criteria}</ul><div class="item-actions">${actions}</div></article>`;}
function applySavedGates(){const gates=readJson(gateKey,{});document.querySelectorAll('[data-tool-confirm]').forEach(box=>{box.checked=Boolean(gates[box.dataset.toolConfirm]);toggleAffiliate(box);});}
function toggleAffiliate(box){const link=box.closest('.gate')?.querySelector('.affiliate-link');if(link)link.hidden=!box.checked;}
function bindResults(){document.querySelectorAll('[data-tool-confirm]').forEach(box=>box.addEventListener('change',()=>{const gates=readJson(gateKey,{});gates[box.dataset.toolConfirm]=box.checked;writeJson(gateKey,gates);toggleAffiliate(box);emit('outage_kit_affiliate_gate_changed',{category:box.dataset.toolConfirm,status:box.checked?'confirmed':'closed'});}));document.querySelectorAll('[data-kit-route]').forEach(link=>link.addEventListener('click',()=>emit('outage_kit_route_opened',{route:link.dataset.kitRoute,category:link.dataset.affiliateCategory||link.dataset.toolId||'general'})));}
function render(result){current=result;$('results').classList.remove('hidden');$('scoreValue').textContent=`${result.score}/100`;$('metricRequired').textContent=String(result.metrics.required);$('metricCovered').textContent=String(result.metrics.covered);$('metricVerify').textContent=String(result.metrics.verify);$('metricMissing').textContent=String(result.metrics.missing);$('metricProfessional').textContent=String(result.metrics.professional);const titles={ready:'Kesinti kitiniz temel işlevleri karşılıyor',verify:'Mevcut ekipmanı önce test edin',gaps:'Eksik işlevleri teknik araçla doğrulayın',professional:'Genel ürün listesi yerine profesyonel plan gerekli'};$('resultTitle').textContent=titles[result.status];$('resultText').textContent=result.status==='ready'?'Yeni ürün önermiyoruz. Mevcut ekipmanı bakım ve gerçek süre testiyle koruyun.':result.status==='professional'?'Tıbbi, tesis veya kritik işletme yükü nedeniyle genel affiliate ürün rotası kapatıldı. Düşük riskli mevcut ekipman yine envanterde korunur.':'Yalnız eksik veya kapasitesi belirsiz işlevler listelendi. Bir ürün sınıfının “yok” olması, teknik aracı tamamlamadan satın alma gerekçesi değildir.';$('itemList').innerHTML=result.items.map(itemCard).join('');applySavedGates();bindResults();$('results').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});emit('outage_kit_rendered',{status:result.status,score:String(result.score),missing:String(result.metrics.missing),professional:String(result.metrics.professional)});}
async function warmOffline(){if(!('caches'in window))return false;try{const names=await caches.keys(),active=names.find(name=>name.startsWith('alo186-emergency-'));if(!active)return false;const cache=await caches.open(active);await Promise.allSettled(['/hesaplama/elektrik-kesintisi-kiti/','/hesaplama/elektrik-planim/','/karar-motoru/','/hesaplama/cozum-sonucu/'].map(route=>cache.add(route)));emit('outage_kit_offline_cached',{status:'ready'});return true;}catch(_){return false;}}
async function save(){if(!current)return;const saved=core.record(current.input,new Date());if(writeJson(core.STORAGE_KEY,saved)){const offline=await warmOffline();$('resultStatus').textContent=`Kit bu cihazda saklandı. ${core.REVIEW_DAYS} gün sonra Elektrik Planım içinde yeniden kontrol edilecek.${offline?' Kritik rotalar çevrimdışı önbelleğe alındı.':''}`;emit('outage_kit_saved',{status:saved.status,score:String(saved.score),review_days:String(core.REVIEW_DAYS),offline:String(offline)});}else $('resultStatus').textContent='Tarayıcı kaydı kullanılamadı; kit yalnız bu oturumda görüntüleniyor.';}
async function copyBrief(){if(!current)return;const text=core.brief(current);try{await navigator.clipboard.writeText(text);$('resultStatus').textContent='Marka bağımsız kesinti kiti şartnamesi kopyalandı.';}catch(_){window.prompt('Şartnameyi kopyalayın:',text);}emit('outage_kit_brief_copied',{status:current.status});}
async function share(){if(!current)return;const payload=core.sharePayload(current);try{if(navigator.share){await navigator.share(payload);$('resultStatus').textContent='Kişisel verisiz kit özeti paylaşım menüsüne gönderildi.';emit('outage_kit_shared',{method:'native'});}else{await navigator.clipboard.writeText(`${payload.text}\n${payload.url}`);$('resultStatus').textContent='Kit özeti panoya kopyalandı.';emit('outage_kit_shared',{method:'clipboard'});}}catch(error){if(error&&error.name==='AbortError'){$('resultStatus').textContent='Paylaşım iptal edildi.';return;}window.prompt('Kişisel verisiz kit özetini kopyalayın:',`${payload.text}\n${payload.url}`);}}
function loadSaved(){const saved=readJson(core.STORAGE_KEY,null);if(!core.isValidRecord(saved))return;$('profile').value=saved.profile;$('outageHours').value=String(saved.outageHours);document.querySelectorAll('input[name="need"]').forEach(input=>input.checked=saved.needs.includes(input.value));document.querySelectorAll('[data-inventory]').forEach(select=>select.value=saved.inventory[select.dataset.inventory]||'missing');render(core.evaluate(saved));$('formStatus').textContent='Bu cihazdaki son kesinti kiti açıldı.';}
function init(){if(!core){$('formStatus').textContent='Kesinti kiti motoru yüklenemedi.';return;}$('kitForm').addEventListener('submit',event=>{event.preventDefault();const input=readForm();if(!input.needs.length){$('formStatus').textContent='En az bir kritik ihtiyacı seçin.';return;}$('formStatus').textContent='';render(core.evaluate(input));});$('saveBtn').addEventListener('click',save);$('copyBtn').addEventListener('click',copyBrief);$('shareBtn').addEventListener('click',share);if(window.Alo186PwaInstall)window.Alo186PwaInstall.bind({button:'installBtn',status:'installStatus',help:'installHelp',label:'ALO186’i ana ekrana ekle'});loadSaved();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
