(()=>{'use strict';
const $=id=>document.getElementById(id),KEY='alo186_pv_cleaning_journal_v1',TTL=730*86400000,MAX=24;
const today=()=>new Date().toISOString().slice(0,10);$('date').value=today();
function load(){let x=[];try{x=JSON.parse(localStorage.getItem(KEY)||'[]')}catch(_){x=[]}const now=Date.now();x=x.filter(r=>r&&now-r.createdAt<TTL).slice(-MAX);localStorage.setItem(KEY,JSON.stringify(x));return x}
function save(x){localStorage.setItem(KEY,JSON.stringify(x.slice(-MAX)))}
function label(id){const el=$(id);return el.options[el.selectedIndex].textContent}
function render(){const x=load(),box=$('records');if(!x.length){box.innerHTML='<p class="small">Henüz kayıt yok.</p>';return}box.replaceChildren(...x.slice().reverse().map(r=>{const d=document.createElement('div');d.className='record';const s=document.createElement('strong');s.textContent=`${r.date} · ${r.recordLabel}`;const p=document.createElement('p');p.className='small';p.textContent=`${r.soilingLabel} · ${r.performanceLabel} · ${r.decision}`;d.append(s,p);return d}))}
function evaluate(r){let level='good',labelText='Temizlik gereği doğrulanmadı',title='Mevcut kayıt temizlik zorunluluğu göstermiyor.',summary='Karşılaştırılabilir performans kaybı yoksa yalnız takvim nedeniyle temizlik yapmayın.',steps=['Aylık kWh/kWp ve veri tamlığını izlemeye devam edin.','Yerel kirlenme ve gölgeyi güvenli noktadan görsel olarak kontrol edin.'],route='İzle / satın alma yok';
if(r.hazard){level='bad';labelText='Temizlik yapmayın';title='Elektriksel veya fiziksel hasar işareti var.';summary='Kırık modül, ark izi, hotspot, açık konnektör veya kablo hasarı temizlikle giderilmez.';steps=['Sisteme yaklaşmadan güvenli izolasyon ve yetkili PV incelemesi planlayın.','Termografi, izolasyon ve string ölçümüyle kök nedeni ayırın.'];route='Profesyonel güvenlik incelemesi'}
else if(r.access==='roof-unsafe'||(r.access==='roof-safe'&&!r.professional)){level='bad';labelText='Erişim güvenliği eksik';title='Çatı erişimi doğrulanmadan temizlik yapılmamalıdır.';summary='Düşme riski ve DC elektrik riski, üretim kazancından önce gelir.';steps=['Profesyonel erişim ve düşmeye karşı koruma planı oluşturun.','Tüketici tipi temizlik ekipmanı satın alarak bu eksikliği kapatmayın.'];route='Profesyonel O&M'}
else if(!r.comparable&&r.performance!=='none'){level='warn';labelText='Veri karşılaştırması eksik';title='Düşüş sinyali var ancak dönem ve hava koşulları karşılaştırılabilir değil.';summary='Temizlikten önce ışınım, sıcaklık, kesinti, curtailment ve inverter olaylarını ayırın.';steps=['GES aylık üretim sağlık günlüğünü tamamlayın.','Aynı ay önceki yıl veya onaylı modelle karşılaştırın.'];route='Veri doğrulama'}
else if(r.performance==='repeated'&&(r.soiling==='heavy'||r.soiling==='localized')&&r.manual){level='warn';labelText='Kontrollü temizlik adayı';title='Tekrarlayan performans sinyali ve görünür kirlenme birlikte doğrulandı.';summary='Güvenli erişim ve üretici yöntemiyle temizlik planlanabilir; öncesi ve sonrası normalize edilmiş veriyi kaydedin.';steps=['Temizlik öncesi referans üretimi kaydedin.','Aşındırıcı kuru fırça, yüksek basınç veya kimyasalı üretici onayı olmadan kullanmayın.','Temizlik sonrası aynı koşullarda toparlanmayı doğrulayın.'];route='Kanıtlı O&M'}
else if((r.soiling==='heavy'||r.soiling==='localized')&&!r.manual){level='warn';labelText='Üretici yöntemi gerekli';title='Kirlenme görünür ancak güvenli temizlik yöntemi doğrulanmadı.';summary='Cam kaplama, su kalitesi, fırça ve kimyasal sınırlarını tam modül talimatından kontrol edin.';steps=['Üretici talimatı olmadan aşındırıcı yöntem kullanmayın.'];route='Talimat doğrulama'}
else if(r.performance==='first'){level='warn';labelText='İlk sinyal';title='Tek karşılaştırılabilir düşüş, temizlik zorunluluğu değildir.';summary='Bir sonraki karşılaştırılabilir dönemi ve görünür kirlenmeyi izleyin.';steps=['İnverter alarmı, string farkı, gölge ve veri eksikliğini kontrol edin.'];route='Tekrar ölçüm'}
else if(r.performance==='recovered'){labelText='Toparlanma kaydı';title='Temizlik sonrası toparlanma kaydedildi.';summary='Aynı koşullarda sürdürülebilir toparlanma görülüyorsa temizlik aralığını tesis verisine göre güncelleyin.';steps=['Tek günlük artışı kalıcı kazanım saymayın.','Bir sonraki kirlenme döngüsünü aynı metriklerle takip edin.'];route='Periyodu veriden üret'}
return{level,labelText,title,summary,steps,route}}
$('form').addEventListener('submit',e=>{e.preventDefault();const ref=Number($('reference').value),cur=Number($('current').value),hasMetric=Number.isFinite(ref)&&ref>0&&Number.isFinite(cur)&&cur>=0;const delta=hasMetric?(cur-ref)/ref*100:null;const r={createdAt:Date.now(),date:$('date').value||today(),recordType:$('recordType').value,recordLabel:label('recordType'),access:$('access').value,accessLabel:label('access'),soiling:$('soiling').value,soilingLabel:label('soiling'),performance:$('performance').value,performanceLabel:label('performance'),rain:$('rain').value,rainLabel:label('rain'),reference:hasMetric?ref:null,current:hasMetric?cur:null,deltaPct:delta,comparable:$('comparable').checked,manual:$('manual').checked,hazard:$('hazard').checked,professional:$('professional').checked,retentionMode:'per-record',officialAcceptance:false,affiliateLinks:0};const out=evaluate(r);r.decision=out.labelText;const all=load();all.push(r);save(all);render();$('result').classList.remove('hidden');$('state').textContent=out.labelText;$('state').className=`pill ${out.level}`;$('title').textContent=out.title;$('summary').textContent=out.summary;$('delta').textContent=delta===null?'Metrik girilmedi':`%${delta.toLocaleString('tr-TR',{maximumFractionDigits:1})}`;$('route').textContent=out.route;$('steps').replaceChildren(...out.steps.map(t=>{const li=document.createElement('li');li.textContent=t;return li}));$('result').scrollIntoView({behavior:'smooth',block:'start'})});
$('export').addEventListener('click',()=>{const data={tool:'ALO186 GES panel temizlik karar günlüğü',exportedAt:new Date().toISOString(),rawPersonalDataCollected:false,financialFieldsUsed:false,records:load()};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='alo186-ges-panel-temizlik-gunlugu.json';a.click();URL.revokeObjectURL(a.href)});
$('calendar').addEventListener('click',()=>{const d=new Date();d.setDate(d.getDate()+30);const fmt=x=>x.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z/,'Z');const ics=`BEGIN:VCALENDAR\nVERSION:2.0\nPRODID:-//ALO186//PV Cleaning Review//TR\nBEGIN:VEVENT\nUID:${Date.now()}@alo186.com\nDTSTAMP:${fmt(new Date())}\nDTSTART:${fmt(d)}\nSUMMARY:GES kirlenme ve üretim karşılaştırması\nDESCRIPTION:Karşılaştırılabilir kWh/kWp, görünür kirlenme ve güvenli erişim koşullarını yeniden değerlendirin.\nEND:VEVENT\nEND:VCALENDAR`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([ics],{type:'text/calendar'}));a.download='ges-temizlik-kontrol.ics';a.click();URL.revokeObjectURL(a.href)});
render()})();
