'use strict';
const assert=require('node:assert/strict');
const tool=require('./app.js');
const base={heatEmergency:false,electricalDanger:false,activeOutage:false,useCase:'single_room',physicalCondition:'good',manualVerified:true,labelVerified:true,exhaustOutside:'yes',windowEgressRisk:false,hoseManufacturerCompatible:true,hoseExtended:false,windowSealVerified:true,connection:'direct_grounded',rcdVerified:true,voltage:230,inputW:1150,ratedA:5.5,outletMaxA:16,breakerA:16,condensateSafe:true,existingUnit:false,realCoolingTest:false,noHeat:true,hoursPerDay:8,days:30,confirmNeed:false,confirmManual:false,confirmAffiliate:false};
assert.equal(tool.decide({...base,heatEmergency:true}).code,'medical_emergency');
assert.equal(tool.decide({...base,electricalDanger:true}).code,'electrical_danger');
assert.equal(tool.decide({...base,activeOutage:true}).code,'active_outage');
assert.equal(tool.decide({...base,useCase:'commercial'}).code,'professional_scope');
assert.equal(tool.decide({...base,manualVerified:false}).code,'evidence');
assert.equal(tool.decide({...base,exhaustOutside:'no'}).code,'no_exhaust');
assert.equal(tool.decide({...base,windowEgressRisk:true}).code,'egress');
assert.equal(tool.decide({...base,hoseExtended:true}).code,'hose');
assert.equal(tool.decide({...base,windowSealVerified:false}).code,'seal');
assert.equal(tool.decide({...base,connection:'extension'}).code,'electrical_connection');
assert.equal(tool.decide({...base,outletMaxA:5}).code,'overload');
assert.equal(tool.decide({...base,condensateSafe:false}).code,'condensate');
assert.equal(tool.decide({...base,existingUnit:true,realCoolingTest:true}).code,'no_buy');
assert.equal(tool.decide(base).code,'confirm');
assert.equal(tool.decide({...base,confirmNeed:true,confirmManual:true,confirmAffiliate:true}).code,'eligible_portable_ac');
const accessory=tool.decide({...base,existingUnit:true,windowSealVerified:false,confirmNeed:true,confirmManual:true,confirmAffiliate:true});assert.equal(accessory.code,'seal');
const calc=tool.calculate(base);assert.equal(calc.currentFromW,5);assert.equal(calc.workingA,5.5);assert.equal(calc.plannedA,6.88);assert.equal(calc.kwh,276);
console.log(JSON.stringify({ok:true,route:tool.ROUTE,noBuy:true,exhaustRequired:true,directOutlet:true,kwhWithoutTariff:true}));