#!/usr/bin/env python3
"""Build CardHit-3 card-linked OOF rows from official TJK block CSV pairs.

The output directly closes the missing-artifact contract:

    date, card_id, leg, betting_interest, winner,
    agf_prob, ganyan_prob, conditional_prob,
    pairwise_prob, lambdamart_prob

Implementation rules
--------------------
* The result CSV first column is finish order, never the program number.
* Result rows are joined to program rows by date/track/race/normalised horse.
* Coupled horses are collapsed into one coupon betting interest.
* Entity-history features use dates strictly earlier than the prediction date;
  all meetings on the same day are snapshotted before that day's results update
  the feature state.
* OOF probabilities are generated by expanding date folds. No row is predicted
  by a model trained on the same date or a future date.
* Historical Ganyan is the final pre-off market quote from the official result
  export. It is explicitly labelled so it is not confused with an early live
  quote used on a future card.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import re
import unicodedata
from collections import defaultdict, deque
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any, Iterable

import numpy as np
import pandas as pd
from lightgbm import LGBMRanker, early_stopping, log_evaluation
from scipy.special import softmax
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

EPS = 1e-12
RACE_HEADER = re.compile(r"\s*(\d+)\.\s*(?:Kosu|Koşu)\s*:", re.I)
AGF_VALUE = re.compile(r"%\s*([0-9]+(?:[.,][0-9]+)?)")
COUNTRY_TAG = re.compile(
    r"\s*\((?:USA|IRE|GB|FR|AUS|JPN|RU|GER|ITY|CAN|ARG|BRZ|NZ|SAF)\)", re.I
)
EQUIPMENT = {
    "KG", "K", "DB", "SK", "SKG", "GKR", "SGKR", "ÖG", "OG", "BB",
    "YP", "GB", "DS", "AP", "A", "B", "D",
}


@dataclass
class State:
    starts: int = 0
    wins: int = 0
    top3: int = 0
    finish_sum: float = 0.0
    recent: deque[int] = field(default_factory=lambda: deque(maxlen=8))
    last_date: pd.Timestamp | None = None


@dataclass
class ProgramRunner:
    number: int
    raw_name: str
    age_text: str
    sire: str
    dam: str
    weight_text: str
    jockey: str
    owner: str
    trainer: str
    gate_text: str
    agf_text: str
    hp_text: str
    recent: str
    kgs_text: str
    s20_text: str
    best_text: str
    scratch: bool

    @property
    def match_name(self) -> str:
        return horse_core(self.raw_name)

    @property
    def agf_tokens(self) -> list[float]:
        return [float(value.replace(",", ".")) / 100.0 for value in AGF_VALUE.findall(self.agf_text)]


@dataclass
class ProgramRace:
    number: int
    distance: float
    surface: str
    description: str
    runners: list[ProgramRunner] = field(default_factory=list)
    coupled_groups: list[list[int]] = field(default_factory=list)


@dataclass
class ResultRunner:
    finish: int
    raw_name: str
    ganyan_odds: float
    result_agf: float

    @property
    def match_name(self) -> str:
        return horse_core(self.raw_name)


def normalized_text(value: str) -> str:
    value = unicodedata.normalize("NFKC", value or "").upper()
    value = value.replace("(KOŞMAZ)", "")
    value = re.sub(r"\(\d+\)", "", value)
    value = COUNTRY_TAG.sub("", value)
    return " ".join(value.split())


def horse_core(value: str) -> str:
    tokens = normalized_text(value).split()
    while tokens and tokens[-1] in EQUIPMENT:
        tokens.pop()
    return " ".join(tokens)


def ascii_code(value: str, modulo: int = 1_000_003) -> float:
    text = unicodedata.normalize("NFKD", str(value or ""))
    text = "".join(ch for ch in text if not unicodedata.combining(ch))
    total = 0
    for index, char in enumerate(text.upper(), start=1):
        total = (total * 131 + index * ord(char)) % modulo
    return float(total)


def first_number(value: str) -> float:
    match = re.search(r"-?\d+(?:[.,]\d+)?", value or "")
    return float(match.group().replace(",", ".")) if match else math.nan


def time_seconds(value: str) -> float:
    match = re.search(r"(\d+)[:.](\d{2})[.:](\d{2})", value or "")
    if not match:
        return math.nan
    return int(match.group(1)) * 60 + int(match.group(2)) + int(match.group(3)) / 100.0


def parse_recent(value: str) -> dict[str, float]:
    compact = re.sub(r"\s+", "", value or "")
    positions: list[int] = []
    for char in compact:
        if char.isdigit():
            positions.append(10 if char == "0" else int(char))
    positions = positions[-6:]
    return {
        "declared_recent_count": float(len(positions)),
        "declared_recent_mean_finish": float(np.mean(positions)) if positions else 9.0,
        "declared_recent_top3_rate": float(np.mean([x <= 3 for x in positions])) if positions else 0.0,
        "declared_recent_win_rate": float(np.mean([x == 1 for x in positions])) if positions else 0.0,
        "declared_recent_best": float(min(positions)) if positions else 9.0,
    }


def parse_couplings(lines: Iterable[str]) -> list[list[int]]:
    groups: list[list[int]] = []
    for line in lines:
        if "eküri" not in line.lower() and "ekuri" not in line.lower():
            continue
        clauses = re.split(r"ek[uü]ridir\.?", line, flags=re.I)
        for clause in clauses[:-1]:
            start = clause.rfind("[")
            fragment = clause[start:] if start >= 0 else clause
            numbers = list(dict.fromkeys(int(value) for value in re.findall(r"\((\d+)\)", fragment)))
            if len(numbers) >= 2:
                groups.append(numbers)
    return groups


def parse_program(path: Path) -> tuple[dict[int, ProgramRace], int | None, int | None]:
    races: dict[int, ProgramRace] = {}
    current: ProgramRace | None = None
    in_table = False
    footer: list[str] = []
    first_start = second_start = None
    text = path.read_text(encoding="utf-8-sig", errors="replace")
    for line in text.splitlines():
        row = next(csv.reader([line], delimiter=";"))
        if not row:
            in_table = False
            continue
        first = row[0].strip()
        header = RACE_HEADER.match(first)
        if header:
            if current is not None:
                current.coupled_groups = parse_couplings(footer)
            race_no = int(header.group(1))
            joined = ";".join(row)
            distances = [int(x) for x in re.findall(r"(?<![\d.])(\d{3,4})m", joined, flags=re.I)]
            distance = float(distances[-1]) if distances else math.nan
            surface = (
                "KUM" if re.search(r"\bKum\b", joined, re.I)
                else "CIM" if re.search(r"\bÇim\b|\bCim\b", joined, re.I)
                else "SENTETIK" if re.search(r"Sentetik", joined, re.I)
                else "UNKNOWN"
            )
            current = ProgramRace(race_no, distance, surface, joined)
            races[race_no] = current
            in_table = False
            footer = []
            continue
        if first == "At No":
            in_table = True
            continue
        if current is None:
            continue
        marker = normalized_text(line).replace("’", "'")
        if re.search(r"1\.\s*6[' ]?LI GANYAN.*BU KOŞUDAN BAŞLAR", marker):
            first_start = current.number
        if re.search(r"2\.\s*6[' ]?LI GANYAN.*BU KOŞUDAN BAŞLAR", marker):
            second_start = current.number
        if in_table and first.isdigit() and len(row) >= 12:
            current.runners.append(
                ProgramRunner(
                    number=int(first), raw_name=row[1], age_text=row[2], sire=row[3], dam=row[4],
                    weight_text=row[5], jockey=row[6], owner=row[7], trainer=row[8],
                    gate_text=row[9], agf_text=row[10], hp_text=row[11],
                    recent=row[12] if len(row) > 12 else "",
                    kgs_text=row[13] if len(row) > 13 else "",
                    s20_text=row[14] if len(row) > 14 else "",
                    best_text=row[15] if len(row) > 15 else "",
                    scratch="KOŞMAZ" in normalized_text(row[1]),
                )
            )
        else:
            if in_table:
                in_table = False
            footer.append(line)
    if current is not None:
        current.coupled_groups = parse_couplings(footer)
    if second_start is None and len(races) >= 6:
        second_start = max(races) - 5
    return races, first_start, second_start


def header_index(header: list[str], tokens: tuple[str, ...], fallback: int) -> int:
    normalized = [normalized_text(value) for value in header]
    for index, value in enumerate(normalized):
        if any(token in value for token in tokens):
            return index
    return fallback


def parse_results(path: Path) -> dict[int, list[ResultRunner]]:
    races: dict[int, list[ResultRunner]] = defaultdict(list)
    current: int | None = None
    in_table = False
    name_index = 1
    gny_index = 10
    agf_index = 11
    for line in path.read_text(encoding="utf-8-sig", errors="replace").splitlines():
        row = next(csv.reader([line], delimiter=";"))
        if not row:
            in_table = False
            continue
        first = row[0].strip()
        header = RACE_HEADER.match(first)
        if header:
            current = int(header.group(1))
            in_table = False
            continue
        if first == "At No":
            in_table = True
            name_index = header_index(row, ("AT İSMİ", "AT ISMI", "AT ADI"), 1)
            gny_index = header_index(row, ("GNY", "GANYAN"), 10)
            agf_index = header_index(row, ("AGF",), 11)
            continue
        if current is None:
            continue
        if in_table and first.isdigit() and len(row) >= 2:
            finish = int(first)
            name = row[name_index] if name_index < len(row) else row[1]
            gny = first_number(row[gny_index]) if gny_index < len(row) else math.nan
            agf_values = AGF_VALUE.findall(row[agf_index]) if agf_index < len(row) else []
            agf = float(agf_values[-1].replace(",", ".")) / 100.0 if agf_values else math.nan
            races[current].append(ResultRunner(finish, name, gny, agf))
        elif in_table:
            in_table = False
    return dict(races)


def state_features(state: State, current_date: pd.Timestamp, prefix: str) -> dict[str, float]:
    starts = state.starts
    recent = list(state.recent)
    days = float((current_date - state.last_date).days) if state.last_date is not None else 999.0
    return {
        f"{prefix}_starts": float(starts),
        f"{prefix}_smoothed_win_rate": float((state.wins + 1.0) / (starts + 8.0)),
        f"{prefix}_smoothed_top3_rate": float((state.top3 + 2.0) / (starts + 6.0)),
        f"{prefix}_mean_finish": float(state.finish_sum / starts) if starts else 9.0,
        f"{prefix}_recent3_top3": float(np.mean([x <= 3 for x in recent[-3:]])) if recent else 0.0,
        f"{prefix}_recent5_top3": float(np.mean([x <= 3 for x in recent[-5:]])) if recent else 0.0,
        f"{prefix}_recent3_win": float(np.mean([x == 1 for x in recent[-3:]])) if recent else 0.0,
        f"{prefix}_days_since": days,
    }


def update_state(state: State, finish: int, current_date: pd.Timestamp) -> None:
    state.starts += 1
    state.wins += int(finish == 1)
    state.top3 += int(finish <= 3)
    state.finish_sum += float(finish)
    state.recent.append(finish)
    state.last_date = current_date


def selected_agf(tokens: list[float], pool: str) -> float:
    if not tokens:
        return math.nan
    return tokens[0] if pool == "FIRST_SIX" else tokens[-1]


def build_physical_and_cards(manifest: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame, dict[str, Any]]:
    physical_races: list[dict[str, Any]] = []
    cards_pending: list[dict[str, Any]] = []
    qa = defaultdict(int)

    for record in manifest.itertuples(index=False):
        program_path = Path(record.program_file)
        result_path = Path(record.result_file)
        if not program_path.exists() or not result_path.exists():
            qa["missing_local_pair"] += 1
            continue
        try:
            programs, first_start, second_start = parse_program(program_path)
            results = parse_results(result_path)
        except Exception:
            qa["parse_failure"] += 1
            continue
        date_value = pd.Timestamp(record.meeting_date)
        track = str(record.track)
        meeting_races: dict[int, dict[str, Any]] = {}
        for race_no, race in programs.items():
            result_rows = results.get(race_no, [])
            result_map = {runner.match_name: runner for runner in result_rows}
            runners: list[dict[str, Any]] = []
            for runner in race.runners:
                if runner.scratch:
                    continue
                matched = result_map.get(runner.match_name)
                if matched is None:
                    continue
                runners.append({
                    "number": runner.number,
                    "name": horse_core(runner.raw_name),
                    "age": first_number(runner.age_text),
                    "sire": normalized_text(runner.sire),
                    "dam": normalized_text(runner.dam),
                    "weight": first_number(runner.weight_text),
                    "jockey": normalized_text(runner.jockey),
                    "owner": normalized_text(runner.owner),
                    "trainer": normalized_text(runner.trainer),
                    "gate": first_number(runner.gate_text),
                    "hp": first_number(runner.hp_text),
                    "recent_text": runner.recent,
                    "kgs": first_number(runner.kgs_text),
                    "s20": first_number(runner.s20_text),
                    "best_time": time_seconds(runner.best_text),
                    "agf_tokens": runner.agf_tokens,
                    "ganyan_odds": matched.ganyan_odds,
                    "finish": matched.finish,
                    "winner": int(matched.finish == 1),
                })
            if len(runners) < 3 or sum(item["winner"] for item in runners) != 1:
                qa["invalid_physical_race"] += 1
                continue
            if any(not np.isfinite(item["ganyan_odds"]) or item["ganyan_odds"] <= 0 for item in runners):
                qa["missing_ganyan_race"] += 1
                continue
            race_id = f"{date_value.date()}|{track}|R{race_no}"
            item = {
                "date": date_value, "track": track, "race_no": race_no, "race_id": race_id,
                "distance": race.distance, "surface": race.surface,
                "description": race.description, "coupled_groups": race.coupled_groups,
                "runners": runners,
            }
            physical_races.append(item)
            meeting_races[race_no] = item

        starts = [("FIRST_SIX", first_start), ("SECOND_SIX", second_start)]
        for pool, start in starts:
            if start is None:
                continue
            race_numbers = list(range(int(start), int(start) + 6))
            if not all(number in meeting_races for number in race_numbers):
                qa["incomplete_pool"] += 1
                continue
            cards_pending.append({
                "date": date_value,
                "track": track,
                "pool": pool,
                "card_id": f"{date_value.date()}|{track}|{pool}",
                "race_numbers": race_numbers,
                "meeting_races": meeting_races,
            })

    # Deduplicate physical races that are referenced by two pools.
    physical_by_id = {item["race_id"]: item for item in physical_races}
    physical_races = sorted(physical_by_id.values(), key=lambda item: (item["date"], item["track"], item["race_no"]))

    states: dict[tuple[str, str], State] = defaultdict(State)
    horse_rows: list[dict[str, Any]] = []
    pending_updates: list[tuple[list[tuple[str, str]], int, pd.Timestamp]] = []
    current_date: pd.Timestamp | None = None

    def flush_updates() -> None:
        nonlocal pending_updates
        for keys, finish, date_value in pending_updates:
            for key in keys:
                update_state(states[key], finish, date_value)
        pending_updates = []

    for race in physical_races:
        date_value = race["date"]
        if current_date is not None and date_value != current_date:
            flush_updates()
        current_date = date_value
        field_size = len(race["runners"])
        for runner in race["runners"]:
            row = {
                "date": date_value,
                "track": race["track"],
                "race_no": race["race_no"],
                "race_id": race["race_id"],
                "number": runner["number"],
                "horse_name": runner["name"],
                "winner": runner["winner"],
                "finish": runner["finish"],
                "agf_tokens": runner["agf_tokens"],
                "ganyan_odds": runner["ganyan_odds"],
                "distance": race["distance"],
                "surface_code": ascii_code(race["surface"]),
                "track_code": ascii_code(race["track"]),
                "field_size": float(field_size),
                "age": runner["age"],
                "weight": runner["weight"],
                "gate": runner["gate"],
                "hp": runner["hp"],
                "kgs": runner["kgs"],
                "s20": runner["s20"],
                "best_time": runner["best_time"],
            }
            row.update(parse_recent(runner["recent_text"]))
            specs = [
                ("horse", runner["name"]), ("jockey", runner["jockey"]),
                ("trainer", runner["trainer"]), ("sire", runner["sire"]),
                ("dam", runner["dam"]),
                ("horse_track", f"{runner['name']}|{race['track']}"),
                ("jockey_track", f"{runner['jockey']}|{race['track']}"),
                ("trainer_track", f"{runner['trainer']}|{race['track']}"),
                ("horse_surface", f"{runner['name']}|{race['surface']}"),
                ("sire_surface", f"{runner['sire']}|{race['surface']}"),
                ("dam_surface", f"{runner['dam']}|{race['surface']}"),
            ]
            keys = []
            for prefix, value in specs:
                key = (prefix, value)
                row.update(state_features(states[key], date_value, prefix))
                keys.append(key)
            pending_updates.append((keys, runner["finish"], date_value))
            horse_rows.append(row)
    flush_updates()
    horse_df = pd.DataFrame(horse_rows)

    # Build unique physical betting-interest rows with pool-independent form features.
    form_units: list[dict[str, Any]] = []
    unit_members: dict[tuple[str, str], list[int]] = {}
    numeric_feature_cols = [
        col for col in horse_df.columns
        if pd.api.types.is_numeric_dtype(horse_df[col]) and col not in {"winner", "finish", "number"}
    ]
    race_lookup = {item["race_id"]: item for item in physical_races}
    for race_id, block in horse_df.groupby("race_id", sort=False):
        race = race_lookup[race_id]
        number_to_group: dict[int, list[int]] = {}
        for group in race["coupled_groups"]:
            active = sorted(number for number in group if number in set(block["number"]))
            if len(active) >= 2:
                for number in active:
                    number_to_group[number] = active
        seen: set[tuple[int, ...]] = set()
        for _, runner in block.iterrows():
            members_tuple = tuple(number_to_group.get(int(runner["number"]), [int(runner["number"])]))
            if members_tuple in seen:
                continue
            seen.add(members_tuple)
            member_block = block[block["number"].isin(members_tuple)]
            interest_id = "+".join(str(value) for value in members_tuple)
            weights = np.ones(len(member_block), float) / len(member_block)
            unit = {
                "date": runner["date"], "track": runner["track"], "race_no": int(runner["race_no"]),
                "race_id": race_id, "interest_id": interest_id,
                "interest_name": " / ".join(member_block["horse_name"].astype(str)),
                "winner": int(member_block["winner"].max()),
            }
            for col in numeric_feature_cols:
                values = pd.to_numeric(member_block[col], errors="coerce").to_numpy(float)
                valid = np.isfinite(values)
                unit[col] = float(np.average(values[valid], weights=weights[valid])) if valid.any() else math.nan
            form_units.append(unit)
            unit_members[(race_id, interest_id)] = list(members_tuple)
    form_df = pd.DataFrame(form_units)

    # Race-relative form features are safe because they use only current pre-race fields and prior history.
    relative = [
        "hp", "weight", "gate", "horse_smoothed_win_rate", "horse_smoothed_top3_rate",
        "jockey_smoothed_win_rate", "trainer_smoothed_win_rate", "horse_recent5_top3",
        "jockey_track_smoothed_win_rate", "trainer_track_smoothed_win_rate",
        "horse_surface_smoothed_top3_rate", "sire_surface_smoothed_top3_rate",
        "dam_surface_smoothed_top3_rate", "declared_recent_mean_finish",
    ]
    for col in relative:
        if col not in form_df:
            continue
        values = pd.to_numeric(form_df[col], errors="coerce")
        group = form_df["race_id"]
        ascending = col in {"weight", "gate", "declared_recent_mean_finish"}
        form_df[f"{col}_race_rank"] = values.groupby(group).rank(method="average", ascending=ascending)
        mean = values.groupby(group).transform("mean")
        std = values.groupby(group).transform(lambda series: series.std(ddof=0))
        form_df[f"{col}_race_z"] = ((values - mean) / std.replace(0, np.nan)).fillna(0.0)

    # Expand card/pool rows and choose the correct first/second-six AGF token.
    card_rows: list[dict[str, Any]] = []
    horse_by_race = {race_id: block for race_id, block in horse_df.groupby("race_id", sort=False)}
    for card in cards_pending:
        candidate_rows: list[dict[str, Any]] = []
        valid_card = True
        for leg, race_no in enumerate(card["race_numbers"], start=1):
            race_id = f"{card['date'].date()}|{card['track']}|R{race_no}"
            horse_block = horse_by_race.get(race_id)
            form_block = form_df[form_df["race_id"].eq(race_id)]
            if horse_block is None or form_block.empty:
                valid_card = False
                break
            leg_rows = []
            for _, unit in form_block.iterrows():
                members = unit_members[(race_id, str(unit["interest_id"]))]
                member_block = horse_block[horse_block["number"].isin(members)]
                agf_raw = 0.0
                for tokens in member_block["agf_tokens"]:
                    value = selected_agf(tokens, card["pool"])
                    if not np.isfinite(value):
                        agf_raw = math.nan
                        break
                    agf_raw += value
                gny_raw = float(np.sum(1.0 / member_block["ganyan_odds"].to_numpy(float)))
                leg_rows.append({
                    "date": card["date"], "track": card["track"], "six_id": card["pool"],
                    "card_id": card["card_id"], "leg": leg, "race_id": race_id,
                    "betting_interest": str(unit["interest_id"]),
                    "interest_id": str(unit["interest_id"]),
                    "interest_name": unit["interest_name"], "winner": int(unit["winner"]),
                    "agf_raw": agf_raw, "gny_raw": gny_raw,
                })
            leg_df = pd.DataFrame(leg_rows)
            if (
                len(leg_df) < 3 or leg_df["winner"].sum() != 1
                or not np.isfinite(leg_df[["agf_raw", "gny_raw"]]).all().all()
                or leg_df["agf_raw"].sum() <= 0 or leg_df["gny_raw"].sum() <= 0
            ):
                valid_card = False
                break
            leg_df["agf_prob"] = leg_df["agf_raw"] / leg_df["agf_raw"].sum()
            leg_df["ganyan_prob"] = leg_df["gny_raw"] / leg_df["gny_raw"].sum()
            candidate_rows.extend(leg_df.drop(columns=["agf_raw", "gny_raw"]).to_dict("records"))
        if valid_card:
            card_rows.extend(candidate_rows)
        else:
            qa["invalid_expanded_card"] += 1
    card_df = pd.DataFrame(card_rows)

    audit = {
        **dict(qa),
        "official_meetings_read": int(len(manifest)),
        "physical_races": int(form_df["race_id"].nunique()),
        "physical_betting_interest_rows": int(len(form_df)),
        "complete_sixfold_cards": int(card_df["card_id"].nunique()) if not card_df.empty else 0,
        "card_rows": int(len(card_df)),
        "date_min": str(form_df["date"].min().date()),
        "date_max": str(form_df["date"].max().date()),
    }
    return form_df, card_df, audit


def race_probabilities(scores: np.ndarray, race_ids: pd.Series, temperature: float) -> np.ndarray:
    output = np.empty(len(scores), float)
    temp = pd.DataFrame({"race_id": race_ids.to_numpy(), "score": scores, "pos": np.arange(len(scores))})
    for _, block in temp.groupby("race_id", sort=False):
        output[block["pos"].to_numpy(int)] = softmax(block["score"].to_numpy(float) / temperature)
    return output


def nll_and_top3(frame: pd.DataFrame, probability: np.ndarray) -> tuple[float, float]:
    test = frame.copy().reset_index(drop=True)
    test["p"] = probability
    ranks = test.groupby("race_id")["p"].rank(method="first", ascending=False)
    winners = test["winner"].eq(1)
    return (
        float(-np.log(np.clip(test.loc[winners, "p"].to_numpy(float), EPS, None)).mean()),
        float((ranks[winners] <= 3).mean()),
    )


def feature_columns(frame: pd.DataFrame) -> list[str]:
    excluded = {
        "date", "track", "race_no", "race_id", "interest_id", "interest_name", "winner",
        "finish", "agf_prob", "ganyan_prob", "agf_tokens", "ganyan_odds",
    }
    columns = [
        col for col in frame.columns
        if col not in excluded and pd.api.types.is_numeric_dtype(frame[col])
    ]
    return [col for col in columns if frame[col].notna().any()]


def scaled_matrices(train: pd.DataFrame, others: list[pd.DataFrame], columns: list[str]) -> tuple[np.ndarray, list[np.ndarray], StandardScaler]:
    x_train = train[columns].apply(pd.to_numeric, errors="coerce").replace([np.inf, -np.inf], np.nan)
    medians = x_train.median().fillna(0.0)
    x_train = x_train.fillna(medians).to_numpy(float)
    other_arrays = [
        other[columns].apply(pd.to_numeric, errors="coerce").replace([np.inf, -np.inf], np.nan).fillna(medians).to_numpy(float)
        for other in others
    ]
    scaler = StandardScaler().fit(x_train)
    return scaler.transform(x_train), [scaler.transform(array) for array in other_arrays], scaler


def pairwise_training(x: np.ndarray, frame: pd.DataFrame) -> tuple[np.ndarray, np.ndarray]:
    pairs = []
    labels = []
    for indices in frame.groupby("race_id", sort=False).indices.values():
        indices = np.asarray(indices, int)
        winners = indices[frame.iloc[indices]["winner"].to_numpy(int) == 1]
        if len(winners) != 1:
            continue
        winner = int(winners[0])
        for loser in indices:
            if loser == winner:
                continue
            diff = x[winner] - x[loser]
            pairs.extend([diff, -diff])
            labels.extend([1, 0])
    return np.asarray(pairs, float), np.asarray(labels, int)


def tune_logistic(train: pd.DataFrame, valid: pd.DataFrame, columns: list[str], pairwise: bool) -> tuple[float, float]:
    x_train, [x_valid], _ = scaled_matrices(train, [valid], columns)
    best: tuple[float, float, float] | None = None
    for c_value in (0.03, 0.1, 0.3, 1.0, 3.0):
        if pairwise:
            pair_x, pair_y = pairwise_training(x_train, train.reset_index(drop=True))
            model = LogisticRegression(C=c_value, fit_intercept=False, max_iter=1000, solver="lbfgs")
            model.fit(pair_x, pair_y)
            scores = x_valid @ model.coef_[0]
        else:
            model = LogisticRegression(C=c_value, max_iter=1000, solver="lbfgs")
            model.fit(x_train, train["winner"].to_numpy(int))
            scores = model.decision_function(x_valid)
        for temperature in (0.55, 0.75, 1.0, 1.3, 1.7, 2.2):
            probability = race_probabilities(scores, valid["race_id"], temperature)
            nll, top3 = nll_and_top3(valid, probability)
            objective = 2.5 * top3 - 0.12 * nll
            candidate = (objective, c_value, temperature)
            if best is None or candidate > best:
                best = candidate
    assert best is not None
    return best[1], best[2]


def fit_logistic_predict(train: pd.DataFrame, test: pd.DataFrame, columns: list[str], c_value: float, temperature: float, pairwise: bool) -> np.ndarray:
    x_train, [x_test], _ = scaled_matrices(train, [test], columns)
    if pairwise:
        pair_x, pair_y = pairwise_training(x_train, train.reset_index(drop=True))
        model = LogisticRegression(C=c_value, fit_intercept=False, max_iter=1200, solver="lbfgs")
        model.fit(pair_x, pair_y)
        scores = x_test @ model.coef_[0]
    else:
        model = LogisticRegression(C=c_value, max_iter=1200, solver="lbfgs")
        model.fit(x_train, train["winner"].to_numpy(int))
        scores = model.decision_function(x_test)
    return race_probabilities(scores, test["race_id"], temperature)


def sorted_for_rank(frame: pd.DataFrame) -> pd.DataFrame:
    return frame.sort_values(["date", "race_id", "interest_id"], kind="mergesort").reset_index(drop=True)


def rank_groups(frame: pd.DataFrame) -> np.ndarray:
    return frame.groupby("race_id", sort=False).size().to_numpy(int)


def tune_lambdamart(train: pd.DataFrame, valid: pd.DataFrame, columns: list[str]) -> tuple[dict[str, Any], float, int]:
    train = sorted_for_rank(train)
    valid = sorted_for_rank(valid)
    x_train = train[columns].apply(pd.to_numeric, errors="coerce").replace([np.inf, -np.inf], np.nan)
    medians = x_train.median().fillna(0.0)
    x_train = x_train.fillna(medians)
    x_valid = valid[columns].apply(pd.to_numeric, errors="coerce").replace([np.inf, -np.inf], np.nan).fillna(medians)
    configs = [
        {"num_leaves": 15, "max_depth": 4, "learning_rate": 0.04, "min_child_samples": 20},
        {"num_leaves": 31, "max_depth": 6, "learning_rate": 0.035, "min_child_samples": 25},
        {"num_leaves": 47, "max_depth": 7, "learning_rate": 0.025, "min_child_samples": 35},
        {"num_leaves": 23, "max_depth": 5, "learning_rate": 0.06, "min_child_samples": 15},
    ]
    best: tuple[float, dict[str, Any], float, int] | None = None
    for config in configs:
        model = LGBMRanker(
            objective="lambdarank", metric="ndcg", label_gain=[0, 1], lambdarank_truncation_level=3,
            n_estimators=350, subsample=0.85, subsample_freq=1, colsample_bytree=0.82,
            reg_alpha=0.05, reg_lambda=5.0, random_state=186, n_jobs=2, verbosity=-1,
            **config,
        )
        model.fit(
            x_train, train["winner"], group=rank_groups(train),
            eval_set=[(x_valid, valid["winner"])], eval_group=[rank_groups(valid)], eval_at=[3],
            callbacks=[early_stopping(40, verbose=False), log_evaluation(0)],
        )
        scores = model.predict(x_valid)
        iteration = int(model.best_iteration_ or 120)
        for temperature in (0.55, 0.75, 1.0, 1.3, 1.7):
            probability = race_probabilities(scores, valid["race_id"], temperature)
            nll, top3 = nll_and_top3(valid, probability)
            objective = 2.5 * top3 - 0.12 * nll
            candidate = (objective, config, temperature, iteration)
            if best is None or candidate[0] > best[0]:
                best = candidate
    assert best is not None
    return best[1], best[2], best[3]


def fit_lambdamart_predict(train: pd.DataFrame, test: pd.DataFrame, columns: list[str], config: dict[str, Any], temperature: float, iterations: int) -> np.ndarray:
    train = sorted_for_rank(train)
    ordered_test = sorted_for_rank(test)
    x_train = train[columns].apply(pd.to_numeric, errors="coerce").replace([np.inf, -np.inf], np.nan)
    medians = x_train.median().fillna(0.0)
    x_train = x_train.fillna(medians)
    x_test = ordered_test[columns].apply(pd.to_numeric, errors="coerce").replace([np.inf, -np.inf], np.nan).fillna(medians)
    model = LGBMRanker(
        objective="lambdarank", metric="ndcg", label_gain=[0, 1], lambdarank_truncation_level=3,
        n_estimators=max(iterations, 40), subsample=0.85, subsample_freq=1,
        colsample_bytree=0.82, reg_alpha=0.05, reg_lambda=5.0,
        random_state=186, n_jobs=2, verbosity=-1, **config,
    )
    model.fit(x_train, train["winner"], group=rank_groups(train))
    probability = race_probabilities(model.predict(x_test), ordered_test["race_id"], temperature)
    lookup = pd.Series(probability, index=ordered_test["race_id"].astype(str) + "|" + ordered_test["interest_id"].astype(str))
    keys = test["race_id"].astype(str) + "|" + test["interest_id"].astype(str)
    return lookup.loc[keys].to_numpy(float)


def generate_oof(form_df: pd.DataFrame, folds: int) -> tuple[pd.DataFrame, list[dict[str, Any]]]:
    frame = form_df.copy()
    frame["date"] = pd.to_datetime(frame["date"])
    dates = sorted(frame["date"].drop_duplicates())
    if len(dates) < 60:
        raise ValueError(f"Need at least 60 distinct dates, found {len(dates)}")
    first_test = max(45, int(len(dates) * 0.55))
    window = max(10, math.ceil((len(dates) - first_test) / folds))
    columns = feature_columns(frame)
    outputs = []
    reports = []
    fold_no = 0
    for start in range(first_test, len(dates), window):
        if fold_no >= folds:
            break
        test_dates = dates[start : min(len(dates), start + window)]
        if not test_dates:
            continue
        fold_no += 1
        train = frame[frame["date"].isin(dates[:start])].copy()
        test = frame[frame["date"].isin(test_dates)].copy()
        train_dates = sorted(train["date"].drop_duplicates())
        valid_size = max(10, int(len(train_dates) * 0.18))
        valid_dates = train_dates[-valid_size:]
        inner_train = train[~train["date"].isin(valid_dates)].copy()
        valid = train[train["date"].isin(valid_dates)].copy()

        conditional_c, conditional_t = tune_logistic(inner_train, valid, columns, pairwise=False)
        pairwise_c, pairwise_t = tune_logistic(inner_train, valid, columns, pairwise=True)
        lambda_config, lambda_t, lambda_iterations = tune_lambdamart(inner_train, valid, columns)

        ordered_test = test.reset_index(drop=True)
        conditional = fit_logistic_predict(train, ordered_test, columns, conditional_c, conditional_t, pairwise=False)
        pairwise = fit_logistic_predict(train, ordered_test, columns, pairwise_c, pairwise_t, pairwise=True)
        lambdamart = fit_lambdamart_predict(train, ordered_test, columns, lambda_config, lambda_t, lambda_iterations)
        output = ordered_test[["date", "race_id", "interest_id", "winner"]].copy()
        output["conditional_prob"] = conditional
        output["pairwise_prob"] = pairwise
        output["lambdamart_prob"] = lambdamart
        output["oof_fold"] = fold_no
        outputs.append(output)
        reports.append({
            "fold": fold_no,
            "train_start": str(train_dates[0].date()),
            "train_end": str(train_dates[-1].date()),
            "test_start": str(test_dates[0].date()),
            "test_end": str(test_dates[-1].date()),
            "train_races": int(train["race_id"].nunique()),
            "test_races": int(test["race_id"].nunique()),
            "conditional": {"C": conditional_c, "temperature": conditional_t},
            "pairwise": {"C": pairwise_c, "temperature": pairwise_t},
            "lambdamart": {**lambda_config, "temperature": lambda_t, "iterations": lambda_iterations},
        })
    if not outputs:
        raise RuntimeError("No OOF fold was produced")
    return pd.concat(outputs, ignore_index=True), reports


def evaluate_probability(frame: pd.DataFrame, column: str) -> dict[str, Any]:
    scored = frame.copy()
    scored["rank"] = scored.groupby(["card_id", "leg"])[column].rank(method="first", ascending=False)
    winners = scored[scored["winner"].eq(1)].copy()
    winners["hit"] = winners["rank"].le(3).astype(int)
    cards = winners.groupby(["date", "card_id"], as_index=False).agg(
        legs=("leg", "nunique"), legs_hit=("hit", "sum")
    )
    cards = cards[cards["legs"].eq(6)]
    cards["exact6"] = cards["legs_hit"].eq(6)
    hits = int(cards["exact6"].sum())
    n_cards = int(len(cards))
    z = 1.959963984540054
    p = hits / n_cards if n_cards else math.nan
    if n_cards:
        denom = 1 + z * z / n_cards
        center = (p + z * z / (2 * n_cards)) / denom
        half = z * math.sqrt((p * (1 - p) + z * z / (4 * n_cards)) / n_cards) / denom
        low, high = max(0.0, center - half), min(1.0, center + half)
    else:
        low = high = math.nan
    return {
        "cards": n_cards,
        "races": int(len(winners)),
        "exact6_hits": hits,
        "exact6_rate": float(p),
        "exact6_wilson95_low": float(low),
        "exact6_wilson95_high": float(high),
        "race_top3_rate": float(winners["hit"].mean()),
        "mean_legs_hit": float(cards["legs_hit"].mean()),
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--folds", type=int, default=5)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    output = args.output
    output.mkdir(parents=True, exist_ok=True)
    manifest = pd.read_csv(args.manifest)
    manifest = manifest[manifest["complete"].astype(str).str.lower().isin({"true", "1"})].copy()
    form_df, card_df, build_audit = build_physical_and_cards(manifest)
    if card_df["card_id"].nunique() < 200:
        raise SystemExit(f"Fail closed: only {card_df['card_id'].nunique()} complete sixfold cards")

    oof_form, fold_reports = generate_oof(form_df, args.folds)
    merge_columns = ["race_id", "interest_id", "conditional_prob", "pairwise_prob", "lambdamart_prob", "oof_fold"]
    oof = card_df.merge(oof_form[merge_columns], on=["race_id", "interest_id"], how="inner", validate="many_to_one")
    complete_oof_cards = oof.groupby("card_id")["leg"].nunique()
    keep_cards = complete_oof_cards[complete_oof_cards.eq(6)].index
    oof = oof[oof["card_id"].isin(keep_cards)].copy()
    oof["market_blend_prob"] = np.exp(
        0.75 * np.log(np.clip(oof["agf_prob"], EPS, None))
        + 0.25 * np.log(np.clip(oof["ganyan_prob"], EPS, None))
    )
    oof["market_blend_prob"] = oof["market_blend_prob"] / oof.groupby(["card_id", "leg"])["market_blend_prob"].transform("sum")
    oof["market_snapshot_source"] = "official_TJK_result_export_final_preoff_GNY"
    oof["label_source"] = "official_TJK_result_export_finish_order"
    oof["feature_cutoff"] = "strictly_earlier_calendar_date"

    required = {
        "date", "card_id", "leg", "betting_interest", "winner", "agf_prob",
        "ganyan_prob", "conditional_prob", "pairwise_prob", "lambdamart_prob",
    }
    if not required.issubset(oof.columns):
        raise AssertionError(f"OOF schema missing: {sorted(required - set(oof.columns))}")
    if not oof.groupby(["card_id", "leg"])["winner"].sum().eq(1).all():
        raise AssertionError("OOF race winner invariant failed")
    if not oof.groupby("card_id")["leg"].nunique().eq(6).all():
        raise AssertionError("OOF card leg invariant failed")
    for column in ("agf_prob", "ganyan_prob", "conditional_prob", "pairwise_prob", "lambdamart_prob", "market_blend_prob"):
        sums = oof.groupby(["card_id", "leg"])[column].sum()
        if not np.allclose(sums.to_numpy(float), 1.0, atol=1e-6):
            raise AssertionError(f"Probability normalization failed for {column}")

    form_df.to_csv(output / "physical_interest_features.csv.gz", index=False, compression="gzip")
    card_df.to_csv(output / "all_card_linked_rows.csv.gz", index=False, compression="gzip")
    oof.to_csv(output / "cardhit3_oof_rows.csv.gz", index=False, compression="gzip")

    evaluations = {
        column: evaluate_probability(oof, column)
        for column in (
            "agf_prob", "ganyan_prob", "market_blend_prob",
            "conditional_prob", "pairwise_prob", "lambdamart_prob",
        )
    }
    card_outputs = []
    for column in evaluations:
        temp = oof.copy()
        temp["rank"] = temp.groupby(["card_id", "leg"])[column].rank(method="first", ascending=False)
        winners = temp[temp["winner"].eq(1)].copy()
        winners["hit"] = winners["rank"].le(3).astype(int)
        cards = winners.groupby(["date", "card_id"], as_index=False).agg(legs_hit=("hit", "sum"))
        cards["model"] = column
        cards["exact6"] = cards["legs_hit"].eq(6)
        card_outputs.append(cards)
    pd.concat(card_outputs, ignore_index=True).to_csv(output / "cardhit3_oof_card_results.csv", index=False)

    audit = {
        "generated_at_utc": datetime.utcnow().isoformat() + "Z",
        "source_manifest": str(args.manifest),
        "build": build_audit,
        "oof": {
            "rows": int(len(oof)),
            "cards": int(oof["card_id"].nunique()),
            "races": int(oof.groupby(["card_id", "leg"]).ngroups),
            "physical_races": int(oof["race_id"].nunique()),
            "date_min": str(pd.to_datetime(oof["date"]).min().date()),
            "date_max": str(pd.to_datetime(oof["date"]).max().date()),
            "folds": fold_reports,
            "probability_columns": [
                "agf_prob", "ganyan_prob", "market_blend_prob",
                "conditional_prob", "pairwise_prob", "lambdamart_prob",
            ],
            "schema_contract_complete": True,
        },
        "base_model_metrics": evaluations,
        "important_limitations": [
            "Historical Ganyan comes from the official result export and represents final pre-off market timing.",
            "Future production must use a comparable time-to-off snapshot or model market-time explicitly.",
            "OOF base probabilities close the data contract; final exact-six ensemble weights must still be tuned only on prior-date cards.",
        ],
    }
    (output / "cardhit3_oof_audit.json").write_text(
        json.dumps(audit, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    print(json.dumps(audit["oof"] | {"base_model_metrics": evaluations}, ensure_ascii=False, indent=2))

    if oof["card_id"].nunique() < 200:
        raise SystemExit("Fail closed: fewer than 200 complete OOF cards")


if __name__ == "__main__":
    main()
