(() => {
'use strict';
const $=id=>document.getElementById(id);
const el={form:$('filters'),query:$('query'),category:$('category'),status:$('status'),topic:$('topic'),audience:$('audience'),reset:$('reset'),results:$('results'),summary:$('resultSummary'),selectedList:$('selectedList'),exportSelected:$('exportSelected'),printSelected:$('printSelected'),entryCount:$('entryCount'),checkedAt:$('checkedAt'),intentGrid:$('intentGrid')};
const state={catalog:null,filtered:[],visible:40,selected:new Map(),intent:null};
const labels={'tuketici':'Tüketici','piyasa-katilimcisi':'Piyasa katılımcısı','edas-gts':'EDAŞ / GTŞ','yatirimci-uretici':'Yatırımcı / üretici','muhendis-elektrikci':'Mühendis / elektrikçi','osb-isletme':'OSB / işletme','genel':'Genel','tarife':'Tarife ve bedeller','baglanti':'Bağlantı ve sistem kullanımı','lisans':'Lisans ve önlisans','uretim':'Üretim ve kapasite','yenilenebilir':'Yenilenebilir enerji','lisanssiz-uretim':'Lisanssız üretim','depolama-toplayicilik':'Depolama ve toplayıcılık','piyasa-isletimi':'Piyasa işletimi','dagitim-kalite':'Dağıtım ve kalite','olcum-sayac':'Ölçüm ve sayaç','sebekeler':'Şebeke ve iletim','denetim':'Denetim ve yaptırım','proje-kabul':'Proje ve kabul','osb-endustri':'OSB ve endüstri','verimlilik':'Enerji verimliliği','ithalat-ihracat':'İthalat ve ihracat'};
const intents={'tuketici':{audience:'tuketici',topic:''},'baglanti':{audience:'',topic:'baglanti'},'lisanssiz-uretim':{audience:'',topic:'lisanssiz-uretim'},'yatirimci-uretici':{audience:'yatirimci-uretici',topic:''},'depolama-toplayicilik':{audience:'',topic:'depolama-toplayicilik'},'piyasa-katilimcisi':{audience:'piyasa-katilimcisi',topic:''},'edas-gts':{audience:'edas-gts',topic:''},'osb-isletme':{audience:'osb-isletme',topic:''}};
const topicDefs=[['tuketici',['tuketici','perakende','fatura','son kaynak','guvence','kesme baglama']],['tarife',['tarife','bedel','gelir','fiyat','ucret','hesap plani']],['baglanti',['baglanti','sistem kullanim','enterkonneksiyon','dagitim varlik']],['lisans',['lisans','onlisans','serbest tuketici']],['uretim',['uretim','santral','kapasite mekanizmasi','yan hizmet']],['yenilenebilir',['yenilenebilir','yekdem','yek g','gunes','ruzgar','jeotermal']],['lisanssiz-uretim',['lisanssiz']],['depolama-toplayicilik',['depolama','toplayicilik','talep tarafi']],['piyasa-isletimi',['dengeleme','uzlastirma','gun oncesi','vadeli','piyasa','teminat','seffaflik']],['dagitim-kalite',['dagitim','teknik kalite','tedarik surekliligi','kayip']],['olcum-sayac',['olcum','sayac','osos','profil']],['sebekeler',['sebeke','iletim','frekans','reaktif guc']],['denetim',['denetim','sorusturma','para ceza','bilisim guvenligi']],['proje-kabul',['proje','kabul','imar','cevresel etki','kamulastirma']],['osb-endustri',['organize sanayi','endustri bolge','osb']],['verimlilik',['verimlilik','kojenerasyon']],['ithalat-ihracat',['ithalat','ihracat']]];
const audienceDefs=[['tuketici',['tuketici','perakende','fatura','sayac','kesme','guvence','son kaynak']],['piyasa-katilimcisi',['lisans','onlisans','piyasa','uzlastirma','teminat','ithalat','ihracat','epias']],['edas-gts',['dagitim','edas','kalite','osos','baglanti']],['yatirimci-uretici',['uretim','yenilenebilir','yekdem','gunes','ruzgar','santral','depolama']],['muhendis-elektrikci',['proje','kabul','teknik','olcum','sebeke','baglanti']],['osb-isletme',['organize sanayi','endustri bolge','osb']]];
function norm(v){return String(v||'').toLocaleLowerCase('tr-TR').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/[^a-z0-9]+/g,' ').trim()}
function esc(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function derive(defs,title){const n=norm(title),out=defs.filter(([,tokens])=>tokens.some(t=>n.includes(t))).map(([key])=>key);return out.length?[...new Set(out)]:['genel']}
function impact(title,status){const n=norm(title);if(['mulga','tarihsel'].includes(status))return'Tarihsel düzenlemedir; güncel işlemde doğrudan uygulanmamalı, yürürlükteki hal resmî kaynaktan bulunmalıdır.';if(['tuketici','fatura','perakende','son kaynak','guvence','kesme baglama','sayac kontrol'].some(t=>n.includes(t)))return'Fatura, sözleşme, sayaç, hizmet kalitesi veya tüketici başvuru sürecini etkileyebilir.';if(['lisanssiz','gunes','ruzgar','yenilenebilir','yekdem','yek g'].some(t=>n.includes(t)))return'GES/RES başvurusu, destek mekanizması, proje, ölçüm veya üretim gelirini etkileyebilir.';if(['baglanti','sistem kullanim','dagitim varlik','enterkonneksiyon'].some(t=>n.includes(t)))return'Bağlantı görüşü, anlaşma, yatırım geri ödemesi veya sistem kullanım yükümlülüklerini etkileyebilir.';if(['tarife','bedel','gelir','fiyat'].some(t=>n.includes(t)))return'Tarife, bedel veya düzenlenmiş gelir hesabında kullanılabilir; dönem ve Kurul kararı ayrıca doğrulanmalıdır.';if(['dengeleme','uzlastirma','piyasa','teminat','gun oncesi','vadeli'].some(t=>n.includes(t)))return'Piyasa katılımı, teklif, teminat, uzlaştırma veya şeffaflık yükümlülüklerini etkileyebilir.';if(['kalite','dagitim','osos','olcum','sayac'].some(t=>n.includes(t)))return'Dağıtım hizmeti, ölçüm, kayıt, teknik kalite veya performans yükümlülüklerini etkileyebilir.';if(['depolama','toplayicilik','talep tarafi'].some(t=>n.includes(t)))return'Esneklik, depolama, toplayıcılık veya yan hizmet katılım koşullarını etkileyebilir.';return'Elektrik piyasası faaliyetinde hak, yükümlülük, başvuru veya teknik uyum açısından ilgili olabilir.'}
function hydrate(row){if(!Array.isArray(row))return row;const[title,category,status]=row;return{id:`${norm(category)}-${norm(title)}`.replace(/\s+/g,'-').slice(0,96),title,category,status,topics:derive(topicDefs,title),audiences:derive(audienceDefs,title),impact:impact(title,status)}}
async function loadCatalog(){const metaResponse=await fetch('./catalog.json',{cache:'no-store'});if(!metaResponse.ok)throw new Error(`Katalog yüklenemedi: ${metaResponse.status}`);const meta=await metaResponse.json();const parts=await Promise.all(meta.files.map(async file=>{const response=await fetch(`./${file.path}`,{cache:'no-store'});if(!response.ok)throw new Error(`Katalog parçası yüklenemedi: ${file.path}`);return response.json()}));meta.entries=parts.flatMap(part=>part.entries||[]).map(hydrate);if(meta.entries.length!==meta.coverage.uniqueEntryCount)throw new Error(`Katalog bütünlüğü bozuldu: ${meta.entries.length}/${meta.coverage.uniqueEntryCount}`);return meta}
function statusLabel(s){return s==='mulga'?'Mülga':s==='tarihsel'?'Tarihsel':s==='degisiklik'?'Değişiklik kaydı':'EPDK listesinde'}
function addOptions(select,values){values.forEach(value=>{const option=document.createElement('option');option.value=value;option.textContent=labels[value]||value;select.appendChild(option)})}
function filters(){return{q:norm(el.query.value),category:el.category.value,status:el.status.value,topic:el.topic.value,audience:el.audience.value}}
function match(entry,f){if(f.category&&entry.category!==f.category)return false;if(f.status&&entry.status!==f.status)return false;if(f.topic&&!entry.topics.includes(f.topic))return false;if(f.audience&&!entry.audiences.includes(f.audience))return false;if(!f.q)return true;const hay=norm([entry.title,entry.category,entry.impact,...entry.topics,...entry.audiences].join(' '));return f.q.split(/\s+/).every(token=>hay.includes(token))}
function card(entry){const chosen=state.selected.has(entry.id),cls=entry.status==='mulga'?'mulga':entry.status==='tarihsel'?'tarihsel':'';return`<article class="result-card" data-entry-id="${esc(entry.id)}"><div class="badges"><span class="badge">${esc(entry.category)}</span><span class="badge ${cls}">${esc(statusLabel(entry.status))}</span></div><h3>${esc(entry.title)}</h3><p>${esc(entry.impact)}</p><div class="result-meta">${entry.topics.slice(0,4).map(t=>`<span>${esc(labels[t]||t)}</span>`).join('')}<span>${entry.audiences.slice(0,3).map(a=>esc(labels[a]||a)).join(' · ')}</span></div>${entry.status==='mulga'?'<p><strong>Uyarı:</strong> Bu başlık güncel işlem kuralı olarak kullanılmamalıdır.</p>':''}<div class="result-actions"><a href="${esc(state.catalog.source.url)}" target="_blank" rel="external noopener">Resmî listede doğrula ↗</a><button type="button" data-copy>Başlığı kopyala</button><button type="button" data-select aria-pressed="${chosen}">${chosen?'Dosyadan çıkar':'Çalışma dosyasına ekle'}</button></div></article>`}
function render(){const total=state.filtered.length,shown=Math.min(total,state.visible);el.summary.textContent=`${total.toLocaleString('tr-TR')} sonuç · ${shown.toLocaleString('tr-TR')} gösteriliyor`;if(!total){el.results.innerHTML='<div class="no-results"><strong>Sonuç bulunamadı.</strong><p>Filtreleri temizleyin veya resmî EPDK listesini açın.</p></div>';return}el.results.innerHTML=state.filtered.slice(0,state.visible).map(card).join('')+(shown<total?`<button type="button" class="button secondary full" id="loadMore">${Math.min(40,total-shown)} sonuç daha göster</button>`:'')}
function apply(){if(!state.catalog)return;const f=filters();state.filtered=state.catalog.entries.filter(entry=>match(entry,f));state.visible=40;render()}
function selected(){const items=[...state.selected.values()];el.exportSelected.disabled=!items.length;el.printSelected.disabled=!items.length;el.selectedList.innerHTML=items.length?items.map(e=>`<div class="selected-item" data-selected-id="${esc(e.id)}"><strong>${esc(e.title)}</strong><small>${esc(e.category)} · ${esc(statusLabel(e.status))}</small><button type="button" data-remove>Çıkar</button></div>`).join(''):'<p class="empty">Henüz başlık seçilmedi.</p>'}
function download(name,type,content){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}
function exportFile(){const items=[...state.selected.values()];if(!items.length)return;download('alo186-elektrik-mevzuat-calisma-dosyasi.json','application/json;charset=utf-8',JSON.stringify({schemaVersion:1,generatedAt:new Date().toISOString(),source:state.catalog.source,disclaimer:'ALO186 bağımsız bilgi platformudur. Resmî metin için EPDK ve Resmî Gazete esas alınır.',selected:items.map(({id,title,category,status,topics,audiences})=>({id,title,category,status,topics,audiences}))},null,2))}
function setIntent(name){const config=intents[name];if(!config)return;state.intent=state.intent===name?null:name;el.intentGrid.querySelectorAll('[data-intent]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.intent===state.intent?'true':'false'));el.audience.value=state.intent?config.audience:'';el.topic.value=state.intent?config.topic:'';apply();$('atlas').scrollIntoView({behavior:'smooth',block:'start'})}
function bind(){el.form.addEventListener('submit',e=>{e.preventDefault();state.intent=null;el.intentGrid.querySelectorAll('[data-intent]').forEach(b=>b.setAttribute('aria-pressed','false'));apply()});[el.category,el.status,el.topic,el.audience].forEach(c=>c.addEventListener('change',apply));el.query.addEventListener('input',()=>{clearTimeout(el.query._t);el.query._t=setTimeout(apply,180)});el.reset.addEventListener('click',()=>{el.form.reset();state.intent=null;el.intentGrid.querySelectorAll('[data-intent]').forEach(b=>b.setAttribute('aria-pressed','false'));apply()});el.intentGrid.addEventListener('click',e=>{const b=e.target.closest('[data-intent]');if(b)setIntent(b.dataset.intent)});el.results.addEventListener('click',async e=>{if(e.target.id==='loadMore'){state.visible+=40;render();return}const node=e.target.closest('[data-entry-id]');if(!node)return;const entry=state.catalog.entries.find(x=>x.id===node.dataset.entryId);if(!entry)return;if(e.target.closest('[data-copy]')){try{await navigator.clipboard.writeText(entry.title);e.target.textContent='Kopyalandı'}catch{window.prompt('Başlığı kopyalayın:',entry.title)}}if(e.target.closest('[data-select]')){state.selected.has(entry.id)?state.selected.delete(entry.id):state.selected.set(entry.id,entry);selected();render()}});el.selectedList.addEventListener('click',e=>{const item=e.target.closest('[data-selected-id]');if(item&&e.target.closest('[data-remove]')){state.selected.delete(item.dataset.selectedId);selected();render()}});el.exportSelected.addEventListener('click',exportFile);el.printSelected.addEventListener('click',()=>{if(state.selected.size)window.print()})}
async function init(){bind();el.results.innerHTML='<div class="loading">EPDK elektrik mevzuatı başlık indeksi yükleniyor…</div>';try{state.catalog=await loadCatalog();addOptions(el.category,state.catalog.categories.map(c=>c.name));addOptions(el.topic,[...new Set(state.catalog.entries.flatMap(e=>e.topics))].sort((a,b)=>(labels[a]||a).localeCompare(labels[b]||b,'tr')));addOptions(el.audience,[...new Set(state.catalog.entries.flatMap(e=>e.audiences))].sort((a,b)=>(labels[a]||a).localeCompare(labels[b]||b,'tr')));el.entryCount.textContent=state.catalog.coverage.uniqueEntryCount.toLocaleString('tr-TR');el.checkedAt.textContent=new Intl.DateTimeFormat('tr-TR',{dateStyle:'long',timeZone:'Europe/Istanbul'}).format(new Date(`${state.catalog.source.checkedAt}T12:00:00+03:00`));const p=new URLSearchParams(location.search);if(p.get('q'))el.query.value=p.get('q');if(p.get('kategori'))el.category.value=p.get('kategori');if(p.get('konu'))el.topic.value=p.get('konu');if(p.get('kullanici'))el.audience.value=p.get('kullanici');apply();selected()}catch(error){el.summary.textContent='Katalog yüklenemedi';el.results.innerHTML=`<div class="no-results"><strong>Mevzuat kataloğu açılamadı.</strong><p>${esc(error.message)}</p><a class="button secondary" href="https://www.epdk.gov.tr/Detay/Icerik/23-2-3/elektrik-piyasasi" target="_blank" rel="external noopener">EPDK resmî listesi ↗</a></div>`}}
init();
})();
