(() => {
  'use strict';
  const state={catalog:null,filtered:[],visible:40,selected:new Map(),activeIntent:null};
  const $=id=>document.getElementById(id);
  const elements={form:$('filters'),query:$('query'),category:$('category'),status:$('status'),topic:$('topic'),audience:$('audience'),reset:$('reset'),results:$('results'),summary:$('resultSummary'),selectedList:$('selectedList'),exportSelected:$('exportSelected'),printSelected:$('printSelected'),entryCount:$('entryCount'),checkedAt:$('checkedAt'),intentGrid:$('intentGrid')};
  const labelMap={'tuketici':'Tüketici','piyasa-katilimcisi':'Piyasa katılımcısı','edas-gts':'EDAŞ / GTŞ','yatirimci-uretici':'Yatırımcı / üretici','muhendis-elektrikci':'Mühendis / elektrikçi','osb-isletme':'OSB / işletme','genel':'Genel','tarife':'Tarife ve bedeller','baglanti':'Bağlantı ve sistem kullanımı','lisans':'Lisans ve önlisans','uretim':'Üretim ve kapasite','yenilenebilir':'Yenilenebilir enerji','lisanssiz-uretim':'Lisanssız üretim','depolama-toplayicilik':'Depolama ve toplayıcılık','piyasa-isletimi':'Piyasa işletimi','dagitim-kalite':'Dağıtım ve kalite','olcum-sayac':'Ölçüm ve sayaç','sebekeler':'Şebeke ve iletim','denetim':'Denetim ve yaptırım','proje-kabul':'Proje ve kabul','osb-endustri':'OSB ve endüstri','verimlilik':'Enerji verimliliği','ithalat-ihracat':'İthalat ve ihracat'};
  const intentMap={'tuketici':{audience:'tuketici',topic:''},'baglanti':{audience:'',topic:'baglanti'},'lisanssiz-uretim':{audience:'',topic:'lisanssiz-uretim'},'yatirimci-uretici':{audience:'yatirimci-uretici',topic:''},'depolama-toplayicilik':{audience:'',topic:'depolama-toplayicilik'},'piyasa-katilimcisi':{audience:'piyasa-katilimcisi',topic:''},'edas-gts':{audience:'edas-gts',topic:''},'osb-isletme':{audience:'osb-isletme',topic:''}};
  function normalize(value){return String(value||'').toLocaleLowerCase('tr-TR').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/[^a-z0-9]+/g,' ').trim()}
  function escapeHtml(value){return String(value||'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]))}
  function statusLabel(status){if(status==='mulga')return'Mülga';if(status==='tarihsel')return'Tarihsel';if(status==='degisiklik')return'Değişiklik kaydı';return'EPDK listesinde'}
  function populateSelect(select,values){for(const value of values){const option=document.createElement('option');option.value=value;option.textContent=labelMap[value]||value;select.appendChild(option)}}
  function currentFilters(){return{query:normalize(elements.query.value),category:elements.category.value,status:elements.status.value,topic:elements.topic.value,audience:elements.audience.value}}
  function matches(entry,filters){if(filters.category&&entry.category!==filters.category)return false;if(filters.status&&entry.status!==filters.status)return false;if(filters.topic&&!entry.topics.includes(filters.topic))return false;if(filters.audience&&!entry.audiences.includes(filters.audience))return false;if(!filters.query)return true;const haystack=normalize([entry.title,entry.category,entry.impact,...entry.topics.map(item=>labelMap[item]||item),...entry.audiences.map(item=>labelMap[item]||item)].join(' '));return filters.query.split(/\s+/).every(token=>haystack.includes(token))}
  function filterAndRender(){if(!state.catalog)return;const filters=currentFilters();state.filtered=state.catalog.entries.filter(entry=>matches(entry,filters));state.visible=40;renderResults()}
  function resultCard(entry){const selected=state.selected.has(entry.id);const statusClass=entry.status==='mulga'?'mulga':entry.status==='tarihsel'?'tarihsel':'';const topics=entry.topics.slice(0,4).map(item=>`<span>${escapeHtml(labelMap[item]||item)}</span>`).join('');const audiences=entry.audiences.slice(0,3).map(item=>escapeHtml(labelMap[item]||item)).join(' · ');return `<article class="result-card" data-entry-id="${escapeHtml(entry.id)}"><div class="result-top"><div><div class="badges"><span class="badge">${escapeHtml(entry.category)}</span><span class="badge ${statusClass}">${escapeHtml(statusLabel(entry.status))}</span></div><h3>${escapeHtml(entry.title)}</h3></div></div><p>${escapeHtml(entry.impact)}</p><div class="result-meta">${topics}<span>${audiences}</span></div>${entry.status==='mulga'?'<p><strong>Uyarı:</strong> Bu başlık tarihsel/mülga olarak sınıflandırılmıştır; güncel işlem kuralı olarak kullanılmamalıdır.</p>':''}<div class="result-actions"><a href="${escapeHtml(state.catalog.source.url)}" target="_blank" rel="external noopener" data-official>Resmî listede doğrula ↗</a><button type="button" data-copy-title>Başlığı kopyala</button><button type="button" data-select aria-pressed="${selected?'true':'false'}">${selected?'Dosyadan çıkar':'Çalışma dosyasına ekle'}</button></div></article>`}
  function renderResults(){const total=state.filtered.length;const shown=Math.min(total,state.visible);elements.summary.textContent=`${total.toLocaleString('tr-TR')} sonuç · ${shown.toLocaleString('tr-TR')} gösteriliyor`;if(!total){elements.results.innerHTML='<div class="no-results"><strong>Sonuç bulunamadı.</strong><p>Arama terimini kısaltın veya filtreleri temizleyin. Resmî tam listeyi EPDK kaynağından da kontrol edin.</p></div>';return}const cards=state.filtered.slice(0,state.visible).map(resultCard).join('');const more=shown<total?`<button type="button" class="button secondary full" id="loadMore">${Math.min(40,total-shown)} sonuç daha göster</button>`:'';elements.results.innerHTML=cards+more}
  function renderSelected(){const items=[...state.selected.values()];elements.exportSelected.disabled=items.length===0;elements.printSelected.disabled=items.length===0;if(!items.length){elements.selectedList.innerHTML='<p class="empty">Henüz başlık seçilmedi.</p>';return}elements.selectedList.innerHTML=items.map(entry=>`<div class="selected-item" data-selected-id="${escapeHtml(entry.id)}"><strong>${escapeHtml(entry.title)}</strong><small>${escapeHtml(entry.category)} · ${escapeHtml(statusLabel(entry.status))}</small><button type="button" data-remove>Çıkar</button></div>`).join('')}
  async function copyText(text,button){try{await navigator.clipboard.writeText(text);const old=button.textContent;button.textContent='Kopyalandı';setTimeout(()=>{button.textContent=old},1500)}catch{window.prompt('Başlığı kopyalayın:',text)}}
  function download(filename,type,content){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=filename;document.body.appendChild(anchor);anchor.click();anchor.remove();URL.revokeObjectURL(url)}
  function exportSelected(){const selected=[...state.selected.values()];if(!selected.length)return;const payload={schemaVersion:1,generatedAt:new Date().toISOString(),source:state.catalog.source,disclaimer:'ALO186 bağımsız bilgi platformudur. Resmî metin ve yürürlük için EPDK ile Resmî Gazete esas alınır.',selected:selected.map(({id,title,category,status,topics,audiences})=>({id,title,category,status,topics,audiences}))};download('alo186-elektrik-mevzuat-calisma-dosyasi.json','application/json;charset=utf-8',`${JSON.stringify(payload,null,2)}\n`)}
  function setIntent(intent){const config=intentMap[intent];if(!config)return;state.activeIntent=state.activeIntent===intent?null:intent;for(const button of elements.intentGrid.querySelectorAll('[data-intent]'))button.setAttribute('aria-pressed',button.dataset.intent===state.activeIntent?'true':'false');if(!state.activeIntent){elements.audience.value='';elements.topic.value=''}else{elements.audience.value=config.audience;elements.topic.value=config.topic}filterAndRender();document.getElementById('atlas').scrollIntoView({behavior:'smooth',block:'start'})}
  function bindEvents(){elements.form.addEventListener('submit',event=>{event.preventDefault();state.activeIntent=null;elements.intentGrid.querySelectorAll('[data-intent]').forEach(button=>button.setAttribute('aria-pressed','false'));filterAndRender()});for(const control of[elements.category,elements.status,elements.topic,elements.audience])control.addEventListener('change',filterAndRender);elements.query.addEventListener('input',()=>{window.clearTimeout(elements.query._timer);elements.query._timer=window.setTimeout(filterAndRender,180)});elements.reset.addEventListener('click',()=>{elements.form.reset();state.activeIntent=null;elements.intentGrid.querySelectorAll('[data-intent]').forEach(button=>button.setAttribute('aria-pressed','false'));filterAndRender()});elements.intentGrid.addEventListener('click',event=>{const button=event.target.closest('[data-intent]');if(button)setIntent(button.dataset.intent)});elements.results.addEventListener('click',event=>{if(event.target.id==='loadMore'){state.visible+=40;renderResults();return}const card=event.target.closest('[data-entry-id]');if(!card)return;const entry=state.catalog.entries.find(item=>item.id===card.dataset.entryId);if(!entry)return;if(event.target.closest('[data-copy-title]'))copyText(entry.title,event.target.closest('[data-copy-title]'));if(event.target.closest('[data-select]')){if(state.selected.has(entry.id))state.selected.delete(entry.id);else state.selected.set(entry.id,entry);renderSelected();renderResults()}});elements.selectedList.addEventListener('click',event=>{const item=event.target.closest('[data-selected-id]');if(item&&event.target.closest('[data-remove]')){state.selected.delete(item.dataset.selectedId);renderSelected();renderResults()}});elements.exportSelected.addEventListener('click',exportSelected);elements.printSelected.addEventListener('click',()=>{if(state.selected.size)window.print()})}
  async function init(){elements.results.innerHTML='<div class="loading">EPDK elektrik mevzuatı başlık indeksi yükleniyor…</div>';bindEvents();try{const response=await fetch('./catalog.json',{cache:'no-store'});if(!response.ok)throw new Error(`Katalog yüklenemedi: ${response.status}`);state.catalog=await response.json();const categories=state.catalog.categories.map(item=>item.name);const topics=[...new Set(state.catalog.entries.flatMap(item=>item.topics))].sort((a,b)=>(labelMap[a]||a).localeCompare(labelMap[b]||b,'tr'));const audiences=[...new Set(state.catalog.entries.flatMap(item=>item.audiences))].sort((a,b)=>(labelMap[a]||a).localeCompare(labelMap[b]||b,'tr'));populateSelect(elements.category,categories);populateSelect(elements.topic,topics);populateSelect(elements.audience,audiences);elements.entryCount.textContent=state.catalog.coverage.uniqueEntryCount.toLocaleString('tr-TR');elements.checkedAt.textContent=new Intl.DateTimeFormat('tr-TR',{dateStyle:'long',timeZone:'Europe/Istanbul'}).format(new Date(`${state.catalog.source.checkedAt}T12:00:00+03:00`));const params=new URLSearchParams(location.search);if(params.get('q'))elements.query.value=params.get('q');if(params.get('kategori')&&categories.includes(params.get('kategori')))elements.category.value=params.get('kategori');if(params.get('konu')&&topics.includes(params.get('konu')))elements.topic.value=params.get('konu');if(params.get('kullanici')&&audiences.includes(params.get('kullanici')))elements.audience.value=params.get('kullanici');filterAndRender();renderSelected()}catch(error){elements.summary.textContent='Katalog yüklenemedi';elements.results.innerHTML=`<div class="no-results"><strong>Mevzuat kataloğu şu anda açılamadı.</strong><p>${escapeHtml(error.message)}. Resmî EPDK listesini doğrudan açın.</p><a class="button secondary" href="https://www.epdk.gov.tr/Detay/Icerik/23-2-3/elektrik-piyasasi" target="_blank" rel="external noopener">EPDK resmî listesi ↗</a></div>`}}
  init();
})();
