(function(root,factory){
  const api=factory();
  if(typeof module==='object'&&module.exports)module.exports=api;
  if(root&&root.document)api.mount(root.document);
})(typeof globalThis!=='undefined'?globalThis:this,function(){
  'use strict';
  const AFFILIATE_TAG='alo186rehber-21';
  const TYPES=['AC','A','F','B'];
  const num=value=>{if(value===null||value===undefined||value==='')return null;const parsed=Number(String(value).replace(',','.'));return Number.isFinite(parsed)?parsed:null;};
  const round=(value,digits=1)=>{if(value===null||value===undefined||!Number.isFinite(value))return null;const factor=10**digits;return Math.round(value*factor)/factor;};
  const base=(status,title,summary,extra={})=>({status,title,summary,commercialAllowed:false,productClass:null,searchTerm:null,searchUrl:null,recommendedType:null,recommendedResidualMa:null,recommendedPoles:null,currentMarginA:null,revisitDays:90,requirements:[],warnings:[],...extra});
  function typeNeed(input={}){
    const explicit=String(input.manufacturerType||'unknown').toUpperCase();
    if(TYPES.includes(explicit))return {type:explicit,reason:'Bağlı ekipmanın üretici dokümanında açıkça belirtilen RCD tipi önceliklidir.'};
    const load=String(input.loadType||'unknown');
    if(load==='general_residential'||load==='electronic_appliances')return {type:'A',reason:'Modern elektronik yüklerde sinüzoidal AC yanında darbeli DC artık akım olasılığı nedeniyle Tip A başlangıç sınıfıdır.'};
    if(load==='single_phase_drive')return {type:'F',reason:'Tek faz beslenen frekans kontrollü yüklerde bileşik frekanslı artık akımlar için Tip F veya üreticinin açıkça istediği daha üst sınıf gerekir.'};
    if(['three_phase_drive','pv_inverter','ups'].includes(load))return {type:'B',reason:'Üç fazlı doğrultucu/konvertör yüklerinde düzgün DC ve daha yüksek frekans bileşenleri oluşabileceğinden Tip B veya üreticinin açık eşdeğeri gerekir.'};
    if(load==='ev_charging'){
      if(input.dcDetection==='verified_6ma')return {type:'A',reason:'EVSE içinde doğrulanmış 6 mA DC algılama varsa üretici talimatına göre Tip A + RDC-DD düzeni kullanılabilir.'};
      if(input.dcDetection==='type_b_required')return {type:'B',reason:'EVSE üreticisi Tip B istiyorsa daha düşük sınıfa inilmez.'};
      return {type:null,reason:'EV şarjında EVSE içindeki DC algılama ve haricî RCD gereksinimi tam model dokümanından doğrulanmalıdır.'};
    }
    return {type:null,reason:'Yük tipi veya üretici RCD gereksinimi doğrulanmadı.'};
  }
  function recommendedResidual(input={}){return String(input.purpose||'unknown')==='additional_personal'?30:null;}
  function recommendedPoles(input={}){if(input.phase==='single')return 2;if(input.phase==='three')return 4;return null;}
  function searchTermFor(productClass,result){
    const current=result.ratedCurrentA?`${result.ratedCurrentA}A`:'';const residual=result.recommendedResidualMa?`${result.recommendedResidualMa}mA`:'';const poles=result.recommendedPoles?`${result.recommendedPoles}P`:'';const type=result.recommendedType?`Tip ${result.recommendedType}`:'';
    if(productClass==='rcbo')return `${type} RCBO ${poles} ${current} ${residual} IEC 61009-1`.replace(/\s+/g,' ').trim();
    if(productClass==='rccb')return `${type} RCCB ${poles} ${current} ${residual} IEC 61008-1`.replace(/\s+/g,' ').trim();
    if(productClass==='type_f_rcd')return `Tip F RCD ${poles} ${current} ${residual} IEC 62423`.replace(/\s+/g,' ').trim();
    if(productClass==='type_b_rcd')return `Tip B RCD ${poles} ${current} ${residual} IEC 62423`.replace(/\s+/g,' ').trim();
    return null;
  }
  function metrics(input={}){
    const ratedCurrentA=num(input.ratedCurrentA),upstreamBreakerA=num(input.upstreamBreakerA);
    return {ratedCurrentA,upstreamBreakerA,currentMarginA:ratedCurrentA!==null&&upstreamBreakerA!==null?round(ratedCurrentA-upstreamBreakerA,1):null,recommendedResidualMa:recommendedResidual(input),recommendedPoles:recommendedPoles(input),...typeNeed(input)};
  }
  function calculate(input={}){
    const m=metrics(input);const done=result=>({...result,...m,recommendedType:m.type,typeReason:m.reason});
    if(input.emergency)return done(base('emergency','Enerjiyi güvenle kesin; ürün seçimine devam etmeyin','Elektrik çarpması, duman, ark, yanık kokusu veya erime varsa panoya yaklaşmayın. Güvenli biçimde enerjiyi kestirin; yangın ya da yaralanmada 112 önceliklidir.'));
    if(input.repeatedTrip==='active_fault')return done(base('fault_first','Sürekli atan röleyi daha büyük veya farklı tip ürünle susturmayın','Tekrarlayan açma; cihaz, kablo, nem, nötr-toprak teması, toplam kaçak veya RCD arızası göstergesi olabilir. İzolasyon ve kaçak akım ölçümü yapılmadan alışveriş bağlantısı açılmaz.'));
    if(input.condition==='recalled'||input.recallChecked==='recalled')return done(base('stop_use','Geri çağrılmış cihazı kullanmayın','Tam marka-model için resmî kullanım durdurma veya geri çağırma kaydı varsa cihazı yeniden devreye almayın; üreticinin resmî sürecini izleyin.'));
    if(['burned','cracked','wet','hot','test_failed'].includes(input.condition||''))return done(base('stop_use','Hasarlı veya testi başarısız RCD kullanılmamalıdır','Yanık, çatlak, ıslanma, olağandışı ısı veya çalışmayan test düğmesi varsa devre yetkin kişi tarafından güvenli biçimde incelenmelidir.'));
    if(input.condition!=='sound')return done(base('evidence_required','Cihazın fiziksel durumunu doğrulayın','Gövde, klemens, etiket, test düğmesi ve bağlantılar sağlam ve kuru olmalıdır.'));
    if(input.userRole==='consumer'&&input.qualifiedSpecification!=='yes')return done(base('professional','Önce yetkin elektrikçiden devre şartnamesi alın','RCD pano içinde çalışan bir koruma cihazıdır. Kullanıcı yalnız ürün etiketiyle tip, mA, kutup ve akım sınıfını güvenli biçimde belirleyemez; devre ve bağlı yük ölçülmelidir.'));
    if(input.qualifiedSpecification!=='yes')return done(base('evidence_required','Yetkin kişi tarafından hazırlanmış devre şartnamesi eksik','Bağlı yük, topraklama sistemi, iletken, kısa devre/arıza koşulları, üst koruma ve seçicilik birlikte doğrulanmalıdır.'));
    if(['industrial','medical','fire_only','upstream_selective'].includes(input.applicationScope||'')||['fire_protection','upstream_selective'].includes(input.purpose||''))return done(base('professional','Bu devre profesyonel koruma koordinasyonu gerektirir','Endüstriyel, medikal, yangın koruması veya üst kademe seçicilik için yalnız mA ve tip etiketiyle ürün seçilmez. Zaman-akım koordinasyonu, topraklama ve süreklilik gereksinimleri projelendirilmelidir.'));
    if(input.earthingSystem==='tn_c')return done(base('professional','TN-C bölümünde RCD seçimi tüketici akışına uygun değildir','PEN ayrımı, nötr ve koruma iletkeni düzeni yetkin kişi tarafından doğrulanmadan RCD eklenmemelidir.'));
    if(!['tt','tn_s','tn_c_s'].includes(input.earthingSystem||''))return done(base('evidence_required','Topraklama ve nötr düzenini doğrulayın','TT, TN-S veya TN-C-S düzeni; PEN ayrım noktası ve koruma iletkeni sürekliliği bilinmeden RCD seçimi tamamlanamaz.'));
    if(input.neutralArrangement==='shared')return done(base('design_gap','Paylaşılan veya karışmış nötr önce düzeltilmelidir','RCD arkasındaki devrelerin nötrleri başka RCD/devrelerle paylaşılırsa hatalı açma veya koruma kaybı oluşabilir. Ürün değiştirmek yerine nötr ayrımı düzeltilmelidir.'));
    if(input.neutralArrangement!=='verified')return done(base('evidence_required','Nötr ayrımını doğrulayın','Korunan bütün aktif iletkenler aynı RCD üzerinden geçmeli; koruma iletkeni RCD içinden geçirilmemeli ve nötrler devreler arasında karışmamalıdır.'));
    if(!m.recommendedPoles)return done(base('evidence_required','Faz yapısını doğrulayın','Monofaze devrede tipik olarak iki kutuplu, trifaze+nötr devrede dört kutuplu düzen gerekir; ürün ve proje bilgisi önceliklidir.'));
    if(!m.type)return done(base('evidence_required','RCD tipini üretici dokümanından doğrulayın',m.typeReason));
    if(input.manufacturerType!=='unknown'&&String(input.manufacturerType).toUpperCase()!==m.type)return done(base('design_gap','Seçilen tip üretici gereksinimiyle uyuşmuyor',`Üretici ${String(input.manufacturerType).toUpperCase()} tipi isterken ${m.type} dışına çıkılamaz.`));
    if(input.loadType==='ev_charging'&&!['verified_6ma','type_b_required'].includes(input.dcDetection||''))return done(base('evidence_required','EVSE DC kaçak algılama düzenini doğrulayın','EV şarjında 6 mA DC algılama/RDC-DD veya Tip B gereksinimi ürünün tam model kılavuzundan ve proje şartından doğrulanmalıdır.'));
    if(input.purpose!=='additional_personal')return done(base('professional','Bu araç yalnız ilave kişisel koruma ön seçimi içindir','100 mA, 300 mA, gecikmeli veya yangın amaçlı düzenler; dokunma gerilimi, topraklama ve seçicilik hesabı gerektirir.'));
    if(!m.ratedCurrentA||!m.upstreamBreakerA||m.ratedCurrentA<1||m.upstreamBreakerA<1)return done(base('evidence_required','RCD anma akımı ve üst koruma değerini girin','RCCB anma akımı, kısa devre koruması değildir; üstteki sigorta/şalterle üretici koordinasyonu doğrulanmalıdır.'));
    if(input.deviceKind==='rccb'&&input.overcurrentProtection!=='yes')return done(base('design_gap','RCCB için üst akım koruması doğrulanmadı','RCCB kaçak akıma karşı çalışır; aşırı akım ve kısa devre için uygun üst koruma ayrıca gerekir.'));
    if(input.deviceKind==='rccb'&&m.ratedCurrentA<m.upstreamBreakerA)return done(base('design_gap','RCCB anma akımı üst korumadan düşük','Üretici koordinasyonu aksi yönde kanıtlanmadıkça RCCB anma akımı üst koruma değerinin altında seçilmemelidir.',{warnings:[`RCD ${m.ratedCurrentA} A; üst koruma ${m.upstreamBreakerA} A.`]}));
    if(input.deviceKind==='rcbo'&&input.overcurrentProtection!=='integrated')return done(base('evidence_required','RCBO aşırı akım fonksiyonu doğrulanmadı','Tam modelin IEC 61009-1 kapsamındaki RCBO olduğu, kutup, kesme kapasitesi ve açma eğrisi devreyle eşleştirilmelidir.'));
    if(!['rccb','rcbo'].includes(input.deviceKind||''))return done(base('evidence_required','RCCB ile RCBO ayrımını doğrulayın','RCCB yalnız artık akım; RCBO artık akım ile aşırı akım korumasını birleştirir. Etiketteki tam ürün sınıfını kontrol edin.'));
    if(input.residualMa!=='30')return done(base('design_gap','İlave kişisel koruma için 30 mA sınıfı doğrulanmadı','Bu akış yalnız 30 mA ilave koruma ön seçimini değerlendirir. Farklı hassasiyetler profesyonel koordinasyon gerektirir.'));
    if(Number(input.poles)!==m.recommendedPoles)return done(base('design_gap','Kutup sayısı faz yapısıyla uyuşmuyor',`${input.phase==='single'?'Monofaze':'Trifaze'} devre için bu ön seçimde ${m.recommendedPoles} kutup beklenir; tam devre şeması yetkin kişi tarafından doğrulanmalıdır.`));
    const selectedType=String(input.selectedType||'unknown').toUpperCase();
    if(!TYPES.includes(selectedType)){
      const productClass=m.type==='F'?'type_f_rcd':m.type==='B'?'type_b_rcd':input.deviceKind;const result=done(base('replace_candidate','Uygun RCD tipi henüz seçilmedi',`${m.type} tipi, ${m.recommendedPoles} kutup, 30 mA ve devreyle koordineli anma akımı doğrulanmalıdır.`,{commercialAllowed:true,productClass,requirements:[`Tip ${m.type}`,`${m.recommendedPoles} kutup`,`30 mA`,`${m.ratedCurrentA} A anma akımı`,`Tam model IEC 61008-1/61009-1 ve gerekiyorsa IEC 62423 kanıtı`]}));result.searchTerm=searchTermFor(productClass,result);return result;
    }
    if(selectedType!==m.type){
      const productClass=m.type==='F'?'type_f_rcd':m.type==='B'?'type_b_rcd':input.deviceKind;const result=done(base('replace_candidate','Seçilen RCD tipi yük dalga biçimine uygun değil',`${selectedType} yerine üretici ve yük sınıfına göre Tip ${m.type} doğrulanmalıdır.`,{commercialAllowed:true,productClass,requirements:[`Tip ${m.type}`,`${m.recommendedPoles} kutup`,`30 mA`,`${m.ratedCurrentA} A anma akımı`]}));result.searchTerm=searchTermFor(productClass,result);return result;
    }
    if(input.recallChecked!=='yes'||input.certification!=='yes')return done(base('evidence_required','Tam model güvenlik ve belge kontrolü eksik','Üretici, model, standarda uygunluk, ürün güvenliği duyurusu, klemens torku ve çalışma gerilimi tam model üzerinden doğrulanmalıdır.'));
    if(input.testButton==='fail')return done(base('stop_use','Test düğmesi çalışmıyor; cihazı kullanmayın','Test düğmesi cihazın mekanizmasını kontrol eder ancak ölçüm cihazı testinin yerine geçmez. Başarısız cihaz yetkin kişi tarafından değiştirilmelidir.'));
    if(input.instrumentTest==='fail')return done(base('stop_use','Ölçümlü açma testi başarısız','Açma süresi/akımı veya devre ölçümleri uygun değilse ürün bağlantısı açılmaz; tesisat ve cihaz birlikte incelenmelidir.'));
    if(input.ownership==='owned'){
      if(input.testButton!=='pass'||input.instrumentTest!=='pass')return done(base('test_first','Mevcut cihazı ölçümlü olarak test ettirin','Test düğmesi tek başına açma süresi, açma akımı, çevrim veya topraklama uygunluğunu kanıtlamaz. Yetkin kişi ölçümlü testi tamamlamalıdır.'));
      return done(base('no_buy','Mevcut RCD yeterli — yeni ürün almayın',`Mevcut ${input.deviceKind.toUpperCase()} Tip ${selectedType}, ${m.ratedCurrentA} A, 30 mA ve ${m.recommendedPoles} kutup şartlarını karşılıyor; test düğmesi ve ölçümlü test başarılı.`,{requirements:['Üretici test periyodunu izleyin.','Klemens ısısı, etiket ve ürün güvenliği duyurularını periyodik kontrol edin.']}));
    }
    const productClass=m.type==='F'?'type_f_rcd':m.type==='B'?'type_b_rcd':input.deviceKind;const result=done(base('qualified','Teknik sınıf eşleşti; satın almadan önce tam modeli yeniden doğrulayın',`${input.deviceKind.toUpperCase()} Tip ${m.type}, ${m.recommendedPoles} kutup, 30 mA ve ${m.ratedCurrentA} A ön şartları eşleşiyor. Kurulum, ölçüm ve devreye alma yetkin elektrikçi tarafından yapılmalıdır.`,{commercialAllowed:true,productClass,requirements:[`Tip ${m.type}`,`${m.recommendedPoles} kutup`,`30 mA`,`${m.ratedCurrentA} A`,input.deviceKind==='rcbo'?'RCBO kesme kapasitesi ve açma eğrisi':'RCCB üst koruma koordinasyonu','Tam model standardı ve klemens torku']}));result.searchTerm=searchTermFor(productClass,result);return result;
  }
  function amazonUrl(term){return term?`https://www.amazon.com.tr/s?k=${encodeURIComponent(term)}&tag=${AFFILIATE_TAG}`:null;}
  function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));}
  function read(doc){const value=id=>{const el=doc.getElementById(id);if(!el)return '';return el.type==='checkbox'?el.checked:el.value;};return {emergency:value('emergency'),repeatedTrip:value('repeatedTrip'),condition:value('condition'),userRole:value('userRole'),qualifiedSpecification:value('qualifiedSpecification'),applicationScope:value('applicationScope'),loadType:value('loadType'),manufacturerType:value('manufacturerType'),dcDetection:value('dcDetection'),purpose:value('purpose'),phase:value('phase'),earthingSystem:value('earthingSystem'),neutralArrangement:value('neutralArrangement'),deviceKind:value('deviceKind'),selectedType:value('selectedType'),residualMa:value('residualMa'),poles:value('poles'),ratedCurrentA:value('ratedCurrentA'),upstreamBreakerA:value('upstreamBreakerA'),overcurrentProtection:value('overcurrentProtection'),recallChecked:value('recallChecked'),certification:value('certification'),testButton:value('testButton'),instrumentTest:value('instrumentTest'),ownership:value('ownership')};}
  function render(doc,result){
    const output=doc.getElementById('result');if(!output)return;const req=(result.requirements||[]).map(item=>`<li>${escapeHtml(item)}</li>`).join('');const warnings=(result.warnings||[]).map(item=>`<li>${escapeHtml(item)}</li>`).join('');const summary=result.recommendedType?`<div class="metrics"><span><b>Tip ${escapeHtml(result.recommendedType)}</b> dalga biçimi</span><span><b>${escapeHtml(result.recommendedPoles)}P</b> kutup</span><span><b>${escapeHtml(result.recommendedResidualMa||'—')} mA</b> hassasiyet</span><span><b>${escapeHtml(result.currentMarginA===null?'—':result.currentMarginA)} A</b> RCD/üst koruma farkı</span></div>`:'';output.className=`result status-${escapeHtml(result.status)}`;output.innerHTML=`<p class="status">${escapeHtml(result.status)}</p><h2>${escapeHtml(result.title)}</h2><p>${escapeHtml(result.summary)}</p>${result.typeReason?`<p class="reason"><strong>Tip gerekçesi:</strong> ${escapeHtml(result.typeReason)}</p>`:''}${summary}${req?`<h3>Doğrulanacak teknik alanlar</h3><ul>${req}</ul>`:''}${warnings?`<ul>${warnings}</ul>`:''}`;output.hidden=false;
    const gate=doc.getElementById('affiliateGate'),link=doc.getElementById('affiliateLink'),checks=[...doc.querySelectorAll('[data-affiliate-check]')];checks.forEach(check=>{check.checked=false;});if(result.commercialAllowed&&result.searchTerm){gate.hidden=false;link.dataset.term=result.searchTerm;link.href='#';link.setAttribute('aria-disabled','true');link.textContent='Üç onayı tamamlayın';}else{gate.hidden=true;link.href='#';link.removeAttribute('data-term');link.setAttribute('aria-disabled','true');}doc.getElementById('exportJson').disabled=false;doc.getElementById('calendar').disabled=false;doc.getElementById('printResult').disabled=false;doc.defaultView.__alo186RcdResult=result;
  }
  function download(doc,name,type,text){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),anchor=doc.createElement('a');anchor.href=url;anchor.download=name;doc.body.appendChild(anchor);anchor.click();anchor.remove();setTimeout(()=>URL.revokeObjectURL(url),0);}
  function ics(result){const start=new Date(Date.now()+(result.revisitDays||90)*86400000),end=new Date(start.getTime()+30*60000),stamp=new Date(),fmt=date=>date.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z');return ['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//ALO186//RCD Kontrol//TR','CALSCALE:GREGORIAN','BEGIN:VEVENT',`UID:alo186-rcd-${Date.now()}@alo186.com`,`DTSTAMP:${fmt(stamp)}`,`DTSTART:${fmt(start)}`,`DTEND:${fmt(end)}`,'SUMMARY:Kaçak akım rölesi güvenlik ve test kontrolü','DESCRIPTION:Üreticinin test talimatı; test düğmesi; ölçümlü açma testi; klemens ısısı; etiket; nötr ayrımı ve ürün güvenliği duyuruları yeniden kontrol edilsin.','END:VEVENT','END:VCALENDAR'].join('\r\n');}
  function mount(doc){
    const form=doc.getElementById('rcdForm');if(!form)return;form.addEventListener('submit',event=>{event.preventDefault();render(doc,calculate(read(doc)));doc.getElementById('result').focus();});doc.querySelectorAll('[data-affiliate-check]').forEach(check=>check.addEventListener('change',()=>{const link=doc.getElementById('affiliateLink'),checks=[...doc.querySelectorAll('[data-affiliate-check]')],ready=checks.every(item=>item.checked);if(ready&&link.dataset.term){link.href=amazonUrl(link.dataset.term);link.removeAttribute('aria-disabled');link.textContent='Amazon Türkiye’de teknik sınıfı karşılaştır';}else{link.href='#';link.setAttribute('aria-disabled','true');link.textContent='Üç onayı tamamlayın';}}));doc.getElementById('affiliateLink').addEventListener('click',event=>{if(event.currentTarget.getAttribute('aria-disabled')==='true')event.preventDefault();});doc.getElementById('exportJson').addEventListener('click',()=>{const result=doc.defaultView.__alo186RcdResult;if(!result)return;const payload={generatedAt:new Date().toISOString(),source:'ALO186 bağımsız bilgi platformu',route:'/hesaplama/kacak-akim-rolesi-tip-secimi-uygunluk/',result,personalDataCollected:false,commercialFields:{price:false,stock:false,rating:false,seller:false,delivery:false,warranty:false}};download(doc,'alo186-kacak-akim-rolesi-teknik-fis.json','application/json;charset=utf-8',JSON.stringify(payload,null,2));});doc.getElementById('calendar').addEventListener('click',()=>{const result=doc.defaultView.__alo186RcdResult;if(result)download(doc,'alo186-kacak-akim-rolesi-kontrol.ics','text/calendar;charset=utf-8',ics(result));});doc.getElementById('printResult').addEventListener('click',()=>doc.defaultView.print());
  }
  return {calculate,metrics,typeNeed,recommendedResidual,recommendedPoles,amazonUrl,ics,mount};
});
