(()=>{'use strict';
const $=id=>document.getElementById(id),KEY='alo186_mode2_ev_outlet_v1',TTL=540*86400000,MAX=18;
const today=()=>new Date().toISOString().slice(0,10);$('date').value=today();
function load(){let x=[];try{x=JSON.parse(localStorage.getItem(KEY)||'[]')}catch(_){x=[]}const now=Date.now();x=x.filter(r=>r&&now-r.createdAt<TTL).slice(-MAX);localStorage.setItem(KEY,JSON.stringify(x));return x}
function save(x){localStorage.setItem(KEY,JSON.stringify(x.slice(-MAX)))}
function labels(id){const el=$(id);return el.options[el.selectedIndex].textContent}
function render(){const x=load(),box=$('records');if(!x.length){box.innerHTML='<p class="small">Henüz kayıt yok.</p>';return}box.replaceChildren(...x.slice().reverse().map(r=>{const d=document.createElement('div');d.className='record';const s=document.createElement('strong');s.textContent=`${r.date} · ${r.useLabel}`;const p=document.createElement('p');p.className='small';p.textContent=`${r.outletLabel} · ${r.currentLabel} · ${r.decision}`;d.append(s,p);return d}))}
function evaluate(r){let level='good',label='Satın almama',title='Yeni ürün için doğrulanmış ihtiyaç oluşmadı.',summary='Mevcut cihaz hasarsızsa, olay üretmiyorsa ve kurulum koşulları doğrulanmışsa kullanmaya devam edin.',steps=['Üretici kılavuzunu ve priz/devre kontrol kaydını saklayın.','Priz ve fişi periyodik olarak enerjisiz görsel kontrol edin.'],commercial=false;
const danger=r.heat||r.wet;const fullGate=r.manual&&r.iccpd&&r.tempDetect&&r.earth&&r.circuit&&r.protection&&r.noAdapter;
if(danger){level='bad';label='Şarjı durdur';title='Priz veya bağlantıda güvenlik sınırı aşıldı.';summary='Yeni cihaz satın almak mevcut priz, bağlantı veya fiziksel hasarı güvenli hâle getirmez.';steps=['Şarjı durdurun ve bağlantıyı zorlamayın.','Priz, devre, PE ve koruma düzenini elektrikçiye kontrol ettirin.','Üretici/yetkili servis olay kodunu değerlendirsin.','Tehlike sürerken ürün ve satış ortaklığı yolu kapalıdır.']}
else if(r.useCase==='daily'||(r.currentClass==='high'&&(r.outlet==='household'||r.outlet==='unknown'))){level='warn';label='Profesyonel devre kararı';title='Kullanım senaryosu taşınabilir ürün seçiminden önce tesis doğrulaması gerektiriyor.';summary='Günlük veya yüksek akımlı şarj, yalnız taşınabilir cihaz seçimiyle çözülemez.';steps=['Tek hat, devre kesiti, bağlantı noktası ve RCD/DC kaçak korumasını doğrulatın.','Sabit EVSE/wallbox seçeneğini kullanım profiliyle karşılaştırın.','Priz veya devre kabulü tamamlanmadan affiliate yolu açılmaz.']}
else if(!fullGate){level='warn';label='Belge ve kurulum eksiği';title='Mode 2 ürün karşılaştırmasına geçmek için güven kapıları eksik.';summary='IC-CPD, sıcaklık algılama, PE, devre ve koruma doğrulanmadan ürün seçmeyin.';steps=[];if(!r.manual)steps.push('Tam model üretici kılavuzunu doğrulayın.');if(!r.iccpd)steps.push('IC-CPD ve uygunluk kapsamını belgeden doğrulayın.');if(!r.tempDetect)steps.push('Fiş/priz sıcaklık algılamasının tam modelde bulunduğunu doğrulayın.');if(!r.earth||!r.circuit||!r.protection)steps.push('Priz, PE, devre ve koruma düzenini elektrikçiye kontrol ettirin.');if(!r.noAdapter)steps.push('Uzatma, çoklayıcı ve üçüncü taraf adaptör kullanmayın.')}
else if((r.session==='reduced'||r.session==='stopped'||r.session==='voltage')&&!r.repeat){level='warn';label='Oturumu tekrar doğrula';title='Tek oturum ürün arızasını veya satın alma ihtiyacını kanıtlamaz.';summary='Aynı koşullarda olay kaydı, priz sıcaklığı ve gerilim davranışını yeniden kontrol edin.';steps=['Araç ve IC-CPD olay saatlerini karşılaştırın.','Tekrarda priz/devre incelemesine geçin.']}
else if(r.repeat&&(r.session==='reduced'||r.session==='stopped'||r.session==='voltage')){level='warn';label='Kök neden ayrımı';title='Tekrarlayan olayda önce priz, devre, araç ve cihazı ayırın.';summary='Yeni taşınabilir şarj cihazı, priz veya araç kaynaklı olayı otomatik çözmez.';steps=['Bilinen uygun priz/devre ve üretici prosedürüyle çapraz kontrol yapın.','Gerilim düşümü ve bağlantı sıcaklığını yetkili personelle ölçün.']}
else if(r.purpose==='purchase'&&r.useCase==='occasional'&&fullGate&&(r.outlet==='dedicated'||r.outlet==='industrial'||(r.outlet==='household'&&r.currentClass!=='high'))){level='good';label='Nitelikli kategori';title='Seyrek kullanım için teknik ürün karşılaştırmasına geçebilirsiniz.';summary='Bu sonuç ürün onayı değildir; tam model akım, fiş, araç ve kurulum uyumu ayrıca doğrulanır.';steps=['Mevcut cihazı seçenek olarak koruyun.','Kablo uzunluğu, akım ayarı, IP sınıfı ve servis belgesini karşılaştırın.'];commercial=true}
return{level,label,title,summary,steps,commercial}}
$('form').addEventListener('submit',e=>{e.preventDefault();const r={createdAt:Date.now(),date:$('date').value||today(),useCase:$('useCase').value,useLabel:labels('useCase'),outlet:$('outlet').value,outletLabel:labels('outlet'),currentClass:$('currentClass').value,currentLabel:labels('currentClass'),purpose:$('purpose').value,session:$('session').value,manual:$('manual').checked,iccpd:$('iccpd').checked,tempDetect:$('tempDetect').checked,earth:$('earth').checked,circuit:$('circuit').checked,protection:$('protection').checked,noAdapter:$('noAdapter').checked,repeat:$('repeat').checked,heat:$('heat').checked,wet:$('wet').checked,officialRecord:false,retentionMode:'per-record'};const out=evaluate(r);r.decision=out.label;const all=load();all.push(r);save(all);render();$('result').classList.remove('hidden');$('state').textContent=out.label;$('state').className=`pill ${out.level}`;$('title').textContent=out.title;$('summary').textContent=out.summary;$('steps').replaceChildren(...out.steps.map(t=>{const li=document.createElement('li');li.textContent=t;return li}));$('commercial').classList.toggle('hidden',!out.commercial);$('result').scrollIntoView({behavior:'smooth',block:'start'})});
$('export').addEventListener('click',()=>{const data={tool:'ALO186 taşınabilir EV şarj ve priz uygunluk günlüğü',exportedAt:new Date().toISOString(),rawPersonalDataCollected:false,officialRecord:false,records:load()};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='alo186-mode2-ev-sarj-gunlugu.json';a.click();URL.revokeObjectURL(a.href)});
$('calendar').addEventListener('click',()=>{const d=new Date();d.setDate(d.getDate()+180);const fmt=x=>x.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z/,'Z');const ics=`BEGIN:VCALENDAR\nVERSION:2.0\nPRODID:-//ALO186//Mode2 Review//TR\nBEGIN:VEVENT\nUID:${Date.now()}@alo186.com\nDTSTAMP:${fmt(new Date())}\nDTSTART:${fmt(d)}\nSUMMARY:Taşınabilir EV şarj cihazı ve priz kontrolü\nDESCRIPTION:Priz, fiş, IC-CPD, PE, koruma ve oturum kayıtlarını yeniden kontrol edin.\nEND:VEVENT\nEND:VCALENDAR`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([ics],{type:'text/calendar'}));a.download='mode2-ev-sarj-kontrol.ics';a.click();URL.revokeObjectURL(a.href)});render()})();