(function(root,factory){
  const api=factory();
  if(typeof module==='object'&&module.exports){module.exports=api;}
  root.Alo186DecisionRules=api;
})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const categories=[
    {id:'outage',label:'Kesinti ve şebeke',note:'Tam/kısmi kesinti, gerilim, faz ve nötr belirtileri'},
    {id:'panel',label:'Pano ve koruma',note:'Sigorta, kaçak akım, priz, ısınma ve temas riski'},
    {id:'external',label:'Dış şebeke',note:'Sokak lambası, direk, trafo ve düşmüş kablo'},
    {id:'meter',label:'Sayaç ve abonelik',note:'Sayaç ekranı, mühür, kaçak şüphesi ve işlemler'}
  ];

  const problems=[
    {id:'area_outage',category:'outage',label:'Bölgede elektrik yok',note:'Sokak veya komşu binalar da karanlık',defaultRoute:'official',steps:['Planlı kesinti ekranını kontrol edin.','Kayıt yoksa 186’yı arayın.'],prep:['İl ve ilçe','Kesintinin başladığı saat','Komşu/sokak gözlemi']},
    {id:'building_outage',category:'outage',label:'Yalnız binada / ortak alanda elektrik yok',note:'Birden fazla bağımsız bölüm veya ortak sistem etkileniyor',defaultRoute:'building',steps:['Bina yönetimi veya teknik sorumluya bildirin.','Ana dağıtım ve ortak sistem kontrolünü yetkili personele yaptırın.'],prep:['Etkilenen blok/ortak alan','Komşu binalarda enerji durumu','Başlangıç saati']},
    {id:'unit_outage',category:'outage',label:'Yalnız dairede / iş yerinde elektrik yok',note:'Komşularda ve ortak alanda enerji var',defaultRoute:'electrician',steps:['Panoyu açmadan görülebilen şalter konumunu not edin.','Yetkili elektrikçiden iç tesisat kontrolü isteyin.'],prep:['Etkilenen alan','Şalter durumu','Bağlı cihazlar']},
    {id:'partial_outage',category:'outage',label:'Bazı odalar veya prizler çalışmıyor',note:'Kısmi enerji, faz veya bağlantı sorunu olabilir',defaultRoute:'electrician',steps:['Etkilenen devreleri ve cihazları not edin.','Tekrar enerji vermeye çalışmadan yetkili elektrikçi çağırın.'],prep:['Çalışmayan oda/prizler','Aynı anda çalışan cihazlar','Panodaki görünen durum'],warning:'Faz veya nötr bağlantı sorunu cihaz hasarı ve ısınma riski oluşturabilir.'},
    {id:'flicker',category:'outage',label:'Elektrik gelip gidiyor',note:'Sık kesilme, titreme veya yeniden başlama',requiresScope:true,routeByScope:{area:'official',building:'mixed',unit:'electrician',unknown:'mixed'},steps:['Hassas cihazları kapatın.','Belirtinin komşularda olup olmadığını güvenli biçimde karşılaştırın.'],prep:['Başlama zamanı','Tekrarlama sıklığı','Etkilenen cihazlar'],warning:'Sık açma-kapama elektronik cihazlara zarar verebilir.'},
    {id:'bright_dim',category:'outage',label:'Lambalar aşırı parlak veya sönük',note:'Düşük/yüksek gerilim veya nötr belirtisi olabilir',requiresScope:true,routeByScope:{area:'official',building:'mixed',unit:'electrician',unknown:'mixed'},steps:['Hassas cihazları kapatın ve prizden ayırın.','Komşu/ortak alan durumunu yalnız güvenli biçimde kontrol edin.'],prep:['Parlaklık değişiminin zamanı','Etkilenen odalar','Komşu durumu'],warning:'Aşırı parlaklık nötr sorunu veya yüksek gerilim belirtisi olabilir; cihazları çalıştırmayın.'},
    {id:'phase_loss',category:'outage',label:'Tek faz eksik veya üç fazlı cihaz çalışmıyor',note:'Bazı bölümler enerjili, bazıları değil',requiresScope:true,routeByScope:{area:'official',building:'mixed',unit:'electrician',unknown:'mixed'},steps:['Üç fazlı motor ve cihazları çalıştırmayın.','Yetkili teknik servis veya 186 ile kapsamı doğrulayın.'],prep:['Çalışmayan faz/bölüm','Üç fazlı cihazlar','Komşu veya bina durumu'],warning:'Faz eksikliği motorlarda aşırı akım ve hasar oluşturabilir.'},
    {id:'neutral_suspect',category:'outage',label:'Nötr arızası şüphesi',note:'Gerilim dengesizliği, cihaz gövdeleri veya parlaklık değişimi',requiresScope:true,routeByScope:{area:'official',building:'mixed',unit:'electrician',unknown:'mixed'},steps:['Cihazları kapatın ve enerjili bölümlere dokunmayın.','Yetkili elektrikçi/EDAŞ tarafından ölçüm yapılmasını isteyin.'],prep:['Fazlar arası belirti farkı','Etkilenen cihazlar','Komşu/bina durumu'],warning:'Nötr arızası ciddi cihaz hasarı ve elektrik çarpması riski oluşturabilir.'},

    {id:'rcd_trips',category:'panel',label:'Kaçak akım rölesi atıyor',note:'Röle açıyor veya tekrar kapanmıyor',defaultRoute:'electrician',steps:['Röleyi tekrar tekrar kaldırmayın.','Bağlı cihazlar ve tesisatı yetkili elektrikçiye kontrol ettirin.'],prep:['Hangi cihaz çalışırken açtığı','Islak alan veya su teması','Röle üzerindeki değerler']},
    {id:'main_breaker_trips',category:'panel',label:'Ana sigorta / şalter atıyor',note:'Yüklenme, kısa devre veya arıza olabilir',defaultRoute:'electrician',steps:['Şalteri tekrar tekrar kaldırmayın.','Yük ve tesisat kontrolü isteyin.'],prep:['Açma zamanı','Aynı anda çalışan büyük yükler','Şalter etiketi ve görünümü']},
    {id:'breaker_hot',category:'panel',label:'Sigorta veya şalter ısınıyor',note:'Dokunmadan hissedilen sıcaklık, renk değişimi veya koku',defaultRoute:'electrician',steps:['Yükü güvenli biçimde azaltın; panoyu açmayın.','Acil yetkili elektrikçi kontrolü isteyin.'],prep:['Isınan eleman','Çalışan yükler','Renk/koku değişimi'],warning:'Aşırı ısınma gevşek bağlantı veya aşırı yük nedeniyle yangın riski oluşturabilir.'},
    {id:'panel_noise',category:'panel',label:'Panodan uğultu, çıtırtı veya ark sesi geliyor',note:'Normal olmayan elektriksel ses',defaultRoute:'electrician',steps:['Panoya yaklaşmayın ve kapağını açmayın.','Ses sürüyorsa acil teknik servis isteyin.'],prep:['Sesin türü ve süresi','Yanık kokusu/duman olup olmadığı','Çalışan büyük yükler'],warning:'Çıtırtı veya ark sesi acil bağlantı arızası belirtisi olabilir.'},
    {id:'burning_smell',category:'panel',label:'Yanık kokusu var',note:'Priz, pano, sayaç veya cihaz yakınında',defaultRoute:'electrician',steps:['Güvenli mesafede kalın; panoyu açmayın.','Duman, kıvılcım veya ısınma artarsa 112’yi arayın.'],prep:['Kokunun geldiği bölge','Duman/kıvılcım bilgisi','Etkilenen cihazlar'],warning:'Yanık kokusu yangın öncesi belirti olabilir; enerji vermeye devam etmeyin.',revenueAllowed:false},
    {id:'socket_burn',category:'panel',label:'Prizde kararma, erime veya ısınma var',note:'Fiş/priz çevresinde fiziksel hasar',defaultRoute:'electrician',steps:['Prizi kullanmayın ve fişi zorlamayın.','Yetkili elektrikçi tarafından priz, iletken ve bağlantı kontrolü yaptırın.'],prep:['Priz fotoğrafı','Bağlı cihaz gücü','Isınmanın süresi'],warning:'Hasarlı priz yangın ve elektrik çarpması riski oluşturur.'},
    {id:'touch_voltage',category:'panel',label:'Cihaz gövdesinde elektrik hissediliyor',note:'Çarpılma, karıncalanma veya metal gövdede gerilim şüphesi',inherentDanger:true,steps:['Cihaza ve metal gövdeye tekrar dokunmayın.','Yaralanma varsa 112’yi arayın.','Yetkili elektrikçi ile topraklama ve kaçak kontrolü yaptırın.'],prep:['Etkilenen cihaz','Yaralanma bilgisi','Islak ortam olup olmadığı']},

    {id:'streetlight_off',category:'external',label:'Sokak lambası yanmıyor',note:'Tek veya birden fazla dış aydınlatma arızası',defaultRoute:'official',steps:['Direğe yaklaşmadan konumu not edin.','186 veya resmî aydınlatma kanalından bildirin.'],prep:['İl/ilçe','Yakın adres veya direk numarası','Kaç armatürün etkilendiği']},
    {id:'pole_spark',category:'external',label:'Direkten veya hattan kıvılcım çıkıyor',note:'Ark, patlama veya yanma belirtisi',inherentDanger:true,steps:['Bölgeden uzaklaşın.','112 ve 186’yı arayın.'],prep:['Güvenli konum bilgisi','Direk/hat/trafo ayrımı','Yangın veya yaralanma bilgisi']},
    {id:'fallen_conductor',category:'external',label:'Kablo yere düştü',note:'Kopmuş veya sarkmış iletken',inherentDanger:true,steps:['En az birkaç metre uzaklaşın.','İnsanları ve hayvanları uzak tutun.','112 ve 186’ya bildirin.'],prep:['Güvenli konum bilgisi','Kablonun temas ettiği alan','Yaralanma/yangın bilgisi']},
    {id:'transformer_noise',category:'external',label:'Trafo olağandışı ses yapıyor',note:'Aşırı uğultu, patlama, koku veya yağ kaçağı',defaultRoute:'official',steps:['Trafoya yaklaşmayın.','186’ya ses, koku ve konum bilgisini bildirin.'],prep:['Trafo konumu','Ses/koku/duman bilgisi','Başlama zamanı'],warning:'Duman, patlama veya yangın varsa 112’yi de arayın.'},
    {id:'damaged_pole',category:'external',label:'Direk eğilmiş veya hasarlı',note:'Devrilme, kırılma veya taşıt çarpması',inherentDanger:true,steps:['Direğin devrilme alanından uzaklaşın.','112 ve 186’ya konum verin.'],prep:['Güvenli konum','Direğin durumu','Kablo sarkması olup olmadığı']},

    {id:'meter_display_off',category:'meter',label:'Sayaç ekranı kapalı veya hata gösteriyor',note:'Ekran görünmüyor, hata kodu veya kayıt sorunu',defaultRoute:'official',steps:['Sayaç kapağına ve mühre dokunmayın.','186 veya yetkili dağıtım kanalından sayaç inceleme kaydı açın.'],prep:['Sayaç seri numarası','Ekran fotoğrafı','Son fatura/endeks']},
    {id:'meter_burned',category:'meter',label:'Sayaç yanmış, ısınmış veya kıvılcım var',note:'Fiziksel hasar ve yangın belirtisi',inherentDanger:true,steps:['Sayaçtan ve panodan uzaklaşın.','112 ve 186’yı arayın.'],prep:['Güvenli konum','Duman/yangın bilgisi','Bina etkilenme durumu']},
    {id:'seal_issue',category:'meter',label:'Sayaç mührü veya bağlantı kapağı sorunu',note:'Mühür hasarlı, kopmuş veya şüpheli',defaultRoute:'official',steps:['Mühre veya kapağa müdahale etmeyin.','Yetkili dağıtım şirketine kayıt açın.'],prep:['Sayaç seri numarası','Görünen durum','Tarih ve fotoğraf']},
    {id:'illegal_electricity',category:'meter',label:'Kaçak elektrik şüphesi',note:'Sayaç, mühür veya dağıtım hattına müdahale şüphesi',defaultRoute:'official',steps:['Kendiniz inceleme veya delil toplama amacıyla müdahale etmeyin.','186 veya resmî ihbar kanalını kullanın.'],prep:['Gözlenen durum','Güvenli konum','Tarih/saat']},
    {id:'subscription',category:'meter',label:'Abonelik, bağlantı veya tesisat işlemi',note:'Yeni bağlantı, güç artışı, abonelik veya sözleşme ayrımı',defaultRoute:'admin',steps:['Bölgenizdeki dağıtım şirketini belirleyin.','Bağlantı işlemi ile perakende satış/abonelik işlemini ayırın.'],prep:['İl ve ilçe','İşlem türü','Tesisin mevcut/yeni durumu']}
  ];

  const routeTemplates={
    emergency:{level:'danger',icon:'!',eyebrow:'Acil güvenlik durumu',title:'Uzaklaşın; önce 112’yi arayın',summary:'Bu belirti can güvenliği riski oluşturabilir. Enerjili bölüme, kabloya, panoya veya kişiye güvenli enerji kesilmeden dokunmayın.',actions:[{label:'112’yi ara',href:'tel:112',kind:'danger'},{label:'186’yı ara',href:'tel:186',kind:'secondary'},{label:'Acil numaraları gör',href:'https://alo186.com/acil-numaralar',kind:'secondary'}],warningTitle:'Hayati güvenlik uyarısı',warningText:'Tehlikeli alana yaklaşmayın. Elektrik yangınında su kullanmayın. Güvenli alana geçip acil çağrı görevlisinin talimatlarını izleyin.',revenueAllowed:false},
    official:{level:'official',icon:'186',eyebrow:'Dağıtım şirketi / resmî kanal',title:'186 ve resmî EDAŞ kanalını kullanın',summary:'Belirti dağıtım şebekesi, sayaç veya dış aydınlatma sorumluluğunda olabilir.',actions:[{label:'186’yı ara',href:'tel:186',kind:''},{label:'EDAŞ’ı bul',href:'https://alo186.com/edas-bul',kind:'secondary'},{label:'Kesintiyi sorgula',href:'https://alo186.com/elektrik-kesintisi',kind:'secondary'}],revenueAllowed:true},
    electrician:{level:'electrician',icon:'⚙',eyebrow:'İç tesisat / yetkili elektrikçi',title:'Yetkili elektrikçi kontrolü gerekir',summary:'Sorun iç tesisat, bağlı cihaz veya koruma elemanıyla ilişkili olabilir.',actions:[{label:'Teknik hizmet talebi',href:'https://alo186.com/iletisim?konu=elektrik-arizasi',kind:''},{label:'Güvenlik rehberi',href:'https://alo186.com/sektor-rehberi/elektrik-guvenligi',kind:'secondary'},{label:'186’yı ara',href:'tel:186',kind:'secondary'}],revenueAllowed:true},
    building:{level:'electrician',icon:'B',eyebrow:'Bina yönetimi / teknik servis',title:'Önce bina yönetimi veya teknik servise bildirin',summary:'Birden fazla bağımsız bölüm veya ortak sistem etkileniyorsa bina ana dağıtımı kontrol edilmelidir.',actions:[{label:'Teknik hizmet talebi',href:'https://alo186.com/iletisim?konu=bina-elektrik',kind:''},{label:'186’yı ara',href:'tel:186',kind:'secondary'},{label:'Kesintiyi sorgula',href:'https://alo186.com/elektrik-kesintisi',kind:'secondary'}],revenueAllowed:true},
    mixed:{level:'mixed',icon:'?',eyebrow:'Kapsamı doğrulayın',title:'Şebeke ve iç tesisat olasılığını ayırın',summary:'Belirtinin komşu, bina ortak alanı veya yalnız sizin bölümünüzde olup olmadığını güvenli biçimde doğrulayın.',actions:[{label:'Kesintiyi sorgula',href:'https://alo186.com/elektrik-kesintisi',kind:''},{label:'186’yı ara',href:'tel:186',kind:'secondary'},{label:'Teknik hizmet talebi',href:'https://alo186.com/iletisim?konu=elektrik-arizasi',kind:'secondary'}],revenueAllowed:true},
    admin:{level:'official',icon:'i',eyebrow:'Bağlantı / abonelik işlemi',title:'Doğru şirket ve işlem türünü belirleyin',summary:'Dağıtım bağlantısı, sayaç ve perakende abonelik işlemleri farklı kurum veya şirketlerce yürütülebilir.',actions:[{label:'EDAŞ’ı bul',href:'https://alo186.com/edas-bul',kind:''},{label:'İşlem rehberini aç',href:'https://alo186.com/sektor-rehberi',kind:'secondary'},{label:'186’yı ara',href:'tel:186',kind:'secondary'}],revenueAllowed:true}
  };

  function getProblem(id){return problems.find(p=>p.id===id)||null;}
  function listByCategory(category){return problems.filter(p=>p.category===category);}
  function resolve(problemId,scope){
    const problem=getProblem(problemId);if(!problem)throw new Error('Problem bulunamadı.');
    const route=problem.inherentDanger?'emergency':(problem.routeByScope&&problem.routeByScope[scope])||problem.defaultRoute||'mixed';
    const template=routeTemplates[route];
    return {...template,problemId:problem.id,problemLabel:problem.label,title:problem.resultTitle||template.title,summary:`${problem.label}: ${template.summary}`,steps:[...(problem.steps||[])],prep:[...(problem.prep||[])],warningTitle:problem.warning?'Güvenlik uyarısı':template.warningTitle,warningText:problem.warning||template.warningText,revenueAllowed:problem.revenueAllowed===false?false:template.revenueAllowed};
  }

  return {categories,problems,routeTemplates,getProblem,listByCategory,resolve};
});
