(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.ALO186VoltageEvidence=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const ROUTE='/hesaplama/gerilim-dalgalanmasi-cihaz-reset-kanit-gunlugu/';
const STORAGE_KEY='alo186_voltage_evidence_v128';
const MAX_RECORDS=24,TTL_DAYS=540;
const n=v=>Number.isFinite(Number(v))?Number(v):0;
const now=()=>Date.now();
function clean(raw){const min=n(raw.minV),max=n(raw.maxV);return{createdAt:n(raw.createdAt)||now(),eventAt:new Date(raw.eventAt||now()).toISOString(),scope:raw.scope||'unknown',symptoms:Array.isArray(raw.symptoms)?raw.symptoms.filter(v=>['dim','bright','reset','ups','flicker','damage'].includes(v)):[],measurementSource:raw.measurementSource||'none',minV:min>0?min:0,maxV:max>0?max:0,repeated:raw.repeated===true,officialRecord:raw.officialRecord===true,lowRiskPlugLoad:raw.lowRiskPlugLoad===true,existingMonitor:raw.existingMonitor===true};}
function valid(record){return record&&record.createdAt>now()-TTL_DAYS*86400000;}
function summarize(records){const cleanRecords=records.map(clean).filter(valid);const recent90=cleanRecords.filter(r=>new Date(r.eventAt).getTime()>=now()-90*86400000);return{records:cleanRecords,recent90:recent90.length,repeatCount:recent90.filter(r=>r.repeated).length,measuredCount:recent90.filter(r=>r.measurementSource!=='none').length,multiScope:recent90.filter(r=>['building','street'].includes(r.scope)).length,resetCount:recent90.filter(r=>r.symptoms.includes('reset')||r.symptoms.includes('ups')).length};}
function decide(input,records){const record=clean(input);const summary=summarize([...records,record]);if(input.emergency)return{code:'emergency',commerce:false,title:'Aktif tehlikede ölçüm yapmayın',text:'Duman, yanık kokusu, açık iletken, elektrik çarpması veya kıvılcım varsa pano ve prize yaklaşmayın. Güvenli alandan 112’yi arayın.'};const neutralSigns=record.symptoms.includes('bright')&&record.symptoms.includes('dim');if(neutralSigns||record.scope==='street'&&record.symptoms.includes('flicker'))return{code:'network_or_neutral',commerce:false,title:'Nötr veya şebeke olayı ihtimali — ticari yol kapalı',text:'Pano açmayın ve elde multimetreyle ölçüm yapmayın. Birden fazla daire/sokak etkileniyorsa 186 veya yetkili EDAŞ; yalnız bina/daire etkileniyorsa yetkili elektrikçi önceliklidir.'};if(record.symptoms.includes('damage'))return{code:'damage',commerce:false,title:'Cihaz hasarında kanıt ve servis rotası',text:'Cihazı yeniden zorlamayın. Olay zamanı, servis raporu ve resmî şebeke kaydını saklayın; ürün satın almak hasar nedenini çözmez.'};if(record.scope==='single_device'&&summary.recent90<2)return{code:'device_first',commerce:false,title:'Önce cihaz veya adaptör sorununu ayırın',text:'Tek cihaz ve tek olay şebeke problemi kanıtı değildir. Aynı prizde güvenli, bilinen sağlam cihaz gözlemi veya üretici servisiyle ilerleyin.'};if(summary.recent90<2&&!record.repeated)return{code:'single_event',commerce:false,title:'Tek belirti ürün gerekçesi değildir',text:'Olay zamanını ve kapsamı kaydedin. Aynı koşul tekrarlanırsa güvenli cihaz logu veya profesyonel ölçümle karşılaştırın.'};if(record.existingMonitor)return{code:'no_buy',commerce:false,title:'Mevcut izleme aracı yeterliyse yeni ürün almayın',text:'Mevcut güvenli cihazın tarih-saatli min/max veya olay kaydını düzenli dışa aktarın; daha yeni ürün etiketi için değiştirmeyin.'};if(!record.lowRiskPlugLoad)return{code:'professional',commerce:false,title:'Sabit, motorlu veya yüksek güçlü yükte tüketici monitörü önerilmez',text:'Güç kalitesi kaydı ve gerilim olayı analizi yetkin personel tarafından uygun kayıt cihazıyla yapılmalıdır.'};if(record.measurementSource==='none'&&summary.recent90>=2)return{code:'qualified_monitor',commerce:true,title:'Tekrarlanan olay için düşük riskli kayıt ihtiyacı doğrulandı',text:'Yalnız düşük güçlü, monofaze, fişli elektronik yükte; üretici sınırları doğrulanmış priz tipi izleme sınıfını değerlendirin. Bu cihaz resmî güç kalitesi raporu yerine geçmez.',productClass:'plug_monitor'};if(summary.resetCount>=2)return{code:'qualified_protection',commerce:true,title:'Tekrarlanan cihaz reseti için teknik çözüm seçiciyi kullanın',text:'Önce olay sınıfını ayırın; UPS, AVR veya gerilim koruması yalnız doğru probleme göre seçilmelidir.',productClass:'protection_selector'};return{code:'evidence',commerce:false,title:'Kanıt birikiyor; henüz ürün yolu açılmadı',text:'Zaman, kapsam, güvenli cihaz logu ve resmî kayıt birlikte değerlendirilmeden ürün seçmeyin.'};}
function load(){try{const raw=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');return Array.isArray(raw)?raw.map(clean).filter(valid).slice(-MAX_RECORDS):[];}catch(_){return[];}}
function save(records){const out=records.map(clean).filter(valid).slice(-MAX_RECORDS);localStorage.setItem(STORAGE_KEY,JSON.stringify(out));return out;}
function csv(records){const head='event_at,scope,symptoms,measurement_source,min_v,max_v,repeated,official_record';return[head,...records.map(r=>[r.eventAt,r.scope,r.symptoms.join('|'),r.measurementSource,r.minV||'',r.maxV||'',r.repeated?'yes':'no',r.officialRecord?'yes':'no'].map(v=>`"${String(v).replaceAll('"','""')}"`).join(','))].join('\n');}
function calendar(days){const start=new Date(now()+days*86400000),end=new Date(start.getTime()+30*60000),stamp=d=>d.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z');return['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//ALO186//Gerilim Olayı Kontrolü//TR','BEGIN:VEVENT',`DTSTAMP:${stamp(new Date())}`,`DTSTART:${stamp(start)}`,`DTEND:${stamp(end)}`,'SUMMARY:Gerilim ve cihaz reset kayıtlarını gözden geçir','DESCRIPTION:Son olayların zamanını, kapsamını, UPS veya güvenli priz tipi cihaz loglarını ve resmî kayıt durumunu karşılaştırın.','END:VEVENT','END:VCALENDAR'].join('\r\n');}
function download(name,type,content){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove();},0);}
function init(){if(typeof document==='undefined')return;const $=id=>document.getElementById(id),form=$('voltageForm'),result=$('result'),affiliate=$('affiliate'),list=$('records');let records=load();const checks=name=>[...document.querySelectorAll(`input[name="${name}"]:checked`)].map(x=>x.value);const read=()=>({eventAt:$('eventAt').value,scope:$('scope').value,symptoms:checks('symptom'),measurementSource:$('measurementSource').value,minV:$('minV').value,maxV:$('maxV').value,repeated:$('repeated').checked,officialRecord:$('officialRecord').checked,lowRiskPlugLoad:$('lowRiskPlugLoad').checked,existingMonitor:$('existingMonitor').checked,emergency:$('emergency').checked,createdAt:now()});
function render(){const s=summarize(records);$('m90').textContent=s.recent90;$('mrepeat').textContent=s.repeatCount;$('mmeasured').textContent=s.measuredCount;$('mreset').textContent=s.resetCount;list.innerHTML=records.length?records.slice().reverse().map((r,i)=>`<div class="record"><div><strong>${new Date(r.eventAt).toLocaleString('tr-TR')} · ${r.scope}</strong><small>${r.symptoms.join(', ')||'belirti seçilmedi'} · ${r.measurementSource}${r.minV||r.maxV?` · ${r.minV||'?'}–${r.maxV||'?'} V`:''}</small></div><button type="button" data-remove="${records.length-1-i}">Kaydı sil</button></div>`).join(''):'<p class="note">Bu cihazda saklanan gerilim olayı yok.</p>';list.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>{records.splice(Number(b.dataset.remove),1);save(records);render();}));}
form.addEventListener('submit',e=>{e.preventDefault();const input=read(),record=clean(input),decision=decide(input,records),s=summarize([...records,record]);result.className=`result status ${decision.code==='emergency'||decision.code==='network_or_neutral'||decision.code==='damage'?'danger':decision.commerce?'ok':'warn'}`;result.innerHTML=`<h2>${decision.title}</h2><p>${decision.text}</p><div class="metrics"><div class="metric"><span>90 gün olay</span><strong>${s.recent90}</strong></div><div class="metric"><span>Tekrar işareti</span><strong>${s.repeatCount}</strong></div><div class="metric"><span>Ölçüm/log</span><strong>${s.measuredCount}</strong></div><div class="metric"><span>Reset/UPS</span><strong>${s.resetCount}</strong></div></div>`;affiliate.classList.toggle('hidden',!decision.commerce);if(decision.commerce){const link=$('affiliateLink');link.href=decision.productClass==='plug_monitor'?'/hesaplama/7-gunluk-cihaz-tuketim-deneyi/':'/hesaplama/gerilim-koruma-cozum-secici/';link.textContent=decision.productClass==='plug_monitor'?'Güvenli ölçüm planına geç — sonraki sayfa satış ortaklığı bağlantıları içerebilir':'Gerilim koruma çözüm seçiciyi aç';}if($('storeLocal').checked&&!input.emergency){records=save([...records,record]);render();}result.scrollIntoView({behavior:'smooth',block:'start'});});$('exportJson').addEventListener('click',()=>download('alo186-gerilim-olaylari.json','application/json',JSON.stringify({exportedAt:new Date().toISOString(),records},null,2)));$('exportCsv').addEventListener('click',()=>download('alo186-gerilim-olaylari.csv','text/csv;charset=utf-8',csv(records)));$('calendar').addEventListener('click',()=>download('alo186-30-gun-gerilim-kontrolu.ics','text/calendar;charset=utf-8',calendar(30)));$('clearAll').addEventListener('click',()=>{records=[];localStorage.removeItem(STORAGE_KEY);render();});render();}
if(typeof window!=='undefined')window.addEventListener('DOMContentLoaded',init);
return{ROUTE,STORAGE_KEY,MAX_RECORDS,TTL_DAYS,clean,summarize,decide,csv,calendar};});