'use strict';
const assert=require('node:assert/strict');
const tool=require('./app.js');
const base={
  emergency:false,meterCondition:'sound',leadCondition:'sound',competence:'qualified',location:'panel',task:'voltage_ac',liveCircuit:'yes',systemVoltage:'230',expectedCurrent:'',ncvOnly:'no',
  existingType:'none',existingCategory:'none',existingVoltage:'',existingCurrent:'',clampMode:'unknown',trueRms:'unknown',inrush:'unknown',probeRating:'unknown',inputProtection:'unknown',certification:'unknown',recallChecked:'unknown',selfCheck:'unknown'
};
const calc=(patch)=>tool.calculate({...base,...patch});
assert.equal(calc({emergency:true}).status,'emergency');
assert.equal(calc({meterCondition:'damaged'}).status,'stop_use');
assert.equal(calc({leadCondition:'exposed'}).status,'stop_use');
assert.equal(calc({competence:'unknown'}).status,'evidence_required');
assert.equal(calc({location:'pv'}).status,'professional');
assert.equal(calc({location:'ev'}).status,'professional');
assert.equal(calc({location:'service'}).status,'professional');
assert.equal(calc({location:'panel',competence:'consumer'}).status,'professional');
assert.equal(calc({location:'socket',competence:'consumer'}).status,'professional');
assert.equal(calc({task:'absence_voltage'}).status,'professional');
assert.equal(calc({task:'leakage'}).status,'professional');
assert.equal(calc({task:'resistance',liveCircuit:'yes'}).status,'stop_use');
assert.equal(calc({location:'unknown'}).status,'evidence_required');
assert.equal(calc({task:'unknown'}).status,'evidence_required');
assert.equal(calc({systemVoltage:'1500'}).status,'professional');
assert.equal(calc({ncvOnly:'yes'}).status,'evidence_required');
const candidate=calc({existingType:'none'});
assert.equal(candidate.status,'conditional_purchase');
assert.equal(candidate.requiredCategory,'cat3');
assert.equal(candidate.requiredVoltage,600);
assert.equal(candidate.productClass,'digital_multimeter');
assert.equal(candidate.trueRmsRequired,true);
assert.equal(candidate.commercialAllowed,true);
assert.ok(tool.affiliateUrl(candidate).includes('tag=alo186rehber-21'));
const clamp=calc({task:'inrush',expectedCurrent:'80',existingType:'none'});
assert.equal(clamp.status,'conditional_purchase');
assert.equal(clamp.productClass,'clamp_meter');
assert.equal(clamp.requiredCurrent,100);
assert.equal(clamp.inrushRequired,true);
assert.equal(calc({existingType:'multimeter',existingCategory:'cat3',existingVoltage:'600'}).status,'evidence_required');
assert.equal(calc({existingType:'multimeter',existingCategory:'cat2',existingVoltage:'600'}).status,'replace_candidate');
assert.equal(calc({existingType:'multimeter',existingCategory:'cat3',existingVoltage:'300'}).status,'replace_candidate');
assert.equal(calc({existingType:'multimeter',existingCategory:'cat3',existingVoltage:'600',trueRms:'no'}).status,'replace_candidate');
assert.equal(calc({existingType:'multimeter',existingCategory:'cat3',existingVoltage:'600',trueRms:'yes',probeRating:'no'}).status,'evidence_required');
assert.equal(calc({existingType:'multimeter',existingCategory:'cat3',existingVoltage:'600',trueRms:'yes',probeRating:'yes',inputProtection:'no'}).status,'evidence_required');
assert.equal(calc({existingType:'multimeter',existingCategory:'cat3',existingVoltage:'600',trueRms:'yes',probeRating:'yes',inputProtection:'yes',certification:'no'}).status,'evidence_required');
assert.equal(calc({existingType:'multimeter',existingCategory:'cat3',existingVoltage:'600',trueRms:'yes',probeRating:'yes',inputProtection:'yes',certification:'yes',recallChecked:'recalled'}).status,'stop_use');
assert.equal(calc({existingType:'multimeter',existingCategory:'cat3',existingVoltage:'600',trueRms:'yes',probeRating:'yes',inputProtection:'yes',certification:'yes',recallChecked:'yes',selfCheck:'unknown'}).status,'test_existing');
const noBuy=calc({existingType:'multimeter',existingCategory:'cat3',existingVoltage:'600',trueRms:'yes',probeRating:'yes',inputProtection:'yes',certification:'yes',recallChecked:'yes',selfCheck:'yes'});
assert.equal(noBuy.status,'no_buy');
assert.equal(noBuy.commercialAllowed,false);
assert.equal(tool.affiliateUrl(noBuy),null);
console.log(JSON.stringify({ok:true,scenarios:31,requiredCategory:candidate.requiredCategory,requiredVoltage:candidate.requiredVoltage,clampRange:clamp.requiredCurrent,noBuy:true,affiliateGate:true,personalData:false}));
