'use strict';
const assert=require('node:assert/strict');
const {calculate}=require('./app.js');
const base={gasEmergency:false,electricalEmergency:false,applianceCondition:'sound',applianceType:'gas_combi',criticalHeating:'no',connectionType:'approved_plug',generatorTransfer:'no',activeOutage:'no',annualService:'yes',flueVentilation:'yes',coAlarm:'yes',manufacturerCompatibility:'yes',phaseNeutralVerified:'yes',recallChecked:'yes',boilerModel:'Bosch GC2201iW 24 C 23',boilerMaxW:105,boilerStartW:220,otherW:15,dutyPercent:60,targetHours:8,existingSource:'none',sourceContinuousW:null,sourceSurgeW:null,sourceWh:null,pureSine:'yes',output230V50Hz:'yes',transferTest:'yes',actualHeatingTest:'yes'};
const c=(patch={})=>calculate({...base,...patch});
assert.equal(c({gasEmergency:true}).status,'emergency');
assert.equal(c({electricalEmergency:true}).status,'emergency');
assert.equal(c({applianceCondition:'damaged'}).status,'stop_use');
assert.equal(c({applianceType:'electric_boiler'}).status,'professional');
assert.equal(c({criticalHeating:'yes'}).status,'professional');
assert.equal(c({connectionType:'fixed_wiring'}).status,'professional');
assert.equal(c({generatorTransfer:'yes'}).status,'professional');
assert.equal(c({activeOutage:'yes'}).status,'active_outage');
assert.equal(c({annualService:'no'}).status,'evidence_required');
assert.equal(c({flueVentilation:'no'}).status,'evidence_required');
assert.equal(c({coAlarm:'no'}).status,'evidence_required');
assert.equal(c({manufacturerCompatibility:'no'}).status,'evidence_required');
assert.equal(c({phaseNeutralVerified:'no'}).status,'evidence_required');
assert.equal(c({recallChecked:'no'}).status,'stop_use');
assert.equal(c({boilerMaxW:24000}).status,'evidence_required');
const buy=c();assert.equal(buy.status,'conditional_purchase');assert.equal(buy.commercialAllowed,true);assert(buy.searchUrl.includes('tag=alo186rehber-21'));
assert.equal(buy.metrics.requiredContinuousW,150);assert.equal(buy.metrics.requiredSurgeW,280);assert.equal(buy.metrics.requiredNominalWh,920);assert.equal(buy.metrics.requiredVA,200);
const noBuy=c({existingSource:'ups',sourceContinuousW:500,sourceSurgeW:800,sourceWh:1200});assert.equal(noBuy.status,'no_buy');assert.equal(noBuy.commercialAllowed,false);
const gap=c({existingSource:'ups',sourceContinuousW:100,sourceSurgeW:200,sourceWh:400});assert.equal(gap.status,'conditional_purchase');assert(gap.metrics.gaps.length>=3);
assert.equal(c({existingSource:'ups',sourceContinuousW:500,sourceSurgeW:800,sourceWh:1200,pureSine:'no'}).status,'conditional_purchase');
console.log(JSON.stringify({ok:true,scenarios:19,requiredContinuousW:buy.metrics.requiredContinuousW,requiredSurgeW:buy.metrics.requiredSurgeW,requiredNominalWh:buy.metrics.requiredNominalWh,noBuy:noBuy.status,affiliateTripleGate:true,personalData:false},null,2));
