'use strict';
const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const core=require('./core.js');
const verified=meta=>({states:Object.fromEntries(meta.fields.map(([id])=>[id,'verified']))});
const power=core.category('power_station');
const ready=core.compare({category:'power_station',existing:'none',candidates:[verified(power),{states:{}},{states:{usable_wh:'fails'}}]});
assert.equal(ready.decision,'ready');assert.equal(ready.best.slot,'A');assert.equal(ready.best.score,100);assert.equal(ready.commercialAllowed,true);
assert.equal(core.canOpenAffiliate(ready,{toolCompleted:true,existingInadequate:true,affiliateDisclosure:true}),true);
assert.equal(core.canOpenAffiliate(ready,{toolCompleted:true,existingInadequate:false,affiliateDisclosure:true}),false);
const noBuy=core.compare({category:'power_station',existing:'adequate',candidates:[verified(power)]});
assert.equal(noBuy.decision,'no_buy');assert.equal(noBuy.commercialAllowed,false);assert.match(noBuy.title,/satın alma gerekmiyor/i);
const conditional=core.compare({category:'ev_cable',existing:'inadequate',candidates:[{states:{phase_current:'verified',connector:'verified',section:'unknown',environment:'verified'}}]});
assert.equal(conditional.decision,'verify');assert.equal(conditional.best.status,'conditional');assert.equal(core.questions(conditional).length,1);
const blocked=core.compare({category:'surge_strip',existing:'none',candidates:[{states:{current:'fails',power:'verified',joules:'verified',overload:'verified',ground:'verified'}}]});
assert.equal(blocked.decision,'blocked');assert.equal(blocked.best.status,'blocked');assert.equal(blocked.commercialAllowed,false);
const receipt=core.normalizeReceipt(ready,new Date('2026-07-28T12:00:00Z'));
assert.equal(receipt.reviewAt,'2026-08-11T12:00:00.000Z');assert.equal(receipt.expiresAt,'2026-09-11T12:00:00.000Z');
const many=Array.from({length:9},(_,i)=>({...receipt,id:`r${i}`,createdAt:new Date(Date.parse(receipt.createdAt)-i*1000).toISOString()}));assert.equal(core.pruneReceipts(many,new Date('2026-07-29T00:00:00Z')).length,6);
const payload=core.exportPayload(ready,receipt);assert.match(payload.privacy,/Marka.*ASIN.*fiyat/i);const exportedData=JSON.stringify({result:payload.result,receipt:payload.receipt});assert.doesNotMatch(exportedData,/"(?:price|stock|rating|seller|warranty|asin|brand|model|email|phone|address)"\s*:/i);assert.doesNotMatch(exportedData,/amazon\.(?:com|com\.tr)|\/dp\//i);
const ics=core.buildIcs(receipt);assert.match(ics,/BEGIN:VCALENDAR/);assert.match(ics,/DTSTART;VALUE=DATE:20260811/);assert.doesNotMatch(ics,/ATTENDEE|ORGANIZER|LOCATION|EMAIL|TEL/i);
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');assert.match(html,/https:\/\/www\.alo186\.com\/hesaplama\/teknik-urun-karsilastirma\//);assert.match(html,/WebApplication/);assert.match(html,/FAQPage/);assert.match(html,/Şimdilik satın alma/);assert.match(html,/satış ortaklığı/);assert.doesNotMatch(html,/type="(?:email|tel|text)"|<textarea/i);assert.doesNotMatch(html,/amazon\.(?:com|com\.tr)\//i);
console.log('ALO186 teknik kısa liste: aday skoru, satın almama, belge kapısı, affiliate, JSON/ICS ve gizlilik testleri başarılı.');
