(() => {
  'use strict';

  const $=id=>document.getElementById(id);
  const catalog=window.Alo186ProductCatalog;
  const matcher=window.Alo186ProductMatcher;
  const storageKey='alo186_product_decision_v1';
  const qualificationKey='alo186_affiliate_qualification_v1';
  const catalogReviewKey='alo186_catalog_recheck_v1';
  const reviewDays=30;
  let selectedCategory=null;

  const guideChecks={
    mini_ups:[
      ['Çıkış gerilimi','Modem ve ONT etiketindeki 5 V, 9 V veya 12 V değeriyle tam eşleşmeli.'],
      ['Jak ve polarite','Jak dış/iç ölçüsü ile merkez artı/eksi polaritesi doğrulanmalı.'],
      ['Toplam watt','Modem + ONT + varsa switch toplamı güvenlik payıyla hesaplanmalı.'],
      ['Geçiş davranışı','Şebeke kesildiğinde yeniden başlatmadan devam edip etmediği doğrulanmalı.']
    ],
    emergency_light:[
      ['Düşük mod süresi','En parlak mod yerine uzun süre kullanılabilen düşük mod süresini karşılaştırın.'],
      ['Fiziksel düğme','Karanlıkta uygulama gerektirmeden açılabilmeli.'],
      ['Pil göstergesi','Şarj seviyesinin önceden görülebilmesi hazırlığı kolaylaştırır.'],
      ['Taşıma ve asma','Odayı aydınlatma ile el feneri ihtiyacını birbirinden ayırın.']
    ],
    smoke_alarm:[
      ['Standart','Ürün ve ambalaj üzerinde EN 14604 uygunluk bilgisini doğrulayın.'],
      ['Test ve düşük pil','Test düğmesi ile sesli düşük pil uyarısı bulunmalı.'],
      ['Sensör ve ömür','Fotoelektrik sensör, üretim tarihi ve son kullanım/ürün ömrü belirtilmeli.'],
      ['Yerleşim','Üretici montaj konumuna uyun; mutfak buharı ve hava akımlarını dikkate alın.']
    ],
    co_alarm:[
      ['Kaynak güvenliği','Alarm, jeneratörü ev, garaj, balkon, sundurma veya binaya yakın yerde güvenli yapmaz.'],
      ['Kapsam','Her kat ve uyuma alanlarının dışı için üretici yerleşim talimatını doğrulayın.'],
      ['Standart ve ömür','EN 50291 uygunluk belgesi, üretim tarihi ve üreticinin değiştirme süresi görünür olmalı.'],
      ['Test ve güç','Test düğmesi, düşük pil uyarısı ve elektrik kesintisinde pil/pil yedeği bulunmalı.']
    ],
    power_station:[
      ['Enerji kapasitesi','Hedef süre için Wh hesabını yapın; etiket kapasitesinin tamamı kullanılamaz.'],
      ['Sürekli ve tepe güç','Motor/kompresör kalkış gücü dahil yükü karşılamalı.'],
      ['Dalga biçimi','Kombi, motor ve hassas cihazlarda saf sinüs gereksinimini doğrulayın.'],
      ['Batarya ve girişler','LiFePO₄ çevrim ömrü, AC/DC/solar giriş sınırları ve konektör uyumunu kontrol edin.']
    ],
    outlet_tester:[
      ['Gösterge kapsamı','LED deseninin hangi temel bağlantı hatalarını gösterebildiğini okuyun.'],
      ['RCD testi','Test akımı ve uyumlu nominal kaçak akım değeri belirtilmeli.'],
      ['Gerilim bölgesi','230 V / Türkiye priz standardıyla uyumlu olmalı.'],
      ['Sınır','Topraklama direnci, izolasyon veya açma süresi ölçümü yerine geçmediğini kabul edin.']
    ],
    smart_plug:[
      ['Sürekli akım','Cihazın gerçek çalışma akımı ürünün sürekli akım sınırının altında kalmalı.'],
      ['Kalkış ve ısıtıcı riski','Motor, kompresör ve gözetimsiz rezistif yük için üretici izni ayrıca doğrulanmalı.'],
      ['Ölçüm işlevi','W, kWh, geçmiş kayıt ve düşük güç çözünürlüğü ihtiyaca uygun olmalı.'],
      ['Bağlantı ve gizlilik','Yerel kontrol ihtiyacı, uygulama hesabı ve bulut bağımlılığı satın alma öncesi bilinmeli.']
    ],
    ev_cable:[
      ['Araç ve istasyon soketi','Araç girişi ile soketli şarj noktasının Type 2 uyumu doğrulanmalı.'],
      ['Faz ve akım','Monofaze/trifaze yapı ile 16 A veya 32 A sınıfı araç ve istasyon sınırlarını karşılamalı.'],
      ['Gerçek güç sınırı','Daha yüksek kablo sınıfının araç desteklemiyorsa şarjı hızlandırmayacağı kabul edilmeli.'],
      ['Fiziksel güvenlik','Konnektör, kilit, dış kılıf, uzunluk ve üretici uygunluğu hasarsız ve doğrulanmış olmalı.']
    ],
    ups_battery:[
      ['Tam model ve kartuş','UPS tam modeli ile üreticinin önerdiği kartuş veya akü seti kodu eşleşmeli.'],
      ['Elektriksel değerler','Gerilim, Ah, kimya, terminal, adet ve seri/paralel düzen aynı olmalı.'],
      ['Set bütünlüğü','Aynı dizide eski-yeni veya farklı kapasitede aküler karıştırılmamalı.'],
      ['Güvenlik ve yaş','Şişme, sızıntı, koku, aşırı ısı veya destek dışı yaşlı UPS varsa servis/yeni cihaz değerlendirilmelidir.']
    ]
  };

  function emit(name,params={}){if(typeof window.Alo186Track==='function')window.Alo186Track(name,params);}
  function readQualification(category){try{const raw=localStorage.getItem(qualificationKey);if(!raw)return null;const data=JSON.parse(raw);if(!data||data.schema!=='alo186.affiliateQualification.v1'||data.category!==category||data.personalData!==false||!data.requirements){return null;}const expires=Date.parse(data.expiresAt);if(!Number.isFinite(expires)||expires<=Date.now()){localStorage.removeItem(qualificationKey);return null;}return data;}catch(_error){return null;}}
  function gateCompatible(receipt,req={}){if(!receipt||receipt.category!=='surge_strip')return false;const minimum=receipt.requirements||{};return Number(req.minOutlets)>=Number(minimum.minOutlets||1)&&Number(req.minJoules)>=Number(minimum.minJoules||250)&&(!minimum.usb||Boolean(req.usb));}
  function readCatalogReview(){try{const data=JSON.parse(localStorage.getItem(catalogReviewKey)||'null');return data&&data.schema==='alo186.catalogRecheck.v1'&&data.personalData===false?data:null;}catch(_error){return null;}}
  function saveCatalogReview(){try{const createdAt=new Date();const reviewAt=new Date(createdAt.getTime()+30*86400000);localStorage.setItem(catalogReviewKey,JSON.stringify({schema:'alo186.catalogRecheck.v1',personalData:false,createdAt:createdAt.toISOString(),reviewAt:reviewAt.toISOString()}));renderCatalogHealth();emit('affiliate_catalog_recheck_saved',{review_days:30});}catch(_error){}}
  function renderCatalogHealth(){if(!catalog||typeof catalog.catalogHealth!=='function'||!$('matcher'))return;const current=document.getElementById('catalogFreshness');if(current)current.remove();const health=catalog.catalogHealth({now:new Date()});const review=readCatalogReview();const reviewDate=review&&new Date(review.reviewAt);const due=reviewDate&&Number.isFinite(reviewDate.getTime())&&reviewDate.getTime()<=Date.now();const section=document.createElement('section');section.id='catalogFreshness';section.className='content-section';section.innerHTML=`<div class="panel"><div class="section-title"><div><span class="eyebrow">Katalog tazeliği ve güven kapıları</span><h2>Doğrulanmış kayıt sayısı değil, yayımlanmasına izin verilen ürün yolu önemlidir.</h2></div></div><div class="brief-summary"><div><small>Doğrudan teknik kapı</small><strong>${health.publicDirect}</strong></div><div><small>Ücretsiz araç sonrası</small><strong>${health.gatedVerified}</strong></div><div><small>Son teknik doğrulama</small><strong>${formatDate(new Date(`${health.verifiedAt}T00:00:00Z`))}</strong></div></div><p>Yalnız <strong>verified_direct</strong> kategorileri public Product Knowledge Graph’a ve doğrudan affiliate kartlarına girer. Diğer doğrulanmış kayıtlar, ilgili ücretsiz uygunluk aracı tamamlanmadan makine tarafından okunabilir satış bağlantısı veya ürün kartı üretmez. Fiyat, stok, puan, satıcı ve garanti tutulmaz.</p><div class="actions"><button type="button" class="btn btn-secondary" id="catalogReviewBtn">${due?'Katalog durumunu şimdi yeniden kontrol et':reviewDate?`Yerel kontrol: ${formatDate(reviewDate)}`:'30 günlük katalog kontrolü kaydet'}</button><a class="btn btn-secondary" href="/yayin-ilkeleri">Doğrulama yöntemini gör</a></div><small>Hatırlatma yalnız bu tarayıcıda tarih olarak saklanır; bildirim, hesap veya kişisel veri kullanılmaz. Katalog kartları ${health.verificationMaxAgeDays} günlük tazelik eşiğini geçince otomatik kapanır.</small></div>`;$('matcher').before(section);const button=document.getElementById('catalogReviewBtn');if(button)button.addEventListener('click',()=>{if(due){try{localStorage.removeItem(catalogReviewKey);}catch(_error){}renderCatalogHealth();}else saveCatalogReview();});}
  function renderCategories(){$('categoryGrid').innerHTML=catalog.categories.map(category=>`<button type="button" class="category-button" data-category="${category.id}" aria-pressed="false"><strong>${escapeHtml(category.name)}</strong><small>${escapeHtml(category.description)}</small></button>`).join('');$('categoryGrid').querySelectorAll('[data-category]').forEach(button=>button.addEventListener('click',()=>selectCategory(button.dataset.category)));}
  function selectCategory(id,options={}){selectedCategory=id;const category=catalog.getCategory(id);const qualification=readQualification(id);const qualified=Boolean(qualification);document.querySelectorAll('[data-category]').forEach(button=>button.setAttribute('aria-pressed',button.dataset.category===id?'true':'false'));$('requirements').classList.remove('hidden');$('requirementsTitle').textContent=category.mode==='direct'||qualified?'Teknik minimumları girin':'Satın almadan önce kontrol edin';$('requirementFields').innerHTML=requirementMarkup(id,category);$('matchBtn').textContent=category.mode==='direct'||qualified?'Uygun seçenekleri göster':'Kontrol listesini göster';$('validation').textContent=qualified?'Ücretsiz uygunluk testinden gelen kişisel verisiz teknik geçiş etkin. Minimumları düşürmeden karşılaştırın.':'';$('results').classList.add('hidden');if(qualified)applyRequirements(id,qualification.requirements);emit('product_category_selected',{category:id,mode:category.mode,risk:category.risk,affiliate_policy:category.affiliatePolicy,qualified_gate:qualified});if(!options.noScroll)$('requirements').scrollIntoView({behavior:'smooth',block:'nearest'});}
  function requirementMarkup(id,category){if(id==='powerbank')return `<div class="form-grid"><label class="field"><span>Minimum kapasite</span><select data-field="minCapacity"><option value="10000">10.000 mAh</option><option value="20000" selected>20.000 mAh</option></select></label><label class="field"><span>Minimum çıkış gücü</span><select data-field="minOutput"><option value="10">10 W — temel telefon</option><option value="25" selected>25 W — hızlı telefon/tablet</option><option value="65">65 W — uyumlu dizüstü</option><option value="100">100 W — yüksek güçlü dizüstü</option></select></label><label class="check-item field full"><input data-field="needWireless" type="checkbox"><span><b>Kablosuz şarj gerekli</b><br><small>Kablolu gücü ayrıca kontrol edin.</small></span></label></div>`;if(id==='surge_strip')return `<div class="form-grid"><label class="field"><span>Minimum priz sayısı</span><select data-field="minOutlets"><option value="1">1</option><option value="4">4</option><option value="5" selected>5</option><option value="6">6</option></select></label><label class="field"><span>Minimum enerji sönümleme</span><select data-field="minJoules"><option value="250">250 J</option><option value="600">600 J</option><option value="900" selected>900 J</option><option value="1000">1.000 J</option></select></label><label class="check-item field full"><input data-field="needUsb" type="checkbox"><span><b>USB çıkışı gerekli</b><br><small>USB özelliklerinin hızlı şarj protokolünü ayrıca doğrulayın.</small></span></label></div>`;const checks=guideChecks[id]||[];return `<p>${escapeHtml(category.description)}</p><div class="guide-list">${checks.map(([title,text])=>`<div class="guide-item"><b>${escapeHtml(title)}</b><span>${escapeHtml(text)}</span></div>`).join('')}</div>`;}
  function field(name){return $('requirementFields').querySelector(`[data-field="${name}"]`);}
  function requirements(){if(selectedCategory==='powerbank')return {minCapacityMah:Number(field('minCapacity').value),minOutputW:Number(field('minOutput').value),wireless:field('needWireless').checked};if(selectedCategory==='surge_strip')return {minOutlets:Number(field('minOutlets').value),minJoules:Number(field('minJoules').value),usb:field('needUsb').checked};return {};}
  function applyRequirements(categoryId,req={}){if(categoryId==='powerbank'){if(field('minCapacity'))field('minCapacity').value=String(req.minCapacityMah||20000);if(field('minOutput'))field('minOutput').value=String(req.minOutputW||25);if(field('needWireless'))field('needWireless').checked=Boolean(req.wireless);}if(categoryId==='surge_strip'){if(field('minOutlets'))field('minOutlets').value=String(req.minOutlets||5);if(field('minJoules'))field('minJoules').value=String(req.minJoules||900);if(field('needUsb'))field('needUsb').checked=Boolean(req.usb);}}
  function runMatch(options={}){$('validation').textContent='';if(!selectedCategory){$('validation').textContent='Önce bir ihtiyaç seçin.';return;}try{const req=requirements();const receipt=readQualification(selectedCategory);const qualified=Boolean(receipt&&gateCompatible(receipt,req));if(receipt&&!qualified)$('validation').textContent='Teknik minimumlar uygunluk aracından gelen alt sınırın altına indirilemez; ücretsiz testi yeniden açın.';const result=matcher.match(selectedCategory,req,{now:new Date(),qualified});$('results').classList.remove('hidden');$('resultTitle').textContent=result.category.name;$('requirementsChip').textContent=matcher.requirementsSummary(selectedCategory,req);if(result.mode==='direct'){if(result.matches.length)$('resultText').textContent=result.qualifiedGate?`${result.matches.length} güncel teknik eşleşme, 30 dakikalık yerel uygunluk kapısından sonra açıldı. Fiyat, stok, satıcı ve garanti Amazon’da doğrulanır.`:`${result.matches.length} güncel teknik eşleşme bulundu. Fiyat, stok, satıcı ve garanti Amazon’da doğrulanır.`;else if(result.staleProductCount)$('resultText').textContent='Doğrulama süresi geçen kartlar satış bağlantısından kaldırıldı. Katalog yenilenene kadar yalnız teknik gereksinimleri kullanın.';else $('resultText').textContent='Bu minimumları karşılayan güncel doğrulanmış kart bulunamadı. Gereksinimi düşürmeden aşağıdaki kapalı teknik arama oluşturucusunu kullanın.';}else{$('resultText').textContent=result.affiliatePolicy==='professional_only'?'Bu kategoride ürün aramasından önce profesyonel ölçüm veya güvenli yönlendirme gerekir.':'Ürün adından önce aşağıdaki teknik kontrol listesini tamamlayın.';}$('directResult').classList.toggle('hidden',result.mode!=='direct');$('guideResult').classList.toggle('hidden',result.mode!=='guide');if(result.mode==='direct')renderProducts(result);else renderGuide(result);saveDecision(selectedCategory,req);renderSavedDecision();if(!options.noScroll)$('results').scrollIntoView({behavior:'smooth',block:'start'});emit('product_match_completed',{category:selectedCategory,mode:result.mode,match_count:result.matches.length,professional_required:result.professionalSelectionRequired,affiliate_policy:result.affiliatePolicy,stale_product_count:result.staleProductCount||0,restored:Boolean(options.restored),qualified_gate:Boolean(result.qualifiedGate)});}catch(error){$('validation').textContent=error.message;}}
  function renderProducts(result){if(!result.matches.length){if(result.staleProductCount){$('directResult').innerHTML=`<div class="empty-products stale-note"><h3>Eski doğrulamayla ürün yönlendirmiyoruz.</h3><p>${result.staleProductCount} kartın teknik kontrol tarihi ${catalog.verificationMaxAgeDays} günlük sınırı geçti. Katalog yenilenene kadar doğrudan affiliate bağlantısı gösterilmez.</p><a class="btn btn-secondary" href="https://alo186.com/yayin-ilkeleri">Doğrulama yöntemini gör</a></div>`;emit('affiliate_exposure_blocked',{category:selectedCategory,reason:'stale_catalog',stale_product_count:result.staleProductCount});}else{$('directResult').innerHTML=`<div class="empty-products"><h3>Bu minimumları karşılayan doğrulanmış kart bulunamadı.</h3><p>ALO186 sırf sonuç üretmek için ürün önermez. Teknik minimumları değiştirmeden ücretsiz uygunluk aracına dönün; satın almamak da geçerli sonuçtur.</p></div>`;emit('affiliate_exposure_blocked',{category:selectedCategory,reason:'no_verified_match'});}return;}$('directResult').innerHTML=result.matches.map(item=>productCard(item)).join('');$('directResult').querySelectorAll('[data-product]').forEach(link=>link.addEventListener('click',()=>emit('affiliate_product_clicked',{category:selectedCategory,product_id:link.dataset.product,asin:link.dataset.asin,match_score:Number(link.dataset.score),placement:'smart_matcher',qualified_gate:Boolean(result.qualifiedGate)})));}
  function productCard(item){const p=item.product;const ageText=item.freshness&&Number.isFinite(item.freshness.ageDays)?` · ${item.freshness.ageDays} gün önce`:'';return `<article class="product-card"><div class="product-head"><span class="rank-label">${escapeHtml(item.label)}</span><h3>${escapeHtml(p.name)}</h3><span class="product-brand">${escapeHtml(p.brand)} · ASIN ${escapeHtml(p.asin)}</span></div><div class="score-row"><strong>${item.score}/100</strong><span>Uygunluk · güven ${escapeHtml(item.confidence||'Orta')}</span></div><div class="product-body"><div><h4>Neden eşleşti?</h4><ul>${item.reasons.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul></div><div><h4>Güçlü yanlar</h4><ul>${p.strengths.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul></div><div><h4>Sınırlar</h4><ul>${p.limits.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul></div>${item.unknowns.length?`<div class="unknowns"><b>Yeniden doğrulayın:</b> ${item.unknowns.map(escapeHtml).join(' ')}</div>`:''}<div class="verification">Teknik liste kontrolü: ${escapeHtml(p.verifiedAt)}${escapeHtml(ageText)}<br>${escapeHtml(p.sourceNote)}</div></div><div class="product-actions"><a class="btn btn-primary" data-product="${escapeAttr(p.id)}" data-asin="${escapeAttr(p.asin)}" data-score="${item.score}" href="${escapeAttr(p.url)}" target="_blank" rel="sponsored nofollow noopener">Amazon ürün sayfasını aç</a></div></article>`;}
  function renderGuide(result){const checks=guideChecks[selectedCategory]||[];const checklist=`<div class="guide-list">${checks.map(([title,text])=>`<div class="guide-item"><b>${escapeHtml(title)}</b><span>${escapeHtml(text)}</span></div>`).join('')}</div>`;const professional=result.professionalSelectionRequired?`<div class="professional-note"><b>Profesyonel seçim sınırı:</b> Bu kategoride bağlantı, tesisat, standart veya ölçüm uyumu yanlış ürün riskini artırır. Sonuç bir uygunluk onayı değildir.</div>`:'';let actions='';if(result.affiliatePolicy==='after_tool'||result.affiliatePolicy==='professional_only'){const next=result.nextStep||{url:'https://alo186.com/karar-motoru/',label:'Ücretsiz ön kontrolü aç'};const professionalUrl=`/kurumsal-elektrik-surekliligi-on-degerlendirme?source=product_center&category=${encodeURIComponent(selectedCategory)}`;actions=`<div class="decision-gate"><b>Satın alma bağlantısı neden gösterilmiyor?</b><p>${result.affiliatePolicy==='professional_only'?'Bu ölçüm kategorisinde yanlış cihaz güvenli olmayan bir sonuca yol açabilir. Önce uzman ölçümü veya güvenli yönlendirme gerekir.':'Güç, enerji, gerilim veya bağlantı uyumu hesaplanmadan ürün aramak yanlış seçim ve iade riskini artırır.'}</p></div><div class="actions"><a class="btn btn-primary" data-next-step href="${escapeAttr(next.url)}">${escapeHtml(next.label)}</a>${result.professionalSelectionRequired?`<a class="btn btn-secondary" data-professional-route href="${escapeAttr(professionalUrl)}">Ücretli teknik ön değerlendirme</a>`:''}</div>`;emit('affiliate_exposure_blocked',{category:selectedCategory,reason:result.affiliatePolicy});}else{actions=`<div class="decision-gate"><b>Genel ürün araması henüz açılmadı.</b><p>Kontrol listesini tamamladıktan sonra aşağıdaki kapalı teknik arama oluşturucusunda mevcut ürün ihtiyacını ve satış ortaklığı açıklamasını ayrıca onaylayın.</p></div>`;emit('affiliate_exposure_blocked',{category:selectedCategory,reason:'qualified_search_required'});}$('guideResult').innerHTML=`<span class="eyebrow">Rehberli seçim</span><h3>Ürün adından önce bu alanları doğrulayın</h3>${checklist}${professional}${actions}`;const nextStep=$('guideResult').querySelector('[data-next-step]');if(nextStep)nextStep.addEventListener('click',()=>emit('free_tool_route_opened',{category:selectedCategory,affiliate_policy:result.affiliatePolicy}));const professionalRoute=$('guideResult').querySelector('[data-professional-route]');if(professionalRoute)professionalRoute.addEventListener('click',()=>emit('professional_conversion_opened',{category:selectedCategory,placement:'guide_result'}));}
  function readDecision(){try{const raw=localStorage.getItem(storageKey);if(!raw)return null;const data=JSON.parse(raw);if(!data||!catalog.getCategory(data.category)||typeof data.savedAt!=='string')return null;return data;}catch(_error){return null;}}
  function saveDecision(category,req){try{const savedAt=new Date();const reviewAt=new Date(savedAt.getTime()+reviewDays*86400000);localStorage.setItem(storageKey,JSON.stringify({category,requirements:req,savedAt:savedAt.toISOString(),reviewAt:reviewAt.toISOString()}));}catch(_error){}}
  function renderSavedDecision(){const section=$('savedDecision');if(!section)return;const data=readDecision();if(!data){section.classList.add('hidden');return;}const category=catalog.getCategory(data.category);const reviewAt=new Date(data.reviewAt||data.savedAt);const due=Number.isFinite(reviewAt.getTime())&&reviewAt.getTime()<=Date.now();$('savedDecisionText').textContent=`${category.name} için son teknik seçim cihazınızda saklandı. ${due?'Kontrol tarihi geldi; teknik bilgiler ve ihtiyacınız değişmiş olabilir.':`Yeniden kontrol: ${formatDate(reviewAt)}.`}`;$('restoreDecisionBtn').textContent=due?'Seçimi şimdi yeniden kontrol et':'Son seçimi geri yükle';section.classList.remove('hidden');}
  function restoreDecision(){const data=readDecision();if(!data)return;selectCategory(data.category,{noScroll:true});applyRequirements(data.category,data.requirements||{});runMatch({restored:true});emit('product_decision_restored',{category:data.category});}
  function clearDecision(){try{localStorage.removeItem(storageKey);}catch(_error){}renderSavedDecision();emit('product_decision_cleared');}
  function reset(){selectedCategory=null;document.querySelectorAll('[data-category]').forEach(button=>button.setAttribute('aria-pressed','false'));$('requirements').classList.add('hidden');$('results').classList.add('hidden');$('validation').textContent='';window.scrollTo({top:$('matcher').offsetTop-80,behavior:'smooth'});}
  function formatDate(value){return new Intl.DateTimeFormat('tr-TR',{day:'2-digit',month:'long',year:'numeric'}).format(value);}
  function escapeHtml(value){return String(value??'').replace(/[&<>"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[ch]));}
  function escapeAttr(value){return escapeHtml(value).replace(/'/g,'&#39;');}
  document.addEventListener('DOMContentLoaded',()=>{if(!catalog||!matcher){$('validation').textContent='Ürün kataloğu yüklenemedi.';return;}renderCategories();renderSavedDecision();renderCatalogHealth();$('matchBtn').addEventListener('click',()=>runMatch());$('resetBtn').addEventListener('click',reset);if($('restoreDecisionBtn'))$('restoreDecisionBtn').addEventListener('click',restoreDecision);if($('clearDecisionBtn'))$('clearDecisionBtn').addEventListener('click',clearDecision);const params=new URLSearchParams(location.search);const query=params.get('kategori');if(query&&catalog.getCategory(query))selectCategory(query);});
})();
