(function(root,factory){
  const api=factory();
  if(typeof module==='object'&&module.exports){module.exports=api;}
  root.Alo186ProductCatalog=api;
  if(root&&root.document&&root.document.head&&typeof root.document.createElement==='function'&&typeof api.knowledgeGraph==='function'){
    const id='alo186-affiliate-knowledge-graph';
    const current=typeof root.document.getElementById==='function'?root.document.getElementById(id):null;
    if(current&&typeof current.remove==='function')current.remove();
    const script=root.document.createElement('script');
    script.id=id;script.type='application/ld+json';
    if(script.dataset)script.dataset.generated='alo186-affiliate-knowledge-graph';
    script.textContent=JSON.stringify(api.knowledgeGraph());
    root.document.head.appendChild(script);
  }
})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const affiliateTag='alo186rehber-21';
  const verifiedAt='2026-07-29';
  const verificationMaxAgeDays=45;
  const siteOrigin='https://alo186.com';
  function amazonProductUrl(asin){const base=`https://www.amazon.com.tr/dp/${encodeURIComponent(asin)}`;return affiliateTag?`${base}?tag=${encodeURIComponent(affiliateTag)}`:base;}
  function amazonSearchUrl(query){const base=`https://www.amazon.com.tr/s?k=${encodeURIComponent(query)}`;return affiliateTag?`${base}&tag=${encodeURIComponent(affiliateTag)}`:base;}
  const categories=[
    {id:'powerbank',name:'Telefon ve mobil cihaz için powerbank',mode:'direct',risk:'consumer',affiliatePolicy:'verified_direct',description:'Kapasite, tek cihaz USB-C çıkış gücü, toplam çoklu port gücü ve kablosuz şarj ihtiyacına göre ürün sayfası teknik verilerini karşılaştırır.',searchQuery:'USB C PD powerbank 20000 mAh dizüstü 65W 100W'},
    {id:'usb_c_charger',name:'USB-C PD duvar şarj cihazı',mode:'direct',risk:'consumer',affiliatePolicy:'verified_direct',description:'Cihazın kabul ettiği güç, USB-C Power Delivery veya üretici hızlı şarj protokolü ve uygun kablo birlikte doğrulanmalıdır. Daha yüksek etiket gücü cihazı zorla daha yüksek güçte şarj etmez.',searchQuery:'USB C PD PPS GaN şarj cihazı 45W'},
    {id:'usb_c_cable',name:'USB-C hızlı şarj ve veri kablosu',mode:'direct',risk:'consumer',affiliatePolicy:'verified_direct',description:'Konnektör tipi, kablonun akım ve güç sınıfı, veri ihtiyacı ve cihaz protokolü birlikte karşılaştırılır. Kablo, adaptörün veya cihazın desteklemediği bir şarj hızını tek başına oluşturmaz.',searchQuery:'USB C USB C 100W 5A hızlı şarj veri kablosu'},
    {id:'usb_c_hub',name:'USB-C hub ve yerleştirme istasyonu',mode:'direct',risk:'consumer',affiliatePolicy:'verified_direct',description:'Görüntü çıkışı, USB veri hızı, Ethernet, kart okuyucu ve PD geçiş gücü ayrı ayrı doğrulanır. PD etiketi hubın kendi güç adaptörü içerdiği anlamına gelmez.',searchQuery:'USB C hub HDMI Ethernet 100W PD 4K 60Hz'},
    {id:'display_cable',name:'USB-C ve DisplayPort görüntü kablosu',mode:'direct',risk:'consumer',affiliatePolicy:'verified_direct',description:'Kaynak cihazın görüntü çıkışı, hedef ekran standardı, çözünürlük, yenileme hızı ve kablo uzunluğu birlikte doğrulanır. Konnektör uyumu tek başına görüntü garantisi değildir.',searchQuery:'USB C DisplayPort 1.4 4K 144Hz 8K kablo'},
    {id:'surge_strip',name:'Akım korumalı grup priz',mode:'guide',risk:'consumer',affiliatePolicy:'after_tool',nextStepUrl:'https://alo186.com/hesaplama/akim-korumali-grup-priz-uygunluk/',nextStepLabel:'Önce yük, priz, joule ve topraklama uygunluğunu test et',description:'Toplam sürekli/tepe yük, etiket amperi ve wattı, joule, priz sayısı, koruma göstergesi, bağlantı ve işlevsel topraklama doğrulanmadan ürün kartı açılmaz. Pano tipi SPD ve tesisat korumasının yerine geçmez.',searchQuery:'akım korumalı grup priz joule'},
    {id:'mini_ups',name:'Modem ve fiber ONT için mini UPS',mode:'guide',risk:'compatibility',affiliatePolicy:'after_tool',nextStepUrl:'https://alo186.com/hesaplama/modem-internet-yedekleme/',nextStepLabel:'Önce modem ve ONT hesabını yap',description:'Voltaj, polarite, jak ölçüsü, toplam watt ve geçiş davranışı doğrulanmadan ürün seçilmemelidir.',searchQuery:'modem mini UPS 12V 9V 5V'},
    {id:'emergency_light',name:'Şarjlı acil aydınlatma',mode:'guide',risk:'consumer',affiliatePolicy:'after_tool',nextStepUrl:'https://alo186.com/hesaplama/acil-aydinlatma-sure-uygunluk/',nextStepLabel:'Önce lümen, adet ve çalışma süresini test et',description:'Alan, aynı moddaki lümen ve çalışma süresi, otomatik yanma, fiziksel düğme, pil göstergesi ve kullanım ortamı doğrulanmadan ürün seçilmemelidir.',searchQuery:'şarjlı acil durum lambası kamp lambası'},
    {id:'smoke_alarm',name:'Fotoelektrik duman alarmı',mode:'guide',risk:'safety',affiliatePolicy:'after_tool',nextStepUrl:'https://alo186.com/hesaplama/duman-alarmi-yerlesim-bakim-uygunluk/',nextStepLabel:'Önce adet, yerleşim, ürün yaşı ve aylık test uygunluğunu değerlendir',description:'Kat, uyuma odası, ayrı uyuma alanı, pişirme uzaklığı, test düğmesi, ürün yaşı, bağlantı ve erişilebilirlik doğrulanmadan ürün rotası açılmaz.',searchQuery:'EN 14604 fotoelektrik duman dedektörü'},
    {id:'co_alarm',name:'Karbonmonoksit alarmı',mode:'guide',risk:'safety',affiliatePolicy:'after_tool',nextStepUrl:'https://alo186.com/hesaplama/karbonmonoksit-alarmi-jenerator-guvenligi/',nextStepLabel:'Önce kaynak, jeneratör konumu, alarm yerleşimi ve test uygunluğunu değerlendir',description:'CO alarmı taşınabilir jeneratörü kapalı veya binaya yakın alanda güvenli yapmaz. Kaynak, kat ve uyuma alanı kapsamı, pil yedeği, test, üretici ömrü ve EN 50291 belgesi doğrulanmadan ürün rotası açılmaz.',searchQuery:'EN 50291 karbonmonoksit alarmı pil yedekli'},
    {id:'power_station',name:'Taşınabilir güç istasyonu',mode:'guide',risk:'compatibility',affiliatePolicy:'after_tool',nextStepUrl:'https://alo186.com/hesaplama/power-station-kapasite-eps-uygunluk/',nextStepLabel:'Önce kapasite, güç ve EPS uyumunu test et',description:'Wh kapasitesi, sürekli/tepe güç, saf sinüs, EPS geçişi, bypass, batarya ve şarj girişleri yük hesabıyla birlikte seçilmelidir.',searchQuery:'LiFePO4 taşınabilir güç istasyonu power station'},
    {id:'generator',name:'Taşınabilir jeneratör',mode:'guide',risk:'safety',affiliatePolicy:'after_tool',nextStepUrl:'https://alo186.com/hesaplama/jenerator-gucu-secimi/',nextStepLabel:'Önce sürekli ve kalkış gücünü hesapla',description:'Sürekli ve kalkış W, faz, bağlantı biçimi, CO güvenliği, gürültü, yakıt ve servis koşulları güç hesabıyla birlikte doğrulanmalıdır.',searchQuery:'inverter jeneratör CO sensörü sürekli kalkış watt'},
    {id:'inverter',name:'Saf sinüs inverter ve batarya sistemi',mode:'guide',risk:'compatibility',affiliatePolicy:'after_tool',nextStepUrl:'https://alo186.com/hesaplama/inverter-uygunluk/',nextStepLabel:'Önce inverter ve batarya hesabını yap',description:'Sürekli/tepe W, saf sinüs, 12/24/48 V DC gerilim, batarya akımı, BMS ve koruma doğrulanmadan ürün seçilmemelidir.',searchQuery:'saf sinüs inverter 12V 24V sürekli tepe watt'},
    {id:'outlet_tester',name:'Priz ve RCD test cihazı',mode:'guide',risk:'measurement',affiliatePolicy:'professional_only',nextStepUrl:'https://alo186.com/karar-motoru/',nextStepLabel:'Önce güvenli yönlendirmeyi aç',description:'Gösterge yalnız temel bağlantı hatalarını ön kontrol eder; izolasyon, topraklama direnci ve koruma açma testi yerine geçmez.',searchQuery:'priz test cihazı RCD tester'},
    {id:'smart_plug',name:'Akıllı priz ve enerji ölçer',mode:'guide',risk:'compatibility',affiliatePolicy:'after_tool',nextStepUrl:'https://alo186.com/hesaplama/akilli-priz-enerji-olcer-uygunluk/',nextStepLabel:'Önce akım, güç ve ölçüm ihtiyacını test et',description:'Cihazın gerçek akımı, motor kalkışı, ölçüm çözünürlüğü, kayıt süresi ve gözetimsiz anahtarlama riski doğrulanmadan ürün seçilmemelidir.',searchQuery:'enerji ölçerli akıllı priz 16A watt kWh geçmiş kayıt'},
    {id:'ev_cable',name:'Type 2 elektrikli araç şarj kablosu',mode:'guide',risk:'compatibility',affiliatePolicy:'after_tool',nextStepUrl:'https://alo186.com/hesaplama/ev-sarj-kablosu-uygunluk/',nextStepLabel:'Önce araç, istasyon, faz ve akım uyumunu test et',description:'Araç soketi, istasyon tipi, monofaze/trifaze yapı, 16/32 A sınıfı, kablo uzunluğu ve fiziksel güvenlik birlikte doğrulanmalıdır.',searchQuery:'Type 2 EV şarj kablosu 32A trifaze 22 kW'},
    {id:'ups_battery',name:'UPS yedek aküsü ve kartuşu',mode:'guide',risk:'compatibility',affiliatePolicy:'after_tool',nextStepUrl:'https://alo186.com/haberler/ups-akusu-ne-zaman-degisir',nextStepLabel:'Önce değişim gereğini ve tam kartuş uyumunu kontrol et',description:'UPS tam modeli, üreticinin kartuş kodu, seri/paralel adet, gerilim, kapasite, terminal ve batarya kimyası doğrulanmadan akü alınmamalıdır.',searchQuery:'UPS yedek akü kartuş 12V 7Ah 9Ah RBC uyumlu'},
    {id:'extension_cord',name:'Uzatma kablosu ve kablo makarası',mode:'guide',risk:'safety',affiliatePolicy:'after_tool',nextStepUrl:'https://alo186.com/hesaplama/uzatma-kablosu-kablo-makarasi-uygunluk/',nextStepLabel:'Önce yük, uzunluk, kesit, etiket ve makara güvenliğini test et',description:'Yük, uzunluk, kesit, etiket akımı, topraklama, sarılı/açılmış makara sınırı ve ortam uygunluğu doğrulanmadan ürün rotası açılmaz.',searchQuery:'topraklı uzatma kablosu kablo makarası 16A termik koruma'}
  ];
  const products=[
    {id:'anker-prime-a1336',category:'powerbank',asin:'B0BYNZXFM2',mpn:'A1336',name:'Anker Prime A1336 20.000 mAh 200 W Toplam',brand:'Anker',status:'verified_listing',verifiedAt:'2026-07-30',attributes:{capacityMah:20000,maxOutputW:100,maxSingleDeviceW:100,totalOutputW:200,wireless:false,usbCPorts:2,usbAPorts:1,display:true,pd3:true,pps:true,weightG:545},strengths:['Tek cihazda 100 W USB-C','İki USB-C ile 200 W toplam sınıfı','Dijital ekran','20.000 mAh'],limits:['200 W değeri toplam çoklu port gücüdür; tek cihaz çıkışı 100 W ile sınırlıdır','Gerçek güç cihaz, kablo, sıcaklık ve doluluk durumuyla sınırlanabilir'],sourceNote:'A1336 model kodu, 20.000 mAh, iki USB-C ve bir USB-A, USB-C başına 100 W ve 200 W toplam çıkış Anker teknik kaynağıyla 30 Temmuz 2026 tarihinde doğrulandı; fiyat, stok, puan ve garanti yayımlanmaz.',url:amazonProductUrl('B0BYNZXFM2')},
    {id:'anker-737-a1289',category:'powerbank',asin:'B09VPHVT2Z',mpn:'A1289',name:'Anker 737 PowerCore 24K 24.000 mAh 140 W',brand:'Anker',status:'verified_listing',verifiedAt:'2026-07-30',attributes:{capacityMah:24000,maxOutputW:140,maxSingleDeviceW:140,totalOutputW:140,wireless:false,usbCPorts:2,usbAPorts:1,display:true,pd31:true,pps:true,weightG:630},strengths:['Tek cihazda 140 W USB-C sınıfı','24.000 mAh kapasite','İki USB-C ve bir USB-A','Akıllı dijital ekran'],limits:['140 W için cihazın ve kablonun USB PD 3.1 desteği gerekir','Birden fazla cihazda toplam güç portlar arasında paylaşılır'],sourceNote:'ASIN B09VPHVT2Z ile A1289 model eşleşmesi; 24.000 mAh, 140 W azami USB-C, iki USB-C, bir USB-A, PD/QC/PPS ve ekran alanları Anker teknik kaynaklarıyla 30 Temmuz 2026 tarihinde doğrulandı; fiyat, stok, puan ve garanti yayımlanmaz.',url:amazonProductUrl('B09VPHVT2Z')},
    {id:'anker-a1383-20k-87w',category:'powerbank',asin:'B0CXDXP8VR',mpn:'A1383',name:'Anker A1383 20.000 mAh 87 W Toplam Powerbank',brand:'Anker',status:'verified_listing',verifiedAt:'2026-07-30',attributes:{capacityMah:20000,maxOutputW:65,maxSingleDeviceW:65,totalOutputW:87,wireless:false,usbCPorts:1,usbAPorts:1,builtInUsbCCable:true,usbCOutputs:2,display:false,weightG:430.91},strengths:['Tek cihazda 65 W USB-C','87 W toplam çoklu cihaz çıkışı','Dahili USB-C kablo','20.000 mAh'],limits:['87 W değeri 65 W + 22 W toplam paylaşım sınıfıdır; tek cihaz çıkışı 65 W ile sınırlıdır','Dahili kablo ve ayrı USB-C çıkışı aynı anda kullanılırken güç paylaşımı uygulanır'],sourceNote:'ASIN B0CXDXP8VR ile A1383 model eşleşmesi; 20.000 mAh, tek cihazda 65 W, 87 W toplam (65 W + 22 W), dahili USB-C kablo, bir USB-C portu ve bir USB-A portu Anker teknik kaynağıyla 30 Temmuz 2026 tarihinde doğrulandı; fiyat, stok, puan ve garanti yayımlanmaz.',url:amazonProductUrl('B0CXDXP8VR')},
    {id:'xiaomi-wireless-10000',category:'powerbank',asin:'B09TWRHGWV',name:'Xiaomi 10 W Wireless Power Bank 10.000',brand:'Xiaomi',status:'verified_listing',verifiedAt,attributes:{capacityMah:10000,energyWh:null,maxOutputW:10,wireless:true,usbCPorts:1,usbAPorts:null,display:false},strengths:['Kablosuz şarj','10.000 mAh','Düşük akım modu'],limits:['Yüksek güçlü dizüstü ihtiyacı için uygun kabul edilmemeli','Kablolu maksimum çıkış üründe yeniden doğrulanmalı'],sourceNote:'ASIN, 10.000 mAh ve 10 W kablosuz özellikleri ürün sayfasından kontrol edildi.',url:amazonProductUrl('B09TWRHGWV')},
    {id:'samsung-eb-u2510x',category:'powerbank',asin:'B0CVGVG7NW',mpn:'EB-U2510X',name:'Samsung EB-U2510X 10.000 mAh Kablosuz Powerbank',brand:'Samsung',status:'verified_listing',verifiedAt,attributes:{capacityMah:10000,wireless:true,usbPorts:2,weightG:150},strengths:['Kablosuz kullanım','10.000 mAh','İki bağlantı noktası'],limits:['Kablolu ve kablosuz maksimum çıkış satın alma öncesi yeniden doğrulanmalı'],sourceNote:'ASIN, EB-U2510X model kodu, 10.000 mAh, iki bağlantı noktası ve 150 g teknik alanları ürün sayfasından doğrulandı; fiyat, stok, puan ve garanti yayımlanmaz.',url:amazonProductUrl('B0CVGVG7NW')},
    {id:'anker-313-a2677',category:'usb_c_charger',asin:'B0BQLGTCG3',mpn:'A2677',name:'Anker 313 Ace USB-C Şarj Cihazı 45 W',brand:'Anker',status:'verified_listing',verifiedAt,attributes:{maxOutputW:45,usbCPorts:1,usbAPorts:0,gan:true,samsungSfc2:true},strengths:['45 W USB-C çıkış sınıfı','Samsung Süper Hızlı Şarj 2.0 desteği','Tek portlu kompakt yapı'],limits:['Şarj kablosu ve cihaz protokolü ayrıca uyumlu olmalıdır','SFC 2.0 için 5 A kablo gerekir'],sourceNote:'ASIN, A2677 model kodu, 45 W, tek USB-C port ve Samsung Süper Hızlı Şarj 2.0 desteği ürün sayfasından doğrulandı; fiyat, stok, puan ve garanti yayımlanmaz.',url:amazonProductUrl('B0BQLGTCG3')},
    {id:'samsung-ep-t6530-trio-65w',category:'usb_c_charger',asin:'B09W2HP21R',mpn:'EP-T6530NBEGWW',name:'Samsung Trio 65 W Üç Portlu USB-C Şarj Adaptörü',brand:'Samsung',status:'verified_listing',verifiedAt:'2026-07-30',attributes:{maxOutputW:65,usbCPorts:2,usbAPorts:1,pd3:true,samsungSfc2:true,multiPortDistribution:'35W+25W+5W'},strengths:['Tek USB-C portta 65 W sınıfı','İki USB-C ve bir USB-A port','PD 3.0 ve Samsung SFC 2.0'],limits:['Üç cihaz birlikte kullanıldığında güç 35 W + 25 W + 5 W olarak paylaşılır','65 W ve Samsung 45 W SFC için 5 A kablo gerekir','Şarj kablosu kutuya dahil değildir'],sourceNote:'ASIN, EP-T6530NBEGWW model kodu, tek portta 65 W, 2 USB-C + 1 USB-A, PD 3.0/SFC 2.0 ve çoklu portta 35 W + 25 W + 5 W dağılımı Amazon ürün sayfası ve Samsung teknik açıklamasıyla 30 Temmuz 2026 tarihinde doğrulandı; fiyat, stok, puan ve garanti yayımlanmaz.',url:amazonProductUrl('B09W2HP21R')},
    {id:'baseus-cafule-catklf-gg1',category:'usb_c_cable',asin:'B0144AE0V6',mpn:'CATKLF-GG1',variantGroup:'baseus-usbc-cable',name:'Baseus Cafule USB-C - USB-C 3 A 1 m Kablo',brand:'Baseus',status:'verified_listing',verifiedAt,attributes:{connectorA:'USB-C',connectorB:'USB-C',maxCurrentA:3,maxPowerW:60,lengthM:1,dataTransfer:true},strengths:['USB-C - USB-C bağlantı','3 A / 60 W sınıfı','1 metre uzunluk','Şarj ve veri aktarımı'],limits:['100 W veya 240 W gerektiren cihazlar için yeterli kabul edilmemeli','Gerçek şarj hızı adaptör ve cihaz protokolüyle sınırlıdır'],sourceNote:'ASIN, CATKLF-GG1 model kodu, USB-C - USB-C, 3 A, 60 W, 1 m ve veri aktarımı alanları ürün sayfasından doğrulandı; fiyat, stok, puan ve garanti yayımlanmaz.',url:amazonProductUrl('B0144AE0V6')},
    {id:'baseus-crystal-shine-100w-2m',category:'usb_c_cable',asin:'B0B46PHW14',variantGroup:'baseus-usbc-cable',name:'Baseus Crystal Shine USB-C - USB-C 100 W 2 m Kablo',brand:'Baseus',status:'verified_listing',verifiedAt,attributes:{connectorA:'USB-C',connectorB:'USB-C',maxCurrentA:5,maxPowerW:100,lengthM:2,dataTransferMbps:480},strengths:['100 W / 5 A sınıfı','2 metre uzunluk','480 Mbps veri aktarımı'],limits:['240 W USB PD EPR ihtiyacı için uygun kabul edilmemeli','Gerçek şarj hızı adaptör ve cihaz protokolüyle sınırlıdır'],sourceNote:'ASIN, 100 W, 5 A, 2 m ve 480 Mbps teknik alanları ürün sayfasından doğrulandı; fiyat, stok, puan ve garanti yayımlanmaz.',url:amazonProductUrl('B0B46PHW14')},
    {id:'ugreen-7in1-60515',category:'usb_c_hub',asin:'B093FKT9BF',mpn:'60515',name:'UGREEN 60515 7’si 1 Arada USB-C Hub',brand:'UGREEN',status:'verified_listing',verifiedAt,attributes:{hdmiMax:'4K@60Hz',ethernetMbps:1000,usbA3Ports:2,sdReader:true,microSdReader:true,pdPassThroughW:100},strengths:['4K@60Hz HDMI','Gigabit Ethernet','SD ve microSD','100 W PD geçiş portu'],limits:['100 W etiketi geçiş üst sınırıdır; hubın kendi adaptörü dahil anlamına gelmez','Kaynak cihaz USB-C görüntü çıkışını desteklemelidir'],sourceNote:'ASIN, 60515 model kodu, 7 bağlantı işlevi, 4K@60Hz HDMI, Gigabit Ethernet, iki USB 3.0, SD/microSD ve 100 W PD geçiş alanları ürün sayfasından doğrulandı; fiyat, stok, puan ve garanti yayımlanmaz.',url:amazonProductUrl('B093FKT9BF')},
    {id:'anker-555-8in1',category:'usb_c_hub',asin:'B0DJN3NDCP',name:'Anker 555 PowerExpand 8’i 1 Arada USB-C Hub',brand:'Anker',status:'verified_listing',verifiedAt,attributes:{ports:8,hdmiMax:'4K@60Hz',dataTransferGbps:10,pdPassThroughW:100,ethernet:true,sdReader:true},strengths:['8 bağlantı işlevi','4K@60Hz HDMI','10 Gbps veri sınıfı','100 W PD geçiş'],limits:['Kaynak cihazın görüntü çıkışı ve PD desteği ayrıca doğrulanmalıdır','Harici güç adaptörü içeriği satın alma öncesi kontrol edilmelidir'],sourceNote:'ASIN, 8’i 1 arada yapı, 4K@60Hz HDMI, 10 Gbps veri ve 100 W PD geçiş alanları ürün sayfasından doğrulandı; fiyat, stok, puan ve garanti yayımlanmaz.',url:amazonProductUrl('B0DJN3NDCP')},
    {id:'ugreen-usbc-dp14-2m',category:'display_cable',asin:'B0C4DB8MLL',mpn:'25158',variantGroup:'ugreen-usbc-dp14',name:'UGREEN USB-C - DisplayPort 1.4 Kablo 2 m',brand:'UGREEN',status:'verified_listing',verifiedAt,attributes:{connectorA:'USB-C',connectorB:'DisplayPort',lengthM:2,maxDataGbps:32.4,displayPortVersion:'1.4'},strengths:['DisplayPort 1.4 sınıfı','32,4 Gbps veri sınıfı','2 metre uzunluk'],limits:['Kaynak USB-C portu DisplayPort Alt Mode veya uyumlu görüntü çıkışı desteklemelidir','Çözünürlük ve yenileme hızı cihaz ve ekranla sınırlıdır'],sourceNote:'ASIN, 25158 model kodu, USB-C - DisplayPort 1.4, 32,4 Gbps ve 2 m varyantı ürün sayfasından doğrulandı; fiyat, stok, puan ve garanti yayımlanmaz.',url:amazonProductUrl('B0C4DB8MLL')},
    {id:'ugreen-usbc-dp14-3m',category:'display_cable',asin:'B0CDW73QH7',mpn:'25158',variantGroup:'ugreen-usbc-dp14',name:'UGREEN USB-C - DisplayPort 1.4 Kablo 3 m',brand:'UGREEN',status:'verified_listing',verifiedAt,attributes:{connectorA:'USB-C',connectorB:'DisplayPort',lengthM:3,maxDataGbps:32.4,displayPortVersion:'1.4'},strengths:['DisplayPort 1.4 sınıfı','32,4 Gbps veri sınıfı','3 metre uzunluk'],limits:['Kaynak USB-C portu DisplayPort Alt Mode veya uyumlu görüntü çıkışı desteklemelidir','Uzunluk arttıkça cihaz ve ekran uyumluluğu ayrıca doğrulanmalıdır'],sourceNote:'ASIN, 25158 model ailesi, USB-C - DisplayPort 1.4, 32,4 Gbps ve 3 m varyantı ürün sayfasından doğrulandı; fiyat, stok, puan ve garanti yayımlanmaz.',url:amazonProductUrl('B0CDW73QH7')},
    {id:'tuncmatik-tsk6136',category:'surge_strip',asin:'B07CST4766',name:'Tunçmatik TSK6136 PowerSurge 5 Priz 1050 J',brand:'Tunçmatik',status:'verified_listing',verifiedAt,attributes:{outlets:5,joules:1050,maxCurrentA:10,maxPowerW:null,usbPorts:0,cableM:1.5},strengths:['1050 joule','5 çocuk emniyetli priz','1,5 m kablo'],limits:['10 A nominal akım','Pano tipi SPD ve uygun topraklamanın yerine geçmez'],sourceNote:'ASIN, 1050 J, 8000 A tepe, 10 A nominal ve 5 priz bilgileri ürün sayfasından kontrol edildi.',url:amazonProductUrl('B07CST4766')},
    {id:'viko-multilet-6',category:'surge_strip',asin:'B08L9KVRP1',mpn:'NK-2918-1664',name:'Viko Multilet Şok Korumalı 6’lı Grup Priz',brand:'Viko',status:'verified_listing',verifiedAt,attributes:{outlets:6,joules:282,maxCurrentA:16,maxPowerW:3500,usbPorts:0,cableM:1.5,protectionLevelKv:1.7,surgeCurrentA:6500},strengths:['6 priz','16 A / 3500 W etiket bilgisi','282 joule','Çocuk koruma'],limits:['Pano tipi SPD ve uygun topraklamanın yerine geçmez','IP20 iç ortam sınıfıdır'],sourceNote:'ASIN, üretici referansı, 6 priz, 16 A, 3500 W, 282 J, 1,7 kV koruma seviyesi ve 6500 A tepe akımı ürün sayfasından doğrulandı; fiyat, stok, puan ve garanti yayımlanmaz.',url:amazonProductUrl('B08L9KVRP1')},
    {id:'tuncmatik-tsk5015',category:'surge_strip',asin:'B08KW6X13Y',name:'Tunçmatik PowerSurge 5 Priz + USB TSK5015',brand:'Tunçmatik',status:'verified_listing',verifiedAt,attributes:{outlets:5,joules:null,maxCurrentA:null,maxPowerW:null,usbPorts:2,cableM:null},strengths:['5 priz','USB çıkışları','Elektronik cihaz kullanım senaryosu'],limits:['Joule ve nominal akım satın alma öncesi ürün etiketinden doğrulanmalı'],sourceNote:'ASIN, model, 5 priz ve USB özellikleri ürün sayfasından kontrol edildi; bilinmeyen alanlar puanda cezalandırılır.',url:amazonProductUrl('B08KW6X13Y')},
    {id:'cata-ct9186',category:'surge_strip',asin:'B09YTYTZ4J',name:'Cata CT-9186 Tekli Akım Korumalı Priz 918 J',brand:'Cata',status:'verified_listing',verifiedAt,attributes:{outlets:1,joules:918,maxCurrentA:null,maxPowerW:4000,usbPorts:0,cableM:0},strengths:['918 joule','Tek cihaz için kompakt kullanım','LED gösterge'],limits:['Tek priz','4000 W ifadesi ürün sayfasında tekrar doğrulanmalı','Pano tipi koruma yerine geçmez'],sourceNote:'ASIN, 918 J ve 4000 W ürün başlığı/açıklamasından kontrol edildi.',url:amazonProductUrl('B09YTYTZ4J')},
    {id:'philips-spn7040wa-62',category:'surge_strip',asin:'B09Y5VH14K',mpn:'SPN7040WA/62',name:'Philips SPN7040WA/62 4’lü Akım Korumalı Grup Priz 600 J',brand:'Philips',status:'verified_listing',verifiedAt,attributes:{outlets:4,joules:600,maxCurrentA:16,maxPowerW:3680,usbPorts:0,cableM:2,doublePoleSwitch:true},strengths:['4 topraklı priz','600 joule','2 m kablo','16 A / 3680 W'],limits:['Pano tipi SPD ve uygun topraklamanın yerine geçmez','600 J sınıfı daha yüksek darbe enerjisi ihtiyacında ayrıca değerlendirilmelidir'],sourceNote:'ASIN, model, 4 priz, 600 J, 2 m, 16 A ve 3680 W alanları ürün sayfasından doğrulandı; fiyat ve stok gösterilmez.',url:amazonProductUrl('B09Y5VH14K')},
    {id:'tuncmatik-tsk6134',category:'surge_strip',asin:'B08L9LF2WC',mpn:'TSK6134',name:'Tunçmatik TSK6134 PowerSurge 5 Priz 1050 J',brand:'Tunçmatik',status:'verified_listing',verifiedAt,attributes:{outlets:5,joules:1050,maxCurrentA:null,maxPowerW:null,usbPorts:0,cableM:1.5},strengths:['5 priz','1050 joule','1,5 m kablo'],limits:['Nominal akım ve maksimum güç ürün etiketinden satın alma öncesi yeniden doğrulanmalı','Pano tipi SPD yerine geçmez'],sourceNote:'ASIN, model, 5 priz, 1050 J ve 1,5 m alanları ürün listelemesinden doğrulandı; bilinmeyen alanlar null tutuldu.',url:amazonProductUrl('B08L9LF2WC')},
    {id:'brennenstuhl-eco-line-6',category:'surge_strip',asin:'B07RWYSQKV',name:'Brennenstuhl Eco-Line 6’lı Akım Korumalı Grup Priz',brand:'Brennenstuhl',status:'verified_listing',verifiedAt,attributes:{outlets:6,joules:null,maxCurrentA:16,maxPowerW:3500,usbPorts:0,cableM:1.5,surgeCurrentA:13500},strengths:['6 priz','13.500 A azami darbe akımı','1,5 m kablo','16 A / 3500 W'],limits:['Joule değeri Amazon sayfasında yeniden doğrulanmalı','Darbe akımı değeri joule değeriyle aynı değildir'],sourceNote:'ASIN; üretici kaynağından 6 priz, 13.500 A, 1,5 m, 16 A ve 3500 W alanları doğrulandı; fiyat ve stok yayımlanmaz.',url:amazonProductUrl('B07RWYSQKV')}
  ];
  function dateOnly(value){const date=value instanceof Date?value:new Date(value);return Number.isNaN(date.getTime())?null:new Date(Date.UTC(date.getUTCFullYear(),date.getUTCMonth(),date.getUTCDate()));}
  function verificationStatus(item,now=new Date()){const checked=dateOnly(item&&item.verifiedAt);const today=dateOnly(now);if(!checked||!today)return {fresh:false,ageDays:null,verifiedAt:item&&item.verifiedAt||null,maxAgeDays:verificationMaxAgeDays};const ageDays=Math.max(0,Math.floor((today.getTime()-checked.getTime())/86400000));return {fresh:ageDays<=verificationMaxAgeDays,ageDays,verifiedAt:item.verifiedAt,maxAgeDays:verificationMaxAgeDays};}
  function getCategory(id){return categories.find(c=>c.id===id)||null;}
  function productsFor(category,options={}){const now=options.now||new Date();const freshOnly=Boolean(options.freshOnly);return products.filter(product=>product.category===category&&product.status==='verified_listing'&&(!freshOnly||verificationStatus(product,now).fresh));}
  function searchUrl(category){const c=getCategory(category);return c?amazonSearchUrl(c.searchQuery):'https://www.amazon.com.tr';}
  function publicAffiliateEligible(product,options={}){const category=getCategory(product&&product.category);const now=options.now||new Date();const freshOnly=options.freshOnly!==false;return Boolean(category&&category.mode==='direct'&&category.affiliatePolicy==='verified_direct'&&product&&product.status==='verified_listing'&&(!freshOnly||verificationStatus(product,now).fresh));}
  function slug(value){return String(value||'').toLocaleLowerCase('tr-TR').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');}
  function productId(product){return `${siteOrigin}/akilli-urun-secimi/urun/${encodeURIComponent(product.id)}#product`;}
  function productPageUrl(product){return `${siteOrigin}/akilli-urun-secimi?kategori=${encodeURIComponent(product.category)}&urun=${encodeURIComponent(product.id)}`;}
  function brandId(brand){return `${siteOrigin}/knowledge-graph/brand/${slug(brand)}#brand`;}
  function categoryId(category){return `${siteOrigin}/knowledge-graph/category/${encodeURIComponent(category)}#category`;}
  function productGroupId(group){return `${siteOrigin}/knowledge-graph/product-group/${encodeURIComponent(group)}#group`;}
  function additionalProperties(product,publicDirect){return [...Object.entries(product.attributes||{}).filter(([,value])=>value!==null&&value!==undefined).map(([name,value])=>({'@type':'PropertyValue',name,value})),{'@type':'PropertyValue',name:'Teknik doğrulama tarihi',value:product.verifiedAt},{'@type':'PropertyValue',name:'Ticari ilişki',value:publicDirect?'Doğrulanmış Amazon satış ortaklığı bağlantısı':'Teknik uygunluk kapısından sonra açılan Amazon satış ortaklığı yolu'}];}
  function productNode(product,options={}){const now=options.now||new Date();const publicDirect=options.publicDirect===undefined?publicAffiliateEligible(product,{now}):Boolean(options.publicDirect);const category=getCategory(product.category);const identifiers=[{'@type':'PropertyValue',propertyID:'ASIN',value:product.asin}];if(product.mpn)identifiers.push({'@type':'PropertyValue',propertyID:'MPN',value:product.mpn});return {'@type':'Product','@id':productId(product),name:product.name,url:productPageUrl(product),sku:product.id,identifier:identifiers,...(product.mpn?{mpn:product.mpn}:{}),...(product.variantGroup?{isVariantOf:{'@id':productGroupId(product.variantGroup)}}:{}),...(publicDirect?{sameAs:product.url}:{}),brand:{'@id':brandId(product.brand)},category:{'@id':categoryId(product.category)},description:product.sourceNote,dateModified:product.verifiedAt,additionalProperty:additionalProperties(product,publicDirect),...(publicDirect?{}:{potentialAction:{'@type':'ViewAction',target:category&&category.nextStepUrl?category.nextStepUrl:productPageUrl(product),name:category&&category.nextStepLabel?category.nextStepLabel:'Önce teknik uygunluğu doğrula'}}),subjectOf:{'@id':`${productPageUrl(product)}#webpage`},mainEntityOfPage:{'@id':`${productPageUrl(product)}#webpage`}};}
  function productGroupNodes(verifiedProducts){const groups=[...new Set(verifiedProducts.map(product=>product.variantGroup).filter(Boolean))];return groups.map(group=>{const variants=verifiedProducts.filter(product=>product.variantGroup===group);return {'@type':'ProductGroup','@id':productGroupId(group),name:`${variants[0].brand} ürün varyant ailesi`,variesBy:['https://schema.org/size'],hasVariant:variants.map(product=>({'@id':productId(product)}))};});}
  function catalogHealth(options={}){const now=options.now||new Date();const fresh=products.filter(product=>product.status==='verified_listing'&&verificationStatus(product,now).fresh);const publicProducts=fresh.filter(product=>publicAffiliateEligible(product,{now}));const checked=dateOnly(verifiedAt);const reviewBy=checked?new Date(checked.getTime()+30*86400000).toISOString().slice(0,10):null;const staleAfter=checked?new Date(checked.getTime()+(verificationMaxAgeDays+1)*86400000).toISOString().slice(0,10):null;return {verifiedAt,verificationMaxAgeDays,totalVerified:fresh.length,publicDirect:publicProducts.length,gatedVerified:fresh.length-publicProducts.length,variantGroups:new Set(fresh.map(product=>product.variantGroup).filter(Boolean)).size,reviewBy,staleAfter};}
  function knowledgeGraph(options={}){const now=options.now||new Date();const verifiedProducts=products.filter(product=>product.status==='verified_listing'&&verificationStatus(product,now).fresh);const publicProducts=verifiedProducts.filter(product=>publicAffiliateEligible(product,{now}));const gatedProducts=verifiedProducts.filter(product=>!publicAffiliateEligible(product,{now,freshOnly:false}));const uniqueBrands=[...new Set(verifiedProducts.map(product=>product.brand))].sort((a,b)=>a.localeCompare(b,'tr'));const brands=uniqueBrands.map(name=>({'@type':'Brand','@id':brandId(name),name}));const categoryNodes=categories.map(category=>({'@type':'DefinedTerm','@id':categoryId(category.id),termCode:category.id,name:category.name,description:category.description,inDefinedTermSet:{'@id':`${siteOrigin}/knowledge-graph/electrical-product-categories#termset`}}));const allList={'@type':'ItemList','@id':`${siteOrigin}/akilli-urun-secimi#verified-products`,name:'ALO186 doğrulanmış affiliate ürün bilgi grafiği',numberOfItems:verifiedProducts.length,itemListElement:verifiedProducts.map((product,index)=>({'@type':'ListItem',position:index+1,item:{'@id':productId(product)}}))};const directList={'@type':'ItemList','@id':`${siteOrigin}/akilli-urun-secimi#direct-affiliate-products`,name:'ALO186 doğrudan affiliate uygun ürünleri',numberOfItems:publicProducts.length,itemListElement:publicProducts.map((product,index)=>({'@type':'ListItem',position:index+1,item:{'@id':productId(product)}}))};const gatedList={'@type':'ItemList','@id':`${siteOrigin}/akilli-urun-secimi#tool-gated-products`,name:'ALO186 teknik uygunluk kapılı affiliate ürünleri',numberOfItems:gatedProducts.length,itemListElement:gatedProducts.map((product,index)=>({'@type':'ListItem',position:index+1,item:{'@id':productId(product)}}))};const graph=[{'@type':'Organization','@id':`${siteOrigin}/#organization`,name:'ALO186',url:`${siteOrigin}/`,description:'Bağımsız elektrik bilgi ve ürün uygunluk platformu.'},{'@type':'WebSite','@id':`${siteOrigin}/#website`,url:`${siteOrigin}/`,name:'ALO186',publisher:{'@id':`${siteOrigin}/#organization`}},{'@type':'DefinedTermSet','@id':`${siteOrigin}/knowledge-graph/electrical-product-categories#termset`,name:'ALO186 elektrik ürün kategorileri',hasDefinedTerm:categoryNodes.map(node=>({'@id':node['@id']}))},allList,directList,gatedList,...categoryNodes,...brands,...productGroupNodes(verifiedProducts),...verifiedProducts.map(product=>productNode(product,{now,publicDirect:publicAffiliateEligible(product,{now})}))];return {'@context':'https://schema.org','@graph':graph};}
  return {affiliateTag,verifiedAt,verificationMaxAgeDays,categories,products,getCategory,productsFor,verificationStatus,amazonProductUrl,amazonSearchUrl,searchUrl,publicAffiliateEligible,productId,productNode,productGroupNodes,catalogHealth,knowledgeGraph};
});
