(() => {
  'use strict';

  const core=window.Alo186DocumentationGrowthCore;
  const catalog=window.Alo186ProductCatalog;
  if(!core||!catalog)return;

  const $=id=>document.getElementById(id);
  let current={category:'',productId:'',productLabel:'',assessment:null};
  let reviews=readReviews();

  function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));}
  function escapeAttr(value){return escapeHtml(value).replace(/`/g,'&#96;');}
  function productById(id){return catalog.products.find(product=>product.id===id)||null;}
  function activeCategory(){return document.querySelector('[data-category][aria-pressed="true"]')?.dataset.category||current.category||'';}
  function emit(name,params={}){const clean={};for(const key of ['category','status','placement','supplier_category']){if(typeof params[key]==='string'&&params[key].length<=80)clean[key]=params[key];}if(Number.isFinite(params.missing_count))clean.missing_count=params.missing_count;if(Number.isFinite(params.score))clean.score=params.score;if(typeof window.Alo186Track==='function')window.Alo186Track(name,clean);}

  function injectStyles(){
    if($('documentationGrowthStyles'))return;
    const style=document.createElement('style');style.id='documentationGrowthStyles';style.textContent=`
      .documentation-lab{margin-top:28px}.documentation-summary{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:18px;align-items:start}.documentation-score{display:grid;place-items:center;min-width:118px;min-height:118px;border-radius:22px;background:#071631;color:#fff}.documentation-score strong{font-size:2rem}.documentation-score small{color:#cfdaec;text-align:center}.documentation-status{display:inline-flex;padding:6px 10px;border-radius:999px;font-size:.78rem;font-weight:900}.documentation-status.complete{background:#d9f4eb;color:#075843}.documentation-status.conditional{background:#fff0bd;color:#6e4900}.documentation-status.blocked,.documentation-status.stale{background:#ffe1dc;color:#8b1b13}.documentation-product-grid{display:grid;gap:10px;margin:18px 0}.documentation-product{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:14px;align-items:center;padding:14px;border:1px solid #dce4ee;border-radius:14px;background:#f8faff}.documentation-product p{margin:.25rem 0;color:#526178}.documentation-question-list{display:grid;gap:9px;padding:0;list-style:none;counter-reset:docq}.documentation-question-list li{counter-increment:docq;display:grid;grid-template-columns:32px 1fr;gap:10px;padding:12px;border-radius:12px;background:#f5f8fd}.documentation-question-list li:before{content:counter(docq);display:grid;place-items:center;width:28px;height:28px;border-radius:50%;background:#e5edff;color:#1749a7;font-weight:900}.documentation-question-list b{display:block;color:#071631}.documentation-question-list small{color:#5c6b80}.documentation-actions{display:flex;flex-wrap:wrap;gap:9px}.documentation-note{padding:13px 15px;border-left:4px solid #3d6fce;background:#f0f5ff}.documentation-review-list{display:grid;gap:9px;margin-top:14px}.documentation-review{display:flex;justify-content:space-between;gap:14px;align-items:center;padding:12px;border:1px solid #dce4ee;border-radius:12px}.doc-badge{display:flex;align-items:center;justify-content:space-between;gap:10px;margin:10px 0;padding:9px 11px;border-radius:11px;background:#eef3fb;color:#25364d;font-size:.83rem}.doc-badge[data-doc-status="blocked"],.doc-badge[data-doc-status="stale"]{background:#fff0ed;color:#7f241d}.doc-question-button{margin-left:auto}.documentation-empty{color:#5c6b80}.documentation-supplier{margin-top:16px;padding:16px;border:1px solid #b7c7e4;border-radius:14px;background:#f7faff}.documentation-supplier strong{display:block;color:#071631}.documentation-supplier p{margin:.35rem 0 1rem;color:#526178}@media(max-width:700px){.documentation-summary{grid-template-columns:1fr}.documentation-score{min-height:92px}.documentation-product{grid-template-columns:1fr}.documentation-actions{display:grid}.documentation-actions .btn{width:100%}.documentation-review{align-items:flex-start;flex-direction:column}}`;
    document.head.appendChild(style);
  }

  function ensurePanel(){
    if($('documentationLab'))return true;
    const anchor=$('productShortlist')||$('results');if(!anchor)return false;
    const section=document.createElement('section');section.id='documentationLab';section.className='content-section documentation-lab hidden';section.setAttribute('aria-live','polite');section.innerHTML=`<div class="panel"><div class="section-title"><div><span class="eyebrow">Belge öncelikli güven ve dönüşüm</span><h2>Teknik belge kapsamı ve satıcı soru paketi</h2></div><span id="documentationStatus" class="documentation-status conditional">Kategori seçin</span></div><div class="documentation-summary"><div><p id="documentationIntro">Ürünü fiyat veya puanla değil, resmî teknik alanların tamamlanma düzeyiyle değerlendirin.</p><div id="documentationProducts" class="documentation-product-grid"></div></div><div id="documentationScore" class="documentation-score"><strong>—</strong><small>belge kapsamı</small></div></div><div id="documentationQuestionPanel" class="hidden"><h3 id="documentationQuestionTitle">Eksik teknik alanlar</h3><ul id="documentationQuestions" class="documentation-question-list"></ul><div class="documentation-actions"><button type="button" class="btn btn-primary" id="copyDocumentationQuestions">Soru paketini kopyala</button><button type="button" class="btn btn-secondary" id="downloadDocumentationQuestions">JSON indir</button><button type="button" class="btn btn-secondary" id="saveDocumentationReview">14 günlük yeniden kontrol oluştur</button></div><p id="documentationActionStatus" role="status"></p><div id="documentationSupplier" class="documentation-supplier"><strong>Üretici veya tedarikçi misiniz?</strong><p>Eksik teknik alanları tamamlamak, kılavuz/veri sayfasını kullanıcı sorularına göre inceletmek veya doğrulanmış veri kartı hazırlatmak için şeffaf ücretli teknik veri hizmetini açın. Ödeme organik sıralamayı veya güvenlik sonucunu değiştirmez.</p><a id="documentationSupplierLink" class="btn btn-secondary" href="/tedarikci-ve-uretici-isbirligi">Teknik veri hazırlık skorunu aç</a></div></div><div id="documentationComplete" class="documentation-note hidden"><strong>Kritik teknik alanlar tamam.</strong> Bu durum ürünün kesin uygun, güvenli veya satın alınması gerekli olduğu anlamına gelmez. Mevcut ekipman yeterliliği ve görünür affiliate onayları ayrıca korunur.</div><div id="documentationReviews"><h3>Belge yeniden kontrol takvimi</h3><p class="documentation-empty" id="documentationReviewsEmpty">Henüz belge kontrol kaydı yok.</p><div id="documentationReviewList" class="documentation-review-list"></div></div></div>`;
    anchor.insertAdjacentElement('afterend',section);
    $('copyDocumentationQuestions').addEventListener('click',copyQuestions);
    $('downloadDocumentationQuestions').addEventListener('click',downloadQuestions);
    $('saveDocumentationReview').addEventListener('click',saveReview);
    $('documentationSupplierLink').addEventListener('click',()=>{const a=current.assessment;emit('supplier_documentation_handoff_opened',{category:current.category,status:a?.status||'unknown',missing_count:a?.missing?.length||0,supplier_category:a?.supplierCategory||''});});
    $('documentationReviewList').addEventListener('click',event=>{const remove=event.target.closest('[data-doc-review-remove]');if(remove){reviews=core.removeReview(reviews,remove.dataset.docReviewRemove);writeReviews();renderReviews();return;}const calendar=event.target.closest('[data-doc-review-calendar]');if(calendar)downloadReviewCalendar(calendar.dataset.docReviewCalendar);});
    renderReviews();return true;
  }

  function readReviews(){try{return core.normalizeReviews(JSON.parse(localStorage.getItem(core.reviewStorageKey)||'[]'));}catch(_){return[];}}
  function writeReviews(){reviews=core.normalizeReviews(reviews);try{localStorage.setItem(core.reviewStorageKey,JSON.stringify(reviews));return true;}catch(_){return false;}}
  function formatDate(value){const date=new Date(value);return Number.isFinite(date.getTime())?new Intl.DateTimeFormat('tr-TR',{dateStyle:'medium'}).format(date):'—';}
  function downloadBlob(filename,content,type){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=filename;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),500);}
  async function clipboard(text){if(navigator.clipboard&&window.isSecureContext)return navigator.clipboard.writeText(text);const area=document.createElement('textarea');area.value=text;area.setAttribute('readonly','');area.style.position='fixed';area.style.opacity='0';document.body.appendChild(area);area.select();document.execCommand('copy');area.remove();}

  function assessmentLabel(assessment){const labels={complete:'Kritik alanlar tamam',conditional:'İsteğe bağlı alanlar eksik',blocked:'Kritik alan eksik',stale:'Doğrulama süresi geçmiş',unsupported:'Desteklenmeyen kategori'};return labels[assessment.status]||'Belge durumu';}
  function assessmentMessage(assessment){if(assessment.status==='stale')return`Teknik kontrol ${assessment.ageDays??'—'} gün önce yapılmış; ${assessment.maxAgeDays} günlük sınır geçti.`;if(assessment.status==='blocked')return`${assessment.criticalMissing.length} kritik teknik alan eksik olduğu için doğrudan affiliate bağlantısı açılmamalı.`;if(assessment.status==='conditional')return'Kritik alanlar mevcut; isteğe bağlı teknik ayrıntılar ürün sayfasında yeniden doğrulanmalı.';if(assessment.status==='complete')return'Katalog kartındaki tanımlı teknik alanlar tamam; gerçek ihtiyaç ve ürün etiketi yine doğrulanmalı.';return'Bu kategori için ürün kartı yerine genel teknik soru paketi kullanın.';}

  function assess(product){return core.assessProduct(product,{maxAgeDays:catalog.verificationMaxAgeDays||45,now:new Date()});}
  function renderCardBadges(){
    document.querySelectorAll('#directResult .product-card').forEach(card=>{
      const link=card.querySelector('[data-product]'),product=productById(link?.dataset.product);if(!link||!product)return;
      const result=assess(product);let badge=card.querySelector('[data-documentation-badge]');if(!badge){badge=document.createElement('div');badge.className='doc-badge';badge.dataset.documentationBadge='true';const actions=card.querySelector('.product-actions');if(actions)actions.parentNode.insertBefore(badge,actions);else card.appendChild(badge);}
      badge.dataset.docStatus=result.status;badge.innerHTML=`<span><strong>Teknik belge kapsamı ${result.score}/100</strong><br>${escapeHtml(assessmentLabel(result))}</span><button type="button" class="btn btn-secondary doc-question-button" data-documentation-open="${escapeAttr(product.id)}">Belge sorularını aç</button>`;
    });
  }

  function currentProducts(category){return catalog.products.filter(product=>product.category===category&&product.status==='verified_listing');}
  function aggregate(category,products){
    if(!products.length){const spec=core.categorySpecs[category];return{category,status:spec?.professionalOnly?'blocked':'conditional',score:0,missing:(spec?.fields||[]).map(f=>f.id),criticalMissing:(spec?.fields||[]).filter(f=>f.critical).map(f=>f.id),questions:(spec?.fields||[]).map(f=>f.question),affiliateAllowed:false,professionalOnly:Boolean(spec?.professionalOnly),supplierCategory:spec?.supplier||''};}
    const assessments=products.map(assess),score=Math.round(assessments.reduce((sum,item)=>sum+item.score,0)/assessments.length),missing=[...new Set(assessments.flatMap(item=>item.missing))],critical=[...new Set(assessments.flatMap(item=>item.criticalMissing))];
    const status=assessments.some(item=>item.status==='stale')?'stale':critical.length?'blocked':missing.length?'conditional':'complete';
    return{category,status,score,missing,criticalMissing:critical,questions:core.questionPack(category,missing).map(item=>item.question),affiliateAllowed:assessments.every(item=>item.affiliateAllowed),professionalOnly:assessments.some(item=>item.professionalOnly),supplierCategory:assessments[0]?.supplierCategory||core.categorySpecs[category]?.supplier||''};
  }

  function render(category,productId=''){
    if(!ensurePanel())return;const safe=core.safeCategory(category);if(!safe){$('documentationLab').classList.add('hidden');return;}
    const products=currentProducts(safe),product=productId?productById(productId):null,assessment=product?assess(product):aggregate(safe,products);
    current={category:safe,productId:product?.id||'category',productLabel:product?.name||core.categorySpecs[safe].label,assessment};
    $('documentationLab').classList.remove('hidden');$('documentationStatus').className=`documentation-status ${assessment.status}`;$('documentationStatus').textContent=assessmentLabel(assessment);$('documentationScore').innerHTML=`<strong>${assessment.score}</strong><small>/100 belge kapsamı</small>`;$('documentationIntro').textContent=product?`${product.name}: ${assessmentMessage(assessment)}`:`${core.categorySpecs[safe].label}: ${products.length?`${products.length} doğrulanmış kart belge kapsamına göre karşılaştırıldı.`:'Henüz güncel doğrulanmış ürün kartı yok; aşağıdaki marka bağımsız sorularla teknik veri isteyin.'}`;
    $('documentationProducts').innerHTML=products.length?products.map(item=>{const a=assess(item);return`<article class="documentation-product"><div><strong>${escapeHtml(item.name)}</strong><p>${escapeHtml(assessmentMessage(a))}</p><span class="documentation-status ${a.status}">${a.score}/100 · ${escapeHtml(assessmentLabel(a))}</span></div><button type="button" class="btn btn-secondary" data-documentation-open="${escapeAttr(item.id)}">Soruları aç</button></article>`;}).join(''):'<p class="documentation-empty">Ürün kartı eklemek için eksik teknik veriler resmî kaynakla tamamlanmalıdır.</p>';
    const questions=core.questionPack(safe,assessment.missing);$('documentationQuestionPanel').classList.toggle('hidden',!questions.length);$('documentationComplete').classList.toggle('hidden',questions.length>0);$('documentationQuestionTitle').textContent=product?`${product.name} için yeniden sorulacak teknik alanlar`:`${core.categorySpecs[safe].label} için teknik veri soru paketi`;$('documentationQuestions').innerHTML=questions.map(item=>`<li><div><b>${escapeHtml(item.label)}${item.critical?' · kritik':''}</b><small>${escapeHtml(item.question)}</small></div></li>`).join('');$('documentationSupplierLink').href=core.supplierRoute(safe,assessment.missing);$('documentationActionStatus').textContent=questions.length?'Sorular yalnız teknik veri ve kaynak kapsamını ister; fiyat, stok veya puan talep etmez.':'Kritik belge alanı eksik görünmüyor.';
    emit('documentation_assessment_rendered',{category:safe,status:assessment.status,score:assessment.score,missing_count:assessment.missing.length,supplier_category:assessment.supplierCategory});
  }

  function openQuestions(productId){const product=productById(productId);if(!product)return;render(product.category,product.id);$('documentationLab').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});emit('documentation_question_pack_opened',{category:product.category,status:assess(product).status,missing_count:assess(product).missing.length});}
  async function copyQuestions(){if(!current.category)return;const text=core.buildQuestionText(current.category,current.productLabel,current.assessment?.missing||[]);try{await clipboard(text);$('documentationActionStatus').textContent='Teknik soru paketi kopyalandı. Kişisel veya ticari değişken eklenmedi.';emit('documentation_question_pack_copied',{category:current.category,status:current.assessment?.status||'unknown',missing_count:current.assessment?.missing?.length||0});}catch(_){$('documentationActionStatus').textContent='Kopyalama başarısız; JSON indirme seçeneğini kullanın.';}}
  function downloadQuestions(){if(!current.category)return;const payload={schema:'alo186-documentation-question-pack-v1',generatedAt:new Date().toISOString(),category:current.category,productRef:current.productId,assessment:{status:current.assessment?.status,score:current.assessment?.score,missing:current.assessment?.missing||[],criticalMissing:current.assessment?.criticalMissing||[]},questions:core.questionPack(current.category,current.assessment?.missing||[]),privacy:'Fiyat, stok, puan, garanti, satıcı, ASIN, haricî URL veya kişisel veri içermez.'};downloadBlob(`alo186-teknik-sorular-${current.category}.json`,JSON.stringify(payload,null,2),'application/json;charset=utf-8');emit('documentation_question_pack_downloaded',{category:current.category,status:current.assessment?.status||'unknown',missing_count:current.assessment?.missing?.length||0});}
  function saveReview(){if(!current.category)return;const record=core.sanitizeReview({category:current.category,productId:current.productId,missing:current.assessment?.missing||[]});reviews=core.upsertReview(reviews,record);if(writeReviews()){$('documentationActionStatus').textContent=`Belge yeniden kontrolü ${formatDate(record.reviewAt)} için yalnız bu tarayıcıda kaydedildi.`;downloadBlob(`alo186-belge-kontrol-${current.category}.ics`,core.buildReviewIcs(record,location.origin),'text/calendar;charset=utf-8');emit('documentation_review_saved',{category:current.category,status:current.assessment?.status||'unknown',missing_count:record.missing.length});}else $('documentationActionStatus').textContent='Tarayıcı depolaması kullanılamadı; kayıt oluşturulamadı.';renderReviews();}
  function downloadReviewCalendar(id){const record=reviews.find(item=>item.id===id);if(!record)return;downloadBlob(`alo186-belge-kontrol-${record.category}.ics`,core.buildReviewIcs(record,location.origin),'text/calendar;charset=utf-8');}
  function renderReviews(){if(!$('documentationReviewList'))return;reviews=readReviews();$('documentationReviewsEmpty').classList.toggle('hidden',reviews.length>0);$('documentationReviewList').innerHTML=reviews.map(item=>`<article class="documentation-review"><div><strong>${escapeHtml(core.categorySpecs[item.category].label)}</strong><p>${item.missing.length} teknik alan · ${formatDate(item.reviewAt)} tarihinde yeniden kontrol</p></div><div class="documentation-actions"><a class="btn btn-secondary" href="/akilli-urun-secimi?kategori=${escapeAttr(item.category)}">Kategoriyi aç</a><button class="btn btn-secondary" type="button" data-doc-review-calendar="${escapeAttr(item.id)}">Takvim</button><button class="btn btn-secondary" type="button" data-doc-review-remove="${escapeAttr(item.id)}">Sil</button></div></article>`).join('');}

  function interceptAffiliate(event){const link=event.target?.closest?.('#directResult [data-product]');if(!link)return;const product=productById(link.dataset.product);if(!product)return;const assessment=assess(product);if(assessment.affiliateAllowed)return;event.preventDefault();event.stopImmediatePropagation();render(product.category,product.id);$('documentationActionStatus').textContent=assessment.status==='stale'?'Teknik doğrulama süresi geçtiği için affiliate bağlantısı kapalı.':'Kritik teknik alan eksik olduğu için affiliate bağlantısı kapalı; önce soru paketini kullanın.';$('documentationLab').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});emit('documentation_affiliate_blocked',{category:product.category,status:assessment.status,score:assessment.score,missing_count:assessment.criticalMissing.length,supplier_category:assessment.supplierCategory});}

  function init(){
    injectStyles();if(!ensurePanel())return;renderCardBadges();renderReviews();
    window.addEventListener('click',interceptAffiliate,true);
    document.addEventListener('click',event=>{const open=event.target.closest?.('[data-documentation-open]');if(open){event.preventDefault();openQuestions(open.dataset.documentationOpen);return;}const categoryButton=event.target.closest?.('[data-category],[data-intent-category]');if(categoryButton)setTimeout(()=>render(categoryButton.dataset.category||categoryButton.dataset.intentCategory),0);});
    const result=$('directResult');if(result)new MutationObserver(()=>{renderCardBadges();const category=activeCategory();if(category)render(category);}).observe(result,{childList:true,subtree:true});
    const query=new URLSearchParams(location.search).get('kategori');if(core.safeCategory(query))setTimeout(()=>render(query),250);
  }

  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
