'use strict';
(function(root,factory){
  const api=factory();
  if(typeof module==='object'&&module.exports)module.exports=api;
  if(root){root.ALO186PortableSafetyPlan=api;if(root.document)api.mount(root.document);}
})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const ROUTE='/sektor-rehberi/elektrik-kesintisi-aydinlatma-ve-guvenli-uzatma-merkezi/';
  function makePlan(data){
    if(data.danger)return {code:'danger',days:0,title:'Önce can ve yangın güvenliği',summary:'Duman, erime, elektrik çarpması, ıslaklık, şişmiş batarya veya ters besleme şüphesinde ürün ve test planı kapanır.',tasks:['Enerji kaynağından güvenli mesafe alın.','Gerekliyse 112, 186/EDAŞ ve yetkili elektrikçi rotasına geçin.','Hasarlı kablo, batarya veya armatürü kullanmayın ve şarj etmeyin.']};
    if(data.commercialOrEgress)return {code:'professional',days:30,title:'Ortak alan ve kaçış yolu için profesyonel test planı',summary:'Apartman, otel, işyeri, çıkış yolu ve yangın güvenliği; portatif ışık veya uzatma kablosuyla ikame edilmez.',tasks:['Acil aydınlatma ve çıkış işaretlerinin proje ve test kayıtlarını kontrol edin.','Akü, süre, şarj göstergesi ve fonksiyon testini yetkin personelle planlayın.','Geçici uzatma kablolarını kalıcı tesisat yerine kullanmayın.','Eksik görevleri 30 gün içinde kapatın ve kayıt altına alın.']};
    if(data.existingPass&&!data.newLoad&&!data.outdoorChange)return {code:'no_buy',days:90,title:'Mevcut güvenli ekipmanı koruyun',summary:'Aydınlatma ve uzatma düzeni gerçek görev testini geçtiyse yalnız daha yeni model için değiştirmeyin.',tasks:['Fener, ışıldak ve şarjlı ampulleri aynı parlaklıkta yeniden test edin.','Uzatma ve makara etiketini, fişi, kesiti ve tam açma durumunu kontrol edin.','Batarya, kablo veya yük değişirse testi erkene alın.','90 gün sonra aynı görev listesini tekrarlayın.']};
    if(data.scenario==='outage')return {code:'outage',days:30,title:'Kesinti sonrası aydınlatma ve kablo kanıt planı',summary:'Aktif kesintide yeni teslimatı çözüm saymayın; olay sonrasında gerçek süre ve bağlantı sonuçlarını kaydedin.',tasks:['Hangi alanların karanlık kaldığını ve mevcut ışıkların kaç saat çalıştığını kaydedin.','Mum veya açık alevi plan dışı bırakın.','Jeneratör varsa erkek–erkek kablo ve ters beslemeyi kesinlikle kullanmayın.','Kesinti sonrası uzatma kablosunda ısınma ve fiş hasarı kontrolü yapın.','30 gün içinde eksik görevi gerçek testle doğrulayın.']};
    if(data.scenario==='outdoor'||data.outdoorChange)return {code:'outdoor',days:30,title:'Dış ortam ve portatif alet kontrol planı',summary:'Ortam sınıfı, RCD, topraklama, mekanik koruma ve makara açma kanıtı tamamlanmadan ürün seçimi yapılmaz.',tasks:['Kablo ve makaranın dış ortam uygunluk işaretini doğrulayın.','Makara varsa tamamen açın ve üretici etiketindeki açık/sarılı sınırı okuyun.','Topraklama ve kaçak akım korumasını güvenilir test kaydıyla doğrulayın.','Gerçek yükte fiş, kablo ve makara sıcaklığını gözlemleyin.','30 gün sonra veya yeni alet eklendiğinde yeniden değerlendirin.']};
    if(data.scenario==='new-light'||data.newLoad)return {code:'new',days:30,title:'Yeni yük veya aydınlatma görevini önce ölçün',summary:'Yeni cihazı mevcut uzatma ve ışık planına eklemeden önce etiket, süre, alan ve koruma zincirini doğrulayın.',tasks:['Yeni yükün gerçek W/A etiketini kaydedin.','Uzatma/makara etiket akımı ve kablo kesitiyle karşılaştırın.','Aydınlatma için seçilen parlaklıkta gerçek çalışma süresini test edin.','Mevcut ekipman yeterliyse satın almama sonucunu kaydedin.','30 gün sonra gerçek kullanım sonucunu yeniden kontrol edin.']};
    return {code:'routine',days:90,title:'90 günlük taşınabilir elektrik güvenliği kontrolü',summary:'Tekrar ziyaret nedeni kampanya değil; batarya, yük, kablo, ortam ve gerçek görev sonucudur.',tasks:['Şarjlı ampul, ışıldak ve fenerlerde batarya/gövde kontrolü yapın.','Aynı parlaklıkta gerçek süre testini yenileyin.','Uzatma kablosu, fiş, makara ve etiketleri kontrol edin.','Zincirleme bağlantı, adaptör ve ters besleme olmadığını doğrulayın.','Mevcut ekipman yeterliyse yeni ürün almayın.']};
  }
  function report(data){return {route:ROUTE,generatedAt:new Date().toISOString(),plan:makePlan(data),personalData:false,officialRecord:false,commerce:false};}
  function calendar(plan){
    const days=Math.max(1,Number(plan.days)||90);
    const start=new Date(Date.now()+days*86400000);
    const end=new Date(start.getTime()+30*60000);
    const stamp=(date)=>date.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z');
    return ['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//ALO186//Portable Electrical Safety Plan//TR','BEGIN:VEVENT',`UID:portable-safety-${Date.now()}@alo186.com`,`DTSTAMP:${stamp(new Date())}`,`DTSTART:${stamp(start)}`,`DTEND:${stamp(end)}`,`SUMMARY:${plan.title.replace(/[,;]/g,' ')}`,`DESCRIPTION:${plan.tasks.join(' | ').replace(/[,;]/g,' ')}`,'END:VEVENT','END:VCALENDAR'].join('\r\n');
  }
  function download(name,text,type){const blob=new Blob([text],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),0);}
  function read(doc){const value=(id)=>doc.getElementById(id)?.value;const checked=(id)=>Boolean(doc.getElementById(id)?.checked);return {scenario:value('scenario'),danger:checked('danger'),commercialOrEgress:checked('commercialOrEgress'),existingPass:checked('existingPass'),newLoad:checked('newLoad'),outdoorChange:checked('outdoorChange')};}
  function mount(doc){const form=doc.getElementById('planForm');if(!form)return;let current=null;form.addEventListener('submit',(event)=>{event.preventDefault();current=report(read(doc));const plan=current.plan;const result=doc.getElementById('result');result.className=`result ${plan.code==='danger'?'danger':plan.code==='no_buy'?'ok':'warn'}`;result.innerHTML=`<h2>${plan.title}</h2><p>${plan.summary}</p><ol>${plan.tasks.map((task)=>`<li>${task}</li>`).join('')}</ol><p><strong>Tekrar kontrol:</strong> ${plan.days?plan.days+' gün':'risk giderildikten sonra'}</p>`;result.scrollIntoView({behavior:'smooth',block:'start'});});doc.getElementById('exportJson')?.addEventListener('click',()=>download('alo186-aydinlatma-uzatma-guvenlik-plani.json',JSON.stringify(current||report(read(doc)),null,2),'application/json'));doc.getElementById('calendar')?.addEventListener('click',()=>{const data=current||report(read(doc));if(data.plan.days)download('alo186-aydinlatma-uzatma-guvenlik-plani.ics',calendar(data.plan),'text/calendar');});}
  return {ROUTE,makePlan,report,calendar,mount};
});