const assert=require('assert');
const core=require('../sureklilik-paneli/growth-core.js');
let passed=0;
function scenario(name,fn){try{fn();passed++;console.log('✓',name);}catch(error){console.error('✗',name);throw error;}}
const NOW=new Date('2026-07-28T06:00:00Z');
function baseState(overrides={}){return {organization:{name:'Gizli Otel',profile:'hotel'},locations:[],criticalLoads:[],assets:[],tests:[],incidents:[],improvementActions:[],maturityImports:[],...overrides};}
scenario('1 — boş planda ücretsiz olgunluk skoru başlangıcı gösterilir',()=>{const rows=core.nextBestActions(baseState());assert.strictEqual(rows.length,1);assert(rows[0].href.includes('elektrik-surekliligi-olgunluk-skoru'));});
scenario('2 — açık aksiyonlar ufuk ve önceliğe göre sıralanır',()=>{const rows=core.nextBestActions(baseState({improvementActions:[{id:'a',title:'Düşük',dimension:'backup',horizonDays:60,priority:1},{id:'b',title:'Önce',dimension:'testing',horizonDays:30,priority:1},{id:'c',title:'Yüksek',dimension:'maintenance',horizonDays:30,priority:2}]}),3);assert.strictEqual(rows[0].title,'Yüksek');assert.strictEqual(rows[1].title,'Önce');});
scenario('3 — tamamlanmış aksiyon önerilmez',()=>{const rows=core.nextBestActions(baseState({improvementActions:[{id:'a',title:'Bitti',dimension:'backup',horizonDays:30,completed:true}]}));assert(!rows.some(x=>x.title==='Bitti'));});
scenario('4 — yedek güç ve bakım ücretsiz araçlara bağlanır',()=>{const rows=core.nextBestActions(baseState({improvementActions:[{id:'a',title:'Kapasite',dimension:'backup',horizonDays:30},{id:'b',title:'Bakım',dimension:'maintenance',horizonDays:60}]}));assert(rows.some(x=>x.href.endsWith('/hesaplama/yedek-guc-cozum-secici/')));assert(rows.some(x=>x.href.endsWith('/hesaplama/ekipman-bakim-plani/')));});
scenario('5 — doğrudan Amazon veya ürün URL’si üretilmez',()=>{const text=JSON.stringify(core.nextBestActions(baseState({improvementActions:[{id:'a',title:'Kapasite',dimension:'backup',horizonDays:30}]})));assert(!/amazon/i.test(text));assert(!/\/urun-/i.test(text));});
scenario('6 — aktivasyon sıfırdan altı adıma ilerler',()=>{assert.strictEqual(core.activationReadiness(baseState()).completed,0);const state=baseState({locations:[{}],criticalLoads:[{}],assets:[{}],tests:[{}],improvementActions:[{completed:false}],incidents:[{status:'closed'}]});const ready=core.activationReadiness(state);assert.strictEqual(ready.completed,6);assert.strictEqual(ready.ready,true);});
scenario('7 — dört aktivasyon adımı pilot iletişimini açmaya yeter',()=>{const state=baseState({locations:[{}],criticalLoads:[{}],assets:[{}],tests:[{}]});assert.strictEqual(core.activationReadiness(state).ready,true);});
scenario('8 — anonim pilot özeti kişisel ve serbest alanları taşımaz',()=>{const state=baseState({organization:{name:'Gizli A.Ş.',profile:'hotel'},locations:[{name:'Özel Adres',province:'Muğla'}],criticalLoads:[{name:'Yaşam destek',priority:'P1',category:'medical',owner:'Ayşe',notes:'0555'}],assets:[{name:'Seri 123',type:'generator',notes:'mail@example.com'}],incidents:[{status:'open',caseNumber:'186-ABC',summary:'Gizli olay'}]});const out=JSON.stringify(core.buildPilotBrief(state,NOW));for(const forbidden of ['Gizli A.Ş.','Özel Adres','Yaşam destek','Ayşe','0555','Seri 123','mail@example.com','186-ABC','Gizli olay','medical'])assert(!out.includes(forbidden),forbidden);});
scenario('9 — anonim pilot özeti yalnız toplulaştırılmış sayıları içerir',()=>{const result=core.buildPilotBrief(baseState({locations:[{},{}],criticalLoads:[{priority:'P1'}],assets:[{type:'ups'}],tests:[{}]}),NOW).brief;assert.strictEqual(result.inventory.locations,2);assert.strictEqual(result.inventory.p1Loads,1);assert.strictEqual(result.inventory.ups,1);assert.strictEqual(result.privacy.containsContact,false);});
scenario('10 — çoklu lokasyon gerekli SaaS yeteneğini ekler',()=>{const result=core.buildPilotBrief(baseState({locations:[{},{}]}),NOW).brief;assert(result.requestedCapabilities.includes('Çoklu lokasyon görünümü'));});
scenario('11 — açık aksiyonlar takvime, tamamlananlar alınmaz',()=>{const events=core.buildCalendarEvents(baseState({improvementActions:[{id:'a',title:'Aksiyon',dimension:'backup',horizonDays:30,createdAt:'2026-07-28T00:00:00Z'},{id:'b',title:'Bitti',dimension:'testing',horizonDays:60,createdAt:'2026-07-28T00:00:00Z',completed:true}]}),NOW);assert(events.some(x=>x.id==='action-a'));assert(!events.some(x=>x.id==='action-b'));});
scenario('12 — varlık takvim olayı isim ve lokasyon taşımaz',()=>{const events=core.buildCalendarEvents(baseState({assets:[{name:'Gizli Jeneratör',type:'generator',locationId:'Özel Otel',testIntervalDays:7,lastTestAt:'2026-07-20T00:00:00Z'}]}),NOW);const text=JSON.stringify(events);assert(!text.includes('Gizli Jeneratör'));assert(!text.includes('Özel Otel'));assert(text.includes('Jeneratör test kontrolü'));});
scenario('13 — takvim aylık tekrar ziyaret olayı üretir',()=>{const events=core.buildCalendarEvents(baseState({improvementActions:[{id:'a',title:'Aksiyon',dimension:'backup',horizonDays:30,createdAt:'2026-07-28T00:00:00Z'}]}),NOW);assert(events.some(x=>x.kind==='review'));});
scenario('14 — ICS geçerli başlık ve ALO186 URL’si içerir',()=>{const ics=core.buildIcs([{id:'a',date:NOW,summary:'Test, kontrol',description:'Satır; açıklama',url:'https://www.alo186.com/isletme-surekliligi'}],NOW);assert(ics.startsWith('BEGIN:VCALENDAR'));assert(ics.includes('BEGIN:VEVENT'));assert(ics.includes('Test\\, kontrol'));assert(ics.includes('Satır\\; açıklama'));assert(ics.includes('https://www.alo186.com/isletme-surekliligi'));assert(ics.endsWith('END:VCALENDAR\r\n'));});
scenario('15 — takvim en fazla 30 olay üretir',()=>{const actions=Array.from({length:40},(_,i)=>({id:`a${i}`,title:`Aksiyon ${i}`,dimension:'backup',horizonDays:30,createdAt:'2026-07-28T00:00:00Z'}));assert.strictEqual(core.buildCalendarEvents(baseState({improvementActions:actions}),NOW).length<=30,true);});
console.log(`Süreklilik büyüme ve aktivasyon döngüsü: ${passed} regresyon senaryosu geçti.`);
