'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'../..');
const read=relative=>fs.readFileSync(path.join(root,relative),'utf8');
const planHtml=read('alo186/hesaplama/elektrik-planim/index.html');
const planCore=read('alo186/hesaplama/elektrik-planim/core.js');
const planApp=read('alo186/hesaplama/elektrik-planim/app.js');
const trustCore=read('alo186/urun-eslestirme/outcome-trust-circuit-core.js');
const trustUi=read('alo186/urun-eslestirme/outcome-trust-circuit.js');
const common=read('alo186/hesaplama/common.js');
const injector=read('alo186/deployment/inject_outcome_runtime.py');
assert.match(planHtml,/https:\/\/www\.alo186\.com\/hesaplama\/elektrik-planim\//);
assert.match(planHtml,/WebApplication/);assert.match(planHtml,/FAQPage/);
assert.match(planHtml,/Ücretli profesyonel hizmete hazırlık/);
assert.doesNotMatch(planHtml,/type="(?:email|tel|text)"|<textarea/i);
assert.doesNotMatch(planHtml,/amazon\.(?:com|com\.tr)/i);
for(const key of ['alo186:solution-outcomes:v1','alo186:pending-solutions:v1','alo186_product_review_calendar_v1','alo186_product_maintenance_v1','alo186.outageJournal.v1','alo186_product_decision_v1','alo186:outage-kit:v1'])assert(planApp.includes(key),`Plan local store eksik: ${key}`);
assert(planCore.includes("title:'Cihaz hasarı belgesini gecikmeden hazırlayın'"));
assert(planCore.includes("noPurchase"));
assert(planCore.includes('professionalPack'));
assert(planCore.includes('alo186-electrical-plan-v1'));
assert(planCore.includes('outage-kit-missing'));
assert(trustCore.includes("status:'safety_block'"));
assert(trustCore.includes("status:'repeated_block'"));
assert(trustCore.includes("status:'no_buy_hold'"));
assert(trustCore.includes("status:'duplicate_hold'"));
assert(trustUi.includes('a[rel~="sponsored"]'));
assert(trustUi.includes("data-outcome-trust-blocked"));
assert(common.includes('outcome-trust-circuit-core.js'));
assert(common.includes('outcome-trust-circuit.js'));
assert(injector.includes('ensure_plan_route'));
assert(injector.includes('raise_tool_count'));
assert(injector.includes('PLAN_HUB_MARKER'));
assert(injector.includes('data-alo186-plan-card'));
assert(injector.includes('offlinePlanRoute'));
assert(injector.includes('ensure_kit_route'));
assert(injector.includes('offlineOutageKitRoute'));
assert(injector.includes('productTrustCircuit'));
console.log('ALO186 unified plan growth: plan, outage kit, local stores, professional pack, affiliate trust circuit and Pages integration successful.');
