const assert=require("assert");const fs=require("fs");const path=require("path");const vm=require("vm");
const ROOT=path.resolve(__dirname,"..","..");const slug="lazerli-uzaklik-olcum-cihazi-elektrik-proje-metraj-secimi";const route=path.join(ROOT,"alo186","amazon-elektrik-urunleri",slug);const html=fs.readFileSync(path.join(route,"index.html"),"utf8");const catalogText=fs.readFileSync(path.join(route,"catalog-v261.js"),"utf8");const appText=fs.readFileSync(path.join(route,"app-v261.js"),"utf8");const overlay=JSON.parse(fs.readFileSync(path.join(ROOT,"alo186","deployment","routing-overlays","261-affiliate-laser-distance-measure.json"),"utf8"));
const sandbox={module:{exports:{}},exports:{},globalThis:{}};vm.runInNewContext(catalogText,sandbox,{filename:"catalog-v261.js"});const catalog=sandbox.module.exports;
assert.strictEqual(catalog.version,261);assert.strictEqual(catalog.affiliateTag,"alo186rehber-21");assert.strictEqual(catalog.verifiedAt,"2026-08-04");assert.strictEqual(catalog.maxVerificationAgeDays,45);assert.strictEqual(catalog.category.slug,slug);assert.strictEqual(catalog.category.risk,"consumer-medium");assert.strictEqual(catalog.category.affiliatePolicy,"after_tool");assert.strictEqual(catalog.category.professionalOnly,false);assert.strictEqual(catalog.category.highRiskDirectCta,false);assert.strictEqual(catalog.products.length,3);
const expectedAsins=["B09NNPNKZY","B08V5BV42G","B08WRC6V8X"];const expectedMpns=["0601072S00","0601072T00","0601072U00"];assert.deepStrictEqual(Array.from(catalog.products,p=>p.asin),expectedAsins);assert.deepStrictEqual(Array.from(catalog.products,p=>p.mpn),expectedMpns);assert.strictEqual(new Set(expectedAsins).size,3);assert.strictEqual(new Set(expectedMpns).size,3);
for(const product of catalog.products){assert.match(product.asin,/^[A-Z0-9]{10}$/);assert.ok(product.brand&&product.userNeed&&product.noBuyWhen);assert.ok(product.strengths.length>=3);assert.ok(product.limitations.length>=3);assert.match(product.noBuyWhen,/satın almayın/);assert.strictEqual(product.amazonAsinSource,`https://www.amazon.com.tr/dp/${product.asin}`);assert.match(product.technicalSource,/^https:\/\/www\.bosch-professional\.com\/tr\/tr\/products\//);assert.strictEqual(catalog.verificationStatus(product,new Date("2026-09-18T00:00:00Z")).fresh,true);assert.strictEqual(catalog.verificationStatus(product,new Date("2026-09-19T00:00:00Z")).fresh,false);const url=catalog.amazonProductUrl(product,new Date("2026-08-04T12:00:00Z"));assert.ok(url.includes("/dp/"+product.asin));assert.ok(url.endsWith("?tag=alo186rehber-21"));assert.strictEqual(catalog.amazonProductUrl(product,new Date("2026-09-19T00:00:00Z")),null);}
const canonical="https://alo186.com/amazon-elektrik-urunleri/lazerli-uzaklik-olcum-cihazi-elektrik-proje-metraj-secimi/";assert.ok(html.includes(`<link rel="canonical" href="${canonical}">`));assert.ok(html.includes('data-commercial-scope="after_tool"'));assert.ok(html.includes('data-professional-only="false"'));assert.ok((html.match(/Görünür satış ortaklığı açıklaması/g)||[]).length>=3);assert.strictEqual((html.match(/rel="sponsored nofollow noopener"/g)||[]).length,3);assert.ok(!/href="https:\/\/www\.amazon\.com\.tr\/dp\/[^\"]+\?tag=/.test(html));assert.ok(!/"@type"\s*:\s*"Offer"|priceCurrency|aggregateRating|ratingValue|reviewCount/.test(html));for(const phrase of ["Kullanıcı ihtiyacı","Güçlü yönler","Sınırlamalar","Satın almayın","Mevcut şerit metre","Enerjili pano","Sınıf 2 lazer"])assert.ok(html.includes(phrase),phrase);
const ids=Array.from(html.matchAll(/\sid="([^"]+)"/g),m=>m[1]);assert.strictEqual(new Set(ids).size,ids.length,"duplicate HTML id");for(const anchor of ["rehber-elektrik-proje-metraj-lazer-olcum","karar-enerjili-alanda-olcum-yapmayin","karar-satin-almama","karsilastirma-lazerli-uzaklik-olcerler","arac-lazerli-olcum-hazirligi","urun-bosch-glm-50-22-0601072s00","urun-bosch-glm-50-27-c-0601072t00","urun-bosch-glm-50-27-cg-0601072u00","kaynaklar-ve-dogrulama"])assert.ok(ids.includes(anchor),anchor);
const graph=JSON.parse(html.match(/<script id="knowledge-graph" type="application\/ld\+json">\s*([\s\S]*?)<\/script>/)[1]);const nodes=graph["@graph"];assert.ok(nodes.some(n=>n["@type"]==="Brand"));assert.strictEqual(nodes.filter(n=>n["@type"]==="Product").length,3);assert.ok(nodes.some(n=>n["@type"]==="ItemList"&&n.numberOfItems===3));assert.ok(nodes.some(n=>n["@type"]==="BreadcrumbList"));for(const product of nodes.filter(n=>n["@type"]==="Product")){assert.strictEqual(product.identifier.length,2);assert.ok(product.additionalProperty.length>=5);}const atIds=nodes.map(n=>n["@id"]).filter(Boolean);assert.strictEqual(new Set(atIds).size,atIds.length,"duplicate JSON-LD @id");
assert.match(appText,/affiliatePolicy!=="after_tool"/);assert.match(appText,/catalog\.category\.professionalOnly/);assert.match(appText,/catalog\.category\.highRiskDirectCta/);assert.match(appText,/removeAttribute\("href"\)/);
function walk(dir){if(!fs.existsSync(dir))return[];return fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>{const full=path.join(dir,e.name);return e.isDirectory()?walk(full):[full];});}const files=walk(path.join(ROOT,"alo186")).filter(f=>/\.(?:js|json|html|md)$/.test(f));for(const asin of expectedAsins){let occurrences=0;for(const file of files){if(file===path.join(route,"index.html")||file===path.join(route,"catalog-v261.js")||file===path.join(ROOT,"alo186","tests","test_affiliate_laser_distance_measure_v261.js"))continue;const matches=fs.readFileSync(file,"utf8").match(new RegExp(asin,"g"));occurrences+=matches?matches.length:0;}assert.strictEqual(occurrences,0,`global duplicate ASIN outside route: ${asin}`);}
assert.strictEqual(overlay.version,261);assert.strictEqual(overlay.routes.length,1);assert.strictEqual(overlay.routes[0].canonicalPath,`/amazon-elektrik-urunleri/${slug}/`);assert.strictEqual(overlay.routes[0].source,`alo186/amazon-elektrik-urunleri/${slug}/index.html`);
console.log(JSON.stringify({ok:true,version:261,products:catalog.products.map(p=>({asin:p.asin,mpn:p.mpn})),checks:["canonical","affiliate-tag","sponsored-nofollow-noopener","duplicate-ASIN-global","stale-45-46","Knowledge-Graph","duplicate-id","duplicate-@id","deep-link-anchors","after_tool","professional_only","high-risk-direct-cta","no-Offer","visible-card-fields"]},null,2));