const assert=require('assert');
const store=require('../sureklilik-paneli/store.js');
let passed=0;
function scenario(name,fn){try{fn();passed++;console.log('✓',name);}catch(error){console.error('✗',name);throw error;}}
const NOW=Date.parse('2026-07-28T06:00:00Z');
function payload(overrides={}){
  const base={version:1,importId:'maturity-test-1',generatedAt:'2026-07-28T05:30:00Z',expiresAt:'2026-08-04T05:30:00Z',facilityType:'hotel',score:42,band:'Reaktif',dimensions:[{id:'backup',title:'Yedek güç',score:25},{id:'incident',title:'Olay yönetimi',score:50}],criticalGapIds:['backup_coverage'],plan:{day30:[{questionId:'backup_coverage',dimension:'backup',action:'Kritik yük kapasitesini doğrulayın.',priority:1.5},{questionId:'roles',dimension:'ownership',action:'Kesinti rollerini belirleyin.',priority:1.2}],day60:[{questionId:'transfer_test',dimension:'testing',action:'Transfer testini kayıtlı uygulayın.',priority:1.1}],day90:[{questionId:'management_review',dimension:'improvement',action:'Yönetim gözden geçirmesi başlatın.',priority:1}]},privacy:{containsPersonalData:false,medicalOrLifeSupportFlagIncluded:false,immediateDangerFlagIncluded:false}};
  return {...base,...overrides};
}
scenario('1 — geçerli handoff kabul edilir',()=>assert.strictEqual(store.validateMaturityHandoff(payload(),NOW).valid,true));
scenario('2 — yanlış sürüm reddedilir',()=>assert.strictEqual(store.validateMaturityHandoff(payload({version:2}),NOW).valid,false));
scenario('3 — süresi dolmuş handoff reddedilir',()=>assert.strictEqual(store.validateMaturityHandoff(payload({expiresAt:'2026-07-28T05:59:59Z'}),NOW).valid,false));
scenario('4 — sekiz günden uzun TTL reddedilir',()=>assert.strictEqual(store.validateMaturityHandoff(payload({expiresAt:'2026-08-20T05:30:00Z'}),NOW).valid,false));
scenario('5 — gelecekte üretilmiş anormal paket reddedilir',()=>assert.strictEqual(store.validateMaturityHandoff(payload({generatedAt:'2026-07-29T05:30:00Z'}),NOW).valid,false));
scenario('6 — skor 0–100 dışında reddedilir',()=>assert.strictEqual(store.validateMaturityHandoff(payload({score:101}),NOW).valid,false));
scenario('7 — aksiyonsuz paket reddedilir',()=>assert.strictEqual(store.validateMaturityHandoff(payload({plan:{day30:[],day60:[],day90:[]}}),NOW).valid,false));
scenario('8 — bilinmeyen boyut aksiyonu allowlist dışına atılır',()=>{const p=payload({plan:{day30:[{questionId:'x',dimension:'evil',action:'Yasak',priority:1}],day60:[],day90:[]}});assert.strictEqual(store.validateMaturityHandoff(p,NOW).valid,false);});
scenario('9 — HTML karakterleri aksiyon metninden temizlenir',()=>{const p=payload({plan:{day30:[{questionId:'x',dimension:'backup',action:'<img> Güvenli > kontrol',priority:1}],day60:[],day90:[]}});const checked=store.validateMaturityHandoff(p,NOW);assert.strictEqual(checked.valid,true);assert(!checked.value.actions[0].text.includes('<'));assert(!checked.value.actions[0].text.includes('>'));});
scenario('10 — geçersiz tesis türü other olur',()=>assert.strictEqual(store.validateMaturityHandoff(payload({facilityType:'secret-company'}),NOW).value.facilityType,'other'));
scenario('11 — import aksiyonları 30/60/90 ufkuna taşır',()=>{const result=store.importMaturityHandoff(store.createState(),payload(),NOW);assert.deepStrictEqual(result.state.improvementActions.map(x=>x.horizonDays).sort(),[30,30,60,90]);});
scenario('12 — import kişisel veya tıbbi alanları state içine taşımaz',()=>{const p=payload({email:'person@example.com',medical:true,organizationName:'Gizli Şirket'});const result=store.importMaturityHandoff(store.createState(),p,NOW);const text=JSON.stringify(result.state);assert(!text.includes('person@example.com'));assert(!text.includes('Gizli Şirket'));assert(!text.includes('"medical"'));});
scenario('13 — ilk import audit kaydı oluşturur',()=>{const result=store.importMaturityHandoff(store.createState(),payload(),NOW);assert(result.state.auditLog.some(x=>x.action==='maturity_plan_imported'));});
scenario('14 — aynı importId ikinci kez aksiyon çoğaltmaz',()=>{const first=store.importMaturityHandoff(store.createState(),payload(),NOW);const second=store.importMaturityHandoff(first.state,payload(),NOW);assert.strictEqual(second.duplicate,true);assert.strictEqual(second.added,0);assert.strictEqual(second.state.improvementActions.length,4);});
scenario('15 — farklı importId aynı aksiyonları dedupe eder',()=>{const first=store.importMaturityHandoff(store.createState(),payload(),NOW);const second=store.importMaturityHandoff(first.state,payload({importId:'maturity-test-2'}),NOW);assert.strictEqual(second.added,0);assert.strictEqual(second.state.improvementActions.length,4);});
scenario('16 — boş panel profili handoff tesis türüyle başlar',()=>{const result=store.importMaturityHandoff(store.createState(),payload({facilityType:'site'}),NOW);assert.strictEqual(result.state.organization.profile,'site');});
scenario('17 — mevcut kuruluş profili importla değişmez',()=>{let state=store.configureOrganization(store.createState(),{name:'Mevcut İşletme',profile:'business'});const result=store.importMaturityHandoff(state,payload({facilityType:'hotel'}),NOW);assert.strictEqual(result.state.organization.profile,'business');});
scenario('18 — aksiyon tamamlanınca ilerleme ve audit güncellenir',()=>{let state=store.importMaturityHandoff(store.createState(),payload(),NOW).state;const action=state.improvementActions[0];const result=store.toggleImprovementAction(state,action.id,true);assert.strictEqual(result.action.completed,true);assert.strictEqual(result.action.status,'completed');assert.strictEqual(store.improvementProgress(result.state),25);assert(result.state.auditLog.some(x=>x.action==='improvement_action_updated'));});
scenario('19 — aksiyon yeniden açılabilir',()=>{let state=store.importMaturityHandoff(store.createState(),payload(),NOW).state;const id=state.improvementActions[0].id;state=store.toggleImprovementAction(state,id,true).state;const result=store.toggleImprovementAction(state,id,false);assert.strictEqual(result.action.completed,false);assert.strictEqual(result.action.completedAt,null);});
scenario('20 — eski v1 panel yedeği geriye uyumlu hydrate edilir',()=>{const hydrated=store.hydrate({schemaVersion:1,organization:{profile:'hotel'},locations:[],criticalLoads:[],assets:[],tests:[],incidents:[],auditLog:[]});assert.strictEqual(hydrated.schemaVersion,2);assert(Array.isArray(hydrated.improvementActions));assert(Array.isArray(hydrated.maturityImports));});
scenario('21 — metrikler aksiyon sayısı ve ilerlemeyi döndürür',()=>{let state=store.importMaturityHandoff(store.createState(),payload(),NOW).state;state=store.toggleImprovementAction(state,state.improvementActions[0].id,true).state;const metrics=store.metrics(state);assert.strictEqual(metrics.improvementActions,4);assert.strictEqual(metrics.improvementProgress,25);});
scenario('22 — bilinmeyen aksiyon kimliği hata verir',()=>assert.throws(()=>store.toggleImprovementAction(store.createState(),'missing',true),/bulunamadı/));
console.log(`Olgunluk skoru → Süreklilik Paneli handoff: ${passed} regresyon senaryosu geçti.`);
