(function(){'use strict';const Core=window.Alo186LifecycleCost;if(!Core)return;const $=id=>document.getElementById(id),STORAGE='alo186:lifecycle-cost:v1';let lastRecord=null,lastResult=null;
function option(value,label){const o=document.createElement('option');o.value=value;o.textContent=label;return o}
function fillSelect(el,map){Object.entries(map).forEach(([k,v])=>el.appendChild(option(k,v.label||v)))}
fillSelect($('context'),Core.CONTEXTS);fillSelect($('system'),Core.SYSTEMS);fillSelect($('horizon'),Core.HORIZONS);$('context').value='small_business';$('system').value='ups';$('horizon').value='5';
const fieldDefs=[['oneTime','Tek seferlik maliyet','Satın alma, kurulum, onarım veya devreye alma'],['annualMaintenance','Yıllık bakım / servis','Periyodik bakım ve planlı servis'],['annualEnergy','Yıllık enerji / yakıt','Elektrik, yakıt ve işletme enerjisi'],['annualDowntime','Yıllık duruş etkisi','Kendi işletme kaydınızdan tahmini kayıp'],['residual','Ufuk sonu kalan değer','Yoksa açıkça 0 girin']];
function buildScenarios(){const grid=$('scenarioGrid');Object.entries(Core.SCENARIOS).forEach(([key,label])=>{const card=document.createElement('section');card.className='scenario';card.dataset.scenario=key;const h=document.createElement('h2');h.textContent=label;card.appendChild(h);const fields=document.createElement('div');fields.className='fields';fieldDefs.forEach(([name,title,hint])=>{const lab=document.createElement('label');lab.textContent=title;const input=document.createElement('input');input.type='number';input.min='0';input.step='any';input.inputMode='decimal';input.dataset.field=name;input.placeholder='Kendi değerinizi girin';const small=document.createElement('span');small.className='hint';small.textContent=hint;lab.append(input,small);fields.appendChild(lab)});const q=document.createElement('label');q.textContent='Veri kaynağı';const sel=document.createElement('select');sel.dataset.field='quality';Object.entries(Core.QUALITY).forEach(([k,v])=>sel.appendChild(option(k,v)));sel.value='unknown';q.appendChild(sel);fields.appendChild(q);card.appendChild(fields);grid.appendChild(card)})}
buildScenarios();
function read(){const scenarios={};document.querySelectorAll('[data-scenario]').forEach(card=>{const values={};card.querySelectorAll('[data-field]').forEach(el=>values[el.dataset.field]=el.value);scenarios[card.dataset.scenario]=values});return{context:$('context').value,system:$('system').value,horizon:$('horizon').value,existingSafe:$('existingSafe').value,safetyRisk:$('safetyRisk').checked,technicalToolCompleted:$('technicalToolCompleted').checked,existingInsufficient:$('existingInsufficient').checked,affiliateAcknowledged:$('affiliateAcknowledged').checked,scenarios}}
function fmt(n){return n===null?'Eksik':new Intl.NumberFormat('tr-TR',{maximumFractionDigits:2}).format(n)+' birim'}
function render(result){lastResult=result;$('result').classList.remove('hidden');$('resultTitle').textContent=result.title;$('resultSummary').textContent=result.summary;$('resultMeta').textContent=`${result.contextLabel} · ${result.systemLabel} · ${result.horizonLabel} · Girilen aynı para birimiyle nominal karşılaştırma`;$('costResults').innerHTML='';result.results.forEach(r=>{const card=document.createElement('article');card.className='score'+(result.best&&result.best.key===r.key?' best':'');const strong=document.createElement('strong');strong.textContent=r.label;const total=document.createElement('b');total.textContent=r.ready?fmt(r.total):'Veri eksik';const annual=document.createElement('small');annual.textContent=r.ready?`Yıllıklaştırılmış: ${fmt(r.annualized)} · ${Core.QUALITY[r.quality]}`:`${Core.QUALITY[r.quality]}${r.missing.length?' · Eksik: '+r.missing.join(', '):''}`;card.append(strong,total,annual);$('costResults').appendChild(card)});const gapBox=$('gaps'),list=$('gapList');list.innerHTML='';if(result.gaps.length){gapBox.classList.remove('hidden');result.gaps.forEach(g=>{const li=document.createElement('li');li.textContent=g;list.appendChild(li)})}else gapBox.classList.add('hidden');[['primaryAction',result.primary],['secondaryAction',result.secondary]].forEach(([id,a])=>{const el=$(id);el.textContent=a.label;el.href=a.href});$('affiliateNotice').classList.toggle('hidden',!result.commercialAllowed);$('exportIcs').disabled=!result.followupDays;$('result').scrollIntoView({behavior:'smooth',block:'start'})}
function loadHistory(){try{return Core.prune(JSON.parse(localStorage.getItem(STORAGE)||'[]'))}catch(_){return[]}}
function saveRecord(rec){const records=Core.prune([rec,...loadHistory()]);localStorage.setItem(STORAGE,JSON.stringify(records));renderHistory(records)}
function date(value){return value?new Intl.DateTimeFormat('tr-TR',{dateStyle:'medium'}).format(new Date(value)):'—'}
function renderHistory(records=loadHistory()){const section=$('history'),list=$('historyList');list.innerHTML='';if(!records.length){section.classList.add('hidden');return}section.classList.remove('hidden');records.forEach(r=>{const card=document.createElement('article');card.className='history-card';const text=document.createElement('div');const strong=document.createElement('strong');strong.textContent=`${Core.SYSTEMS[r.system].label} · ${r.status}`;const small=document.createElement('small');small.textContent=`Karar: ${date(r.createdAt)} · Yeniden kontrol: ${date(r.reviewAt)} · Tutarlar kaydedilmez`;text.append(strong,document.createElement('br'),small);const a=document.createElement('a');a.className='button secondary';a.href='./';a.textContent='Yeni değerlerle güncelle';card.append(text,a);list.appendChild(card)})}
function blobDownload(name,type,text){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('costForm').addEventListener('submit',e=>{e.preventDefault();try{const raw=read(),result=Core.evaluate(raw),rec=Core.record(raw);lastRecord=rec;render(result);saveRecord(rec);$('status').textContent='Karar yalnız bu tarayıcıda işlendi; ayrıntılı maliyet değerleri geçmişe kaydedilmedi.'}catch(err){$('status').textContent='Hesaplama tamamlanamadı. Alanları kontrol edin.';console.error(err)}});
$('exportJson').addEventListener('click',()=>{if(!lastRecord)return;blobDownload('alo186-yasam-dongusu-karar-makbuzu.json','application/json',JSON.stringify(lastRecord,null,2))});
$('exportIcs').addEventListener('click',()=>{if(!lastRecord)return;const ics=Core.buildIcs(lastRecord);if(ics)blobDownload('alo186-yasam-dongusu-yeniden-kontrol.ics','text/calendar;charset=utf-8',ics)});
$('printBtn').addEventListener('click',()=>window.print());$('clearHistory').addEventListener('click',()=>{localStorage.removeItem(STORAGE);renderHistory([])});renderHistory();})();
