(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.Alo186LifecycleCost=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const VERSION=1,MAX_RECORDS=6,TTL_DAYS=365,DAY_MS=86400000;
const CONTEXTS={home:'Ev / bireysel kullanım',small_business:'Küçük işletme',hotel:'Otel / konaklama tesisi',site:'Site / ortak yaşam alanı'};
const HORIZONS={1:'1 yıl',3:'3 yıl',5:'5 yıl',10:'10 yıl'};
const SYSTEMS={
 plug_products:{label:'Tak-çalıştır düşük riskli ürün',highRisk:false,tool:'/hesaplama/teknik-urun-karsilastirma/',professional:'/kurumsal-elektrik-surekliligi-on-degerlendirme?problem=urun_uygunlugu&scope=maliyet'},
 ups:{label:'UPS ve akü sistemi',highRisk:true,tool:'/hesaplama/ups-suresi/',professional:'/kurumsal-elektrik-surekliligi-on-degerlendirme?problem=yedek_guc&scope=maliyet'},
 generator:{label:'Jeneratör, ATS ve AMF',highRisk:true,tool:'/hesaplama/jenerator-gucu-secimi/',professional:'/kurumsal-elektrik-surekliligi-on-degerlendirme?problem=yedek_guc&scope=maliyet'},
 inverter_storage:{label:'İnverter ve enerji depolama',highRisk:true,tool:'/hesaplama/inverter-uygunluk/',professional:'/kurumsal-elektrik-surekliligi-on-degerlendirme?problem=ges_batarya&scope=maliyet'},
 ev_charging:{label:'EV şarj ve wallbox',highRisk:true,tool:'/hesaplama/ev-sarj-uygunluk/',professional:'/kurumsal-elektrik-surekliligi-on-degerlendirme?problem=ev_sarj&scope=maliyet'},
 ges:{label:'GES ve PV inverter',highRisk:true,tool:'/hesaplama/gunes-paneli-power-station-uygunluk/',professional:'/kurumsal-elektrik-surekliligi-on-degerlendirme?problem=ges_batarya&scope=maliyet'},
 protection:{label:'RCD, SPD, topraklama ve pano',highRisk:true,tool:'/hesaplama/gerilim-koruma-cozum-secici/',professional:'/kurumsal-elektrik-surekliligi-on-degerlendirme?problem=genel_risk&scope=maliyet'},
 power_quality:{label:'Harmonik ve güç kalitesi',highRisk:true,tool:'/isletme-surekliligi',professional:'/kurumsal-elektrik-surekliligi-on-degerlendirme?problem=genel_risk&scope=olcum_kampanyasi'}
};
const SCENARIOS={maintain:'Mevcut sistemi güvenli biçimde sürdür',repair:'Bakım / onarım / sınırlı iyileştirme',replace:'Yeni çözüm / sistem yenileme'};
const QUALITY={documented:'Belge veya teklifle doğrulandı',estimated:'Kullanıcı tahmini',unknown:'Eksik / bilinmiyor'};
function own(o,k){return Object.prototype.hasOwnProperty.call(o,k)}
function enumValue(v,map,fallback){v=String(v??'').trim();return own(map,v)?v:fallback}
function bool(v){return v===true||v==='true'||v===1||v==='1'||v==='yes'||v==='on'}
function amount(v){if(v===''||v===null||typeof v==='undefined')return null;const n=Number(String(v).replace(',','.'));return Number.isFinite(n)&&n>=0?Math.min(n,1e12):null}
function scenario(raw={}){return{oneTime:amount(raw.oneTime),annualMaintenance:amount(raw.annualMaintenance),annualEnergy:amount(raw.annualEnergy),annualDowntime:amount(raw.annualDowntime),residual:amount(raw.residual),quality:enumValue(raw.quality,QUALITY,'unknown')}}
function sanitize(raw={}){const system=enumValue(raw.system,SYSTEMS,'ups'),horizon=enumValue(raw.horizon,HORIZONS,'5');return{context:enumValue(raw.context,CONTEXTS,'small_business'),system,horizon:Number(horizon),existingSafe:enumValue(raw.existingSafe,{yes:1,no:1,unknown:1},'unknown'),safetyRisk:bool(raw.safetyRisk),technicalToolCompleted:bool(raw.technicalToolCompleted),affiliateAcknowledged:bool(raw.affiliateAcknowledged),existingInsufficient:bool(raw.existingInsufficient),scenarios:Object.fromEntries(Object.keys(SCENARIOS).map(k=>[k,scenario(raw.scenarios&&raw.scenarios[k])]))}}
function calc(key,s,horizon){const fields=['oneTime','annualMaintenance','annualEnergy','annualDowntime','residual'],missing=fields.filter(f=>s[f]===null);if(missing.length||s.quality==='unknown')return{key,label:SCENARIOS[key],ready:false,missing,quality:s.quality,total:null,annualized:null};const total=Math.max(0,s.oneTime+horizon*(s.annualMaintenance+s.annualEnergy+s.annualDowntime)-s.residual);return{key,label:SCENARIOS[key],ready:true,missing:[],quality:s.quality,total,annualized:total/horizon}}
function evaluate(raw={}){const input=sanitize(raw),profile=SYSTEMS[input.system],results=Object.entries(input.scenarios).map(([k,s])=>calc(k,s,input.horizon));const ready=results.filter(x=>x.ready).sort((a,b)=>a.total-b.total);let status='conditional',title='Karşılaştırma için doğrulanmış maliyet kalemleri eksik',summary='ALO186 fiyat üretmez. Her senaryonun tek seferlik, yıllık bakım, enerji, duruş ve kalan değer alanlarını kendi teklif veya kayıtlarınızdan tamamlayın.',commercialAllowed=false,primary={label:'İlgili ücretsiz teknik aracı aç',href:profile.tool},secondary={label:'Teknik teklif kapsamını karşılaştır',href:'/hesaplama/teknik-teklif-kapsam-karsilastirma/'},followupDays=30,best=null,nearTie=false;
 if(input.safetyRisk){status='safety';title='Maliyet karşılaştırmasını durdurun';summary='Duman, alev, elektrik çarpması, erime veya hızla yükselen sıcaklıkta ticari karar değil can güvenliği önceliklidir.';primary={label:'Karar Motorunu aç',href:'/karar-motoru'};secondary={label:'Doğru EDAŞ kanalını bul',href:'/edas-bul'};followupDays=0;}
 else if(input.existingSafe==='no'){status='professional';title='Mevcut sistem güvenli doğrulanmadı; en düşük maliyet seçilemez';summary='Güvenlik ve teknik uygunluk maliyet sıralamasından önce gelir. Yetkili ölçüm ve kapsam doğrulaması tamamlanmadan mevcut sistemi sürdürmeyin.';primary={label:'Bağımsız teknik ön değerlendirmeyi aç',href:profile.professional};}
 else if(ready.length<3){status='conditional';}
 else{best=ready[0];nearTie=ready[1]&&ready[1].total<=best.total*1.10;
  if(nearTie){status='review';title='İki seçenek birbirine yakın; sahte kesinlik üretmeyin';summary='En düşük iki toplam arasında yüzde 10’dan az fark var. Teknik kapsam, güvenilirlik ve kabul kanıtı maliyet kadar belirleyicidir.';primary={label:'Teknik teklif kapsamını karşılaştır',href:'/hesaplama/teknik-teklif-kapsam-karsilastirma/'};followupDays=30;}
  else if(best.key==='maintain'&&input.existingSafe==='yes'){status='no_buy';title='Mevcut sistemi sürdürmek en düşük yaşam döngüsü maliyetine sahip';summary='Girdiğiniz doğrulanmış değerlere göre yeni ürün veya sistem gerekmiyor. Bakım, kabul ve yeniden test planını koruyun.';primary={label:'Bakım planı oluştur',href:'/hesaplama/ekipman-bakim-plani/'};secondary={label:'Elektrik Planım’ı aç',href:'/hesaplama/elektrik-planim/'};followupDays=180;}
  else if(profile.highRisk){status='professional';title=`${best.label} maliyet açısından önde, ancak bağımsız teknik inceleme gerekli`;summary='Bu sonuç yatırım onayı veya yüklenici seçimi değildir. Sabit tesisat ve yüksek güçlü sistemlerde teknik kapsam, güvenlik, devreye alma ve kabul ayrıca doğrulanmalıdır.';primary={label:'Bağımsız yaşam döngüsü incelemesini aç',href:profile.professional};secondary={label:'Teknik devir ve kabul paketi oluştur',href:'/hesaplama/teknik-devir-kabul-paketi/'};followupDays=30;}
  else if(best.key!=='replace'){status='no_buy';title=`${best.label} yeni satın almadan daha düşük maliyetli`;summary='Mevcut çözüm güvenliyse bakım veya sınırlı iyileştirme önceliklidir; gereksiz ürün yönlendirmesi açılmaz.';primary={label:'Bakım planı oluştur',href:'/hesaplama/ekipman-bakim-plani/'};secondary={label:'Şimdilik satın alma',href:'/hesaplama/elektrik-planim/'};followupDays=180;}
  else if(!input.technicalToolCompleted||!input.existingInsufficient||!input.affiliateAcknowledged){status='conditional';title='Yeni ürün maliyet açısından önde; üç güven kapısı tamamlanmalı';summary='Ücretsiz teknik araç, mevcut çözümün yetersizliği ve satış ortaklığı açıklaması ayrı ayrı doğrulanmadan affiliate rota açılmaz.';primary={label:'Teknik kısa listeyi aç',href:'/hesaplama/teknik-urun-karsilastirma/'};secondary={label:'Şimdilik satın alma',href:'/hesaplama/elektrik-planim/'};followupDays=30;}
  else{status='ready_affiliate';commercialAllowed=true;title='Yeni düşük riskli çözüm, doğrulanmış girdilerle maliyet açısından önde';summary='Satış ortaklığı niteliği görünür ürün merkezi kullanıcı onayıyla açılabilir. Mağaza bilgileri güncel ürün sayfasında yeniden doğrulanmalıdır.';primary={label:'Şeffaf Ürün Merkezini aç',href:'/akilli-urun-secimi'};secondary={label:'Teknik kısa listeyi yeniden aç',href:'/hesaplama/teknik-urun-karsilastirma/'};followupDays=90;}}
 const gaps=results.filter(x=>!x.ready).map(x=>`${x.label}: ${x.quality==='unknown'?'veri kaynağı seçilmedi':x.missing.join(', ')||'eksik alan'}`);return{version:VERSION,input,status,title,summary,commercialAllowed,systemLabel:profile.label,contextLabel:CONTEXTS[input.context],horizonLabel:HORIZONS[String(input.horizon)],results,best,nearTie,gaps,primary,secondary,followupDays}}
function hashText(text){let h=2166136261;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(16).padStart(8,'0')}
function record(raw,nowValue=new Date()){const now=nowValue instanceof Date?nowValue:new Date(nowValue),r=evaluate(raw);const payload={schema:'alo186-lifecycle-cost-v1',version:VERSION,createdAt:now.toISOString(),expiresAt:new Date(now.getTime()+TTL_DAYS*DAY_MS).toISOString(),reviewAt:r.followupDays?new Date(now.getTime()+r.followupDays*DAY_MS).toISOString():null,context:r.input.context,system:r.input.system,horizon:r.input.horizon,status:r.status,best:r.best?r.best.key:null,nearTie:r.nearTie,commercialAllowed:r.commercialAllowed,readyScenarioCount:r.results.filter(x=>x.ready).length};return{...payload,checksum:hashText(JSON.stringify(payload))}}
function validateRecord(pkg){if(!pkg||pkg.schema!=='alo186-lifecycle-cost-v1'||pkg.version!==VERSION)return false;const copy={...pkg};delete copy.checksum;if(hashText(JSON.stringify(copy))!==pkg.checksum)return false;return own(CONTEXTS,pkg.context)&&own(SYSTEMS,pkg.system)&&own(HORIZONS,String(pkg.horizon))}
function prune(records,nowValue=new Date()){const now=nowValue instanceof Date?nowValue:new Date(nowValue);return(Array.isArray(records)?records:[]).filter(validateRecord).filter(x=>Date.parse(x.expiresAt)>now.getTime()).sort((a,b)=>Date.parse(b.createdAt)-Date.parse(a.createdAt)).slice(0,MAX_RECORDS)}
function buildIcs(pkg){if(!validateRecord(pkg)||!pkg.reviewAt)return'';const d=new Date(pkg.reviewAt),date=`${d.getUTCFullYear()}${String(d.getUTCMonth()+1).padStart(2,'0')}${String(d.getUTCDate()).padStart(2,'0')}`;return['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//ALO186//Lifecycle Cost Review//TR','BEGIN:VEVENT',`UID:${pkg.checksum}@alo186.com`,`DTSTART;VALUE=DATE:${date}`,'SUMMARY:Elektrik çözümü yaşam döngüsü maliyetini yeniden kontrol et','DESCRIPTION:Kendi teklif ve kayıtlarındaki maliyet kalemlerini güncelle. ALO186 fiyat sağlamaz.','URL:https://alo186.com/hesaplama/elektrik-cozumu-yasam-dongusu-maliyeti/','END:VEVENT','END:VCALENDAR'].join('\r\n')}
return{VERSION,MAX_RECORDS,TTL_DAYS,CONTEXTS,HORIZONS,SYSTEMS,SCENARIOS,QUALITY,sanitize,evaluate,record,validateRecord,prune,buildIcs};});
