(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root&&typeof root==='object')root.Alo186PumpBackup=api;if(root&&root.document)api.init(root.document);})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const SQRT3=Math.sqrt(3);const PF_DEFAULT=0.8;const RESERVE=1.25;const BATTERY_EFF=0.85;const USABLE=0.8;
const START_MULTIPLIER={direct:6,soft:3,vfd:1.5};
const CATEGORY_LINKS={generator:{label:'Jeneratör ürün sınıfını aç',href:'../../akilli-urun-secimi?kategori=generator'},power_station:{label:'Güç istasyonu ürün sınıfını aç',href:'../../akilli-urun-secimi?kategori=power_station'},inverter:{label:'İnverter ürün sınıfını aç',href:'../../akilli-urun-secimi?kategori=inverter'}};
const TOOL_LINKS={generator:{label:'Jeneratör güç hesabını aç',href:'../jenerator-gucu-secimi/'},inverter:{label:'İnverter uygunluk testini aç',href:'../inverter-uygunluk/'},power:{label:'Power station uygunluk testini aç',href:'../power-station-kapasite-eps-uygunluk/'},outcome:{label:'Çözüm sonucunu kaydet',href:'../cozum-sonucu/'}};
const n=v=>{const raw=String(v??'').trim().replace(',','.');if(!raw)return null;const x=Number(raw);return Number.isFinite(x)?x:null};const uniq=a=>[...new Set(a.filter(Boolean))];const r=(v,d=1)=>Number(v.toFixed(d));
function base(status,title,summary){return{status,title,summary,issues:[],steps:[],metrics:null,commerceCategories:[],toolKeys:[],commerceClosed:true}}
function calculations(input){const phase=input.phase==='three'?3:1;const voltage=n(input.voltage);const current=n(input.ratedCurrent);const pf=n(input.powerFactor)??PF_DEFAULT;const otherW=n(input.otherLoadW)??0;const hours=n(input.targetHours);const mult=START_MULTIPLIER[input.startMethod]??null;if(!voltage||!current||!mult||!hours)return null;const kva=(phase===3?SQRT3:1)*voltage*current/1000;const runningW=kva*pf*1000;const startW=runningW*mult;const totalRunningW=runningW+otherW;const requiredContinuousW=totalRunningW*RESERVE;const requiredSurgeW=(startW+otherW)*1.15;const requiredWh=totalRunningW*hours/BATTERY_EFF/USABLE;return{phase,voltage,current,pf,mult,kva:r(kva,2),runningW:r(runningW),startW:r(startW),totalRunningW:r(totalRunningW),requiredContinuousW:r(requiredContinuousW),requiredSurgeW:r(requiredSurgeW),requiredWh:r(requiredWh),targetHours:r(hours,2)}}
function evaluate(input={}){
 if(input.emergency){const o=base('emergency','Acil: pompa devresini kullanmayın','Su, duman, kıvılcım, yanık kokusu veya elektrik çarpması riski varken hesap ve ticari yönlendirme yapılmaz.');o.issues=['Su ile elektrik ekipmanı aynı alandaysa enerjiyi güvenli biçimde kesmeden yaklaşmayın.'];o.steps=['Güvenliyse ana enerjiyi kesin; suya veya ıslak ekipmana dokunmayın.','Yangın, yaralanma veya elektrik çarpması riski varsa 112’yi arayın.'];return o}
 if(input.environment==='wet'&&input.protection!=='rated'){const o=base('stop','Islak ortam koruması doğrulanmadan kullanmayın','Pompa gövdesi, fiş, priz, uzatma kablosu ve yedek kaynak ıslak ortam için uygun değilse elektrik çarpması riski oluşur.');o.issues=['Üretici ortam/IP sınırı veya kaçak akım koruması doğrulanmadı.'];o.steps=['Kuru ve güvenli bağlantı noktası sağlayın; üretici talimatını ve koruma düzenini doğrulayın.'];return o}
 if(['fire','sewage_hazard'].includes(input.pumpType)){const o=base('professional','Kritik pompa sistemi profesyonel tasarım gerektirir','Yangın pompası veya tehlikeli ortam atık su pompası tüketici tipi ürün seçimine açılamaz.');o.issues=['Kaynak yedekliliği, transfer, koruma, alarm ve periyodik test birlikte projelendirilmelidir.'];o.steps=['Yetkili elektrik ve mekanik proje uzmanıyla sistem mimarisini doğrulayın.'];return o}
 const evidence=[];if(!['single','three'].includes(input.phase))evidence.push('Faz bilgisi doğrulanmadı.');if(!n(input.voltage)||n(input.voltage)<100||n(input.voltage)>500)evidence.push('Etiket gerilimi 100–500 V aralığında doğrulanmadı.');if(!n(input.ratedCurrent)||n(input.ratedCurrent)<=0||n(input.ratedCurrent)>200)evidence.push('Motor etiket akımı doğrulanmadı.');if(!START_MULTIPLIER[input.startMethod])evidence.push('Kalkış yöntemi bilinmiyor.');if(!n(input.targetHours)||n(input.targetHours)<=0||n(input.targetHours)>48)evidence.push('Hedef çalışma süresi 0–48 saat aralığında doğrulanmadı.');if(input.connection==='unknown')evidence.push('Pompanın fişli mi sabit bağlı mı olduğu bilinmiyor.');if(evidence.length){const o=base('evidence_required','Önce motor etiketini ve bağlantıyı doğrulayın','Faz, volt, amper, kalkış yöntemi ve süre bilinmeden jeneratör veya inverter seçilmez.');o.issues=evidence;o.steps=['Motor etiketindeki V, A, faz ve varsa cosφ değerini kaydedin.','Kontaktör, soft starter veya sürücü olup olmadığını doğrulayın.'];return o}
 const m=calculations(input);if(!m){const o=base('evidence_required','Hesap için gerekli veri eksik','Sayısal bilgiler tamamlanmadan ürün yolu açılmaz.');return o}
 const fixed=input.connection==='fixed';const highPower=m.runningW>1500;const three=input.phase==='three';const borehole=input.pumpType==='borehole';if(fixed||three||highPower||borehole){const o=base('professional','Pompa ve yedek kaynak koordinasyonu uzman doğrulaması gerektirir','Sabit bağlı, trifaze, kuyu tipi veya yüksek güçlü pompalarda yalnız watt hesabı yeterli değildir.');o.metrics=m;o.issues=uniq([fixed&&'Sabit tesisat bağlantısı transfer ve koruma koordinasyonu gerektirir.',three&&'Trifaze motorda faz sırası, dengesizlik ve jeneratör gerilim regülasyonu doğrulanmalıdır.',borehole&&'Kuyu pompasında kablo uzunluğu, gerilim düşümü ve kuru çalışma koruması değerlendirilmelidir.',highPower&&'Motor gücü tüketici tipi taşınabilir kaynak sınırını aşıyor.']);o.steps=['Yetkili elektrik uzmanına etiket, kablo, koruma, kalkış ve transfer verilerini doğrulatın.','Jeneratör veya sürücüyü yalnız sürekli güç değil kalkış ve kısa devre davranışıyla seçin.'];o.toolKeys=['generator','inverter'];return o}
 const existing=input.sourceStatus==='existing';if(existing){if(input.sourceType==='auto'){const o=base('evidence_required','Mevcut kaynağın sınıfını doğrulayın','Otomatik tercih, mevcut kaynağın jeneratör mü yoksa bataryalı inverter/power station mı olduğunu kanıtlamaz; hedef süre bu ayrım olmadan doğrulanamaz.');o.metrics=m;o.issues=['Mevcut kaynak sınıfı seçilmedi.'];o.steps=['Kaynağı jeneratör, power station veya inverter + batarya olarak seçin.','Bataryalı kaynakta nominal Wh; jeneratörde yakıt ve üretici çalışma süresi bilgisini ayrıca doğrulayın.'];return o}const cont=n(input.sourceContinuousW);const surge=n(input.sourceSurgeW);const wh=n(input.sourceWh);const contOk=cont!==null&&cont>=m.requiredContinuousW;const surgeOk=surge!==null&&surge>=m.requiredSurgeW;const batteryNeeded=['power_station','inverter'].includes(input.sourceType);const whOk=!batteryNeeded||(wh!==null&&wh>=m.requiredWh);if(cont===null||surge===null||(batteryNeeded&&wh===null)){const o=base('evidence_required','Mevcut kaynağın sürekli, tepe ve enerji değerini doğrulayın','Sadece model adı veya maksimum pazarlama gücü yeterli değildir.');o.metrics=m;o.issues=['Kaynağın sürekli W, tepe W ve bataryalıysa Wh değeri eksik.'];o.steps=['Üretici teknik sayfasındaki aynı model ve çıkış koşullarını doğrulayın.'];return o}if(contOk&&surgeOk&&whOk){const generator=input.sourceType==='generator';const o=base('no_buy','Mevcut kaynak güç eşiklerini karşılıyorsa yeni ürün almayın',generator?'Girilen etiket değerlerine göre mevcut jeneratör sürekli ve kalkış gücü eşiklerini karşılıyor; hedef süre için yakıt ve üretici çalışma süresini ayrıca doğrulayın.':'Girilen etiket değerlerine göre mevcut bataryalı kaynak sürekli güç, kalkış ve hedef enerji eşiklerini karşılıyor.');o.metrics=m;o.steps=generator?['Pompayı gerçek yük altında kontrollü başlatma testiyle doğrulayın.','Hedef süre için yakıt kapasitesi, yük oranı, havalandırma ve üretici çalışma süresini doğrulayın.']:['Pompayı gerçek yük altında kontrollü başlatma ve süre testiyle doğrulayın.','Kablo, priz, RCD ve susuz çalışma korumasını periyodik kontrol edin.'];o.toolKeys=['outcome'];return o}}
 let category='generator';if(input.sourceType==='power_station'||(input.sourceType==='auto'&&m.requiredSurgeW<=2200&&m.requiredWh<=2000&&m.targetHours<=4))category='power_station';else if(input.sourceType==='inverter')category='inverter';const o=base('conditional_purchase','Kaynak yetersiz veya eksik; yalnız hesaplanan sınıfa ilerleyin','Bu sonuç belirli marka/model onayı değildir. Sürekli güç, kalkış gücü ve enerji kapasitesi birlikte doğrulanmalıdır.');o.metrics=m;o.issues=[`En az yaklaşık ${m.requiredContinuousW} W sürekli güç gerekir.`,`Kalkış için yaklaşık ${m.requiredSurgeW} W kısa süreli kapasite gerekir.`,...(['power_station','inverter'].includes(category)?[`Hedef süre için yaklaşık ${m.requiredWh} Wh nominal enerji gerekir.`]:[])];o.steps=['Üretici sayfasında sürekli güç ile tepe gücü ayırın.','Motor kalkışına izin verilen süreyi ve dalga biçimini doğrulayın.','Fiş, kablo, RCD ve kuru çalışma korumasını ürün seçiminden ayrı değerlendirin.'];o.commerceCategories=[category];o.toolKeys=[category==='generator'?'generator':category==='inverter'?'inverter':'power'];o.commerceClosed=false;return o
}
function init(doc){const form=doc.getElementById('pumpForm');if(!form)return;const g=id=>doc.getElementById(id);let last=null;const read=()=>({emergency:g('emergency').checked,pumpType:g('pumpType').value,phase:g('phase').value,voltage:g('voltage').value,ratedCurrent:g('ratedCurrent').value,powerFactor:g('powerFactor').value,startMethod:g('startMethod').value,connection:g('connection').value,otherLoadW:g('otherLoadW').value,targetHours:g('targetHours').value,environment:g('environment').value,protection:g('protection').value,sourceStatus:g('sourceStatus').value,sourceType:g('sourceType').value,sourceContinuousW:g('sourceContinuousW').value,sourceSurgeW:g('sourceSurgeW').value,sourceWh:g('sourceWh').value});
function metrics(m){if(!m)return'';return`<div class="metrics"><article><span>Motor çalışma gücü</span><strong>${m.runningW.toLocaleString('tr-TR')} W</strong></article><article><span>Önerilen sürekli güç</span><strong>${m.requiredContinuousW.toLocaleString('tr-TR')} W</strong></article><article><span>Kalkış kapasitesi</span><strong>${m.requiredSurgeW.toLocaleString('tr-TR')} W</strong></article><article><span>Hedef enerji</span><strong>${m.requiredWh.toLocaleString('tr-TR')} Wh</strong></article></div>`}
function render(v){last=v;g('resultBadge').textContent=v.status.replaceAll('_',' ');g('resultTitle').textContent=v.title;g('resultSummary').textContent=v.summary;g('metricArea').innerHTML=metrics(v.metrics);g('issueList').innerHTML=v.issues.length?v.issues.map(x=>`<li>${x}</li>`).join(''):'<li>Kritik eksik kaydedilmedi.</li>';g('stepList').innerHTML=v.steps.map(x=>`<li>${x}</li>`).join('');g('toolLinks').innerHTML=(v.toolKeys||[]).map(k=>TOOL_LINKS[k]?`<a class="button" href="${TOOL_LINKS[k].href}">${TOOL_LINKS[k].label}</a>`:'').join('');g('result').className=`panel result status-${v.status}`;g('result').focus();g('commerceGate').classList.toggle('hidden',v.commerceClosed);g('productLinks').innerHTML='';['actualNeed','technicalCheck','affiliateCheck'].forEach(id=>g(id).checked=false);g('openProducts').disabled=true}
function sourceFields(){g('existingFields').classList.toggle('hidden',g('sourceStatus').value!=='existing')}
function gate(){g('openProducts').disabled=!['actualNeed','technicalCheck','affiliateCheck'].every(id=>g(id).checked)}
form.addEventListener('submit',e=>{e.preventDefault();render(evaluate(read()))});g('resetBtn').addEventListener('click',()=>{form.reset();sourceFields();g('result').className='panel result hidden';g('commerceGate').classList.add('hidden')});g('sourceStatus').addEventListener('change',sourceFields);['actualNeed','technicalCheck','affiliateCheck'].forEach(id=>g(id).addEventListener('change',gate));g('openProducts').addEventListener('click',()=>{if(!last||last.commerceClosed)return;g('productLinks').innerHTML=last.commerceCategories.map(k=>CATEGORY_LINKS[k]?`<a class="button primary" href="${CATEGORY_LINKS[k].href}">${CATEGORY_LINKS[k].label}</a>`:'').join('');g('productLinks').focus()});sourceFields()}
return{evaluate,calculations,init,constants:{START_MULTIPLIER,RESERVE,BATTERY_EFF,USABLE,CATEGORY_LINKS}};
});
