'use strict';
const assert=require('node:assert/strict');
const app=require('./app.js');
const base={emergency:false,pumpType:'domestic',phase:'single',voltage:230,ratedCurrent:5,powerFactor:.8,startMethod:'direct',connection:'plug',otherLoadW:0,targetHours:2,environment:'dry',protection:'rated',sourceStatus:'none',sourceType:'auto',sourceContinuousW:'',sourceSurgeW:'',sourceWh:''};
const calc=app.calculations(base);assert.equal(calc.runningW,920);assert.equal(calc.requiredContinuousW,1150);assert.equal(calc.requiredSurgeW,6348);assert.equal(calc.requiredWh,2706);
assert.equal(app.evaluate({...base,emergency:true}).status,'emergency');
assert.equal(app.evaluate({...base,pumpType:'fire'}).status,'professional');
assert.equal(app.evaluate({...base,phase:'three',voltage:400}).status,'professional');
assert.equal(app.evaluate({...base,pumpType:'borehole'}).status,'professional');
assert.equal(app.evaluate({...base,connection:'fixed'}).status,'professional');
assert.equal(app.evaluate({...base,environment:'wet',protection:'not_rated'}).status,'stop');
assert.equal(app.evaluate({...base,ratedCurrent:''}).status,'evidence_required');
const gen=app.evaluate(base);assert.equal(gen.status,'conditional_purchase');assert.deepEqual(gen.commerceCategories,['generator']);
const ps=app.evaluate({...base,ratedCurrent:2,startMethod:'vfd',sourceType:'auto'});assert.equal(ps.status,'conditional_purchase');assert.deepEqual(ps.commerceCategories,['power_station']);
const inv=app.evaluate({...base,ratedCurrent:2,startMethod:'soft',sourceType:'inverter'});assert.deepEqual(inv.commerceCategories,['inverter']);
const noBuy=app.evaluate({...base,sourceStatus:'existing',sourceType:'generator',sourceContinuousW:1500,sourceSurgeW:7000});assert.equal(noBuy.status,'no_buy');assert.equal(noBuy.commerceClosed,true);
const weak=app.evaluate({...base,sourceStatus:'existing',sourceType:'generator',sourceContinuousW:500,sourceSurgeW:1000});assert.equal(weak.status,'conditional_purchase');
assert.equal(app.constants.START_MULTIPLIER.direct,6);assert.equal(app.constants.START_MULTIPLIER.soft,3);assert.equal(app.constants.START_MULTIPLIER.vfd,1.5);assert(!Object.values(app.constants.CATEGORY_LINKS).some(x=>x.href.includes('amazon.')));
console.log(JSON.stringify({ok:true,scenarios:12,route:'/hesaplama/hidrofor-pompa-yedek-guc-uygunluk/'},null,2));
