(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root&&root.document)api.init(root.document,root);})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const STORAGE_KEY='alo186-pump-backup-records-v1';const MAX_RECORDS=8;const TTL_DAYS=365;const REVIEW_DAYS=90;const DAY_MS=86400000;
const n=v=>{const raw=String(v??'').trim().replace(',','.');if(!raw)return null;const value=Number(raw);return Number.isFinite(value)?value:null};const safe=v=>String(v??'').slice(0,180);const addDays=(date,days)=>new Date(date.getTime()+days*DAY_MS);
function normalizeRecord(input,result,now=new Date()){const created=now instanceof Date?now:new Date(now);if(Number.isNaN(created.getTime()))throw new Error('Geçersiz kayıt tarihi');const metrics=result&&result.metrics?result.metrics:null;return{id:`pump-${created.getTime()}`,createdAt:created.toISOString(),expiresAt:addDays(created,TTL_DAYS).toISOString(),reviewAt:addDays(created,REVIEW_DAYS).toISOString(),input:{pumpType:safe(input.pumpType),phase:safe(input.phase),voltage:n(input.voltage),ratedCurrent:n(input.ratedCurrent),powerFactor:n(input.powerFactor)??0.8,startMethod:safe(input.startMethod),connection:safe(input.connection),otherLoadW:n(input.otherLoadW)??0,targetHours:n(input.targetHours),environment:safe(input.environment),protection:safe(input.protection),sourceStatus:safe(input.sourceStatus),sourceType:safe(input.sourceType),sourceContinuousW:n(input.sourceContinuousW),sourceSurgeW:n(input.sourceSurgeW),sourceWh:n(input.sourceWh)},result:{status:safe(result.status),title:safe(result.title),metrics:metrics?{requiredContinuousW:metrics.requiredContinuousW,requiredSurgeW:metrics.requiredSurgeW,requiredWh:metrics.requiredWh,targetHours:metrics.targetHours}:null,commerceCategories:Array.isArray(result.commerceCategories)?result.commerceCategories.slice(0,2).map(safe):[]}}}
function purgeRecords(records,now=new Date()){const time=(now instanceof Date?now:new Date(now)).getTime();return(Array.isArray(records)?records:[]).filter(record=>record&&Date.parse(record.expiresAt)>time).sort((a,b)=>Date.parse(b.createdAt)-Date.parse(a.createdAt)).slice(0,MAX_RECORDS)}
function exportPayload(records,now=new Date()){return{schemaVersion:1,exportedAt:(now instanceof Date?now:new Date(now)).toISOString(),privacy:'Kişisel veri içermez; yalnız kullanıcı tarafından kaydedilen pompa ve güç hesabı alanları bulunur.',records:purgeRecords(records,now)}}
function icsDate(value){return new Date(value).toISOString().slice(0,10).replaceAll('-','')}
function calendarText(record){const date=icsDate(record.reviewAt);return['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//ALO186//Pompa Yedek Güç Kontrolü//TR','CALSCALE:GREGORIAN','BEGIN:VEVENT',`UID:${record.id}@alo186.com`,`DTSTART;VALUE=DATE:${date}`,`DTEND;VALUE=DATE:${icsDate(addDays(new Date(record.reviewAt),1))}`,'SUMMARY:Hidrofor ve pompa yedek güç kontrollü testi','DESCRIPTION:Pompa etiketini kontrollü kalkışı kablo-priz-RCD durumunu ve mevcut yedek kaynağın sürekli/tepe gücünü yeniden doğrulayın. Mevcut çözüm yeterliyse yeni ürün almayın.','END:VEVENT','END:VCALENDAR',''].join('\r\n')}
function init(doc,env){const form=doc.getElementById('pumpForm');const decision=env&&env.Alo186PumpBackup;if(!form||!decision)return;const g=id=>doc.getElementById(id);let last=null;let lastInput=null;let storage=null;try{storage=env.localStorage}catch{storage=null}
const read=()=>({emergency:g('emergency').checked,pumpType:g('pumpType').value,phase:g('phase').value,voltage:g('voltage').value,ratedCurrent:g('ratedCurrent').value,powerFactor:g('powerFactor').value,startMethod:g('startMethod').value,connection:g('connection').value,otherLoadW:g('otherLoadW').value,targetHours:g('targetHours').value,environment:g('environment').value,protection:g('protection').value,sourceStatus:g('sourceStatus').value,sourceType:g('sourceType').value,sourceContinuousW:g('sourceContinuousW').value,sourceSurgeW:g('sourceSurgeW').value,sourceWh:g('sourceWh').value});
function load(){if(!storage)return[];try{return purgeRecords(JSON.parse(storage.getItem(STORAGE_KEY)||'[]'))}catch{return[]}}
function write(records){if(!storage)return false;try{storage.setItem(STORAGE_KEY,JSON.stringify(purgeRecords(records)));return true}catch{return false}}
function download(content,type,name){if(typeof env.Blob!=='function'||!env.URL||typeof env.URL.createObjectURL!=='function')return false;const url=env.URL.createObjectURL(new env.Blob([content],{type}));const link=doc.createElement('a');link.href=url;link.download=name;doc.body.appendChild(link);link.click();link.remove();env.URL.revokeObjectURL(url);return true}
function renderRecords(){const records=load();if(storage)write(records);g('recordList').innerHTML=records.length?records.map(record=>`<article class="record"><strong>${record.result.title}</strong><span>${new Date(record.createdAt).toLocaleDateString('tr-TR')} · ${safe(record.input.pumpType)} · ${safe(record.input.phase)}</span><small>${record.result.metrics?`${record.result.metrics.requiredContinuousW} W sürekli · ${record.result.metrics.requiredSurgeW} W tepe · ${record.result.metrics.requiredWh} Wh`:'Güvenlik veya kanıt sonucu'}</small></article>`).join(''):'<p class="privacy">Henüz cihazda saklanan kayıt yok.</p>';g('clearRecords').disabled=!records.length;g('exportResults').disabled=!records.length}
form.addEventListener('submit',()=>{lastInput=read();last=decision.evaluate(lastInput);g('saveResult').disabled=false;g('calendarResult').disabled=false;if(last.status==='professional'){const area=g('toolLinks');if(area&&!area.querySelector('[data-pump-workorder]')){const link=doc.createElement('a');link.className='button';link.dataset.pumpWorkorder='true';link.href='../elektrikci-is-emri-ozeti/';link.textContent='Elektrikçi iş emri özetini aç';area.appendChild(link)}}});
g('resetBtn').addEventListener('click',()=>{last=null;lastInput=null;g('saveResult').disabled=true;g('calendarResult').disabled=true});
g('saveResult').addEventListener('click',()=>{if(!last||!lastInput)return;const record=normalizeRecord(lastInput,last);if(write([record,...load()])){renderRecords();g('recordStatus').textContent='Sonuç bu cihazda 365 gün saklandı; ziyaret etmek süreyi uzatmaz.'}else g('recordStatus').textContent='Tarayıcı kaydı kullanılamadı; JSON dışa aktarımını kullanın.'});
g('exportResults').addEventListener('click',()=>{const records=load();if(records.length)download(JSON.stringify(exportPayload(records),null,2),'application/json','alo186-pompa-yedek-guc-kayitlari.json')});
g('calendarResult').addEventListener('click',()=>{if(last&&lastInput)download(calendarText(normalizeRecord(lastInput,last)),'text/calendar','alo186-pompa-90-gun-kontrol.ics')});
g('clearRecords').addEventListener('click',()=>{if(storage)storage.removeItem(STORAGE_KEY);renderRecords();g('recordStatus').textContent='Bu cihazdaki pompa kayıtları silindi.'});renderRecords()}
return{normalizeRecord,purgeRecords,exportPayload,calendarText,init,constants:{STORAGE_KEY,MAX_RECORDS,TTL_DAYS,REVIEW_DAYS}};
});
