'use strict';
const assert=require('node:assert/strict');
const retention=require('./retention.js');
const input={pumpType:'domestic',phase:'single',voltage:230,ratedCurrent:5,powerFactor:.8,startMethod:'direct',connection:'plug',otherLoadW:0,targetHours:2,environment:'dry',protection:'rated',sourceStatus:'none',sourceType:'generator',sourceContinuousW:null,sourceSurgeW:null,sourceWh:null};
const result={status:'conditional_purchase',title:'Kaynak yetersiz veya eksik',metrics:{requiredContinuousW:1150,requiredSurgeW:6348,requiredWh:2705.9,targetHours:2},commerceCategories:['generator']};
const now=new Date('2026-07-30T06:00:00Z');
const record=retention.normalizeRecord(input,result,now);
assert.equal(record.createdAt,'2026-07-30T06:00:00.000Z');
assert.equal(record.reviewAt,'2026-10-28T06:00:00.000Z');
assert.equal(record.expiresAt,'2027-07-30T06:00:00.000Z');
assert.equal(record.input.voltage,230);
assert.equal(record.result.status,'conditional_purchase');
assert.doesNotMatch(JSON.stringify(record),/"(?:email|phone|address|location|price|stock|rating|seller|warranty|availability|offers)"\s*:/i);
const expired={...record,id:'expired',expiresAt:'2026-07-29T00:00:00Z'};
const many=Array.from({length:10},(_,index)=>({...record,id:`r${index}`,createdAt:new Date(now.getTime()+index*1000).toISOString()}));
const kept=retention.purgeRecords([expired,...many],now);assert.equal(kept.length,8);assert.ok(!kept.some(item=>item.id==='expired'));
const payload=retention.exportPayload([record],now);assert.equal(payload.schemaVersion,1);assert.equal(payload.records.length,1);assert.match(payload.privacy,/Kişisel veri içermez/);
const calendar=retention.calendarText(record);assert.match(calendar,/BEGIN:VCALENDAR/);assert.match(calendar,/DTSTART;VALUE=DATE:20261028/);assert.match(calendar,/Mevcut çözüm yeterliyse yeni ürün almayın/);assert.doesNotMatch(calendar,/mailto|email|telefon|adres/i);
assert.equal(retention.constants.MAX_RECORDS,8);assert.equal(retention.constants.TTL_DAYS,365);assert.equal(retention.constants.REVIEW_DAYS,90);
console.log(JSON.stringify({ok:true,scenarios:4,records:8,reviewDays:90},null,2));
