'use strict';
const assert=require('assert');
const {whFromMah,classify,amazonUrl,makeIcs}=require('./app.js');
const base={condition:'sound',recall:'clear',timing:'planning',airlineChecked:'yes',airlineProfile:'other',useCase:'phone',labelMode:'wh',labelWh:74,capacityMah:'',cellVoltage:'',outputW:30,requiredW:20,existing:'yes',need:'real',tested:'yes',shortCircuit:'yes'};
assert.strictEqual(whFromMah(20000,3.7),74);
assert.strictEqual(classify(base).status,'no_buy');
assert.strictEqual(classify({...base,condition:'damaged'}).status,'danger');
assert.strictEqual(classify({...base,recall:'recalled'}).status,'danger');
assert.strictEqual(classify({...base,useCase:'medical'}).status,'professional');
assert.strictEqual(classify({...base,labelMode:'marketing'}).status,'verify');
assert.strictEqual(classify({...base,labelWh:120}).status,'airline_block');
assert.strictEqual(classify({...base,airlineChecked:'no'}).status,'airline_block');
assert.strictEqual(classify({...base,airlineChecked:'unknown'}).status,'verify');
assert.strictEqual(classify({...base,shortCircuit:'no'}).status,'verify');
assert.strictEqual(classify({...base,timing:'active',existing:'none'}).status,'active');
assert.strictEqual(classify({...base,need:'none'}).status,'no_buy');
assert.strictEqual(classify({...base,need:'unknown'}).status,'verify');
assert.strictEqual(classify({...base,requiredW:''}).status,'verify');
assert.strictEqual(classify({...base,tested:'not_tested'}).status,'verify');
const qualified=classify({...base,existing:'none',tested:'no',outputW:'',requiredW:65,useCase:'laptop'});
assert.strictEqual(qualified.status,'qualified');
assert.strictEqual(qualified.commercialAllowed,true);
const underpowered=classify({...base,tested:'no',outputW:18,requiredW:30});
assert.strictEqual(underpowered.status,'qualified');
assert(underpowered.facts.some(x=>x.includes('18 W')));
assert(amazonUrl(65).includes('alo186rehber-21'));
assert(amazonUrl(65).includes('100Wh'));
assert(makeIcs().includes('BEGIN:VEVENT'));
assert(makeIcs().includes('Powerbank uçuş uygunluğunu'));
console.log(JSON.stringify({ok:true,scenarios:18,noBuy:true,affiliateTripleGate:true}));
