'use strict';
const assert=require('node:assert/strict');
const tool=require('./app.js');
const base={activeOutage:'no',profile:'home',duration:6,context:'standard',reviewCycle:90,flags:{internet:true,medical:false,cold:true,heating:false,aquarium:false,security:false,pump:false,generator:false,elevator:false},ready:{officialReady:true,phoneReady:true,lightingReady:true,sourceReady:true,coldEvidence:true}};
const run=(patch={})=>tool.buildPlan({...base,...patch,flags:{...base.flags,...(patch.flags||{})},ready:{...base.ready,...(patch.ready||{})}});
const ready=run();
assert.equal(ready.status,'ready');
assert.equal(ready.score,100);
assert.equal(ready.commercialAllowed,false);
assert.equal(ready.affiliateLinks,0);
assert(ready.routes.some((r)=>r.key==='modem'));
assert(ready.routes.some((r)=>r.key==='cold'));
const gap=run({ready:{sourceReady:false,lightingReady:false}});
assert.equal(gap.status,'gap');
assert(gap.gaps.includes('kritik yükler için gerçek kesinti testi'));
assert(gap.routes.some((r)=>r.key==='source'));
assert(gap.routes.some((r)=>r.key==='lighting'));
const outage=run({activeOutage:'yes'});
assert.equal(outage.status,'active_outage');
assert.equal(outage.commercialAllowed,false);
const medical=run({flags:{medical:true}});
assert(medical.routes.some((r)=>r.key==='cpap'));
assert(medical.routes.some((r)=>r.key==='emergency'));
const broad=run({profile:'hotel',duration:12,context:'remote-work',flags:{heating:true,aquarium:true,security:true,pump:true,generator:true,elevator:true}});
assert.equal(broad.status,'professional');
for(const key of ['heating','aquarium','security','generator','continuity','remoteWork'])assert(broad.routes.some((r)=>r.key===key),key);
assert.equal(tool.STORAGE_DAYS,180);
console.log(JSON.stringify({ok:true,scenarios:6,readyStatus:ready.status,readyScore:ready.score,gapCount:gap.gaps.length,professionalRoutes:broad.routes.length,affiliateLinks:ready.affiliateLinks,storageDays:tool.STORAGE_DAYS},null,2));
