'use strict';
(function(root,factory){
  const api=factory();
  if(typeof module==='object'&&module.exports)module.exports=api;
  if(root){root.ALO186PortableAC=api;if(root.document)api.mount(root.document);}
})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const ROUTE='/hesaplama/portatif-klima-egzoz-pencere-priz-uygunluk/';
  const n=(v)=>Number(v);
  const round=(v,d=2)=>Number(n(v).toFixed(d));
  function calculate(data){
    const voltage=n(data.voltage), inputW=n(data.inputW), ratedA=n(data.ratedA);
    const currentFromW=voltage>0&&inputW>=0?inputW/voltage:NaN;
    const workingA=Math.max(Number.isFinite(currentFromW)?currentFromW:0,Number.isFinite(ratedA)?ratedA:0);
    const plannedA=workingA*1.25;
    const kwh=inputW*Math.max(0,n(data.hoursPerDay))*Math.max(0,n(data.days))/1000;
    return {currentFromW:round(currentFromW,2),workingA:round(workingA,2),plannedA:round(plannedA,2),kwh:round(kwh,2)};
  }
  function decide(data){
    const calc=calculate(data);
    const confirms=Boolean(data.confirmNeed&&data.confirmManual&&data.confirmAffiliate);
    if(data.heatEmergency)return {...calc,code:'medical_emergency',commerce:false,category:'none',tone:'danger',title:'Sıcak çarpması belirtisinde 112’yi arayın',summary:'Bilinç değişikliği, nöbet, bayılma veya çok sıcak-kuru ciltte ürün kurulumunu bırakın; güvenli serin alan ve acil sağlık desteği önceliklidir.'};
    if(data.electricalDanger||data.physicalCondition!=='good')return {...calc,code:'electrical_danger',commerce:false,category:'none',tone:'danger',title:'Portatif klimayı prize bağlamayın',summary:'Duman, erime, su teması, gevşeklik, sıcak priz veya elektrik çarpması riskinde enerjiyi güvenli biçimde ayırın ve yetkili elektrikçiden destek alın.'};
    if(data.activeOutage)return {...calc,code:'active_outage',commerce:false,category:'none',tone:'warn',title:'Aktif kesintide henüz alınmamış klima çözüm değildir',summary:'Resmî kesinti kanalını, güvenli serin alanı ve mevcut test edilmiş düşük güçlü serinleme planını kullanın.'};
    if(data.useCase!=='single_room')return {...calc,code:'professional_scope',commerce:false,category:'none',tone:'warn',title:'Bu kullanım portatif tüketici cihazı kapsamını aşıyor',summary:'Çok odalı, ticari, server, medikal veya ortak alan soğutması için ısı yükü, havalandırma ve elektrik projesi gerekir.'};
    if(!data.manualVerified||!data.labelVerified)return {...calc,code:'evidence',commerce:false,category:'none',tone:'warn',title:'Tam model kılavuzu ve etiket kanıtı eksik',summary:'Gerçek giriş W/A, egzoz kiti, hortum sınırı, drenaj ve priz şartı doğrulanmadan uygunluk sonucu üretilemez.'};
    if(data.exhaustOutside!=='yes')return {...calc,code:'no_exhaust',commerce:false,category:'none',tone:'danger',title:'Sıcak egzoz havası dışarı atılamıyor',summary:'Portatif klima egzozunu aynı odaya vermek soğutma amacını bozar. Üreticinin uyumlu dışarı atım düzeni olmadan ürün karşılaştırmayın.'};
    if(data.windowEgressRisk)return {...calc,code:'egress',commerce:false,category:'none',tone:'danger',title:'Pencere kiti kaçış veya güvenlik açıklığını engelliyor',summary:'Tek kaçış penceresi, çocuk güvenliği, bina cephesi veya sabit montaj sınırı çözülmeden kurulum yapmayın.'};
    if(!data.hoseManufacturerCompatible||data.hoseExtended)return {...calc,code:'hose',commerce:false,category:'none',tone:'warn',title:'Egzoz hortumu üretici sınırına uygun değil',summary:'Rastgele uzatılmış, ezilmiş, delik veya uyumsuz hortum performans ve ısınma sorununa yol açabilir. Tam model uyumlu kiti kullanın.'};
    if(!data.windowSealVerified){
      if(data.existingUnit&&confirms)return {...calc,code:'eligible_accessory',commerce:true,category:'window_kit',tone:'ok',title:'Yalnız uyumlu pencere / egzoz aksesuarı sınıfı açıldı',summary:'Mevcut cihaz çalışıyorsa yeni klima yerine tam model hortum çapına ve pencere tipine uyumlu sökülebilir kiti karşılaştırın.'};
      return {...calc,code:'seal',commerce:false,category:'window_kit',tone:'info',title:'Önce pencere sızdırmazlık kitini doğrulayın',summary:'Dış sıcak havanın geri girmesini azaltan, pencere tipine ve üretici hortum çapına uyumlu sökülebilir kit olmadan yeni klima seçmek yerine kurulum açığını çözün.'};
    }
    if(data.connection!=='direct_grounded'||!data.rcdVerified)return {...calc,code:'electrical_connection',commerce:false,category:'none',tone:'danger',title:'Doğrudan topraklı priz ve RCD kanıtı gerekli',summary:'Uzatma, grup priz, adaptör zinciri veya doğrulanmamış koruma ile portatif klima çalıştırmayın.'};
    if(!Number.isFinite(calc.plannedA)||n(data.outletMaxA)<=0||n(data.breakerA)<=0)return {...calc,code:'invalid',commerce:false,category:'none',tone:'warn',title:'Etiket ve devre değerlerini tamamlayın',summary:'Gerilim, giriş W/A, priz sınırı ve devre sigortası değerlerini doğrulanmış kaynaktan girin.'};
    if(calc.plannedA>n(data.outletMaxA)||calc.plannedA>n(data.breakerA))return {...calc,code:'overload',commerce:false,category:'none',tone:'danger',title:'Planlama akımı priz veya devre sınırını aşıyor',summary:'Daha büyük sigorta takmayın. Devre, kablo ve üretici şartını yetkili elektrikçiyle doğrulayın.'};
    if(!data.condensateSafe)return {...calc,code:'condensate',commerce:false,category:'none',tone:'warn',title:'Yoğuşma suyu yönetimi doğrulanmadı',summary:'Taşma, hortum çıkması veya suyun prize yaklaşması riski çözülmeden cihazı çalıştırmayın.'};
    if(data.existingUnit&&data.realCoolingTest&&data.noHeat)return {...calc,code:'no_buy',commerce:false,category:'none',tone:'ok',title:'Mevcut portatif klima ve kurulum yeterli — yeni ürün almayın',summary:'Gerçek sıcak gün testi, dışarı egzoz, pencere sızdırmazlığı, elektrik bağlantısı ve yoğuşma yönetimi başarılıysa yalnız yeni model için değişim gerekmez.'};
    if(!confirms)return {...calc,code:'confirm',commerce:false,category:'none',tone:'info',title:'Önce üç güven onayını tamamlayın',summary:'Gerçek kapasite veya kurulum açığını, tam model kılavuzunu ve satış ortaklığı bilgisini ayrı ayrı onaylayın.'};
    return {...calc,code:'eligible_portable_ac',commerce:true,category:'portable_ac',tone:'ok',title:'Koşullu portatif klima sınıfı açıldı',summary:'Yalnız tek oda, dışarı egzoz, uyumlu pencere kiti, doğrudan topraklı priz, RCD ve doğrulanmış akım sınırı için ürün sınıfını karşılaştırın.'};
  }
  function read(doc){const id=(x)=>doc.getElementById(x);return {heatEmergency:id('heatEmergency').checked,electricalDanger:id('electricalDanger').checked,activeOutage:id('activeOutage').checked,useCase:id('useCase').value,physicalCondition:id('physicalCondition').value,manualVerified:id('manualVerified').checked,labelVerified:id('labelVerified').checked,exhaustOutside:id('exhaustOutside').value,windowEgressRisk:id('windowEgressRisk').checked,hoseManufacturerCompatible:id('hoseManufacturerCompatible').checked,hoseExtended:id('hoseExtended').checked,windowSealVerified:id('windowSealVerified').checked,connection:id('connection').value,rcdVerified:id('rcdVerified').checked,voltage:id('voltage').value,inputW:id('inputW').value,ratedA:id('ratedA').value,outletMaxA:id('outletMaxA').value,breakerA:id('breakerA').value,condensateSafe:id('condensateSafe').checked,existingUnit:id('existingUnit').checked,realCoolingTest:id('realCoolingTest').checked,noHeat:id('noHeat').checked,hoursPerDay:id('hoursPerDay').value,days:id('days').value,confirmNeed:id('confirmNeed').checked,confirmManual:id('confirmManual').checked,confirmAffiliate:id('confirmAffiliate').checked};}
  function esc(s){return String(s).replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function mount(doc){const form=doc.getElementById('portableAcForm');if(!form)return;const result=doc.getElementById('result');const affiliate=doc.getElementById('affiliate');let last=null;const render=()=>{last=decide(read(doc));result.className='result '+last.tone;result.innerHTML='<h2>'+esc(last.title)+'</h2><p>'+esc(last.summary)+'</p><div class="metrics"><span><b>'+esc(last.currentFromW)+'</b> A W/V</span><span><b>'+esc(last.workingA)+'</b> A esas alınan</span><span><b>'+esc(last.plannedA)+'</b> A %25 planlama</span><span><b>'+esc(last.kwh)+'</b> kWh dönem</span></div><small>%25 yalnız görünür ALO186 ön planlama payıdır; standart, kablo veya sigorta seçimi değildir.</small>';affiliate.classList.toggle('hidden',!last.commerce);affiliate.dataset.category=last.category||'none';};form.addEventListener('submit',(e)=>{e.preventDefault();render();result.scrollIntoView({behavior:'smooth',block:'start'});});doc.getElementById('exportJson').addEventListener('click',()=>{if(!last)render();const a=doc.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({route:ROUTE,createdAt:new Date().toISOString(),input:read(doc),decision:last},null,2)],{type:'application/json'}));a.download='alo186-portatif-klima-uygunluk.json';a.click();URL.revokeObjectURL(a.href);});doc.getElementById('calendar').addEventListener('click',()=>{const d=new Date();d.setDate(d.getDate()+30);const stamp=(x)=>x.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z');const ics=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//ALO186//Portable AC Check//TR','BEGIN:VEVENT','UID:'+Date.now()+'@alo186.com','DTSTAMP:'+stamp(new Date()),'DTSTART:'+stamp(d),'SUMMARY:Portatif klima kurulumunu yeniden test et','DESCRIPTION:Egzoz hortumu pencere sızdırmazlığı priz sıcaklığı RCD yoğuşma ve gerçek soğutma testini yeniden doğrulayın.','END:VEVENT','END:VCALENDAR'].join('\r\n');const a=doc.createElement('a');a.href=URL.createObjectURL(new Blob([ics],{type:'text/calendar'}));a.download='alo186-portatif-klima-30-gun.ics';a.click();URL.revokeObjectURL(a.href);});}
  return {calculate,decide,mount,ROUTE};
});