'use strict';
(function(root,factory){
  const api=factory();
  if(typeof module==='object'&&module.exports)module.exports=api;
  if(root){root.ALO186ElectronicsPlan=api;if(root.document)api.mount(root.document);}
})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const ROUTE='/sektor-rehberi/elektronik-cihaz-guc-seyahat-koruma-merkezi/';
  function makePlan(data){
    if(data.danger)return {code:'danger',days:0,title:'Önce can ve yangın güvenliği',summary:'Duman, yanık kokusu, şişmiş batarya, erime, elektrik çarpması veya aktif yangın riskinde ürün ve seyahat planı kapanır.',tasks:['Enerji kaynağından güvenli mesafe alın.','Gerekliyse 112 ve yetkili servis/elektrikçi rotasına geçin.','Hasarlı batarya veya koruma cihazını kullanmayın ve taşımayın.']};
    if(data.existingWorks&&!data.newDevice&&!data.majorEvent)return {code:'no_buy',days:90,title:'Mevcut güvenli düzeni koruyun',summary:'Cihaz, powerbank, adaptör ve koruma düzeni gerçek ihtiyacı karşılıyorsa yalnız daha yeni model için değiştirmeyin.',tasks:['Etiket ve fiziksel durumu yeniden kaydedin.','Kablo, port, gösterge ve gerçek yükü kontrollü test edin.','90 gün sonra veya cihaz/seyahat koşulu değiştiğinde tekrar kontrol edin.']};
    if(data.scenario==='travel')return {code:'travel',days:Math.max(1,Number(data.tripDays)||7),title:'Seyahat öncesi dört kanıtı tamamlayın',summary:'Havayolu, powerbank Wh, cihaz USB-C ihtiyacı ve hedef ülke voltaj/priz bilgisi ayrı ayrı doğrulanmalıdır.',tasks:['Uçuşu gerçekleştiren havayolunun güncel powerbank Wh, adet, kabin ve kullanım kuralını kontrol edin.','Powerbank Wh ve USB-C PD uygunluğunu hesaplayın; mevcut ürün yeterliyse yenisini almayın.','Cihaz INPUT etiketini hedef ülke voltajı ve frekansıyla karşılaştırın.','Powerbank terminallerini ve kabloları kısa devre/fiziksel hasara karşı hazırlayın.']};
    if(data.scenario==='storm'||data.majorEvent)return {code:'storm',days:30,title:'Elektrik olayı sonrası kanıt ve yeniden test planı',summary:'Yıldırım veya şebeke darbesinden sonra otomatik ürün değişimi yerine gösterge, fiziksel durum, cihaz logu ve kök neden kanıtı toplanır.',tasks:['Koruma cihazını açmadan fiziksel durum ve göstergeyi kontrol edin.','Tam model üretici kılavuzunda gösterge anlamını doğrulayın.','Cihaz reseti veya gerilim olayını kanıt günlüğüne kaydedin.','Bina çapında veya tekrarlayan belirtide EDAŞ kaydı ve profesyonel ölçüm planlayın.','Yaklaşık bir ay sonra ya da yeni olayda tekrar test edin.']};
    if(data.scenario==='new-device'||data.newDevice)return {code:'device',days:30,title:'Yeni cihaz güç zincirini doğrulayın',summary:'Yeni cihaz için adaptör, USB-C PD, kablo, grup priz yükü ve koruma düzeni ayrı kanıtlarla kontrol edilmelidir.',tasks:['Cihazın INPUT V/A/Hz veya USB-C PD gereksinimini tam modelden okuyun.','Mevcut adaptör, kablo ve powerbankın gerçek güç sınırını karşılaştırın.','Aynı priz/devredeki eşzamanlı wattı hesaplayın.','Mevcut koruma göstergesi ve topraklama durumunu kontrol edin.','Yaklaşık bir ay sonra gerçek kullanım ve ısınma sonucunu yeniden değerlendirin.']};
    return {code:'routine',days:90,title:'90 günlük elektronik güç ve koruma kontrolü',summary:'Kampanya yerine cihaz, kablo, batarya, seyahat ve elektrik olayı değişiklikleri tekrar ziyaret nedeni yapılır.',tasks:['Powerbank ve lityum bataryalarda şişme, ısınma ve etiket kontrolü yapın.','USB-C kablo/adaptör güç zincirini yeni cihazlarla yeniden karşılaştırın.','Akım korumalı priz göstergesi ve gerçek yükünü kontrol edin.','Seyahat planı varsa havayolu ve ülke elektrik kurallarını yeniden doğrulayın.','Mevcut sistem yeterliyse satın almama sonucunu kaydedin.']};
  }
  function report(data){return {route:ROUTE,generatedAt:new Date().toISOString(),plan:makePlan(data),personalData:false,officialRecord:false,commerce:false};}
  function calendar(plan){const days=Math.max(1,Number(plan.days)||90);const start=new Date(Date.now()+days*86400000);const end=new Date(start.getTime()+30*60000);const stamp=(date)=>date.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z');return ['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//ALO186//Electronics Protection Plan//TR','BEGIN:VEVENT',`UID:electronics-plan-${Date.now()}@alo186.com`,`DTSTAMP:${stamp(new Date())}`,`DTSTART:${stamp(start)}`,`DTEND:${stamp(end)}`,`SUMMARY:${plan.title.replace(/[,;]/g,' ')}`,`DESCRIPTION:${plan.tasks.join(' | ').replace(/[,;]/g,' ')}`,'END:VEVENT','END:VCALENDAR'].join('\r\n');}
  function download(name,text,type){const blob=new Blob([text],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),0);}
  function read(doc){const value=(id)=>doc.getElementById(id)?.value;const checked=(id)=>Boolean(doc.getElementById(id)?.checked);return {scenario:value('scenario'),tripDays:value('tripDays'),danger:checked('danger'),existingWorks:checked('existingWorks'),newDevice:checked('newDevice'),majorEvent:checked('majorEvent')};}
  function mount(doc){const form=doc.getElementById('planForm');if(!form)return;let current=null;form.addEventListener('submit',(event)=>{event.preventDefault();const data=read(doc);current=report(data);const plan=current.plan;const result=doc.getElementById('result');result.className=`result ${plan.code==='danger'?'danger':plan.code==='no_buy'?'ok':'warn'}`;result.innerHTML=`<h2>${plan.title}</h2><p>${plan.summary}</p><ol>${plan.tasks.map((task)=>`<li>${task}</li>`).join('')}</ol><p><strong>Tekrar kontrol:</strong> ${plan.days?plan.days+' gün':'risk giderildikten sonra'}</p>`;result.scrollIntoView({behavior:'smooth',block:'start'});});doc.getElementById('exportJson')?.addEventListener('click',()=>download('alo186-elektronik-seyahat-koruma-plani.json',JSON.stringify(current||report(read(doc)),null,2),'application/json'));doc.getElementById('calendar')?.addEventListener('click',()=>{const reportData=current||report(read(doc));if(reportData.plan.days)download('alo186-elektronik-seyahat-koruma-plani.ics',calendar(reportData.plan),'text/calendar');});}
  return {ROUTE,makePlan,report,calendar,mount};
});