(() => {'use strict';const core=window.Alo186TechnicalShortlist,$=id=>document.getElementById(id),STORE='alo186:technical-shortlist-receipts:v1';let lastResult=null,lastReceipt=null;
function track(name,params={}){const allowed={};for(const[key,value]of Object.entries(params)){if(['category','decision','status','route','slot'].includes(key)&&typeof value==='string'&&value.length<80)allowed[key]=value;}if(typeof window.Alo186Track==='function')window.Alo186Track(name,allowed);}
function escapeHtml(value){return String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));}
function readReceipts(){try{return core.pruneReceipts(JSON.parse(localStorage.getItem(STORE)||'[]'));}catch(_){return[];}}
function saveReceipt(receipt){const items=core.saveReceipt(readReceipts(),receipt);try{localStorage.setItem(STORE,JSON.stringify(items));}catch(_){}return items;}
function download(name,content,type){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function initSelects(){$('category').innerHTML=Object.entries(core.CATEGORIES).map(([id,item])=>`<option value="${id}">${escapeHtml(item.label)}</option>`).join('');$('existing').innerHTML=Object.entries(core.EXISTING).map(([id,label])=>`<option value="${id}">${escapeHtml(label)}</option>`).join('');const requested=new URLSearchParams(location.search).get('kategori');if(core.category(requested))$('category').value=requested;$('existing').value='uncertain';}
function renderCandidates(){const meta=core.category($('category').value);$('candidateGrid').innerHTML=['A','B','C'].map((slot,index)=>`<article class="candidate" data-candidate="${index}"><h3>Aday ${slot}</h3><div class="field-row">${meta.fields.map(([id,label,critical,question])=>`<label>${escapeHtml(label)}${critical?' *':''}<small>${escapeHtml(question)}</small><select data-field="${id}"><option value="unknown">Belirsiz / belge yok</option><option value="verified">Belgeyle doğrulandı</option><option value="fails">İhtiyacı karşılamıyor</option></select></label>`).join('')}</div></article>`).join('');}
function collect(){const candidates=[...document.querySelectorAll('[data-candidate]')].map(card=>{const states={};card.querySelectorAll('[data-field]').forEach(select=>states[select.dataset.field]=select.value);return{states};});return{category:$('category').value,existing:$('existing').value,candidates};}
function statusLabel(status){return status==='ready'?'Kritik alanlar tam':status==='conditional'?'Doğrulama gerekli':'Kritik engel';}
function renderScores(result){$('scoreCards').innerHTML=result.candidates.map(item=>`<article class="score-card ${item.status}"><span class="status ${item.status}">${statusLabel(item.status)}</span><h3>Aday ${item.slot}</h3><strong>${item.score}/100</strong><p>${item.criticalFailures.length?`${item.criticalFailures.length} kritik başarısız`:item.criticalUnknowns.length?`${item.criticalUnknowns.length} kritik belirsiz`:'Kritik alanlar doğrulandı'}</p>${item.criticalFailures.length||item.criticalUnknowns.length?`<ul>${[...item.criticalFailures,...item.criticalUnknowns].map(x=>`<li>${escapeHtml(x.label)}</li>`).join('')}</ul>`:''}</article>`).join('');}
function gate(){if(!lastResult)return;const confirmations={toolCompleted:$('toolConfirmed').checked,existingInadequate:$('existingConfirmed').checked,affiliateDisclosure:$('affiliateConfirmed').checked},allowed=core.canOpenAffiliate(lastResult,confirmations),link=$('affiliateLink');link.classList.toggle('disabled',!allowed);link.setAttribute('aria-disabled',allowed?'false':'true');link.href=allowed?`/akilli-urun-secimi?kategori=${encodeURIComponent(lastResult.productCategory)}&source=technical_shortlist`:'#';if(allowed){link.dataset.outcomeStart='true';link.dataset.outcomeAction='free_tool';}else{delete link.dataset.outcomeStart;delete link.dataset.outcomeAction;}}
function render(result){lastResult=result;lastReceipt=core.normalizeReceipt(result);saveReceipt(lastReceipt);$('result').classList.remove('hidden');$('resultEyebrow').textContent=result.categoryLabel;$('resultTitle').textContent=result.title;$('resultText').textContent=result.summary;renderScores(result);const qs=core.questions(result);$('questionBox').classList.toggle('hidden',!qs.length);$('questionList').innerHTML=qs.map(q=>`<li>${escapeHtml(q)}</li>`).join('');$('toolLink').href=result.tool;$('receiptText').textContent=`${result.categoryLabel} · ${result.decision} · ${result.best?`Aday ${result.best.slot}, ${result.best.score}/100`:'aday yok'} · 14 gün sonra yeniden kontrol`;$('toolConfirmed').checked=false;$('existingConfirmed').checked=result.existing==='inadequate'||result.existing==='none';$('affiliateConfirmed').checked=false;gate();$('result').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});track('technical_shortlist_completed',{category:result.category,decision:result.decision,slot:result.best?result.best.slot:'none'});}
function compare(event){event.preventDefault();$('validation').textContent='';try{render(core.compare(collect()));}catch(error){$('validation').textContent=error.message;}}
function copyQuestions(){if(!lastResult)return;const text=core.questions(lastResult).map((q,i)=>`${i+1}. ${q}`).join('\n');if(!text)return;if(navigator.clipboard)navigator.clipboard.writeText(text).then(()=>{$('copyQuestions').textContent='Kopyalandı';setTimeout(()=>$('copyQuestions').textContent='Soruları kopyala',1400);}).catch(()=>window.prompt('Soruları kopyalayın:',text));else window.prompt('Soruları kopyalayın:',text);track('technical_shortlist_questions_copied',{category:lastResult.category});}
function exportJson(){if(!lastResult||!lastReceipt)return;download(`alo186-teknik-karsilastirma-${lastResult.category}.json`,JSON.stringify(core.exportPayload(lastResult,lastReceipt),null,2),'application/json;charset=utf-8');track('technical_shortlist_receipt_exported',{category:lastResult.category});}
function calendar(){if(!lastReceipt)return;download(`alo186-karsilastirma-kontrol-${lastReceipt.category}.ics`,core.buildIcs(lastReceipt,location.origin),'text/calendar;charset=utf-8');track('technical_shortlist_review_saved',{category:lastReceipt.category});}
function noBuy(){$('existing').value='adequate';render(core.compare(collect()));track('technical_shortlist_no_buy_selected',{category:$('category').value});}
document.addEventListener('DOMContentLoaded',()=>{if(!core){$('validation').textContent='Karşılaştırma motoru yüklenemedi.';return;}initSelects();renderCandidates();$('category').addEventListener('change',renderCandidates);$('compareForm').addEventListener('submit',compare);['toolConfirmed','existingConfirmed','affiliateConfirmed'].forEach(id=>$(id).addEventListener('change',gate));$('affiliateLink').addEventListener('click',event=>{if(event.currentTarget.getAttribute('aria-disabled')==='true'){event.preventDefault();return;}track('technical_shortlist_product_center_opened',{category:lastResult.category,route:'product_center'});});$('toolLink').addEventListener('click',()=>track('technical_shortlist_tool_opened',{category:$('category').value,route:$('toolLink').getAttribute('href')}));$('copyQuestions').addEventListener('click',copyQuestions);$('jsonBtn').addEventListener('click',exportJson);$('calendarBtn').addEventListener('click',calendar);$('printBtn').addEventListener('click',()=>window.print());$('noBuyBtn').addEventListener('click',noBuy);});})();