(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.Alo186TechnicalShortlist=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const VERSION=1,MAX_RECEIPTS=6,TTL_DAYS=45,REVIEW_DAYS=14,DAY=86400000;
const FIELD_STATE={verified:'Belgeyle doğrulandı',unknown:'Belirsiz / belge yok',fails:'İhtiyacı karşılamıyor'};
const EXISTING={adequate:'Mevcut ürün gerçek kullanımda yeterli',uncertain:'Mevcut ürün var fakat doğrulanmadı',inadequate:'Mevcut ürün yetersiz',none:'Mevcut ürün yok'};
const CATEGORIES={
 power_station:{label:'Power station',productCategory:'power_station',tool:'/hesaplama/power-station-kapasite-eps-uygunluk/',fields:[['usable_wh','Kullanılabilir enerji (Wh)',true,'AC çıkışta kullanılabilir Wh ve test yükü doğrulanmalı.'],['continuous_power','Sürekli güç',true,'Sürekli AC güç gerçek yükün üstünde olmalı.'],['surge_power','Tepe güç ve süresi',true,'Kalkış gücü ve izin verilen tepe süresi belgelenmeli.'],['waveform','Saf sinüs / THD',true,'Dalga biçimi ve THD yük koşuluyla belirtilmeli.'],['eps','EPS geçişi ve bypass',false,'EPS süresi, bypass limiti ve desteklenmeyen yükler açıklanmalı.']]},
 surge_strip:{label:'Akım korumalı grup priz',productCategory:'surge_strip',tool:'/hesaplama/akim-korumali-grup-priz-uygunluk/',fields:[['current','Nominal sürekli akım',true,'Etiket akımı gerçek sürekli yükü karşılamalı.'],['power','Azami sürekli güç',true,'230 V azami güç ve uzun kullanım sınırı bilinmeli.'],['joules','Joule / darbe enerjisi',true,'Joule değeri ve koruma göstergesi belgelenmeli.'],['overload','Aşırı akım koruması',true,'Termik veya aşırı akım koruması bulunmalı.'],['ground','Topraklı bağlantı',true,'Topraklama ve doğrudan duvar bağlantısı doğrulanmalı.']]},
 mini_ups:{label:'Modem / ONT mini UPS',productCategory:'mini_ups',tool:'/hesaplama/modem-internet-yedekleme/',fields:[['voltage','Çıkış gerilimi',true,'Modem ve ONT gerilimleri tam eşleşmeli.'],['polarity','Jak ve polarite',true,'Jak ölçüsü ile merkez polaritesi doğrulanmalı.'],['runtime','Gerçek yükte süre',true,'Beyan edilen süre hangi watt yükte ölçüldüğüyle verilmelidir.'],['transfer','Kesintisiz geçiş',true,'Bağlı cihazı yeniden başlatmadan geçiş davranışı doğrulanmalı.']]},
 powerbank:{label:'Powerbank',productCategory:'powerbank',tool:'/hesaplama/powerbank-usb-c-uygunluk/',fields:[['energy','Gerçek enerji (Wh)',true,'mAh yanında Wh ve aktarım kaybı değerlendirilmelidir.'],['pd','USB-C PD profilleri',true,'Cihazın istediği voltaj/güç profili desteklenmeli.'],['output','Tek port azami güç',true,'Tek port ve toplam kullanım güçleri ayrı verilmelidir.'],['sharing','Çoklu port paylaşımı',false,'Aynı anda kullanımda güç paylaşımı bilinmelidir.']]},
 ev_cable:{label:'Type 2 EV şarj kablosu',productCategory:'ev_cable',tool:'/hesaplama/ev-sarj-kablosu-uygunluk/',fields:[['phase_current','Faz ve akım',true,'Araç ve istasyonla aynı faz/akım sınıfı doğrulanmalı.'],['connector','Type 2 / IEC 62196',true,'Her iki uç ve standart kapsamı belgelenmeli.'],['section','Uzunluk ve iletken kesiti',true,'Kesit, uzunluk ve sıcaklık sınıfı açıklanmalı.'],['environment','IP ve sıcaklık',true,'Bağlı durumda IP ile çalışma sıcaklığı bilinmeli.']]},
 smart_plug:{label:'Akıllı priz ve enerji ölçer',productCategory:'smart_plug',tool:'/hesaplama/akilli-priz-enerji-olcer-uygunluk/',fields:[['current','Sürekli akım',true,'Gerçek uzun süreli akım sınırı belgelenmeli.'],['motor','Motor/kompresör sınırı',true,'Kalkış akımı için üretici izni bulunmalı.'],['meter','W ve kWh doğruluğu',true,'Ölçüm doğruluğu ve çözünürlük bilinmeli.'],['privacy','Yerel/bulut çalışma',false,'Hesap, internet ve veri saklama gereksinimi açıklanmalı.']]},
 emergency_light:{label:'Acil aydınlatma',productCategory:'emergency_light',tool:'/hesaplama/acil-aydinlatma-sure-uygunluk/',fields:[['lumens','Aynı modda lümen',true,'Lümen değeri seçilen parlaklık moduna ait olmalı.'],['runtime','Aynı modda süre',true,'Çalışma süresi aynı parlaklık modu için verilmelidir.'],['auto_on','Kesintide otomatik yanma',false,'İhtiyaç varsa otomatik yanma davranışı doğrulanmalı.'],['environment','Pil, IP ve sıcaklık',true,'Pil durumu ve ortam sınırları belgelenmeli.']]},
 smoke_alarm:{label:'Duman alarmı',productCategory:'smoke_alarm',tool:'/hesaplama/duman-alarmi-yerlesim-bakim-uygunluk/',fields:[['standard','EN 14604 kapsamı',true,'Uygunluk belgesi tam modeli kapsamalı.'],['sensor','Sensör türü',true,'Fotoelektrik sensör ve kullanım sınırı belirtilmeli.'],['life','Ürün/pil ömrü',true,'Üretim tarihi, ömür sonu ve düşük pil uyarısı bulunmalı.'],['test','Test ve susturma',true,'Test düğmesi ve alarm davranışı doğrulanmalı.']]},
 ups_battery:{label:'UPS aküsü / kartuşu',productCategory:'ups_battery',tool:'/hesaplama/ups-aku-degisim-uygunluk/',fields:[['model','Tam UPS ve kartuş uyumu',true,'Tam UPS modeli ve üretici kartuş/set kodu eşleşmeli.'],['string','Gerilim, Ah ve adet',true,'Blok ve toplam string değerleri aynı olmalı.'],['terminal','Kimya, terminal ve ölçü',true,'Kimya, terminal, ölçü ve montaj yönü doğrulanmalı.'],['policy','Set değiştirme politikası',true,'Tek blok mu bütün string mi değişeceği kılavuzda bulunmalı.']]}
};
function category(id){return CATEGORIES[id]||null;}
function sanitizeState(value){return Object.prototype.hasOwnProperty.call(FIELD_STATE,value)?value:'unknown';}
function sanitizeCandidate(raw={},index=0){const slot=['A','B','C'][index]||String(index+1);const states={};Object.entries(raw.states||{}).forEach(([key,value])=>{states[String(key).slice(0,40)]=sanitizeState(value);});return{slot,states};}
function scoreCandidate(categoryId,raw,index=0){const meta=category(categoryId);if(!meta)throw new Error('Desteklenmeyen kategori.');const candidate=sanitizeCandidate(raw,index);let total=0,earned=0;const criticalFailures=[],criticalUnknowns=[],optionalUnknowns=[],verified=[];for(const [id,label,critical,question] of meta.fields){const weight=critical?2:1,state=sanitizeState(candidate.states[id]);total+=weight;if(state==='verified'){earned+=weight;verified.push(label);}else if(state==='unknown'){earned+=weight*.2;(critical?criticalUnknowns:optionalUnknowns).push({id,label,question});}else if(critical){criticalFailures.push({id,label,question});}}
const score=Math.round(100*earned/total);const status=criticalFailures.length?'blocked':criticalUnknowns.length?'conditional':'ready';return{slot:candidate.slot,score,status,criticalFailures,criticalUnknowns,optionalUnknowns,verified};}
function compare(input={}){const categoryId=String(input.category||'');const meta=category(categoryId);if(!meta)throw new Error('Önce ürün kategorisini seçin.');const existing=Object.prototype.hasOwnProperty.call(EXISTING,input.existing)?input.existing:'uncertain';const candidates=(Array.isArray(input.candidates)?input.candidates:[]).slice(0,3).map((item,index)=>scoreCandidate(categoryId,item,index));const ranked=[...candidates].sort((a,b)=>b.score-a.score||a.slot.localeCompare(b.slot));const best=ranked.find(item=>item.status==='ready')||ranked.find(item=>item.status==='conditional')||ranked[0]||null;let decision='incomplete',commercialAllowed=false,title='Aday bilgilerini tamamlayın',summary='En az bir aday için teknik belge durumunu işaretleyin.';
if(existing==='adequate'){decision='no_buy';title='Mevcut ürün yeterli: yeni satın alma gerekmiyor';summary='Gerçek kullanımda yeterli ve güvenli olan mevcut ekipman, yeni adayların önünde tutulur.';}else if(!best){decision='incomplete';}else if(best.status==='blocked'){decision='blocked';title='Hiçbir aday kritik teknik kapıyı geçemedi';summary='Kritik alanı karşılamayan aday için affiliate veya satın alma rotası açılmaz.';}else if(best.status==='conditional'){decision='verify';title=`Aday ${best.slot} önde; kritik belge eksik`;summary='Eksik kritik alanlar satıcı veya üreticiden doğrulanmadan ürün rotasına ilerlemeyin.';}else{decision='ready';commercialAllowed=['none','inadequate'].includes(existing);title=`Aday ${best.slot} teknik olarak en güçlü`;summary=commercialAllowed?'Kritik alanlar doğrulandı. Mevcut ekipmanın yetersizliği ve satış ortaklığı açıklaması ayrıca onaylanırsa ürün merkezi açılabilir.':'Teknik aday hazır; ancak mevcut ekipmanın yetersizliği henüz doğrulanmadı.';}
return{version:VERSION,category:categoryId,categoryLabel:meta.label,tool:meta.tool,productCategory:meta.productCategory,existing,decision,commercialAllowed,best,candidates:ranked,title,summary};}
function canOpenAffiliate(result,confirmations={}){return Boolean(result&&result.decision==='ready'&&result.commercialAllowed&&confirmations.toolCompleted===true&&confirmations.existingInadequate===true&&confirmations.affiliateDisclosure===true);}
function questions(result){if(!result||!result.best)return[];return[...result.best.criticalFailures,...result.best.criticalUnknowns,...result.best.optionalUnknowns].map(item=>item.question);}
function normalizeReceipt(result,nowValue=new Date()){const now=nowValue instanceof Date?nowValue:new Date(nowValue);return{version:VERSION,id:`shortlist_${now.getTime().toString(36)}`,createdAt:now.toISOString(),reviewAt:new Date(now.getTime()+REVIEW_DAYS*DAY).toISOString(),expiresAt:new Date(now.getTime()+TTL_DAYS*DAY).toISOString(),category:result.category,existing:result.existing,decision:result.decision,bestSlot:result.best?result.best.slot:null,bestScore:result.best?result.best.score:null,unknownCount:result.best?result.best.criticalUnknowns.length+result.best.optionalUnknowns.length:0,tool:result.tool};}
function validReceipt(item){return item&&item.version===VERSION&&category(item.category)&&Number.isFinite(Date.parse(item.createdAt))&&Number.isFinite(Date.parse(item.expiresAt));}
function pruneReceipts(items,nowValue=new Date()){const now=nowValue instanceof Date?nowValue:new Date(nowValue);return(Array.isArray(items)?items:[]).filter(validReceipt).filter(item=>Date.parse(item.expiresAt)>now.getTime()).sort((a,b)=>Date.parse(b.createdAt)-Date.parse(a.createdAt)).slice(0,MAX_RECEIPTS);}
function saveReceipt(items,receipt,nowValue=new Date()){return pruneReceipts([receipt,...(Array.isArray(items)?items:[])],nowValue);}
function exportPayload(result,receipt){return{schema:'alo186-technical-shortlist-v1',privacy:'Marka, model, ASIN, fiyat, stok, puan, satıcı, garanti veya kişisel veri içermez.',result:{category:result.category,categoryLabel:result.categoryLabel,existing:result.existing,decision:result.decision,bestSlot:result.best?result.best.slot:null,bestScore:result.best?result.best.score:null,candidates:result.candidates.map(item=>({slot:item.slot,score:item.score,status:item.status,criticalFailures:item.criticalFailures.map(x=>x.label),criticalUnknowns:item.criticalUnknowns.map(x=>x.label)}))},receipt};}
function ymd(value){const d=new Date(value);return`${d.getUTCFullYear()}${String(d.getUTCMonth()+1).padStart(2,'0')}${String(d.getUTCDate()).padStart(2,'0')}`;}
function buildIcs(receipt,origin='https://alo186.com'){if(!validReceipt(receipt))return'';const meta=category(receipt.category);const route=`${String(origin).replace(/\/$/,'')}/hesaplama/teknik-urun-karsilastirma/?kategori=${encodeURIComponent(receipt.category)}`;return['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//ALO186//Technical Shortlist Review//TR','BEGIN:VEVENT',`UID:${receipt.id}@alo186.com`,`DTSTART;VALUE=DATE:${ymd(receipt.reviewAt)}`,`DTEND;VALUE=DATE:${ymd(new Date(Date.parse(receipt.reviewAt)+DAY))}`,`SUMMARY:ALO186 ${meta.label} teknik karşılaştırmasını yenile`,`DESCRIPTION:Teknik belgeleri ve mevcut ekipman yeterliliğini yeniden kontrol edin. Fiyat stok puan veya garanti kaydı tutulmaz. ${route}`,`URL:${route}`,'END:VEVENT','END:VCALENDAR',''].join('\r\n');}
return{VERSION,MAX_RECEIPTS,TTL_DAYS,REVIEW_DAYS,FIELD_STATE,EXISTING,CATEGORIES,category,sanitizeCandidate,scoreCandidate,compare,canOpenAffiliate,questions,normalizeReceipt,validReceipt,pruneReceipts,saveReceipt,exportPayload,buildIcs};});
