(()=>{'use strict';
const $=id=>document.getElementById(id),KEY='alo186_mini_ups_runtime_health_v1',TTL=730*86400000,MAX=24;const today=()=>new Date().toISOString().slice(0,10);$('date').value=today();
function load(){let x=[];try{x=JSON.parse(localStorage.getItem(KEY)||'[]')}catch(_){x=[]}const now=Date.now();x=x.filter(r=>r&&now-r.createdAt<TTL).slice(-MAX);localStorage.setItem(KEY,JSON.stringify(x));return x}function save(x){localStorage.setItem(KEY,JSON.stringify(x.slice(-MAX)))}function labels(id){const el=$(id);return el.options[el.selectedIndex].textContent}
function render(){const x=load(),box=$('records');if(!x.length){box.innerHTML='<p class="small">Henüz kayıt yok.</p>';return}box.replaceChildren(...x.slice().reverse().map(r=>{const d=document.createElement('div');d.className='record';const s=document.createElement('strong');s.textContent=`${r.date} · ${r.actual} / ${r.target} dk`;const p=document.createElement('p');p.className='small';p.textContent=`${r.scopeLabel} · ${r.stageLabel} · ${r.decision}`;d.append(s,p);return d}))}
function evaluate(r){let level='good',label='Satın almama',title='Mevcut mini UPS hedef süreyi karşılıyor.',summary='Uyumluluk ve fiziksel güvenlik devam ettiği sürece yeni ürün almanız gerekmiyor.',steps=['Gerçek süre kaydını saklayın.','Aynı yükle 180 gün sonra tekrar test edin.'],commercial=false;const validSetup=r.fullCharge&&r.stableLoad&&r.voltage&&r.polarity&&r.manual;const ratio=r.target>0?r.actual/r.target:0;
if(r.hazard){level='bad';label='Kullanımı durdur';title='Batarya veya cihazda fiziksel güvenlik belirtisi var.';summary='Yeniden süre testi ya da ürün karşılaştırması yapmayın.';steps=['Cihazı üretici talimatına göre enerjiden ayırın.','Şişmiş veya hasarlı bataryayı delmeyin, sıkıştırmayın ve evsel atığa atmayın.','Üretici/servis ve uygun atık sürecine geçin.','Tehlike sürerken affiliate yolu kapalıdır.']}
else if(!validSetup){level='warn';label='Test geçersiz';title='Gerçek süreyi karşılaştırmak için test koşulları eksik.';summary='Tek düşük sonuç değişim ihtiyacını kanıtlamaz.';steps=[];if(!r.fullCharge)steps.push('Üreticinin belirttiği süre kadar tam şarj edin.');if(!r.stableLoad)steps.push('Aynı modem, ONT ve ağ yüküyle yeniden test edin.');if(!r.voltage||!r.polarity)steps.push('Voltaj, jak ve merkez polaritesini doğrulayın.');if(!r.manual)steps.push('Tam model üretici kılavuzunu doğrulayın.')}
else if(r.upstream){level='warn';label='Altyapı ayrımı';title='Yedek güç çalıştı fakat internet hizmeti devam etmedi.';summary='Yeni mini UPS, operatör saha dolabı veya bağlantı kesintisini çözmez.';steps=['Modem ve ONT ışıklarını olay saatiyle kaydedin.','Operatör altyapı kesintisini güç yedeğinden ayrı değerlendirin.']}
else if(ratio>=1&&!r.dropout){level='good';label='Satın almama';title='Mevcut mini UPS hedef süreyi karşılıyor.';summary='Aynı kullanım hedefi için yeni ürün gerekmiyor.';steps=['Kablo ve batarya durumunu periyodik kontrol edin.','180 günlük yeniden test kaydı oluşturun.']}
else if(r.stage==='first'){level='warn';label='Yeniden test';title='İlk düşük süre sonucu değişim kanıtı değildir.';summary=r.dropout?'Çıkış kesintisi kaydedildi; tam şarj ve eşit yükle yeniden test edin.':'Ölçülen süre hedefin altında kaldı; koşulları eşitleyip yeniden test edin.';steps=['Tam şarj sonrası aynı cihazları bağlayın.','Test başlangıç ve bitiş saatini kaydedin.','Gerilim/polarite/jak uyumunu değiştirmeyin.']}
else if(r.stage==='retest'&&(ratio<1||r.dropout)){level='warn';label='Doğrulanmış süre kaybı';title='Yeniden testte hedef süre sağlanamadı.';summary='Batarya yaşlanması, şarj devresi veya cihaz çıkış kararlılığı doğrulanmalıdır.';steps=['Tam modelde kullanıcı tarafından değiştirilebilir batarya olup olmadığını kontrol edin.','Kartuş veya cihaz değişimini yalnız üretici parça/uyumluluk bilgisiyle değerlendirin.'];if(r.purpose==='replacement'){commercial=true;steps.push('Mevcut cihazı seçenek olarak koruyarak mini UPS teknik kategorisini karşılaştırın.')}}return{level,label,title,summary,steps,commercial}}
$('form').addEventListener('submit',e=>{e.preventDefault();const r={createdAt:Date.now(),date:$('date').value||today(),scope:$('scope').value,scopeLabel:labels('scope'),target:Number($('target').value),actual:Number($('actual').value),stage:$('stage').value,stageLabel:labels('stage'),purpose:$('purpose').value,fullCharge:$('fullCharge').checked,stableLoad:$('stableLoad').checked,voltage:$('voltage').checked,polarity:$('polarity').checked,manual:$('manual').checked,dropout:$('dropout').checked,hazard:$('hazard').checked,upstream:$('upstream').checked,officialRecord:false,retentionMode:'per-record'};const out=evaluate(r);r.decision=out.label;const all=load();all.push(r);save(all);render();$('result').classList.remove('hidden');$('state').textContent=out.label;$('state').className=`pill ${out.level}`;$('title').textContent=out.title;$('summary').textContent=out.summary;$('steps').replaceChildren(...out.steps.map(t=>{const li=document.createElement('li');li.textContent=t;return li}));$('commercial').classList.toggle('hidden',!out.commercial);$('result').scrollIntoView({behavior:'smooth',block:'start'})});
$('export').addEventListener('click',()=>{const data={tool:'ALO186 modem ve ONT mini UPS süre sağlık günlüğü',exportedAt:new Date().toISOString(),rawPersonalDataCollected:false,records:load()};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='alo186-mini-ups-sure-gunlugu.json';a.click();URL.revokeObjectURL(a.href)});
$('calendar').addEventListener('click',()=>{const d=new Date();d.setDate(d.getDate()+180);const fmt=x=>x.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z/,'Z');const ics=`BEGIN:VCALENDAR\nVERSION:2.0\nPRODID:-//ALO186//Mini UPS Runtime Review//TR\nBEGIN:VEVENT\nUID:${Date.now()}@alo186.com\nDTSTAMP:${fmt(new Date())}\nDTSTART:${fmt(d)}\nSUMMARY:Modem ve ONT mini UPS gerçek süre testi\nDESCRIPTION:Aynı yük, tam şarj ve aynı çıkış uyumuyla gerçek süreyi yeniden ölçün.\nEND:VEVENT\nEND:VCALENDAR`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([ics],{type:'text/calendar'}));a.download='mini-ups-sure-testi.ics';a.click();URL.revokeObjectURL(a.href)});render()})();