(()=>{'use strict';
const $=id=>document.getElementById(id),KEY='alo186_mini_ups_runtime_health_v2',TTL=730*86400000,MAX=24;const today=()=>new Date().toISOString().slice(0,10);$('date').value=today();
function load(){let x=[];try{x=JSON.parse(localStorage.getItem(KEY)||'[]')}catch(_){x=[]}const now=Date.now();x=x.filter(r=>r&&Number.isFinite(r.createdAt)&&now-r.createdAt<TTL).slice(-MAX);localStorage.setItem(KEY,JSON.stringify(x));return x}
function save(x){localStorage.setItem(KEY,JSON.stringify(x.slice(-MAX)))}
function labels(id){const el=$(id);return el.options[el.selectedIndex].textContent}
function validSetup(r){return Boolean(r.fullCharge&&r.stableLoad&&r.voltage&&r.polarity&&r.manual&&!r.hazard)}
function testTime(r){const value=Date.parse(`${r.date||''}T12:00:00`);return Number.isFinite(value)?value:r.createdAt}
function comparablePrior(records,current){const currentTime=testTime(current);return records.filter(r=>r&&r.id!==current.id&&r.scope===current.scope&&Number(r.target)===Number(current.target)&&validSetup(r)&&testTime(r)<currentTime).sort((a,b)=>testTime(a)-testTime(b)).at(-1)||null}
function failed(r){return Number(r.target)>0&&(Number(r.actual)/Number(r.target)<1||Boolean(r.dropout))}
function render(){const x=load(),box=$('records');if(!x.length){box.innerHTML='<p class="small">Henüz kayıt yok.</p>';return}box.replaceChildren(...x.slice().sort((a,b)=>testTime(b)-testTime(a)).map(r=>{const d=document.createElement('div');d.className='record';const s=document.createElement('strong');s.textContent=`${r.date} · ${r.actual} / ${r.target} dk`;const p=document.createElement('p');p.className='small';p.textContent=`${r.scopeLabel} · ${r.stageLabel} · ${r.decision}`;d.append(s,p);return d}))}
function evaluate(r,records){let level='good',label='Satın almama',title='Mevcut mini UPS hedef süreyi karşılıyor.',summary='Uyumluluk ve fiziksel güvenlik devam ettiği sürece yeni ürün almanız gerekmiyor.',steps=['Gerçek süre kaydını saklayın.','Aynı yükle 180 gün sonra tekrar test edin.'],commercial=false;const setupOk=validSetup(r),ratio=r.target>0?r.actual/r.target:0,prior=comparablePrior(records,r),priorFailed=Boolean(prior&&failed(prior));
if(r.hazard){level='bad';label='Kullanımı durdur';title='Batarya veya cihazda fiziksel güvenlik belirtisi var.';summary='Yeniden süre testi ya da ürün karşılaştırması yapmayın.';steps=['Cihazı üretici talimatına göre enerjiden ayırın.','Şişmiş veya hasarlı bataryayı delmeyin, sıkıştırmayın ve evsel atığa atmayın.','Üretici/servis ve uygun atık sürecine geçin.','Tehlike sürerken affiliate yolu kapalıdır.']}
else if(!setupOk){level='warn';label='Test geçersiz';title='Gerçek süreyi karşılaştırmak için test koşulları eksik.';summary='Tek düşük sonuç değişim ihtiyacını kanıtlamaz.';steps=[];if(!r.fullCharge)steps.push('Üreticinin belirttiği süre kadar tam şarj edin.');if(!r.stableLoad)steps.push('Aynı modem, ONT ve ağ yüküyle yeniden test edin.');if(!r.voltage||!r.polarity)steps.push('Voltaj, jak ve merkez polaritesini doğrulayın.');if(!r.manual)steps.push('Tam model üretici kılavuzunu doğrulayın.')}
else if(r.upstream){level='warn';label='Altyapı ayrımı';title='Yedek güç çalıştı fakat internet hizmeti devam etmedi.';summary='Yeni mini UPS, operatör saha dolabı veya bağlantı kesintisini çözmez.';steps=['Modem ve ONT ışıklarını olay saatiyle kaydedin.','Operatör altyapı kesintisini güç yedeğinden ayrı değerlendirin.']}
else if(ratio>=1&&!r.dropout){level='good';label='Satın almama';title='Mevcut mini UPS hedef süreyi karşılıyor.';summary='Aynı kullanım hedefi için yeni ürün gerekmiyor.';steps=['Kablo ve batarya durumunu periyodik kontrol edin.','180 günlük yeniden test kaydı oluşturun.']}
else if(r.stage==='first'){level='warn';label='Yeniden test';title='İlk düşük süre sonucu değişim kanıtı değildir.';summary=r.dropout?'Çıkış kesintisi kaydedildi; tam şarj ve eşit yükle yeniden test edin.':'Ölçülen süre hedefin altında kaldı; koşulları eşitleyip yeniden test edin.';steps=['Tam şarj sonrası aynı cihazları bağlayın.','Aynı hedef süre ve yük kapsamını koruyun.','Test başlangıç ve bitiş saatini kaydedin.']}
else if(r.stage==='retest'&&!prior){level='warn';label='Karşılaştırılabilir ilk kayıt eksik';title='Yeniden test sonucu için daha eski ve eş koşullu bir başlangıç kaydı bulunamadı.';summary='Geriye dönük veya farklı yük/hedef kaydıyla değişim kararı vermeyin.';steps=['Bu kaydı ilk doğrulanmış test olarak saklayın.','Aynı yük, hedef süre ve tam şarjla ikinci testi yapın.']}
else if(r.stage==='retest'&&failed(r)&&!priorFailed){level='warn';label='Bir kez daha doğrula';title='Son test hedefin altında; ancak önceki karşılaştırılabilir kayıt başarısız değildi.';summary='Tek yeni düşüş affiliate veya değişim kararı açmaz.';steps=['Aynı yük, hedef ve tam şarjla bir doğrulama testi daha yapın.','Kablo, adaptör, sıcaklık ve bağlı cihaz değişikliklerini dışlayın.']}
else if(r.stage==='retest'&&failed(r)&&priorFailed){level='warn';label='Tekrarlayan doğrulanmış süre kaybı';title='İki karşılaştırılabilir testte hedef süre sağlanamadı.';summary='Batarya yaşlanması, şarj devresi veya cihaz çıkış kararlılığı teknik olarak ayrılmalıdır.';steps=['Tam modelde kullanıcı tarafından değiştirilebilir batarya olup olmadığını kontrol edin.','Kartuş veya cihaz değişimini yalnız üretici parça/uyumluluk bilgisiyle değerlendirin.'];if(r.purpose==='replacement'){commercial=true;steps.push('Mevcut cihazı seçenek olarak koruyarak mini UPS teknik kategorisini karşılaştırın.')}}
return{level,label,title,summary,steps,commercial,priorId:prior&&prior.id||null}}
$('form').addEventListener('submit',e=>{e.preventDefault();const records=load(),r={id:`m${Date.now()}`,createdAt:Date.now(),date:$('date').value||today(),scope:$('scope').value,scopeLabel:labels('scope'),target:Number($('target').value),actual:Number($('actual').value),stage:$('stage').value,stageLabel:labels('stage'),purpose:$('purpose').value,fullCharge:$('fullCharge').checked,stableLoad:$('stableLoad').checked,voltage:$('voltage').checked,polarity:$('polarity').checked,manual:$('manual').checked,dropout:$('dropout').checked,hazard:$('hazard').checked,upstream:$('upstream').checked,officialRecord:false,retentionMode:'per-record'};const out=evaluate(r,records);r.decision=out.label;r.comparedWith=out.priorId;records.push(r);save(records);render();$('result').classList.remove('hidden');$('state').textContent=out.label;$('state').className=`pill ${out.level}`;$('title').textContent=out.title;$('summary').textContent=out.summary;$('steps').replaceChildren(...out.steps.map(t=>{const li=document.createElement('li');li.textContent=t;return li}));$('commercial').classList.toggle('hidden',!out.commercial);$('result').scrollIntoView({behavior:'smooth',block:'start'})});
$('export').addEventListener('click',()=>{const data={tool:'ALO186 modem ve ONT mini UPS süre sağlık günlüğü',exportedAt:new Date().toISOString(),rawPersonalDataCollected:false,officialRecord:false,records:load()};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='alo186-mini-ups-sure-gunlugu.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)});
$('calendar').addEventListener('click',()=>{const d=new Date();d.setDate(d.getDate()+180);const fmt=x=>x.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z/,'Z');const ics=`BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//ALO186//Mini UPS Runtime Review//TR\r\nBEGIN:VEVENT\r\nUID:${Date.now()}@alo186.com\r\nDTSTAMP:${fmt(new Date())}\r\nDTSTART:${fmt(d)}\r\nSUMMARY:Modem ve ONT mini UPS gerçek süre testi\r\nDESCRIPTION:Aynı yük, hedef süre, tam şarj ve aynı çıkış uyumuyla gerçek süreyi yeniden ölçün.\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([ics],{type:'text/calendar'}));a.download='mini-ups-sure-testi.ics';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)});render()})();